### ISSUE TITLE
useAnimatedStyle in react-native-library will report error

### ISSUE THREAD

**Issue by chj-damon** [software-mansion/react-native-reanimated#2123] opened 2021-06-09 03:53 UTC
## Description
I'm using `react-native-reanimated@2.1.0` to build my react-native-library, the repository is: https://github.com/thundersdata-frontend/td-design/tree/master/packages/react-native

Then I use this library in my project and I find that it will report errors when using some components which have reanimated included. like `Input`.
![simulator_screenshot_A4194282-4A57-4F22-82F0-FF5928EA72C4](https://user-images.githubusercontent.com/4902684/121289696-fbbf9680-c917-11eb-9f52-2860fb1eb1dc.png)

the weird thing is, I can use reanimated in the project directly without any problem. 

```tsx
  const x = useSharedValue(0);

  const rotateStyle = useAnimatedStyle(() => ({
    transform: [
      {
        translateX: x.value,
      },
    ],
  }));

  const handleRotate = () => {
    x.value = withTiming(100);
  };

  return (
      <Animated.View style={[{ backgroundColor: '#0189fb', width: 50, height: 50 }, rotateStyle]} />
      <Button title="rotate" onPress={handleRotate} />
  );
```
I noticed there's an tip says in the doc that I should clean metro cache: https://docs.swmansion.com/react-native-reanimated/docs/2.0.0/troubleshooting
but it doesn't work for me, because the animation code written directly in the project works fine, but it fails only when I use components in my library which using reanimated.

this is the compiled input file in `node_modules/@td-design/react-native/lib/commonjs/input/index.js`:
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireWildcard(require("react"));

var _restyle = require("@shopify/restyle");

var _reactNative = require("react-native");

var _reactNativeReanimated = _interopRequireWildcard(require("react-native-reanimated"));

var _InputItem = _interopRequireDefault(require("./InputItem"));

var _TextArea = _interopRequireDefault(require("./TextArea"));

var _text = _interopRequireDefault(require("../text"));

var _flex = _interopRequireDefault(require("../flex"));

var _box = _interopRequireDefault(require("../box"));

var _icon = _interopRequireDefault(require("../icon"));

var _helpers = _interopRequireDefault(require("../helpers"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _getRequireWildcardCache() { if (typeof WeakMap !== "function") return null; var cache = new WeakMap(); _getRequireWildcardCache = function () { return cache; }; return cache; }

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } if (obj === null || typeof obj !== "object" && typeof obj !== "function") { return { default: obj }; } var cache = _getRequireWildcardCache(); if (cache && cache.has(obj)) { return cache.get(obj); } var newObj = {}; var hasPropertyDescriptor = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { var desc = hasPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : null; if (desc && (desc.get || desc.set)) { Object.defineProperty(newObj, key, desc); } else { newObj[key] = obj[key]; } } } newObj.default = obj; if (cache) { cache.set(obj, newObj); } return newObj; }

function _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }

const AnimatedTouchableIcon = _reactNativeReanimated.default.createAnimatedComponent(_reactNative.TouchableOpacity);

const {
  ONE_PIXEL,
  px
} = _helpers.default;
const Input = /*#__PURE__*/(0, _react.forwardRef)(({
  label,
  labelPosition = 'left',
  leftIcon,
  rightIcon,
  inputType = 'input',
  allowClear = true,
  value,
  onChange,
  disabled = false,
  colon = false,
  required = false,
  style,
  ...restProps
}, ref) => {
  const theme = (0, _restyle.useTheme)();
  const [inputValue, setInputValue] = (0, _react.useState)(value);
  const [eyeOpen, setEyeOpen] = (0, _react.useState)(inputType === 'password');
  (0, _react.useEffect)(() => {
    setInputValue(value);
  }, [value]);

  const handleInputClear = () => {
    if (onChange) {
      onChange('');
    } else {
      setInputValue('');
    }
  };

  const handleChange = val => {
    if (onChange) {
      onChange(val);
    } else {
      setInputValue(val);
    }
  };

  const triggerPasswordType = () => {
    setEyeOpen(!eyeOpen);
  };

  let LabelComp = null;

  if (label) {
    if (typeof label === 'string') {
      LabelComp = /*#__PURE__*/_react.default.createElement(_flex.default, {
        marginRight: "x2",
        marginBottom: "x1",
        alignItems: "center"
      }, required && /*#__PURE__*/_react.default.createElement(_text.default, {
        color: "func600",
        paddingTop: "x2"
      }, "*", ' '), /*#__PURE__*/_react.default.createElement(_text.default, {
        variant: "p0",
        color: "gray500"
      }, label), /*#__PURE__*/_react.default.createElement(_text.default, null, colon ? ' :' : ''));
    } else {
      LabelComp = /*#__PURE__*/_react.default.createElement(_flex.default, {
        marginRight: "x2",
        marginBottom: "x1"
      }, required && /*#__PURE__*/_react.default.createElement(_text.default, {
        color: "func600",
        paddingTop: "x2"
      }, "*", ' '), label, colon ? ' :' : '');
    }
  }

  const clearIconStyle = (0, _reactNativeReanimated.useAnimatedStyle)(() => {
    return {
      marginRight: !!inputValue ? (0, _reactNativeReanimated.withTiming)(theme.spacing.x1) : (0, _reactNativeReanimated.withTiming)(0),
      opacity: !!inputValue ? (0, _reactNativeReanimated.withTiming)(1) : (0, _reactNativeReanimated.withTiming)(0)
    };
  }, [inputValue]);

  const InputContent = /*#__PURE__*/_react.default.createElement(_flex.default, {
    flex: labelPosition === 'left' ? 1 : 0,
    borderWidth: ONE_PIXEL,
    borderColor: "border",
    borderRadius: "x1"
  }, leftIcon && /*#__PURE__*/_react.default.createElement(_box.default, {
    marginHorizontal: "x1"
  }, leftIcon), /*#__PURE__*/_react.default.createElement(_box.default, {
    flexGrow: 1
  }, /*#__PURE__*/_react.default.createElement(_reactNative.TextInput, _extends({
    ref: ref
  }, restProps, {
    style: [{
      height: px(40),
      paddingLeft: theme.spacing.x1,
      fontSize: px(16),
      color: theme.colors.text
    }, style],
    editable: !disabled,
    textAlignVertical: "center",
    placeholderTextColor: theme.colors.gray300,
    value: inputValue,
    onChangeText: handleChange,
    onSubmitEditing: e => handleChange(e.nativeEvent.text),
    secureTextEntry: eyeOpen
  }))), allowClear && !!inputValue && /*#__PURE__*/_react.default.createElement(AnimatedTouchableIcon, {
    activeOpacity: 0.8,
    onPress: handleInputClear,
    style: clearIconStyle
  }, /*#__PURE__*/_react.default.createElement(_icon.default, {
    name: "closecircleo",
    color: theme.colors.icon
  })), inputType === 'password' && /*#__PURE__*/_react.default.createElement(_reactNative.TouchableOpacity, {
    activeOpacity: 0.8,
    onPress: triggerPasswordType,
    style: {
      marginRight: theme.spacing.x1
    }
  }, /*#__PURE__*/_react.default.createElement(_icon.default, {
    type: "entypo",
    name: eyeOpen ? 'eye-with-line' : 'eye',
    color: theme.colors.icon
  })), rightIcon && /*#__PURE__*/_react.default.createElement(_box.default, {
    marginRight: "x1"
  }, rightIcon));

  return labelPosition === 'left' ? /*#__PURE__*/_react.default.createElement(_flex.default, null, LabelComp, InputContent) : /*#__PURE__*/_react.default.createElement(_box.default, null, LabelComp, InputContent);
});

var _default = Object.assign(Input, {
  InputItem: _InputItem.default,
  TextArea: _TextArea.default
});

exports.default = _default;
//# sourceMappingURL=index.js.map
```

### Expected behavior
the animation component in the library should work fine.
### Actual behavior & steps to reproduce
the animation in the library doesn't work, but the animation written directly in the project works fine.
## Snack or minimal code example
this is my reproduce repo: https://github.com/thundersdata-frontend/rn-template

## Package versions

- React Native: 0.64.1
- React Native Reanimated: 2.2.0
- NodeJS: v16.2.0
- Xcode: Version 12.2 (12B45b)
- Java & Gradle: JDK8

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by piaskowyk** [comment] 2021-06-09 09:29
It looks like the Reanimated Babel plugin doesn't transform your library code. The problem is because the `_closure` property in `updater` is undefined, this happens when the plugin doesn't transform `worklet` code. I'll try to find why.

**Comment by chj-damon** [comment] 2021-06-09 10:36
that makes sense. I changed the way of import from `commonjs` to `module`, and now it works fine. but I don't know why.

**Comment by Szymon20000** [comment] 2021-06-15 09:04
I guess it's no longer a problem. I will close it tentatively. Please, reopen if I'm wrong.

**Closed by Szymon20000** 2021-06-15 09:04 UTC
Labels: 🏠  Reanimated2, 🐞 Bug
