### ISSUE TITLE
Reanimated doesn't compile with React Native macOS 0.75

### ISSUE THREAD

**Issue by Saadnajmi** [software-mansion/react-native-reanimated#6501] opened 2024-09-11 00:01 UTC
### Description

Someone on discord reported that Reanimated doesn't compile with React Native macOS 0.75, specifically on this line: https://github.com/software-mansion/react-native-reanimated/blob/1754695cff875614f9518857363cc822c7f04e65/packages/react-native-reanimated/apple/reanimated/REANodesManager.mm#L576

I _think_ the issue is because of this:

In earlier versions React Native macOS, we defined the view registry as `NSDictionary<NSNumber *, RCTUIView *> *viewRegistry`, where `RCTUIView` is a subclass of NSView that overrides and adds some methods for easier compatibility with iOS. In React Native macOS 0.75 (and maybe 0.74?), we changed the definition to `NSDictionary<NSNumber *, RCTPlatformView *> *viewRegistry`, where `RCTPlatformView` is simply a typedef of either NSView or UIView. 

I thought the change would be innocuous since we were _widening_ the scope of what views were accepted into the view registry, but I guess not? Said person on discord can get around the issue by replacing `REAUIView` with `RCTPlatformView` wherever there's an error. 

I'm not entirely sure whether the fix should be React Native macOS reverts the change I described above, or we update Reanimated to use something like `REAPlatformView`. My main concern is whether or not updating Reanimated keeps it backwords compatible with earlier versions of React Native macOS.

### Steps to reproduce

Try to build a new macOS test app (initialized with `react-native-macos-init`) with Reanimated.

### Snack or a link to a repository

I'm copy pasta-ing info someone sent me on discord.. so I don't have one yet.

### Reanimated version

the latest?

### React Native version

0.75

### Platforms

macOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Saadnajmi** [comment] 2024-09-11 00:03
I'll add the image from Discord as well for minimal repro: 
![image](https://github.com/user-attachments/assets/042177c8-370b-494a-ac5a-81324cf79c72)

**Comment by BlackCatTB** [comment] 2024-09-11 15:38
Thanks absolute legend!

**Comment by BlackCatTB** [comment] 2024-09-11 16:24
I found this is a quick fix when you replace the following lines with these code blocks:

#### **Files and Fixes**:

---

### `REANNodesManager`

**Lines 575-594**

```objc
[_uiManager
    addUIBlock:^(__unused RCTUIManager *manager, __unused NSDictionary<NSNumber *,
#if TARGET_OS_OSX
    RCTPlatformView
#else
    REAUIView
#endif
    *> *viewRegistry) {
        __typeof__(self) strongSelf = weakSelf;
        if (strongSelf == nil) {
            return;
        }
        atomic_store(&strongSelf->_shouldFlushUpdateBuffer, false);
        NSMutableDictionary *componentUpdateBuffer = [strongSelf->_componentUpdateBuffer copy];
        strongSelf->_componentUpdateBuffer = [NSMutableDictionary new];
        for (NSNumber *tag in componentUpdateBuffer) {
            ComponentUpdate *componentUpdate = componentUpdateBuffer[tag];
            if (componentUpdate == Nil) {
                continue;
            }
            [strongSelf updateProps:componentUpdate.props
                      ofViewWithTag:componentUpdate.viewTag
                           withName:componentUpdate.viewName];
        }
        [strongSelf performOperations];
}];
```

---

### `REASwizzeledUIManager`

**Line 235**

```objc
#if TARGET_OS_OSX
    return ^(__unused RCTUIManager *uiManager, NSDictionary<NSNumber *, RCTPlatformView *> *viewRegistry) {
#else
    return ^(__unused RCTUIManager *uiManager, NSDictionary<NSNumber *, REAUIView *> *viewRegistry) {
#endif
```

---

**Lines 379-382**

```objc
[self reanimated_addUIBlock:^(
    __unused RCTUIManager *manager, __unused NSDictionary<NSNumber *,
#if TARGET_OS_OSX
    RCTPlatformView
#else
    REAUIView
#endif
    *> *viewRegistry) {
        --isFlushingBlocks;
}];
```

---

### `REAModule`

**Lines 239-245**

```objc
[uiManager
    addUIBlock:^(__unused RCTUIManager *manager, __unused NSDictionary<NSNumber *,
#if TARGET_OS_OSX
    RCTPlatformView
#else
    REAUIView
#endif
    *> *viewRegistry) {
        for (AnimatedOperation operation in operations) {
            operation(nodesManager);
        }
        [nodesManager operationsBatchDidComplete];
    }];
```

---

### `RNGestureHandler`

**Lines 271-276**

```objc
[uiManager
    addUIBlock:^(__unused RCTUIManager *manager, __unused NSDictionary<NSNumber *,
#if TARGET_OS_OSX
    RCTPlatformView
#else
    RNGHUIView
#endif
    *> *viewRegistry) {
        for (GestureHandlerOperation operation in operations) {
            operation(self->_manager);
        }
    }];
```

---

These fixes introduce platform-specific checks using `#if TARGET_OS_OSX` to ensure compatibility between macOS and iOS.

Thank you!

**Comment by m-bert** [comment] 2024-09-16 14:10
Hi @Saadnajmi! Thank you for reporting this issue.

Was there a specific reason to change `RCTUIView` to `RCTPlatformView`? I've tried to change our `REAUIView` definition into `RCTPlatformView`, but it restrains us from accessing fields defined in `RCTUIView` (e.g. `transform` or `backgroundColor`). 

A potential solution in our codebase would be to create new type:

```obj-c
#if TARGET_OS_OSX
typedef NSDictionary<NSNumber *, RCTPlatformView *> ViewRegistry;
#else
typedef NSDictionary<NSNumber *, RCTUIView *>  ViewRegistry;
#endif
```
and then using `ViewRegistry`. However, we believe that it would be better if you could revert this change in `react-native-macos` if possible.

**Comment by hsjoberg** [comment] 2024-09-16 14:58
This looks like a dupe of #6421.

I did make some quick fixes for reanimated and gesture handler here:

https://github.com/hsjoberg/react-native-reanimated/tree/rn75fix
https://github.com/hsjoberg/react-native-gesture-handler/tree/rn75fix

But perhaps something like `REAPlatformView` is more appropriate.

**Comment by Saadnajmi** [comment] 2024-09-16 22:30
@m-bert I was hoping it would be a non-breaking change that just widened the view registry. I assume we can't guarantee only RCTUIView's will be there. But it's true that `transform` and `backgroundColor` are hard to access. I'll do some more investigating before I revert the change.

**Comment by Saadnajmi** [comment] 2024-09-19 17:21
@m-bert I did some testing and it seems React Native Gesture Handler has the same issues with my change, so I'm more likely to revert. 
A question: I see that Reanimated extended `RCTUIView` to add a `center` prop to match iOS. If I upstream that to React Native macOS (and back port to say... 0.73), would that be good fro you? I'm worried about "duplicate property" style issues, but if I back port the change to the minimum RN version you support and then remove, I think it'll be OK?

**Comment by Saadnajmi** [comment] 2024-09-19 17:54
@m-bert I found the fix! I need to add `__kindof` to `RCTViewManagerUIBlock`. AKA:

>typedef void (^RCTViewManagerUIBlock)(RCTUIManager *uiManager, NSDictionary<NSNumber *, **__kindof** RCTPlatformView *> *viewRegistry); // [macOS]

I can do that and backport!

**Comment by Saadnajmi** [comment] 2024-09-19 21:52
PRs here:
https://github.com/microsoft/react-native-macos/pull/2196
https://github.com/microsoft/react-native-macos/pull/2197
https://github.com/microsoft/react-native-macos/pull/2198

**Comment by m-bert** [comment] 2024-09-20 07:53
>I did some testing and it seems React Native Gesture Handler has the same issues with my change

We were aware of it.

Thank you very much for your PRs!

**Comment by Saadnajmi** [comment] 2024-09-23 16:47
Closing this issue as with RNM `0.74.6` and `0.75.4`, I no longer see this issues. I do see warnings with reanimated of this form, but they don't block the build anymore. I'm happy to follow up or make separate fixes for that warning too.
![image](https://github.com/user-attachments/assets/b9c95439-ae2c-4e06-b62c-6176ff36b487)

**Closed** 2024-09-23 16:48 UTC
Labels: Missing repro
