### ISSUE TITLE
export 'default'.'interpolate' (imported as 'Animated') was not found in 'react-native-reanimated' using expo web

### ISSUE THREAD

**Issue by kirtikapadiya** [software-mansion/react-native-reanimated#4524] opened 2023-06-02 09:57 UTC
### Description

WARNING in ./node_modules/@react-navigation/drawer/lib/module/views/legacy/Overlay.js:11:4
export 'default'.'interpolate' (imported as 'Animated') was not found in 'react-native-reanimated' (possible exports: Clock, Code, EasingNode, Extrapolate, FlatList, Image, Node, ScrollView, SpringUtils, Text, Transition, Transitioning, Value, View, abs, acc, acos, adapt, add, addWhitelistedNativeProps, addWhitelistedUIProps, always, and, asin, atan, block, call, ceil, clockRunning, color, concat, cond, cos, createAnimatedComponent, createTransitioningComponent, debug, decay, defined, diff, diffClamp, divide, eq, event, exp, floor, greaterOrEq, greaterThan, interpolateColors, interpolateNode, lessOrEq, lessThan, log, max, min, modulo, multiply, neq, not, onChange, or, pow, proc, round, set, sin, spring, sqrt, startClock, stopClock, sub, tan, timing, useCode, useValue)
   9 |   cond,
  10 |   greaterThan,
> 11 | } = Animated;
     |    ^
  12 | 
  14 |   interpolateNode ?? interpolateDeprecated;

### Steps to reproduce

npx expo export:web 

### Snack or a link to a repository

https://github.com/kirtikapadiya/exposdk48web 

### Reanimated version

2.14.4

### React Native version

0.71.8

### Platforms

Web

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kirtikapadiya** [comment] 2023-06-02 10:35
downgrading "react-native-reanimated": "~2.2.4" solved the issue for me but the getting warning like
`Some dependencies are incompatible with the installed expo version:
  react-native-reanimated@2.2.4 - expected version: ~2.14.4`

**Comment by blacksnowsoon** [comment] 2023-06-15 15:11
did you try to comment the line of interpolate in the Overlay.js:11:4 it worked for me , I have the same error with the same environment as you are for my project   they already assigned interpolatedNode to interpolate just after the destructuring of Animated I Solved that way

**Comment by m-bert** [comment] 2023-08-25 13:15
Hi @kirtikapadiya! I've looked into that issue and it seems that it is connected to `react-navigation` rather than `reanimated`.  As you can see, the line that @blacksnowsoon suggested to comment comes from `react-navigation`.

I will close this issue since there is nothing we can do about it. You can consider opening a new issue in `react-navigation`.

**Closed by m-bert** 2023-08-25 13:15 UTC
Labels: Platform: Web, Needs review, Repro provided

**Comment by seanburman** [comment] 2023-12-07 00:43
I found a solution to this issue that compiled.
The problem is that `./node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js` contains a conditional import from either `.//legacy/Drawer` or `./modern/Drawer`

I deleted `/legacy` and removed the option to import `./legacy/Drawer` in `./node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js` on line 93.
