### ISSUE TITLE
Animated scrollTo not work on the web

### ISSUE THREAD

**Issue by oldi92** [software-mansion/react-native-reanimated#1626] opened 2021-01-14 12:57 UTC
## Description
I am building a drag and drop app similiar to trello cards. I used the Reaniamted 2 playground repo as a start. When i am dragging a cloumn i want  to scroll programmatically in x axis with the scrollTo provided by Reaniamted v2. In the ios and android it is work just perfect and you can scroll. In web it doesnt respond at all, it is not throwing any erros it no showing anything it just doesnt work.

## Steps To Reproduce

Use the onScroll attribute with event from reanimated
The animated value is not updating

## Package versions

Expo Asset: 8.2.0
React Native: 0.63.4
React Native Reanimated: 2.0.0-rc.1
React Native Web: 0.14.7

- React: 
- React Native:
- React Native Reanimated:
- NodeJS:

**Comment by jakub-gonet** [comment] 2021-01-14 13:10
Duplicate of #1627.

**Closed by jakub-gonet** 2021-01-14 13:10 UTC
Labels: 🐞 Bug

**Comment by oldi92** [comment] 2021-01-14 13:12
Sorry i throw me a 404 page didnt know it publish it

**Comment by jakub-gonet** [comment] 2021-01-14 13:15
No worries 😄

**Comment by oldi92** [comment] 2021-01-14 13:21
weird machines 😂
