### ISSUE TITLE
Android crash - folly::toJson: JSON object value was a NaN

### ISSUE THREAD

**Issue by cristianoccazinsp** [software-mansion/react-native-reanimated#2914] opened 2022-02-01 16:10 UTC
## Description
Random crash reported from the crash analytics tool.

```
java.lang.RuntimeException: folly::toJson: JSON object value was a NaN when serializing value at "velocity"->"y"
        at com.facebook.react.bridge.NativeMap.toString(NativeMap.java:-2)
        at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:-2)
        at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:56)
        at com.facebook.react.uimanager.events.Event.dispatch(Event.java:180)
        at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:515)
        at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:489)
        at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
        at com.facebook.react.views.scroll.ReactScrollViewHelper.emitScrollEvent(ReactScrollViewHelper.java:88)
        at com.facebook.react.views.scroll.ReactScrollViewHelper.emitScrollEndDragEvent(ReactScrollViewHelper.java:57)
        at com.facebook.react.views.scroll.ReactScrollView.onTouchEvent(ReactScrollView.java:362)
        at android.view.View.dispatchTouchEvent(View.java:14360)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2785)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:39)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:39)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:530)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4221)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:488)
        at android.view.View.dispatchPointerEvent(View.java:14619)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6174)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5977)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5468)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5525)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5491)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5643)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5499)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5700)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5472)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5525)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5491)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5499)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5472)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8318)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8234)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8195)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8454)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:227)
        at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
        at android.os.MessageQueue.next(MessageQueue.java:342)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:7868)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```

### Expected behavior
No crash

### Actual behavior & steps to reproduce
Crash.

The crash seems to have happened when scrolling through a scroll view or flat list.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.66.3      |
| react-native-reanimated              |     2.3.1    |
| NodeJS                               |    16     |
| Java                                 |     11?    |
| Gradle                               |      6.9   |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by tomekzaw** [comment] 2022-02-01 17:43
Thanks for reporting. Duplicate of #2814. Will be fixed with #2901.

**Comment by cristianoccazinsp** [comment] 2022-02-02 00:14
Awesome, what’s pending for this to be released? This is starting to affect a high number of users

**Comment by tomekzaw** [comment] 2022-02-02 07:24
We plan to release 2.4.0 this week. Just a few more PRs to merge that also improve stability, some internal testing and we're ready to go.

**Comment by cristianoccazinsp** [comment] 2022-02-09 22:47
@tomekzaw  Still not fixed with 2.4.1. Just got this from an android device using such version:

```
java.lang.RuntimeException: folly::toJson: JSON object value was a NaN when serializing value at "translationY"
        at com.facebook.react.bridge.NativeMap.toString(NativeMap.java:-2)
        at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:-2)
        at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:57)
        at com.swmansion.gesturehandler.react.RNGestureHandlerStateChangeEvent.dispatch(RNGestureHandlerStateChangeEvent.kt:36)
        at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:517)
        at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:491)
        at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:117)
        at com.swmansion.gesturehandler.react.RNGestureHandlerModule.onStateChange(RNGestureHandlerModule.kt:569)
        at com.swmansion.gesturehandler.react.RNGestureHandlerModule.access$onStateChange(RNGestureHandlerModule.kt:15)
        at com.swmansion.gesturehandler.react.RNGestureHandlerModule$eventListener$1.onStateChange(RNGestureHandlerModule.kt:318)
        at com.swmansion.gesturehandler.GestureHandler.dispatchStateChange(GestureHandler.kt:83)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onHandlerStateChange(GestureHandlerOrchestrator.kt:155)
        at com.swmansion.gesturehandler.GestureHandler.moveToState(GestureHandler.kt:523)
        at com.swmansion.gesturehandler.GestureHandler.fail(GestureHandler.kt:618)
        at com.swmansion.gesturehandler.PanGestureHandler.onHandle(PanGestureHandler.kt:229)
        at com.swmansion.gesturehandler.GestureHandler.handle(GestureHandler.kt:349)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandler(GestureHandlerOrchestrator.kt:269)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandlers(GestureHandlerOrchestrator.kt:215)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.kt:44)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.kt:95)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:37)
```

**Comment by tomekzaw** [comment] 2022-02-10 10:24
@cristianoccazinsp Thanks for letting us know. In Reanimated 2.4.0 we've added a try/catch block for `folly::parse_error` but I forgot to handle `folly::print_error` (the one you've encountered) in this case as well. We'll fix it soon and release it as 2.5.0.

**Comment by cristianoccazinsp** [comment] 2022-02-22 18:32
Any updates on the release for this?

**Comment by tomekzaw** [comment] 2022-02-22 20:30
We have 2.5.0 release scheduled for next week.

In the meantime, feel free to use nightly build from [here](https://github.com/software-mansion/react-native-reanimated/actions/workflows/build-npm-package.yml). Don't worry about 2.4.1 in the filename though - we still need to make some changes to our CI so it puts the current date and commit hash in the version in package.json as well as in the name of *.tgz.

Closing this issue as #2992 fixes it.

**Closed by tomekzaw** 2022-02-22 20:30 UTC
Labels: 🧰needs-repro, 🤖android

**Comment by cjhines** [comment] 2022-08-17 07:47
I'm still experiencing this on 2.5.0

I'm also experiencing this.

```
    "@react-native-async-storage/async-storage": "^1.17.5",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-gesture-handler": "2.5.0",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-windows": "0.68.11",
```
