### ISSUE TITLE
Reanimated alpha version will not work on Android with productFlavors configured

### ISSUE THREAD

**Issue by chakrihacker** [software-mansion/react-native-reanimated#2292] opened 2021-08-18 11:19 UTC
## Description

The problem occurs from this file https://github.com/software-mansion/react-native-reanimated/blob/master/android-npm/build.gradle from line 63 to 72.

When product flavors are configured the task name changes from the default `mergeDebugNativeLibs` to something like `mergeDevelopmentDebugNativeLibs`.

My opinion is to let developers add few properties to the app's build.gradle (which can be provided at installation instructions)

```
replaceSoTaskDebug.dependsOn(
    project.getTasks().getByPath("${appName}:mergeDebugNativeLibs"),
    project.getTasks().getByPath("${appName}:stripDebugDebugSymbols")
)
project.getTasks().getByPath("${appName}:packageDebug").dependsOn(replaceSoTaskDebug)

replaceSoTaskRelease.dependsOn(
    project.getTasks().getByPath("${appName}:mergeReleaseNativeLibs"),
    project.getTasks().getByPath("${appName}:stripReleaseDebugSymbols")
)
project.getTasks().getByPath("${appName}:packageRelease").dependsOn(replaceSoTaskRelease)
```

### Expected behavior

Build Android app without issues

### Actual behavior & steps to reproduce

Gradle build failed at the above place

## Snack or minimal code example

Can produce if necessary

## Package versions

- React Native: 0.64
- React Native Reanimated: 2.3.0-aplha-2
- NodeJS: 16
- Java & Gradle: 1.8 and 6.7

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by chakrihacker** [comment] 2021-08-18 13:07
I did some debugging and came near to the solution, I hope this helps

```
def getCurrentFlavor() {
    Gradle gradle = getGradle()
    String  tskReqStr = gradle.getStartParameter().getTaskRequests().toString()
    Pattern pattern

    if( tskReqStr.contains( "assemble" ) )
        pattern = Pattern.compile("assemble(\\w+)(Release|Debug)")
    else
        pattern = Pattern.compile("generate(\\w+)(Release|Debug)")

    Matcher matcher = pattern.matcher( tskReqStr )

    if( matcher.find() )
        return matcher.group(1)
    else
    {
        println "NO MATCH FOUND"
        return ""
    }
}
```

We can get the current flavor from this function

And this can be used this way

```
def flavorString = getCurrentFlavor()
println('flavorString: ' + flavorString)

replaceSoTaskDebug.dependsOn(
    project.getTasks().getByPath("${appName}:merge${flavorString}DebugNativeLibs"),
    project.getTasks().getByPath("${appName}:strip${flavorString}DebugDebugSymbols")
)
project.getTasks().getByPath("${appName}:package${flavorString}Debug").dependsOn(replaceSoTaskDebug)

replaceSoTaskRelease.dependsOn(
    project.getTasks().getByPath("${appName}:merge${flavorString}ReleaseNativeLibs"),
    project.getTasks().getByPath("${appName}:strip${flavorString}ReleaseDebugSymbols")
)
project.getTasks().getByPath("${appName}:package${flavorString}Release").dependsOn(replaceSoTaskRelease)
```

**Comment by jmysliv** [comment] 2021-08-18 14:01
Duplicate of #2245

**Closed by jmysliv** 2021-08-18 14:01 UTC
Labels: 🐞 Bug, 🏠  Reanimated2

**Comment by piaskowyk** [comment] 2021-08-24 10:11
Fixed with: https://github.com/software-mansion/react-native-reanimated/pull/2319
