### ISSUE TITLE
Android crash on launch, Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30 in tid 24002 (mqt_js), pid 23922

### ISSUE THREAD

**Issue by tara-singh-danu** [software-mansion/react-native-reanimated#6509] opened 2024-09-15 12:29 UTC
### Description

Android application is getting crashed on launch, getting below error in logcat:
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30 in tid 24002 (mqt_js), pid 23922

### Steps to reproduce

Run the application

### Reanimated version

3.15.2, 3.15.1

### React Native version

0.75.3, 0.75.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

None

### Build type

Debug app & dev bundle

### Device

Android emulator

### Acknowledgements

Yes

 buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.24"

**Comment by tara-singh-danu** [comment] 2024-09-15 12:31
pid: 23922, tid: 24002, name: mqt_js  >>> com.xxx <<<
17:51:36.990  A        #00 pc 00000000001c3639  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreanimated.so (offset 0x4634000) (BuildId: 4caa97f5db086f9fd4c2f7cf96e1228e2fdeaf2a)
17:51:36.991  A        #01 pc 00000000001bf679  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreanimated.so (offset 0x4634000) (std::__ndk1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::function(std::__ndk1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)> const&)+41) (BuildId: 4caa97f5db086f9fd4c2f7cf96e1228e2fdeaf2a)
17:51:36.991  A        #02 pc 00000000000efbc7  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libworklets.so (offset 0x1500000) (reanimated::ShareableHostFunction::ShareableHostFunction(facebook::jsi::Runtime&, facebook::jsi::Function)+231) (BuildId: df93606af79d9e3388f05b478733a051ec727220)
17:51:36.992  A        #03 pc 00000000000efa1a  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libworklets.so (offset 0x1500000) (BuildId: df93606af79d9e3388f05b478733a051ec727220)
17:51:36.993  A        #04 pc 00000000000ef6d5  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libworklets.so (offset 0x1500000) (void std::__ndk1::allocator_traits<std::__ndk1::allocator<reanimated::ShareableHostFunction> >::construct[abi:v170000]<reanimated::ShareableHostFunction, facebook::jsi::Runtime&, facebook::jsi::Function, void, void>(std::__ndk1::allocator<reanimated::ShareableHostFunction>&, reanimated::ShareableHostFunction*, facebook::jsi::Runtime&, facebook::jsi::Function&&)+53) (BuildId: df93606af79d9e3388f05b478733a051ec727220)
17:51:36.994  A        #05 pc 00000000000ef1ef  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libworklets.so (offset 0x1500000) (std::__ndk1::__shared_ptr_emplace<reanimated::ShareableHostFunction, std::__ndk1::allocator<reanimated::ShareableHostFunction> >::__shared_ptr_emplace[abi:v170000]<facebook::jsi::Runtime&, facebook::jsi::Function>(std::__ndk1::allocator<reanimated::ShareableHostFunction>, facebook::jsi::Runtime&, facebook::jsi::Function&&)+127) (BuildId: df93606af79d9e3388f05b478733a051ec727220)
17:51:36.994  A        #06 pc 00000000000eefad  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libworklets.so (offset 0x1500000) (BuildId: df93606af79d9e3388f05b478733a051ec727220)
17:51:36.995  A        #07 pc 00000000000daa5d  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libworklets.so (offset 0x1500000) (BuildId: df93606af79d9e3388f05b478733a051ec727220)
17:51:36.995  A        #08 pc 00000000000d982f  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libworklets.so (offset 0x1500000) (reanimated::makeShareableClone(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const&, facebook::jsi::Value const&)+767) (BuildId: df93606af79d9e3388f05b478733a051ec727220)
17:51:36.995  A        #09 pc 000000000018fc38  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreanimated.so (offset 0x4634000) (reanimated::NativeReanimatedModule::makeShareableClone(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const&, facebook::jsi::Value const&)+72) (BuildId: 4caa97f5db086f9fd4c2f7cf96e1228e2fdeaf2a)
17:51:36.996  A        #10 pc 00000000001b9472  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreanimated.so (offset 0x4634000) (BuildId: 4caa97f5db086f9fd4c2f7cf96e1228e2fdeaf2a)
17:51:36.997  A        #11 pc 000000000027296c  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreanimated.so (offset 0x4634000) (BuildId: 4caa97f5db086f9fd4c2f7cf96e1228e2fdeaf2a)
17:51:36.998  A        #12 pc 00000000002728f2  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreanimated.so (offset 0x4634000) (BuildId: 4caa97f5db086f9fd4c2f7cf96e1228e2fdeaf2a)
17:51:36.999  A        #13 pc 000000000027281c  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreanimated.so (offset 0x4634000) (BuildId: 4caa97f5db086f9fd4c2f7cf96e1228e2fdeaf2a)
17:51:37.000  A        #14 pc 000000000027279c  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreanimated.so (offset 0x4634000) (BuildId: 4caa97f5db086f9fd4c2f7cf96e1228e2fdeaf2a)
17:51:37.000  A        #15 pc 0000000000270fb0  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreanimated.so (offset 0x4634000) (BuildId: 4caa97f5db086f9fd4c2f7cf96e1228e2fdeaf2a)
17:51:37.001  A        #16 pc 0000000000093cd4  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (BuildId: 4a514a10f785bf94)
17:51:37.002  A        #17 pc 0000000000093c1c  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (std::__ndk1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const+76) (BuildId: 4a514a10f785bf94)
17:51:37.003  A        #18 pc 0000000000093bba  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (facebook::jsi::DecoratedHostFunction::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)+90) (BuildId: 4a514a10f785bf94)
17:51:37.005  A        #19 pc 0000000000093b55  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (BuildId: 4a514a10f785bf94)
17:51:37.006  A        #20 pc 0000000000093adf  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (facebook::jsi::Value std::__ndk1::__invoke_void_return_wrapper<facebook::jsi::Value, false>::__call<facebook::jsi::DecoratedHostFunction&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long>(facebook::jsi::DecoratedHostFunction&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&)+63) (BuildId: 4a514a10f785bf94)
17:51:37.006  A        #21 pc 0000000000093a8f  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (BuildId: 4a514a10f785bf94)
17:51:37.007  A        #22 pc 0000000000092b53  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (std::__ndk1::__function::__func<facebook::jsi::DecoratedHostFunction, std::__ndk1::allocator<facebook::jsi::DecoratedHostFunction>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&)+67) (BuildId: 4a514a10f785bf94)
17:51:37.008  A        #23 pc 00000000000e83e3  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.008  A        #24 pc 0000000000168bac  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.008  A        #25 pc 0000000000188c9d  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.009  A        #26 pc 0000000000187ef5  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.014  A        #27 pc 0000000000168eb0  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.015  A        #28 pc 000000000016684d  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.015  A        #29 pc 00000000001a6c41  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.016  A        #30 pc 000000000018b9d9  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.017  A        #31 pc 0000000000187ef5  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.018  A        #32 pc 0000000000168eb0  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.018  A        #33 pc 0000000000167508  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.020  A        #34 pc 0000000000244ed5  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.020  A        #35 pc 0000000000168bac  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.022  A        #36 pc 0000000000188c9d  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.022  A        #37 pc 0000000000187ef5  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.023  A        #38 pc 0000000000168eb0  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.024  A        #39 pc 0000000000168670  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.025  A        #40 pc 00000000000dfb23  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes.so (offset 0x5174000) (BuildId: 195a6fd6b2a5de1bc55429ff8697add78b691fba)
17:51:37.025  A        #41 pc 0000000000091007  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (facebook::jsi::RuntimeDecorator<facebook::jsi::Runtime, facebook::jsi::Runtime>::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)+71) (BuildId: 4a514a10f785bf94)
17:51:37.026  A        #42 pc 000000000008f0b9  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (BuildId: 4a514a10f785bf94)
17:51:37.027  A        #43 pc 000000000009d79a  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (facebook::jsi::Value facebook::jsi::Function::call<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, facebook::jsi::Value>(facebook::jsi::Runtime&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, facebook::jsi::Value&&) const+218) (BuildId: 4a514a10f785bf94)
17:51:37.029  A        #44 pc 000000000009d600  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (BuildId: 4a514a10f785bf94)
17:51:37.030  A        #45 pc 0000000000086341  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (BuildId: 4a514a10f785bf94)
17:51:37.030  A        #46 pc 0000000000086304  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (std::__ndk1::function<void ()>::operator()() const+20) (BuildId: 4a514a10f785bf94)
17:51:37.031  A        #47 pc 000000000007e494  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (facebook::react::JSIExecutor::defaultTimeoutInvoker(std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>)+20) (BuildId: 4a514a10f785bf94)
17:51:37.032  A        #48 pc 0000000000084275  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (BuildId: 4a514a10f785bf94)
17:51:37.034  A        #49 pc 00000000000841f4  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (void std::__ndk1::__invoke_void_return_wrapper<void, true>::__call<void (*&)(std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>), std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()> >(void (*&)(std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>), std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>&&)+36) (BuildId: 4a514a10f785bf94)
17:51:37.034  A        #50 pc 00000000000841bc  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (BuildId: 4a514a10f785bf94)
17:51:37.035  A        #51 pc 00000000000833d8  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (std::__ndk1::__function::__func<void (*)(std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>), std::__ndk1::allocator<void (*)(std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>)>, void (std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>)>::operator()(std::__ndk1::function<void ()> const&, std::__ndk1::function<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > ()>&&)+40) (BuildId: 4a514a10f785bf94)
17:51:37.036  A        #52 pc 000000000009a330  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (facebook::react::JSIExecutor::callFunction(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, folly::dynamic const&)+656) (BuildId: 4a514a10f785bf94)
17:51:37.036  A        #53 pc 00000000002e2cae  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.039  A        #54 pc 00000000002e299f  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.040  A        #55 pc 00000000002e294c  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.042  A        #56 pc 00000000002e2924  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.043  A        #57 pc 00000000002e1a50  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.044  A        #58 pc 00000000002eb919  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.044  A        #59 pc 00000000002eb899  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (std::__ndk1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const+41) (BuildId: 9559eed9b0714453)
17:51:37.044  A        #60 pc 00000000002eb866  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.047  A        #61 pc 00000000002eb804  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.049  A        #62 pc 00000000002eb7c4  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.050  A        #63 pc 00000000002eb79c  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.052  A        #64 pc 00000000002ea828  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.052  A        #65 pc 0000000000086341  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (BuildId: 4a514a10f785bf94)
17:51:37.053  A        #66 pc 0000000000086304  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libhermes_executor.so (offset 0x3efc000) (std::__ndk1::function<void ()>::operator()() const+20) (BuildId: 4a514a10f785bf94)
17:51:37.055  A        #67 pc 000000000024479b  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.056  A        #68 pc 0000000000244724  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.056  A        #69 pc 00000000002446e4  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.058  A        #70 pc 00000000002446bc  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.061  A        #71 pc 00000000002438d8  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libreactnativejni.so (offset 0x3fc8000) (BuildId: 9559eed9b0714453)
17:51:37.062  A        #72 pc 0000000000018964  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libfbjni.so (offset 0x3a1c000) (facebook::jni::detail::MethodWrapper<void (facebook::jni::JNativeRunnable::*)(), &(facebook::jni::JNativeRunnable::run()), facebook::jni::JNativeRunnable, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>)+68) (BuildId: ece3c6492eed837eaeaed17c60fcfb41082c6211)
17:51:37.064  A        #73 pc 00000000000188a3  /data/app/~~dA5MJg-TlIRPKDsYXgM2uw==/com.abc.xyz-256yfaDvsmWvOhOD197trg==/base.apk!libfbjni.so (offset 0x3a1c000) (facebook::jni::detail::FunctionWrapper<void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>), facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*, void>::call(_JNIEnv*, _jobject*, void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>))+51) (BuildId: ece3c6492eed837eaeaed17c60fcfb41082c6211)

**Comment by EmilJunker** [comment] 2024-09-16 06:34
This is a duplicate of #6415

**Comment by piaskowyk** [comment] 2024-09-16 12:57
It seems like a duplication of https://github.com/software-mansion/react-native-reanimated/issues/6415 so i will close this one to keep discussion in one place

**Closed by piaskowyk** 2024-09-16 12:57 UTC
Labels: Missing repro, Platform: Android, Missing info
