### ISSUE TITLE
Can not build Android with react-native version 0.72.0

### ISSUE THREAD

**Issue by AllmaG3st** [software-mansion/react-native-reanimated#4715] opened 2023-07-12 07:42 UTC
### Description

After installing Reanimated 3 (versions 3.0.0 and 3.3.0 were tried) android app does not build any more. 
Attempt to build the app from VS code just stuck on 
`info JS server already running.`

Attempt to build from Android Studio gives this at first 
`Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.`

and then error:
`[CXX1101] NDK at /Users/'user'/Library/Android/sdk/ndk/23.1.7779620 did not have a source.properties file
`

### Steps to reproduce

1. Create React Native Project with npx init (version 0.72.0)
2. Install react-native-reanimated following the instruction (version 3.0.0 or 3.3.0)
3. Try to build on Android.

### Snack or a link to a repository

https://github.com/AllmaG3st/RN-Weather-Quest

### Reanimated version

3.0.0

### React Native version

0.72.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Any

### Acknowledgements

Yes

**Comment by giannismanie** [comment] 2023-07-12 07:59
I have had the same issue.
Try to clean gradlew (cd android && call gradlew clean && ./gradlew cleanBuildCache && cd ..)
Also, rm node_modules and npm i just in case... & use the reanimated 3.3.0

**Comment by efstathiosntonas** [comment] 2023-07-12 08:27
can you try with ndk `24.0.8215888`?

**Comment by vincemavill** [comment] 2023-07-12 08:29
@efstathiosntonas not working sir
this is the error message
react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModuleSpec.cpp.o cannot be safely placed under this directory. The build may not work correctly. 
ninja: error: manifest 'build.ninja' still dirty after 100 tries

**Comment by efstathiosntonas** [comment] 2023-07-12 08:40
ok so the error changed to this now? Is this a real path on your mac: `/Users/'user'/Library` maybe the problem is that `user` has quotes.

**Comment by AllmaG3st** [comment] 2023-07-12 08:46
> ok so the error changed to this now? Is this a real path on your mac: `/Users/'user'/Library` maybe the problem is that `user` has quotes.
> 
> edit: https://visualgdb.com/documentation/cmake/CMAKE_OBJECT_PATH_MAX/

I just changed my username, and quoted 'user' :D

**Comment by AllmaG3st** [comment] 2023-07-12 08:47
So, I think I found out the reason, I started completely new project with updated Node version, previously I was using 16.20.0, I upgraded to 18.16.0 and now it works.

**Comment by vincemavill** [comment] 2023-07-12 09:17
mine is still not working on Android
I am using RN 0.72 and reanimated 3.3.0

**Comment by AllmaG3st** [comment] 2023-07-12 10:06
> mine is still not working on Android I am using RN 0.72 and reanimated 3.3.0

is it 0.72.0 or 0.72.1?

**Comment by vincemavill** [comment] 2023-07-12 10:07
@AllmaG3st 0.72.0 sir,

**Comment by TylerJackson** [comment] 2023-07-14 14:47
Also not working for me with error - RN 0.72.3 RNR 3.3
It does work locally for me but not from our CI machine

**Comment by TylerJackson** [comment] 2023-07-14 16:17
any thoughts @efstathiosntonas?

**Comment by CoonHouse** [comment] 2023-07-15 18:51
Also an error, but another one.

`Task :react-native-reanimated:buildCMakeDebug[armeabi-v7a] FAILED`
`Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.`

RN 0.72.3 RNR 3.3.0 (New project)
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "23.1.7779620"

**Comment by lekbit** [comment] 2023-07-18 20:13
>`* What went wrong:
Execution failed for task ':react-native-reanimated:buildCMakeDebug[arm64-v8a]'.
 Unable to delete file 'C:\Users\Artem\Documents\flashcardseng\node_modules\react-native-reanimated\android\build\intermediates\cxx\Debug\1o6v2eo5\obj\ar
m64-v8a'`

I swear, someday I'll throw this React Native into the trash bin with all its endless errors in Reanimated.

**Comment by lekbit** [comment] 2023-07-20 19:37
I will describe all the steps I took to make it work, but I can't say for sure which of them was actually necessary. Firstly, I recreated the project from scratch.
1)npx react-native@X.XX.X init AwesomeProject --version 0.72.1
2)Then I immediately installed "reanimated", "gesture-handler"
3)delete the "node_modules" folder
4)Open "VS code" as administrator.
5)npm install
6)npx react-native run-android
Also note my NDK version in "Android studio" is 23.1.77

**Comment by lekbit** [comment] 2023-07-20 20:37
I will describe all the steps I took to make it work, but I can't say for sure which of them was actually necessary. Firstly, I recreated the project from scratch.
1)npx react-native@X.XX.X init AwesomeProject --version 0.72.1
2)add string `kotlinVersion = '1.8.10'` to "android/app/build.gradle"
3)Then I immediately installed "reanimated", "gesture-handler"
4)delete the "node_modules" folder
5)Open "VS code" as administrator.
6)npm install
7)npx react-native run-android
Also note my NDK version in "Android studio" is 23.1.77

**Comment by lekbit** [comment] 2023-07-20 20:38
I will describe all the steps I took to make it work, but I can't say for sure which of them was actually necessary. Firstly, I recreated the project from scratch.
1)npx [react-native@X.XX.X](mailto:react-native@X.XX.X) init AwesomeProject --version 0.72.1
2)add string kotlinVersion = '1.8.10' to "android/build.gradle"
3)Then I immediately installed "reanimated", "gesture-handler"
4)delete the "node_modules" folder
5)Open "VS code" as administrator.
6)npm install
7)npx react-native run-android
Also note my NDK version in "Android studio" is 23.1.77

**Comment by lekbit** [comment] 2023-07-20 20:38
I will describe all the steps I took to make it work, but I can't say for sure which of them was actually necessary. Firstly, I recreated the project from scratch.
1)npx [react-native@X.XX.X](mailto:react-native@X.XX.X) init AwesomeProject --version 0.72.1
2)add string `kotlinVersion = '1.8.10'` to "android/app/build.gradle"
3)Then I immediately installed "reanimated", "gesture-handler"
4)delete the "node_modules" folder
5)Open "VS code" as administrator.
6)npm install
7)npx react-native run-android
Also note my NDK version in "Android studio" is 23.1.77

**Comment by lekbit** [comment] 2023-07-20 20:39
I will describe all the steps I took to make it work, but I can't say for sure which of them was actually necessary. Firstly, I recreated the project from scratch.
1)npx [react-native@X.XX.X](mailto:react-native@X.XX.X) init AwesomeProject --version 0.72.1
2)add string `kotlinVersion = '1.8.10'` to "android/build.gradle"
3)Then I immediately installed "reanimated", "gesture-handler"
4)delete the "node_modules" folder
5)Open "VS code" as administrator.
6)npm install
7)npx react-native run-android
Also note my NDK version in "Android studio" is 23.1.77

**Comment by Dat-Mobile** [comment] 2023-07-21 08:48
@TylerJackson please refer [this comment](https://github.com/software-mansion/react-native-reanimated/issues/4712#issuecomment-1632433278)

Remove `_JAVA_OPTIONS` in cimg/android on circleci and it works now

**Comment by revealer409** [comment] 2023-07-27 05:59
Finally build successfully 👍 

![image](https://github.com/software-mansion/react-native-reanimated/assets/48885797/8e38567a-e50b-4b01-9693-c3c83e285515)


here are some changes I have made:
Packages & dependencies 
"@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "react": "18.2.0",
    "react-native": "0.72.1",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-reanimated": "^3.4.0",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.23.0"

steps:
1. uninstall  "react-native-reanimated" and then install this version of **RNR  3.4.0**
2. Installed ndk version "23.1.7779620"
3. added **ndk** path in **local.properties** file under **android**    like below
ndk.dir=C\:\\Users\\kashif\\AppData\\Local\\Android\\sdk\\ndk\\23.1.7779620

- move project to main drive like D\:  because **RNR** CMAKE  PATH characters should be less than 250.

EXCEPTIONAL Chcange  

 minSdkVersion  from 21 to 23 as i was using status bar so that requires min SDK v=23

Build succeeded. 💯

**Comment by mog-rn** [comment] 2023-07-30 20:17
> Finally build successfully +1
> 
> ![image](https://user-images.githubusercontent.com/48885797/256356832-8e38567a-e50b-4b01-9693-c3c83e285515.png)
> 
> here are some changes I have made: Packages & dependencies "@react-navigation/drawer": "^6.6.3", "@react-navigation/native": "^6.1.7", "react": "18.2.0", "react-native": "0.72.1", "react-native-gesture-handler": "^2.12.0", "react-native-reanimated": "^3.4.0", "react-native-safe-area-context": "^4.7.1", "react-native-screens": "^3.23.0"
> 
> steps:
> 
> 1. uninstall  "react-native-reanimated" and then install this version of **RNR  3.4.0**
> 2. Installed ndk version "23.1.7779620"
> 3. added **ndk** path in **local.properties** file under **android**    like below
>    ndk.dir=C:\Users\kashif\AppData\Local\Android\sdk\ndk\23.1.7779620
> 
> * move project to main drive like D:  because **RNR** CMAKE  PATH characters should be less than 250.
> 
> EXCEPTIONAL Chcange
> 
> minSdkVersion from 21 to 23 as i was using status bar so that requires min SDK v=23
> 
> Build succeeded. 100

I followed these steps on a my linux pc. Didn't work for the first time but after doing this and also `unset _JAVA_OPTIONS` and it worked for me.

**Comment by manage-some** [comment] 2023-08-01 16:59
+1 facing same issue

**Comment by blwinters** [comment] 2023-08-12 17:17
Uninstalling and reinstalling the NDK (`23.1.7779620` in my `build.gradle`), as described [here](https://github.com/software-mansion/react-native-reanimated/issues/4241#issuecomment-1590742192), fixed the error for me.

**Comment by mog-rn** [comment] 2023-08-13 17:27
> Uninstalling and reinstalling the NDK (`23.1.7779620` in my `build.gradle`), as described [here](https://github.com/software-mansion/react-native-reanimated/issues/4241#issuecomment-1590742192), fixed the error for me.

I tried that severally and it did't work for me

**Comment by diegodorado** [comment] 2023-08-24 14:51
> > Uninstalling and reinstalling the NDK (`23.1.7779620` in my `build.gradle`), as described [here](https://github.com/software-mansion/react-native-reanimated/issues/4241#issuecomment-1590742192), fixed the error for me.
> 
> I tried that severally and it did't work for me

Didn't worked for me either. It was working fine with RN 0.71.8

**Comment by MateusPitura** [comment] 2023-10-28 17:36
In my case I'm trying to use react-navigation and when I run `npx react-native start` it shows an error about `reanimated` and the message:

`[CXX1101] NDK at /Users/'user'/Library/Android/sdk/ndk/23.1.7779620 did not have a source.properties file`

To solve this, I opened my Android Studio > More Actions > SDK Manager > Languages & Frameworks > Android SDK > SDK Tools and I selected the NDK version **24.0.8215888** and unchecked other versions. Then  `Apply` and ran the react-native project again. It works!

**Comment by rmarquois** [comment] 2023-11-14 10:38
I also recommend using the SDK Manager to download the corresponding NDK. You can see its version when you run `./gradlew clean` from the "android" folder. Otherwise we don't know if the `run android` process is blocked or not.

**Comment by soransh-singh** [comment] 2024-02-16 12:17
i am new to react-native and i am getting this same problem what will work ??

**Comment by TheEhsanSarshar** [comment] 2024-02-28 05:44
cd to the missing source file ndk directory `/Users/'user'/Library/Android/sdk/ndk/23.1.7779620`
and then delete it using `rm -rf 23.1.7779620`

**Comment by analuizaalvesm** [comment] 2024-03-28 15:52
> Also an error, but another one.
> 
> `Task :react-native-reanimated:buildCMakeDebug[armeabi-v7a] FAILED` `ninja: error: manifest 'build.ninja' still dirty after 100 tries`
> 
> RN 0.72.3 RNR 3.3.0 (New project) buildToolsVersion = "33.0.0" minSdkVersion = 21 compileSdkVersion = 33 targetSdkVersion = 33 ndkVersion = "23.1.7779620"
> 
> Update: Tried some other versions of RNR with RN 0.72.3 Until 2.17.0 it is working, as of 3.0.0 it goes wrong.
> 
> Update: I was able to get RNR 3.3.0 working with RN 0.72.3 by removing `armeabi-v7a` from `reactNativeArchitectures` in `android/gradle.properties`

You literally saved my life. Thank you so much

**Comment by analuizaalvesm** [comment] 2024-03-28 16:33
> Also an error, but another one.
> 
> `Task :react-native-reanimated:buildCMakeDebug[armeabi-v7a] FAILED` `ninja: error: manifest 'build.ninja' still dirty after 100 tries`
> 
> RN 0.72.3 RNR 3.3.0 (New project) buildToolsVersion = "33.0.0" minSdkVersion = 21 compileSdkVersion = 33 targetSdkVersion = 33 ndkVersion = "23.1.7779620"
> 
> Update: Tried some other versions of RNR with RN 0.72.3 Until 2.17.0 it is working, as of 3.0.0 it goes wrong.
> 
> Update: I was able to get RNR 3.3.0 working with RN 0.72.3 by removing `armeabi-v7a` from `reactNativeArchitectures` in `android/gradle.properties`

@CoonHouse you literally saved my project, thank you

**Comment by Sanjeev12357** [comment] 2024-04-10 18:15
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-screens'.
> [CXX1101] NDK at C:\Users\sanju\AppData\Local\Android\Sdk\ndk\25.1.8937393 did not have a source.properties file
 I am having this error someone please help

**Comment by gustavosantaella** [comment] 2024-05-02 17:46
I have the same issue with react native verion **0.74.0**

**Comment by Pratik-2102** [comment] 2024-05-03 07:41
> > I have the same issue with react native verion **0.74.0**
> 
> I have resolved the issue you need to delete the sdk/ndk/25.1.8937 and bundle the app again

Could you please describe it in more detail. I am also facing same issue

**Comment by Sanjeev12357** [comment] 2024-05-03 07:45
> > > I have the same issue with react native verion **0.74.0**
> > 
> > 
> > I have resolved the issue you need to delete the sdk/ndk/25.1.8937 and bundle the app again
> 
> Could you please describe it in more detail. I am also facing same issue


see if you are having the issue mentioned below  you can resolve this by manually goind to the users / yourusername/appdata/local/android/sdk/ndk and delete the version like mine was 25.1.8937 that was giving me the error so i deleted the folder and reinstall the dependecy of react native screens so the issue was resolved by doing this
[CXX1101] NDK at C:\Users\sanju\AppData\Local\Android\Sdk\ndk\25.1.8937393 did not have a source.properties file

**Comment by Sanjeev12357** [comment] 2024-05-03 07:47
This issue in my pc arised when i stopped the installation of a react-native-screens dependency in middle so it was not able to install properly by deleting the sdk/ndk version  folder it will try to reinstall the dependency properly so by that means it would work

**Comment by qureshikaif** [comment] 2024-05-04 10:07
In my case. My android>build.gradle file had an NDK version which was not even installed on my system. I had v25.1.8937393 NDK installed and android>build.gradle was pointing towards v26.1.10909125. I just changed the version in android>build.gradle to the one i have installed and it fixed the issue for me.

**Comment by jaumereg** [comment] 2024-05-30 11:01
After days of pain and uncertainty, I can confirm that in my case going to Android Studio > Tools > SDK Manager > SDK Tools and updating NDK worked! 🎉🎉🎉

**Comment by Varofon** [comment] 2024-06-10 07:38
Weirdly enough reinstalling NDK v26.1.10909125 solved the problem for me as well

**Closed** 2024-06-10 15:12 UTC
Labels: Platform: Android, Needs review, Repro provided
