### ISSUE TITLE
SvgText with animatedProps crashes on Android 

### ISSUE THREAD

**Issue by matinzd** [software-mansion/react-native-reanimated#4091] opened 2023-02-23 09:29 UTC
### Description

**NOTE: I am not sure if this issue is related to `react-native-reanimated` or `react-native-svg`**

Passing `animatedProps` to `AnimatedSvgText` will crash on Android.

### Steps to reproduce

1. Create `AnimatedSvgText` component with `Reanimated.createAnimatedComponent(Text)`
2. Pass in `animatedProps`
3. It crashes on Android, works fine on iOS (Not sure if it is reanimated issue or svg)

<img width="436" alt="Screenshot 2023-02-23 at 10 23 33" src="https://user-images.githubusercontent.com/24797481/220867270-9f2339e0-ffb4-49f7-b972-b10d90820afe.png">

### Snack or a link to a repository

https://snack.expo.dev/@ddappteam/reanimated-svg-crash

### Reanimated version

2.14.4

### React Native version

0.71.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 3A

### Acknowledgements

Yes

Reference: https://github.com/software-mansion/react-native-svg/issues/1991

**Comment by matinzd** [comment] 2023-02-23 09:41
The issue is not happening on provided example on https://snack.expo.dev.

**Comment by matinzd** [comment] 2023-03-07 11:09
@tomekzaw

**Comment by Latropos** [comment] 2023-03-13 12:11
You can wrap x and y values in array, like this:
```
  const animatedTextProps = useAnimatedProps(() => {
    return {
      x: [position.value],
      y: [position.value],
    }
  })
```
I've tested the solution above both on Android and IOS

**Comment by matinzd** [comment] 2023-03-13 12:30
> react

Yeah I figured it out after posting the issue. https://github.com/software-mansion/react-native-svg/issues/1991#issuecomment-1460015562

But it seems this is inconsistency between android and iOS. So it needs to be fixed.

**Comment by tomekzaw** [comment] 2023-03-14 17:24
Just for the record, @WoLewicki knows what's the root cause of this issue and promised to take a look at it.

**Comment by Latropos** [comment] 2023-05-16 08:34
Thank for submitting the issue, we are closing, since after looking in the problem we have found that it is not related to reanimated

**Closed by Latropos** 2023-05-16 08:34 UTC
Labels: Platform: Android, Reproducible 🎉, Needs review, Repro provided
