### ISSUE TITLE
`property is not configurable` when accessing props from worklet callback

### ISSUE THREAD

**Issue by kirillzyusko** [software-mansion/react-native-reanimated#6134] opened 2024-06-18 12:19 UTC
### Description

Hey 👋 

It seems like after 3.12 there was some breaking changes, so the code like:

```tsx
import { forwardRef, useCallback } from "react";
import { useAnimatedReaction, useSharedValue } from "react-native-reanimated";

import type React from "react";
import type { ScrollView } from "react-native";

const CustomScrollView = forwardRef<ScrollView, React.PropsWithChildren<{}>>(
  ({ ...rest }, ref) => {
    const input = useSharedValue({ layout: {}, target: 1 });

    const a = useCallback(() => {
      "worklet";

      console.log(rest.snapToOffsets);
    }, [rest.snapToOffsets]);

    useAnimatedReaction(
      () => input.value,
      (current, previous) => {
        a();
      },
      [],
    );

    return null;
  },
);

export default CustomScrollView;
```

will throw an exception `property is not configurable` immediately 😕 

I've seen similar issues with `useAnimatedStyle` hook and the suggestion was to not include static styles into `useAnimatedStyle` hook. Though my problem is a bit different and I don't see a straightforward solution for that.

### Steps to reproduce

1. Copy & paste code from description into example screen
2. run example app and go to broken screen

### Snack or a link to a repository

-

### Reanimated version

3.12.0

### React Native version

0.74.0

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Device model

iPhone 15 Pro

### Acknowledgements

Yes

**Comment by kirillzyusko** [comment] 2024-06-18 12:24
@tjzel just discovered that it looks like it has been fixed in https://github.com/software-mansion/react-native-reanimated/pull/6098 right?

May I kindly ask you to prepare a new patch release for 3.12? 🙏 I think it's a very critical one 😓

**Comment by tjzel** [comment] 2024-06-19 09:15
Yeah, I think that's a reasonable request. We released it in an RC version because I'm not absolutely certain it works in all scenarios. Have you tried the RC release to see if it works for you?

**Comment by tjzel** [comment] 2024-06-19 09:17
Duplicate of #6066

**Closed by tjzel** 2024-06-19 09:17 UTC
Labels: Missing repro, Platform: Android, Platform: iOS, Missing info

**Comment by kirillzyusko** [comment] 2024-06-19 09:22
> Have you tried the RC release to see if it works for you?

@tjzel No, not yet. But it was in my To Do list 🙃 

Though it's worth to note, that I created a patch from your PR and it fixed a problem in my case (but I haven't tested a new RC yet).

> We released it in an RC version because I'm not absolutely certain it works in all scenarios.

Well, even if it works not in all scenarios, then later on you can release a new version with additional fixes 😁

I understand, that you want to keep as small as possible releases and don't publish an official release for each new important bug fix, but this commit is actually very important, because it break a compatibility with all old versions (basic functionality works for sure, but I think many people were relying on capturing external objects in closures) 😔

**Comment by tjzel** [comment] 2024-06-19 09:30
No, that's actually not the case here. I'd normally release it in a patch immediately, but I had some reasons regarding the changes in our repo structure that made me postpone it.

However, when I went over them right now it turns out they are actually invalid. I will try to publish the patch later today 😃

**Comment by tjzel** [comment] 2024-06-19 10:39
3.12.1 containing the fix is out!
