### ISSUE TITLE
Buggy animations on Android

### ISSUE THREAD

**Issue by akabolov** [software-mansion/react-native-reanimated#5324] opened 2023-10-28 13:15 UTC
### Description

I've provided a snack for testing - try to drag the modal up and down. The problem occurs only for Android, iOS is fine. I'm doing something wrong?

### Steps to reproduce

1. Drag the grey modal up and down
2. You will see buggy animation

### Snack or a link to a repository

https://snack.expo.dev/@akabolov/09dc26

### Reanimated version

3.3.0

### React Native version

0.72.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

None

### Build type

None

### Device

None

### Device model

Redmi 5, snack, simulators of pixel 7

### Acknowledgements

Yes

**Comment by akabolov** [comment] 2023-10-28 13:17
https://github.com/software-mansion/react-native-reanimated/assets/90328234/a6febca7-658b-44ca-9558-42d0f205d187

Here is the video of an issue

**Comment by piaskowyk** [comment] 2023-10-30 10:21
It seems that you doing every think fine. I will try to reproduce it on my device

**Comment by tjzel** [comment] 2023-10-30 16:56
This seems to me like a duplicate of #4625 - although it's weird that it happens on `transform`. @akabolov I suggest you try to reproduce this behavior without `react-native-reanimated` or `react-native-gesture-handler`, e.g. using https://reactnative.dev/docs/gesture-responder-system to see if it maybe stems from `react-native`

**Comment by akabolov** [comment] 2023-12-10 18:50
Was able to resolve this issue, for whatever reason pangestureHandler returns negative values for `event.changeY`
```
 WARN  35.755096435546875
 WARN  -33.794158935546875
 WARN  34.61865234375
 WARN  -32.508575439453125
 WARN  33.59465026855469
 WARN  -31.69097900390625
 WARN  34.2080078125
 WARN  -32.42152404785156
 WARN  33.884063720703125
 WARN  -32.86412048339844
 WARN  34.85052490234375
```
Adding a condition to check if this value is negative resolved my issue.
Not sure if I should create issue for pangestureHandler package

**Comment by szydlovsky** [comment] 2024-06-28 13:23
@akabolov sorry for late reply, but yes, please submit an issue to [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) 😄

**Closed by szydlovsky** 2024-06-28 13:23 UTC
Labels: Platform: Android, Reproducible 🎉, Repro provided
