### ISSUE TITLE
Reanimated Stops Working Completely on iOS

### ISSUE THREAD

**Issue by phantom-xrn** [software-mansion/react-native-reanimated#6371] opened 2024-08-04 01:30 UTC
### Description

Reanimated completely stops working after a while on production on iOS. I've attached a video and a minimum reproducible repo.

Some thoughts:
- This bug occurs 100 out of 100 times with Video but if you remove it, it only happens around 1 out of 100 times.
- Occurs with both react-native-video and expo-av.
- Once the bug occurs everything that touches reanimated stops working but everything else including the native Animated API works fine. 
- Only occurs on iOS on release mode on actual device.

https://github.com/user-attachments/assets/beb2353c-1e71-48c9-a118-d8e4d4366b2d

### Steps to reproduce

Clone https://github.com/phantom-xrn/reanimated-bug/tree/main

0. Run it on release mode on an 120hz iOS device(Replicated on 14 pro/15 pro/15 pro max but not on 12 mini/13)
1. Wait for the video to start playing.
2. Press and Long Press on the bottom two cards a few times.
3. Reanimated will stop working after a while. The buttons will not scale anymore when pressed and any component that uses reanimated like bottom sheets stop working.
4. Only error on Xcode console is `Unbalanced calls start/end for tag 19` 

### Snack or a link to a repository

https://github.com/phantom-xrn/reanimated-bug/tree/main

### Reanimated version

3.14.0

### React Native version

0.73.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

Iphone 15 Pro

### Acknowledgements

Yes

**Comment by phantom-xrn** [comment] 2024-08-04 01:43
Just added a $512 sponsorship and am happy to pay $128/hour for the time to fix this. This is affecting us in production and would really appreciate if you guys could prioritize the issue.

**Comment by tomekzaw** [comment] 2024-08-05 11:45
Hi @phantom-xrn, thanks for reporting this issue as well as preparing the minimal reproducible example.

Could you please contact us at projects@swmansion.com? We'd be happy to prioritize work this issue.

**Comment by bartlomiejbloniarz** [comment] 2024-08-22 18:55
Hi @phantom-xrn 

I prepared a PR #6442 that should resolve this issue. We might need some time to get it merged, since it has to do with an important part of our logic, you can use this patch on your app.
[react-native-reanimated+3.15.0.patch](https://github.com/user-attachments/files/16716333/react-native-reanimated%2B3.15.0.patch)

**Closed** 2024-08-28 10:32 UTC
Labels: Platform: iOS, Reproducible 🎉, Repro provided

**Comment by bartlomiejbloniarz** [comment] 2024-08-28 17:27
@phantom-xrn We just published a new version of reanimated ([3.15.1](https://www.npmjs.com/package/react-native-reanimated/v/3.15.1)) that includes this fix.
