### ISSUE TITLE
Deleting item in ScrollView create visual bug of last item in list on Android device 

### ISSUE THREAD

**Issue by QuangBinhDinh** [software-mansion/react-native-reanimated#3888] opened 2022-12-23 08:49 UTC
### Description

I watched this tutorial about handling animation when delete item in a list:  https://www.youtube.com/watch?v=p3BLiloo2UM . I already set up my code and it worked perfectly fine on iPhone (animation is smooth , no visual bug ). Then I switch to Android device and found this visual bug : 

https://user-images.githubusercontent.com/43164997/209303109-3e8156d0-f398-4793-82fa-96d0d1eff2b4.mp4

As you can see, when I delete an item (simply by touching the view), the last item split into half before fade animation go in. 

### Steps to reproduce

1. Follow the tutorial : https://www.youtube.com/watch?v=p3BLiloo2UM
2. Run the code and test on Android device (git link: https://github.com/enzomanuelmangano/animate-with-reanimated/tree/main/14-layout-animations). Code is from `App.tsx` file
3. While testing, touch any view to remove it from the list
4. The last item occurs visual bug, split into half

### Snack or a link to a repository

https://snack.expo.dev/@quangbinh1999/bug-reanimated

### Reanimated version

2.11.0

### React Native version

0.66.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Samsung M21

### Acknowledgements

Yes

**Comment by QuangBinhDinh** [comment] 2022-12-27 03:22
Any update on this ?

**Comment by tomekzaw** [comment] 2023-01-03 17:41
Hey, can you set some background color (e.g `yellow`) for the container? Maybe when you remove the item the height of the container immediately decreases and the last item is clipped?

**Comment by Latropos** [comment] 2023-05-10 10:43
It looks that the bug can't be reproduced with Reanimated 3.

**Comment by Latropos** [comment] 2024-03-05 10:16
Closing, since we are dropping support for Reanimated 2, and this problem is not reproducible with Reanimated 3

**Closed by Latropos** 2024-03-05 10:16 UTC
Labels: Platform: Android, 🏠  Reanimated 2, Needs review, Repro provided
