### ISSUE TITLE
Transitioning and Transition are missing from RN-reanimated 3.4.1

### ISSUE THREAD

**Issue by kapscudi** [software-mansion/react-native-reanimated#4865] opened 2023-08-02 09:02 UTC
### Description

I've created a new app to use RN new arch 0.72.x and moving code from RN 0.69.1 and RNReanimated 2.10.0, i've got Transition and Transitioning missing from the 3.4.1 module. How can i solve the problem?

### Steps to reproduce

1. create a new RN app
2. install RN Reanimated 3.4.1
3. install pods for RN New Arch
4. import {Transitioning, Transition} from 'react-native-reanimated';

### Snack or a link to a repository

none

### Reanimated version

3.4.1

### React Native version

0.72.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14

### Acknowledgements

Yes

**Comment by lkgithub** [comment] 2023-08-02 10:14
See https://github.com/software-mansion/react-native-reanimated/issues/4362

**Comment by kapscudi** [comment] 2023-08-02 13:57
here is the codes: 
old one : 
import {Transitioning, Transition, acc} from 'react-native-reanimated';
...
const transition = (
  <Transition.Together>
    <Transition.Out type="fade" durationMs={200} interpolation="easeOut" />
    <Transition.Change />
    <Transition.In type="fade" durationMs={200} interpolation="easeIn" />
  </Transition.Together>
);
...
const ref = useRef<any>();
return (<Transitioning.View
      ref={ref}
      transition={transition}
      style={styles.container}>

how to convert to use with rn reanimated 3.4.1?

**Comment by tjzel** [comment] 2023-08-03 08:46
@kapscudi It's explained with issue linked by @lkgithub. In your case it would something about the lines:
```TSX
return (
<Animated.View
  ref={ref}
  entering={FadeIn.duration(200).easing(Easing.out(Easing.ease))}
  exiting={FadeOut.duration(200).easing(Easing.in(Easing.ease))}
/>
```

Please visit [our new docs]https://reanimated-beta-docs.swmansion.com/docs/layout-animations/entering-exiting-animations since `LayoutAnimations` are described there very well!

Closing because duplicate of #4362.

**Closed by tjzel** 2023-08-03 08:46 UTC
Labels: Missing repro, Platform: iOS, Needs review

**Comment by kapscudi** [comment] 2023-08-03 09:08
> @kapscudi It's explained with issue linked by @lkgithub. In your case it would something about the lines:
> 
> ```tsx
> return (
> <Animated.View
>   ref={ref}
>   entering={FadeIn.duration(200).easing(Easing.out(Easing.ease))}
>   exiting={FadeOut.duration(200).easing(Easing.in(Easing.ease))}
>   style={styles.container}
> />
> ```
> 
> Please visit [our new docs]https://reanimated-beta-docs.swmansion.com/docs/layout-animations/entering-exiting-animations since `LayoutAnimations` are described there very well!
> 
> Closing because duplicate of #4362.

thx

**Comment by kapscudi** [comment] 2023-08-03 13:50
sorry to bother but i didn't found any clue for ref.current.animateNextTransition(). ? can you tell me what can i use instead?

**Comment by tjzel** [comment] 2023-08-03 13:57
This API is from `react-native`'s `Animated` API, not from `react-native-reanimated`. We don't support such syntax.

**Comment by SETAGI** [comment] 2023-10-26 16:23
Hi @kapscudi did you resolve your last question, if yes what was your approach?

**Comment by kapscudi** [comment] 2023-11-07 14:15
nope because i'm not transitioning. from a screen to another, i was transitioning from an accordion section. to. another lie. this code:

`const transition = (
  <Transition.Together>
    <Transition.Out type="fade" durationMs={200} interpolation="easeOut" />
    <Transition.Change />
    <Transition.In type="fade" durationMs={200} interpolation="easeIn" />
  </Transition.Together>
);

const Profile: React.FC = () => {
  const navigation = useNavigation();
  const dispatch = useAppDispatch();
  const {
    profileCreate,
    logout,
    resetPassword,
    updateProfileAvatar,
    getCurrentProfile,
    deleteAccount,
  } = bindActionCreators(actionCreators, dispatch);
  const screenWidth = Dimensions.get('window').width;
  const {user} = useAppSelector(state => state.auth);
  const {avatar, profile} = useAppSelector(state => state.profile);
  const ref = useRef<any>();
  const [selectedColor, setSelectedColor] = useState('');
  const [password, setPassword] = useState('');
  const [edit, setEdit] = useState(false);
  const [rePass, setRePass] = useState(false);
  const [file, setFile] = useState<any>();
  const [formData, setFormData] = useState<any>({
    bio: '',
    location: '',
    firstname: '',
    lastname: '',
    instagram: '',
  });
  // function dateCompare(item: string) {
  //   const today = new Date(Date.now()).toISOString();
  //   const date = new Date(item).toISOString();
  //   return today >= date;
  // }
  // const evntLib =
  //   profile !== null &&
  //   profile.events
  //     .map((item: any) => item.event)
  //     .filter((elmt: any) => dateCompare(elmt.date));

  useEffect(() => {
    navigation.setOptions({
      title: `${user.username}`,
    });
    if (profile !== null) {
      setEdit(true);
      setFormData({
        bio: profile.bio,
        location: profile.location,
        firstname: profile.firstname,
        lastname: profile.lastname,
        instagram: profile.instagram,
      });
    } else getCurrentProfile();
  }, [profile]);

  const {bio, location, firstname, lastname, instagram} = formData;

  function sendData() {
    profileCreate(formData, edit);
  }

  async function renewPic(item: any) {
    const data = new FormData();
    await data.append('avatar', {
      name: item.fileName,
      type: item.type,
      uri: Platform.OS === 'ios' ? item.uri.replace('file://', '') : item.uri,
    });
    await updateProfileAvatar(data);
    setFile('');
  }

  async function resetPass(e: any) {
    e.preventDefault();
    if (password.length > 6) {
      await resetPassword(password);
      setRePass(false);
    }
  }

  function deleteTheDish() {
    Alert.alert(
      'En mode suppression de compte',
      'Sûre de vouloir partir ? Note bien que toutes tes données et ta biblioteque seront supprimé!',
      [
        {
          text: 'Nah, je blague!',
          onPress: () => {},
          style: 'cancel',
        },
        {
          text: 'CIAO!',
          onPress: () => deleteAccount(),
        },
      ],
    );
  }

  const onOpenLink = async (url: string) => {
    await openLink(url, 'dark-content');
  };

  return (
    <Transitioning.View
      ref={ref}
      transition={transition}
      style={styles.container}>
      <TouchableOpacity
        activeOpacity={0.9}
        onPress={() => {
          ref.current.animateNextTransition();
          setSelectedColor('info' === selectedColor ? '' : 'info');
          setRePass(false);
        }}
        style={styles.cardContainer}>
        <View
          style={[
            styles.card,
            {backgroundColor: accordionStyle.compte.background},
          ]}>
          <Text style={[styles.category, {color: accordionStyle.compte.color}]}>
            compte
          </Text>
          {selectedColor === 'info' && (
            <>
              <View
                style={{
                  flexDirection: 'row',
                  alignItems: 'center',
                  marginTop: 20,
                }}>
                <Pressable
                  onPress={() => {
                    launchImageLibrary(
                      {
                        mediaType: 'photo',
                        selectionLimit: 1,
                        includeBase64: false,
                      },
                      (res: any) => {
                        if (res.assets) {
                          setFile(res.assets[0]);
                          renewPic(res.assets[0]);
                        }
                      },
                    );
                  }}>
                  <Image
                    style={styles.avatar}
                    loadingIndicatorSource={{uri: '../assets/logo.webp'}}
                    source={{
                      uri: `${
                        user.avatar && user.avatar.split('/')[0] === 'uploads'
                          ? servUrl
                          : 'https:'
                      }${avatar ? avatar : user?.avatar}`,
                    }}
                  />
                  <Icon
                    name="plus-circle"
                    size={30}
                    style={{
                      color: 'rgb(204, 53, 179)',
                      position: 'absolute',
                      top: 10,
                      left: 0,
                    }}
                  />
                </Pressable>
                <View style={{width: '55%', marginLeft: 20}}>
                  <Text
                    numberOfLines={1}
                    style={[styles.text, {color: accordionStyle.compte.color}]}>
                    NAME{' '}
                  </Text>
                  <Text
                    numberOfLines={1}
                    style={[
                      styles.subtext,
                      {
                        color: accordionStyle.compte.background,
                        backgroundColor: accordionStyle.compte.color,
                      },
                    ]}>
                    {firstname && lastname
                      ? `${firstname} ${lastname}`
                      : user.username}
                  </Text>
                  <Text
                    numberOfLines={1}
                    style={[styles.text, {color: accordionStyle.compte.color}]}>
                    EMAIL{' '}
                  </Text>
                  <Text
                    numberOfLines={1}
                    style={[
                      styles.subtext,
                      {
                        color: accordionStyle.compte.background,
                        backgroundColor: accordionStyle.compte.color,
                      },
                    ]}>
                    {' '}
                    {user.email}
                  </Text>
                  <Text
                    numberOfLines={1}
                    style={[styles.text, {color: accordionStyle.compte.color}]}>
                    MEMBRE{' '}
                  </Text>
                  <Text
                    numberOfLines={1}
                    style={[
                      styles.subtext,
                      {
                        color: accordionStyle.compte.background,
                        backgroundColor: accordionStyle.compte.color,
                      },
                    ]}>
                    {' '}
                    {moment(user?.date).locale('fr').fromNow()}
                  </Text>
                </View>
              </View>
              <View
                style={{
                  flexDirection: 'row',
                  justifyContent: 'center',
                  alignItems: 'center',
                  marginTop: 20,
                }}>
                <TouchableOpacity
                  style={[
                    styles.button,
                    {
                      backgroundColor: buttonStyles.pwdreset.background,
                    },
                  ]}
                  onPress={e => (rePass ? resetPass(e) : setRePass(true))}>
                  <Text
                    style={{
                      color: buttonStyles.pwdreset.color,
                      fontWeight: '600',
                      textAlign: 'center',
                    }}>
                    {rePass ? 'VALIDER' : 'RESET PASSWORD'}
                  </Text>
                </TouchableOpacity>
                {rePass ? (
                  <View>
                    <TextInput
                      style={[
                        styles.subtext2,
                        {
                          paddingVertical: Platform.OS === 'ios' ? 1 : 0,
                          color: accordionStyle.compte.background,
                          backgroundColor: accordionStyle.compte.color,
                        },
                      ]}
                      onChangeText={(text: any) => setPassword(text)}
                      value={password}
                      defaultValue={password}
                      placeholder="nouveau mot de passe"
                      keyboardType="default"
                      onSubmitEditing={Keyboard.dismiss}
                    />
                  </View>
                ) : (
                  <>
                    <TouchableOpacity
                      style={[
                        styles.button,
                        {backgroundColor: buttonStyles.logout.background},
                      ]}
                      onPress={() => {
                        logout();
                      }}>
                      <Text
                        style={{
                          color: buttonStyles.logout.color,
                          fontWeight: '600',
                        }}>
                        LOGOUT
                      </Text>
                    </TouchableOpacity>
                    <TouchableOpacity
                      style={[
                        styles.button,
                        {backgroundColor: buttonStyles.delete.background},
                      ]}
                      onPress={() => deleteTheDish()}>
                      <Text style={{color: 'white', fontWeight: '600'}}>
                        SUPPRIMER
                      </Text>
                    </TouchableOpacity>
                  </>
                )}
              </View>
            </>
          )}
        </View>
      </TouchableOpacity>
      {/* PROFILE */}
      <TouchableOpacity
        activeOpacity={0.9}
        onPress={() => {
          ref.current.animateNextTransition();
          setSelectedColor('profile' === selectedColor ? '' : 'profile');
        }}
        style={styles.cardContainer}>
        <View
          style={[
            styles.card,
            {backgroundColor: accordionStyle.profile.background},
          ]}>
          <Text
            style={[styles.category, {color: accordionStyle.profile.color}]}>
            profile
          </Text>
          {selectedColor === 'profile' && (
            <KeyboardAvoidingView
              behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
              style={{flexGrow: 1}}>
              <View style={{marginTop: 20}}>
                <View style={{flexDirection: 'row'}}>
                  <Text
                    style={[
                      styles.text,
                      {color: accordionStyle.profile.color},
                    ]}>
                    PRENOM
                  </Text>
                  <TextInput
                    style={[
                      styles.subtext,
                      {
                        paddingVertical: Platform.OS === 'ios' ? 1 : 0,
                        color: accordionStyle.profile.background,
                        backgroundColor: accordionStyle.profile.color,
                      },
                    ]}
                    onChangeText={(text: any) =>
                      setFormData({
                        ...formData,
                        firstname: text,
                      })
                    }
                    value={firstname}
                    defaultValue={firstname}
                    placeholder="ton prénom ici"
                    keyboardType="default"
                    onSubmitEditing={Keyboard.dismiss}
                  />
                </View>
                <View style={{flexDirection: 'row'}}>
                  <Text
                    style={[
                      styles.text,
                      {color: accordionStyle.profile.color},
                    ]}>
                    NOM
                  </Text>
                  <TextInput
                    style={[
                      styles.subtext,
                      {
                        paddingVertical: Platform.OS === 'ios' ? 1 : 0,
                        color: accordionStyle.profile.background,
                        backgroundColor: accordionStyle.profile.color,
                      },
                    ]}
                    editable
                    onChangeText={(text: any) =>
                      setFormData({
                        ...formData,
                        lastname: text,
                      })
                    }
                    value={lastname}
                    defaultValue={lastname}
                    placeholder="ton nom ici"
                    keyboardType="default"
                    onSubmitEditing={Keyboard.dismiss}
                  />
                </View>
                <View style={{flexDirection: 'row'}}>
                  <Text
                    style={[
                      styles.text,
                      {color: accordionStyle.profile.color},
                    ]}>
                    LOCATION
                  </Text>
                  <TextInput
                    style={[
                      styles.subtext,
                      {
                        paddingVertical: Platform.OS === 'ios' ? 1 : 0,
                        color: accordionStyle.profile.background,
                        backgroundColor: accordionStyle.profile.color,
                      },
                    ]}
                    editable
                    onChangeText={(text: any) =>
                      setFormData({
                        ...formData,
                        location: text,
                      })
                    }
                    value={location}
                    defaultValue={location}
                    placeholder="t'es d'où?"
                    keyboardType="default"
                    onSubmitEditing={Keyboard.dismiss}
                  />
                </View>
                <View style={{flexDirection: 'row'}}>
                  <Text
                    style={[
                      styles.text,
                      {color: accordionStyle.profile.color},
                    ]}>
                    <Icon name="instagram" size={20} />
                  </Text>
                  <TextInput
                    style={[
                      styles.subtext,
                      {
                        paddingVertical: Platform.OS === 'ios' ? 1 : 0,
                        color: accordionStyle.profile.background,
                        backgroundColor: accordionStyle.profile.color,
                      },
                    ]}
                    editable
                    onChangeText={(text: any) =>
                      setFormData({
                        ...formData,
                        instagram: text,
                      })
                    }
                    value={instagram}
                    defaultValue={instagram}
                    placeholder="@instagram?"
                    keyboardType="default"
                    onSubmitEditing={Keyboard.dismiss}
                  />
                </View>
                <View style={{flexDirection: 'row'}}>
                  <Text
                    style={[
                      styles.text,
                      {color: accordionStyle.profile.color},
                    ]}>
                    BIO
                  </Text>
                  <TextInput
                    style={[
                      styles.subtext,
                      {
                        paddingVertical: Platform.OS === 'ios' ? 1 : 0,
                        width: '80%',
                        height: 95,
                        color: accordionStyle.profile.background,
                        backgroundColor: accordionStyle.profile.color,
                      },
                    ]}
                    multiline
                    numberOfLines={5}
                    editable
                    onChangeText={(text: any) =>
                      setFormData({
                        ...formData,
                        bio: text,
                      })
                    }
                    value={bio}
                    defaultValue={bio}
                    placeholder="entrer une bio de min 6 charactères"
                    keyboardType="default"
                    onSubmitEditing={Keyboard.dismiss}
                  />
                </View>
                <View
                  style={{
                    flexDirection: 'row',
                    marginTop: contentScaler(20),
                    justifyContent: 'center',
                    marginBottom:
                      Platform.OS === 'android' ? contentScaler(10) : 0,
                  }}>
                  <TouchableOpacity
                    style={[
                      styles.button,
                      {backgroundColor: buttonStyles.add.background},
                    ]}
                    onPress={() => sendData()}>
                    <Text
                      style={{
                        color: buttonStyles.add.color,
                        fontWeight: '600',
                      }}>
                      {!edit ? 'CREER' : 'MODIFIER'}
                    </Text>
                  </TouchableOpacity>
                  <TouchableOpacity
                    style={[
                      styles.button,
                      {backgroundColor: buttonStyles.like.background},
                    ]}
                    onPress={() =>
                      onOpenLink('https://kapscudi.github.io/privacy/')
                    }>
                    <Text
                      style={{
                        color: buttonStyles.like.color,
                        fontWeight: '600',
                      }}>
                      DATA & VIE PRIVÉE
                    </Text>
                  </TouchableOpacity>
                </View>
              </View>
            </KeyboardAvoidingView>
          )}
        </View>
      </TouchableOpacity>
      {/* AUDIO */}
      <TouchableOpacity
        activeOpacity={0.9}
        onPress={() => {
          ref.current.animateNextTransition();
          setSelectedColor('audio' === selectedColor ? '' : 'audio');
        }}
        style={styles.cardContainer}>
        <View
          style={[
            styles.card,
            {backgroundColor: accordionStyle.audioCollect.background},
          ]}>
          <Text
            style={[
              styles.category,
              {color: accordionStyle.audioCollect.color},
            ]}>
            collection audio
          </Text>
          {selectedColor === 'audio' && (
            <View style={{marginTop: 20}}>
              {profile !== null && profile.library.length > 0 ? (
                <View style={{width: screenWidth, height: 100}}>
                  <Carousel
                    data={profile.library}
                    url={servUrl}
                    spot="profile"
                  />
                </View>
              ) : (
                <Text
                  style={[
                    styles.topic,
                    {color: accordionStyle.audioCollect.color},
                  ]}>
                  {profile !== null
                    ? 'aucune sauvegarde...'
                    : 'aucun profile créé! Créé ton profile pour pouvoir savegarder tes podcasts!'}
                </Text>
              )}
            </View>
          )}
        </View>
      </TouchableOpacity>
      {/* EVENT CAL */}
      <TouchableOpacity
        activeOpacity={0.9}
        onPress={() => {
          ref.current.animateNextTransition();
          setSelectedColor('event' === selectedColor ? '' : 'event');
        }}
        style={styles.cardContainer}>
        <View
          style={[
            styles.card,
            {backgroundColor: accordionStyle.eventSaved.background},
          ]}>
          <Text
            style={[styles.category, {color: accordionStyle.eventSaved.color}]}>
            events
          </Text>
          {selectedColor === 'event' && (
            <View style={{marginTop: 20}}>
              {profile !== null && profile.events.length > 0 ? (
                <View style={{width: screenWidth, height: 100}}>
                  <Carousel
                    data={profile.events}
                    url={servUrl}
                    spot="profEvent"
                  />
                </View>
              ) : (
                <Text
                  style={[
                    styles.topic,
                    {color: accordionStyle.eventSaved.color},
                  ]}>
                  {profile !== null
                    ? 'aucune sauvegarde...'
                    : 'aucun profile créé! Créé ton profile pour pouvoir savegarder tes events !'}
                </Text>
              )}
            </View>
          )}
        </View>
      </TouchableOpacity>
    </Transitioning.View>
  );
};

export default Profile;

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  cardContainer: {
    flexGrow: 1,
  },
  card: {
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: 1,
  },
  category: {
    fontSize: contentScaler(32),
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: -2,
  },
  topic: {
    fontSize: contentScaler(18),
    textAlign: 'center',
    lineHeight: contentScaler(18 * 1.5),
  },
  text: {fontSize: 18, fontWeight: 'bold', marginRight: 10, marginBottom: 5},
  subtext: {
    fontSize: contentScaler(18),
    fontWeight: '600',
    paddingLeft: contentScaler(10),
    paddingRight: contentScaler(10),
    borderRadius: contentScaler(9),
    maxWidth: '80%',
    marginBottom: contentScaler(5),
  },
  subtext2: {
    fontSize: contentScaler(18),
    borderRadius: contentScaler(9),
    fontWeight: '600',
    paddingHorizontal: contentScaler(10),
    height: contentScaler(36),
    //maxWidth: '90%',
    //marginBottom: contentScaler(5),
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 99,
  },
  button: {padding: 10, borderRadius: 9, marginHorizontal: 5},
  epCover: {width: 50, height: 50, resizeMode: 'contain'},
});`
