### ISSUE TITLE
App started crashing with the errors mentioned on description

### ISSUE THREAD

**Issue by tusharkhatiwada** [software-mansion/react-native-reanimated#2361] opened 2021-09-03 07:33 UTC
## Description
App was working perfectly fine earlier. The next day when I tried to run the project, I started getting the following errors:

> Error: If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation, js engine: hermes
> 
> Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
>       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

I tried to reinstall the package but still getting these errors. I followed the documentation for installation.

If I remove the imports from react-native-reanimated, the app works.

### Expected behavior

The app should run without the above errors.

## Snack or minimal code example
**babel.config.js**

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['.'],
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
        ],
        alias: {
          '@screens': './src/screens',
          '@constants': './src/constants',
          '@components': './src/components',
          '@images': './src/assets/images',
          '@api': './src/api',
        },
      },
    ],
    'react-native-reanimated/plugin',
  ],
};
```
**Podfile**

```
use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )
```

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.3.0-alpha.2
- NodeJS: 12.14.0
- Xcode: 12.5.1

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by rvasseur31** [comment] 2021-09-03 10:47
I am using yarn

try to execute this command : watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache

**Comment by tusharkhatiwada** [comment] 2021-09-04 06:45
@rvasseur31 Not working. Cleared the cache and still the same problem

**Comment by wendan52** [comment] 2021-09-07 09:01
> @rvasseur31 Not working. Cleared the cache and still the same problem

have you fix this problem?

**Comment by mysport12** [comment] 2021-09-07 14:02
Try running yarn upgrade and see if that helps.

**Comment by BECkvalentine** [comment] 2021-09-22 22:02
I was running into a similar issue as well and what fixed it for me was removing `module:metro-react-native-babel-preset`

I am using expo so I am using the babel-preset-expo preset.  Below is how my babel config is

`
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: ["react-native-reanimated/plugin"],
  };
};

`

Not sure why that fixed things for me but maybe it might help someone else running into this issue

**Comment by jkadamczyk** [comment] 2022-01-28 10:21
Hi @tusharkhatiwada 

I had a very similar issue myself and it was something with the Babel preset. I can't help you directly since I don't remember how I fixed it because it was a long time ago.

What I would suggest if you would like us to help you is, try stripping everything from the app you are working on so that you are not leaking any sensitive info and any code that you can't show us and making it so that you leave the configuration, so that we can reproduce the configuration issue you have.

If you managed to fix the issue please, share with others what was helpful for you.

Until then I will close the issue, thank you for reporting and have a good day 😊

**Closed by jkadamczyk** 2022-01-28 10:21 UTC
Labels: 🐞 Bug, 🏠  Reanimated2
