### ISSUE TITLE
withTiming callback function is called multiple times

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#1241] opened 2020-09-17 12:57 UTC
## Description

**Short:** If duration is `250` or similar value - `withTiming` callback is called **multiple times**. That breaks animation.

I use `withTiming` to detect when animation is finished. And if animation is completed successfully I call callback `_onSwipeRight`.

```ts
  const containerStyle = useAnimatedStyle(() => {
    return {
      height:
        rowHeight.value !== undefined
          ? withTiming(
              rowHeight.value,
              {
                duration: 250,
                easing: Easing.out(Easing.ease)
              },
              (isFinished) => {
                console.log(`withTiming is finished? ${isFinished}`);
                if (isFinished) {
                  if (swipeDirection.value === 'left') {
                    onSwipeLeft();
                  } else if (swipeDirection.value === 'right') {
                    console.log(
                      `SwipableRow: isFinished? ${isFinished}, rowHeight: ${rowHeight.value}`
                    );
                    _onSwipeRight && _onSwipeRight();
                  }
                }
              }
            )
          : undefined
    };
  });
```

Later inside this `_onSwipeRight()` I update sqlite database (mark task as _completed_) and unmount component (render **undefined** instead of task - at this time `height` of row should be `0`)

```ts
  const [isVisible, setVisible] = useState(true);
  const onTaskCompletion = useCallbackOne(
    (id: string) => {
      console.log(`[onTaskCompletion] complete task ${id}`);
      taskRepository.update(id, { isCompleted: true }).then((_) => {
        setVisible(false);
      });
    },
    [taskRepository]
  );
  ...
  return (
    <>
      {isVisible ? (
        <SwipableTask
          id={state.id}
          title={state.title}
          isCompleted={state.isCompleted}
          isTracked={state.isTracked}
          trackedSeconds={state.trackedSeconds}
          onCompletionButtonPressed={onCompletionButtonPressed}
          onTrackButtonPressed={onTrackButtonPressed}
          onCompletionSwipe={onTaskCompletion}
        />
      ) : undefined}
    </>
  );
```

If I use duration `150` or `300` for `withTiming` I see expected behaviour and logging. But for `250` milliseconds

```bash
[Thu Sep 17 2020 15:19:49.708]  LOG      withTiming is finished? true // <-- First call
[Thu Sep 17 2020 15:19:49.710]  LOG      SwipableRow: isFinished? true, rowHeight: 0
[Thu Sep 17 2020 15:19:49.710]  LOG      [onTaskCompletion] complete task f2dcb1fa-7531-4b1e-a63c-dbf713589c22
[Thu Sep 17 2020 15:19:49.711]  INFO     query:  UPDATE "tasks" SET "isCompleted" = ? WHERE "id" IN (?) -- PARAMETERS: [1,"f2dcb1fa-7531-4b1e-a63c-dbf713589c22"]
[Thu Sep 17 2020 15:19:49.729]  LOG      Row: isVisible? false, id [f2dcb1fa-7531-4b1e-a63c-dbf713589c22], title [Task 11]
[Thu Sep 17 2020 15:19:49.987]  LOG      withTiming is finished? true // <-- Second call
[Thu Sep 17 2020 15:19:49.989]  LOG      SwipableRow: isFinished? true, rowHeight: 0
[Thu Sep 17 2020 15:19:49.990]  LOG      [onTaskCompletion] complete task f2dcb1fa-7531-4b1e-a63c-dbf713589c22
[Thu Sep 17 2020 15:19:49.991]  INFO     query:  UPDATE "tasks" SET "isCompleted" = ? WHERE "id" IN (?) -- PARAMETERS: [1,"f2dcb1fa-7531-4b1e-a63c-dbf713589c22"]
[Thu Sep 17 2020 15:19:49.997]  LOG      Row: isVisible? false, id [f2dcb1fa-7531-4b1e-a63c-dbf713589c22], title [Task 11]
```

### Screenshots
<table>
  <tr>
    <td>250 ms</td>
     <td>300 ms</td>
     <td>150 ms</td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/842306/93471096-934d0700-f8fb-11ea-86fa-87ac1a4ecfb1.gif" width=270 height=480></td>
    <td><img src="https://user-images.githubusercontent.com/842306/93471102-9516ca80-f8fb-11ea-8673-c094e6f27747.gif" width=270 height=480></td>
    <td><img src="https://user-images.githubusercontent.com/842306/93471105-9647f780-f8fb-11ea-93cc-e8a2a53a3b3d.gif" width=270 height=480></td>
  </tr>
 </table>

### Expected behavior

Callback is called only once.

### Actual behavior

Callback might be called multiple times.

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.6

**Comment by piaskowyk** [comment] 2020-11-20 10:41
Hey @likern
Thanks for your report. It was a bug but this issue is resolved in a newer release. if you still have a problem try a newer version of reanimated. I tested this on alpha.9 and it works.

**Closed by piaskowyk** 2020-11-20 10:41 UTC
Labels: Reanimated2, 🐞 Bug

**Comment by facuescobar** [comment] 2022-05-28 16:11
Hi, this ticket should be reopened.

withTimingCallback function is still being called multiple times.|

Code
```
isFinished => {
    console.log('animationEnd', isFinished)
}, 
```

Log:
```
 LOG  animationEnd true
 LOG  animationEnd true
 LOG  animationEnd true
```

Lib Version
```
    "react": "17.0.1",
    "react-native": "0.66.0",
    "react-native-reanimated": "^2.8.0",
```

**Comment by thisisadarshjais** [comment] 2023-02-28 07:35
Any update on this?

**Comment by adamsolomon1986** [comment] 2023-04-17 21:37
+1 still happening

**Comment by mpvdk** [comment] 2023-06-05 19:16
Also having this issue

**Comment by thisisadarshjais** [comment] 2023-06-06 07:12
+1 having this issue

**Comment by piaskowyk** [comment] 2023-08-08 13:43
@jannesiera Could you provide a reproduction?

**Comment by jannesiera** [comment] 2023-08-08 13:48
@piaskowyk I don't have time to set something up for you, but should be easily reproducable by just trying `shared.value = withTiming(100, { duration: 3000, easing: Easing.in(Easing.linear) }, (finished) => { console.log(finished) });`

Basically what @facuescobar said.

**Comment by jannesiera** [comment] 2023-08-08 13:52
If it helps the component this line is in gets rerender every X seconds (because of data being polled).

**Comment by jannesiera** [comment] 2023-09-14 11:29
As multiple people are running into this issue I suggest it should be re-opened.

**Comment by piaskowyk** [comment] 2023-09-28 13:46
I've tried to reproduce it but it works without any problems

**Comment by macstr1k3r** [comment] 2023-11-19 12:44
+1

**Comment by YaoHuiJi** [comment] 2023-12-03 15:53
still exists

**Comment by RajThapa7** [comment] 2023-12-20 08:06
issue still exists

**Comment by oliviercperrier** [comment] 2024-03-15 16:38
Still an issue

**Comment by nguyenhoanghung99** [comment] 2024-04-09 01:42
Still an issue
