### ISSUE TITLE
Does useAnimatedStyle have access to component props?

### ISSUE THREAD

**Issue by MinimogDev** [software-mansion/react-native-reanimated#1014] opened 2020-07-23 13:43 UTC
## Description
I am passing a prop to my component named `reversed`. It's a boolean and I want to adjust animation logic based on this prop. Whenever I log it inside `useAnimatedStyle` callback it is always `undefined` even though it is defined in component itself. I tried to pass it to `useSharedValue` but still had not luck.

I am not sure if this is a bug or me miss-using / miss-understanding these hooks, so decided to open this issue as a question.

With code below I get console output like following:
```zsh
outside true
inside undefined
```

## Code

```js
function MyComponent({ reversed }) {
   console.log('outside', reversed);
   const animation = useSharedValue(0);
   const animation = useAnimatedStyle(() => {
       return {
           height: withTiming(animated.value, null, () => console.log('inside', reversed));
       };
   });

   /* rest */
}
```

### Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: alpha

**Comment by terrysahaidak** [comment] 2020-07-24 06:19
Could you try to define callback outside of useAnimatedStyle? I thing this should work.

But still it seems like a bug. 
There is some babel magic behind capturing all the variables used inside useAnimatedStyle hook. Maybe it messed around with this reversed variable.

**Comment by MinimogDev** [comment] 2020-07-24 08:59
@terrysahaidak Just tried with callback being outside, same result

**Comment by terrysahaidak** [comment] 2020-07-24 18:09
I couldn't reproduce this issue. What exact version of Reanimated2 did you use? Make sure you used Reanimated's babel plugin.

**Comment by MinimogDev** [comment] 2020-07-27 10:15
@terrysahaidak latest alpha. I will try to replicate it outside of my project today and make a snack.

**Comment by jakub-gonet** [comment] 2020-07-27 10:40
Snack won't help here, as the Reanimated alpha isn't included in the expo at the moment. Just paste the entire code here in the code block.

**Comment by MinimogDev** [comment] 2020-07-27 11:30
@jakub-gonet it's pretty much all here https://github.com/software-mansion/react-native-reanimated/issues/1014#issuecomment-663427421 I'm in clean react native 0.63.2 project with only addition being reanimated's babel plugin. Also using typescript.

**Comment by terrysahaidak** [comment] 2020-07-27 13:43
Or would be cool to have a repository reproducing this so we can see the same result you have with the same env.

**Comment by MinimogDev** [comment] 2020-07-29 12:36
@terrysahaidak did you try to reproduce it on master or latest alpha? Repo I am seeing this in is private so I can't share it, I need to find some time and set up small reproduction repo, prob this weekend. But I am reliably able to reproduce this in different scenarios using different variable names / values.

Not sure if related but I also noticed that when I wrap animation functions like `withTiming` inside `delay` then animation callback is not triggered at all.

**Comment by terrysahaidak** [comment] 2020-07-29 13:40
I tested this on latest alpha as well as on master branch. Also, I didn't see this behavior previously.

**Comment by jakub-gonet** [comment] 2020-07-29 14:42
@MinimogDev, could you at least share your babel config? This is likely connected with the plugin setup.

**Comment by MinimogDev** [comment] 2020-07-30 07:01
@jakub-gonet sure, here it is

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['.'],
        extensions: ['.ts', '.tsx', '.json'],
        alias: {
          $app: './src',
          $images: './assets/images'
        }
      }
    ],
    'react-native-reanimated/plugin'
  ]
};
```

Related `package.json` entries

```
"@babel/core": "^7.10.5",
"@babel/runtime": "^7.10.5",
"react-native-reanimated": "alpha",
"react-native": "0.63.2",
"babel-plugin-module-resolver": "^4.0.0",
"metro-react-native-babel-preset": "^0.59.0"
```

I guess module resolver plugin could have something to do here? Other than that this is a pretty standard non-monorepo react native setup

**Comment by karol-bisztyga** [comment] 2020-09-17 10:57
This apparently has been fixed by the way in on of the alpha versions that have been released since this was reported.
This code works just fine:
```
import Animated, {
  withTiming,
  useAnimatedStyle,
} from 'react-native-reanimated';
import { View, Button } from 'react-native';
import React, { useState } from 'react';

function MyComponent({ reversed }) {
   console.log('outside', reversed);
   const styles = useAnimatedStyle(() => {
     const h = (reversed) ? 200 : 300;
       return {
          height: withTiming(h, null, () => console.log('inside', reversed)),
       };
   });

   return (
     <View>
       <Animated.View style={[{width: 100, height: 100, backgroundColor: 'orange'}, styles]} />
     </View>
   )
}

export default function Parent() {
  const [state, setState] = useState(false);

  console.log('render parent ' + state)

  return (
    <View>
      <Button title="change state" onPress={()=>{
        setState(!state)
      }} />
      <MyComponent reversed={ state } />
    </View>
  );
}

```

**Comment by karol-bisztyga** [comment] 2020-09-17 10:57
@MinimogDev can this issue be closed?

**Comment by terrysahaidak** [comment] 2020-09-17 11:01
@karol-bisztyga I would suggest to at least pass reversed directly to dependencies, so it's more clear why it's working. By default if I remember correctly it will recreate animated styles on each render that may create additional problems.

**Comment by karol-bisztyga** [comment] 2020-09-17 11:15
> @karol-bisztyga I would suggest to at least pass reversed directly to dependencies, so it's more clear why it's working. By default if I remember correctly it will recreate animated styles on each render that may create additional problems.

What difference would it make if `reversed` was passed to dependencies or not(besides clarity)?
What problems may come up when recreating animated styles on every render?

**Comment by terrysahaidak** [comment] 2020-09-17 12:11
> What difference would it make if `reversed` was passed to dependencies or not(besides clarity)?
> What problems may come up when recreating animated styles on every render? 

At least for future readers. There is not mention about dependencies and why it works in documentation at the moment. But also it might be a problem for something more "real life" :)

I had to pass ty arrays for each of my hook to avoid some of the bugs after upgrading. But I'm agree my usecase are way far from most of the users. But still less magic is better :)

**Closed** 2020-10-20 07:20 UTC
Labels: Reanimated2, ❓Question
