### ISSUE TITLE
[3.4] Fails to build in expo eas

### ISSUE THREAD

**Issue by 0xAsimetriq** [software-mansion/react-native-reanimated#4831] opened 2023-07-27 05:48 UTC
### Description

Following error is logged during build

```zsh
❌  (node_modules/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm:63:15)

  61 | {
  62 | #if __has_include(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED
> 63 |   reanimated::REAInitializer(bridge);
     |               ^ no type named 'REAInitializer' in namespace 'reanimated'
  64 | #endif // __has_inclide(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED
  65 | 
  66 |   return [super jsExecutorFactoryForBridge:bridge];
```

### Steps to reproduce

Build project on 3.4 in expo's eas. Issue is fixed by reverting back to 3.3.x version

### Snack or a link to a repository

https://github.com/expo/expo

### Reanimated version

3.4.0

### React Native version

0.72.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

None

### Acknowledgements

Yes

**Comment by tjzel** [comment] 2023-07-27 08:49
Hi @0xAsimetriq. Relevant [fix](https://github.com/expo/expo/pull/23726) was already merged into expo.

**Comment by thefranfran** [comment] 2023-07-29 09:36
Same issue here on 3.4.1 reanimated & expo ~49.0.6

**Comment by robertherber** [comment] 2023-07-31 18:03
@thefranfran For some reason expo-dev-client still has 2.4.7 (which includes the fix) [tagged as next version](https://www.npmjs.com/package/expo-dev-client?activeTab=versions). To fix it install version 2.4.7 explicitly.

**Comment by jingp-ofload** [comment] 2023-08-23 03:23
Same here

**Comment by Dankniel** [comment] 2023-08-28 00:07
I fixed this by adding `"expo-dev-launcher": "^3.0.0"` in my Package.json

**Comment by piaskowyk** [comment] 2023-08-28 07:57
Thanks for confirming that update helps!

**Closed** 2023-08-28 07:57 UTC
Labels: Missing repro, Platform: iOS, Needs review

**Comment by outaTiME** [comment] 2023-08-28 23:58
sadly it keeps happening in `expo-dev-client": "~2.4.8"`, (for the moment) I reverted to version `~3.3.0` of reanimated

**Comment by dakshshah96** [comment] 2023-08-29 06:16
@piaskowyk I believe this issue should be reopened.

iOS builds fail on `expo-dev-client: 2.4.8` and `react-native-reanimated: 3.4.2`.

```
CompileC /Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/Objects-normal/arm64/EXRCTAppDelegateInterceptor.o /Users/expo/workingdir/build/node_modules/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'expo-dev-launcher' from project 'Pods')
    cd /Users/expo/workingdir/build/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/expo/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos16.4-20E238-.sdkstatcache -target arm64-apple-ios13.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c++17 -stdlib\=libc++ -fobjc-arc -fmodules -fmodules-cache-path\=/Users/expo/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/expo/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=EXDevLauncher -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DEX_DEV_LAUNCHER_VERSION\=2.4.10 -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -iquote /Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/expo-dev-launcher-generated-files.hmap -I/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/expo-dev-launcher-own-target-headers.hmap -I/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/expo-dev-launcher-all-non-framework-target-headers.hmap -ivfsoverlay /Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/all-product-headers.yaml -iquote /Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/expo-dev-launcher-project-headers.hmap -I/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/expo-dev-launcher/include -I/Users/expo/workingdir/build/ios/Pods/Headers/Private -I/Users/expo/workingdir/build/ios/Pods/Headers/Private/expo-dev-launcher -I/Users/expo/workingdir/build/ios/Pods/Headers/Public -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/DoubleConversion -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/ExpoModulesCore -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/FBLazyVector -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/RCT-Folly -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/RCTRequired -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/RCTTypeSafety -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-Codegen -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-Core -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-NativeModulesApple -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-RCTBlob -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-callinvoker -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-cxxreact -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-debug -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-hermes -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-jsi -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-jsiexecutor -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-jsinspector -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-logger -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-perflogger -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-runtimeexecutor -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-runtimescheduler -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-utils -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/ReactCommon -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/Yoga -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/expo-dev-launcher -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/expo-dev-menu -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/fmt -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/glog -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/hermes-engine -I/Users/expo/workingdir/build/ios/Pods/Headers/Private/React-Core -I/Users/expo/workingdir/build/ios/Pods/Headers/Public/RNReanimated -I/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/EXManifests/Swift\ Compatibility\ Header -I/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/EXUpdatesInterface/Swift\ Compatibility\ Header -I/Users/expo/workingdir/build/ios/Pods/boost -I/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/DerivedSources-normal/arm64 -I/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/DerivedSources/arm64 -I/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/DerivedSources -F/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/expo-dev-launcher -F/Users/expo/workingdir/build/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal -F/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/XCFrameworkIntermediates/hermes-engine/Pre-built -F/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/RNReanimated -fmodule-map-file\=/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/EXManifests/EXManifests.modulemap -fmodule-map-file\=/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/EXUpdatesInterface/EXUpdatesInterface.modulemap -fmodule-map-file\=/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap -fmodule-map-file\=/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/expo-dev-menu-interface/EXDevMenuInterface.modulemap -fmodule-map-file\=/Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/BuildProductsPath/Debug-iphoneos/expo-dev-menu/EXDevMenu.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/React-Core/React/React-Core.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/React_Codegen/React-Codegen.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/React_NativeModulesApple/React-NativeModulesApple.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/React_RCTAppDelegate/React-RCTAppDelegate.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/folly/RCT-Folly.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/react_debug/React-debug.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/react_utils/React-utils.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/reacthermes/React-hermes.modulemap -fmodule-map-file\=/Users/expo/workingdir/build/ios/Pods/Headers/Public/yoga/Yoga.modulemap -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -Wno-comma -Wno-shorten-64-to-32 -include /Users/expo/workingdir/build/ios/Pods/Target\ Support\ Files/expo-dev-launcher/expo-dev-launcher-prefix.pch -MMD -MT dependencies -MF /Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/Objects-normal/arm64/EXRCTAppDelegateInterceptor.d --serialize-diagnostics /Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/Objects-normal/arm64/EXRCTAppDelegateInterceptor.dia -c /Users/expo/workingdir/build/node_modules/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm -o /Users/expo/Library/Developer/Xcode/DerivedData/TiltDev-gxbhxovynhpdomejllsxpjfmgnxn/Build/Intermediates.noindex/ArchiveIntermediates/TiltDev/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/expo-dev-launcher.build/Objects-normal/arm64/EXRCTAppDelegateInterceptor.o
In file included from /Users/expo/workingdir/build/node_modules/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm:3:
In file included from /Users/expo/workingdir/build/ios/Pods/Headers/Private/expo-dev-launcher/EXDevLauncher/EXRCTAppDelegateInterceptor.h:2:
/Users/expo/workingdir/build/ios/Pods/Headers/Public/expo-dev-menu/EXDevMenu/DevClientAppDelegate.h:13:14: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
- (RCTBridge *)createBridgeAndSetAdapterWithLaunchOptions:(NSDictionary *_Nullable)launchOptions;
             ^
/Users/expo/workingdir/build/ios/Pods/Headers/Public/expo-dev-menu/EXDevMenu/DevClientAppDelegate.h:13:14: note: insert '_Nullable' if the pointer may be null
- (RCTBridge *)createBridgeAndSetAdapterWithLaunchOptions:(NSDictionary *_Nullable)launchOptions;
             ^
              _Nullable
/Users/expo/workingdir/build/ios/Pods/Headers/Public/expo-dev-menu/EXDevMenu/DevClientAppDelegate.h:13:14: note: insert '_Nonnull' if the pointer should never be null
- (RCTBridge *)createBridgeAndSetAdapterWithLaunchOptions:(NSDictionary *_Nullable)launchOptions;
             ^
              _Nonnull
/Users/expo/workingdir/build/node_modules/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm:63:15: error: no type named 'REAInitializer' in namespace 'reanimated'
  reanimated::REAInitializer(bridge);
  ~~~~~~~~~~~~^
1 warning and 1 error generated.
```

**Comment by christiantakle** [comment] 2023-08-30 16:17
So I made a simple test.

* create a folder "package-test" + cd into it
* npm install a@npm:expo-dev-launcher@2.4.9
* npm install b@npm:expo-dev-launcher@2.4.10
* git diff node_modules/{a,b}/ios/EXRCTAppDelegateInterceptor.mm

```patch
diff --git a/node_modules/a/ios/EXRCTAppDelegateInterceptor.mm b/node_modules/b/ios/EXRCTAppDelegateInterceptor.mm
index 7776439..d9d8c89 100644
--- a/node_modules/a/ios/EXRCTAppDelegateInterceptor.mm
+++ b/node_modules/b/ios/EXRCTAppDelegateInterceptor.mm
@@ -59,12 +59,9 @@

 - (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
 {
-#if __has_include(<RNReanimated/REAInitializer.h>) \
-  && __has_include(<RNReanimated/UIResponder+Reanimated.h>) /* removed in react-native-reanimated@3.4.0 */ \
-  && !RCT_NEW_ARCH_ENABLED
-  // required and available only for react-native-reanimated < 3.4.0
+#if __has_include(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED
   reanimated::REAInitializer(bridge);
-#endif
+#endif // __has_inclide(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED

   return [super jsExecutorFactoryForBridge:bridge];
 }
```

Went back to my project with `expo-dev-client": "2.4.8"` mutated `node_modules/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm` with code from @2.4.9 and it works.

So I assume its a regression in `expo-dev-launcher@{2.4.9=>2.4.10}`.

One could add a patch or just downgrade to `expo-dev-client": "2.4.7"` where `expo-dev-launcher@2.4.9` is a transitive dependency. 

Would expect a `expo-dev-client": "2.4.9"` with a fix.

I don't know enough about the project or Objective-c to know if I'm missing something.

**Comment by piaskowyk** [comment] 2023-08-31 08:57
I have prepared PR to expo to fix this issue - https://github.com/expo/expo/pull/23726. Patch should be available in the newest version of expo-dev-client.

**Comment by christiantakle** [comment] 2023-08-31 09:23
Newest as in `expo-dev-client@2.4.8` because that doesn't work or newest as `expo-dev-client@next ~ 3.0.0`?

Where "doesn't work" is:
```
expo prebuild --platform ios --clean
 ```
 try to build in xcode and I get the error mentioned in this issue.

**Comment by wcastand** [comment] 2023-08-31 11:31
the fix is not published yet guys, when he says newest i assumed it meant the next released version. 2.4.8 is 9 days old so i don't think it's in when he poste 2 hours ago.

most likely be in 2.4.9

**Comment by christiantakle** [comment] 2023-08-31 11:58
Maybe; My confusing is from
> @[lukmccall](https://github.com/lukmccall) lukmccall merged commit [e4df60a](https://github.com/expo/expo/commit/e4df60a48a21ac7e714a65e8013f792f8969ac42) into expo:main [on Jul 26](https://github.com/expo/expo/pull/23726#event-9924027292)

from: https://github.com/expo/expo/pull/23726

Which is older than the expo-dev-client@2.4.8 release and when you click the pr you see it have the "published" label implying that the changes should be on npmjs.

Anywho feel this belong to an expo issue and not react-native-reanimated.

**Comment by jadiaheno** [comment] 2023-09-06 20:38
> I fixed this by adding `"expo-dev-launcher": "^3.0.0"` in my Package.json

Fixed my issue.

**Comment by Aryk** [comment] 2023-09-07 23:07
`    "expo-dev-client": "3.1.0",` 

Fixed it for me. I didn't want to add expo-dev-launcher, so just tried bumping the expo-dev-client to the "next" version...

**Comment by elenitaex5** [comment] 2023-10-11 06:58
> ` "expo-dev-client": "3.1.0",`
> 
> Fixed it for me. I didn't want to add expo-dev-launcher, so just tried bumping the expo-dev-client to the "next" version...

This work for me. Thanks! 
(`expo-dev-launcher` not needed to be installed)

**Comment by hlspablo** [comment] 2023-10-24 14:38
Guys, Always use npx expo install react-native-reanimated, it will ensure that the correct version is installed, at the current momento on SDK 49 the right version is 3.3.0
