### ISSUE TITLE
[iOS Crash] 3.3.0 - 3.5.4: Slow scroll, fast crash. Memory Leak. useAnimatedScrollHandler Animated ExpoImage

### ISSUE THREAD

**Issue by tyrauber** [software-mansion/react-native-reanimated#5181] opened 2023-10-05 04:02 UTC
### Description

Animating an expo-image height within (or outside of) a ScrollView, using useAnimatedScrollHandler and useAnimatedStyle, will crash on an iOS device if you touch and scroll **and do not release your finger**.  The memory will balloon until the app crashes.

https://github.com/software-mansion/react-native-reanimated/assets/109972/5bc9983d-82c0-44e3-9d1a-cd4137bbeeae

Happens in Expo Go or Dev Client on iOS, debug and release.

https://snack.expo.dev/@tyrauber/reanimated-3-useanimatedstyle-crash

![download](https://github.com/software-mansion/react-native-reanimated/assets/109972/783119b3-473e-40ed-9cbe-25366a65da49)

```
  const HEADER_HEIGHT = 600;
  const scrollY = useSharedValue(0);

  const scrollHandler = useAnimatedScrollHandler((event) => {
    scrollY.value = event.contentOffset.y;
  });

  const headerHeight = useAnimatedStyle(() => {
    const height = interpolate(scrollY.value, [0, HEADER_HEIGHT], [HEADER_HEIGHT, 20 + Constants.statusBarHeight], Extrapolate.CLAMP);
    return { height: height };
  });

  return (
    <View style={styles.container}>
       <Animated.ScrollView
        style={styles.scroll}
        onScroll={scrollHandler}
        scrollEventThrottle={16}>
          <AnimatedImage
            style={[{position: 'relative', left: 0, right: 0, flex: 1, height: HEADER_HEIGHT }, headerHeight]}
            source='https://images.unsplash.com/photo-1682686581362-796145f0e123?auto=format&fit=crop&w=2940&q=80'
          />
          <View style={{backgroundColor: 'blue', flex: 1, height: 1200, padding: 10 }}/>
       </Animated.ScrollView>
     </View>
  )
      
```

### Steps to reproduce

1. Create an AnimatedComponent with expo-image
2. Wrap AnimatedImage with an AnimatedScrollView
3.  Add a scrollHandler with `useAnimatedScrollHandler` that sets a sharedValue with `event.contentOffset.y`
4. Use `useAnimatedStyle` to calculate a height based on the sharedValue
5. Use the style to animated the height of the Image
6. Build the app on an iOS device (does not appear to crash on simulator)
7. Touch and scroll slowly, memory will balloon and eventually (10-20seconds) the app will crash

### Snack or a link to a repository

https://snack.expo.dev/@tyrauber/reanimated-3-useanimatedstyle-crash

### Reanimated version

3.3.0-3.5.4

### React Native version

0.72.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo Go

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Real device

### Device model

iPhone 11

### Acknowledgements

Yes

**Comment by tyrauber** [comment] 2023-10-09 14:28
Hi @efstathiosntonas, @Latropos, I am curious if this issue is resolved in #5183? Is a patch possible?

**Comment by gkasdorf** [comment] 2023-10-17 03:35
I have produced this myself when changing the scale of an expo-image. https://github.com/expo/expo/issues/24894

**Comment by gkasdorf** [comment] 2023-10-19 20:22
@tyrauber Just a heads up - and you may have already figured this out - placing the image inside of an `Animated.View` and animating that will prevent the issues. A bit wonky as (at least for my implementation) some additional styling is required on the view to make it function the way animating the image itself would work, but still preferred over using the base RN `Image` component.

**Comment by tyrauber** [comment] 2023-10-20 12:00
Thanks, @gkasdorf, for the suggestion. Unfortunately, I am not seeing that.  I have updated the original Snack. Even wrapping the Image, Animated or not, in Animated.View and animating the Animated.View causes the memory leak and crash.

```
<Animated.View
   style={[{position: 'relative', left: 0, right: 0, flex: 1, height: HEADER_HEIGHT }, headerHeight]}
>
   <Image
       style={{ height: '100%', width: '100%' }}  
       source='https://images.unsplash.com/photo-1682686581362-796145f0e123?auto=format&fit=crop&w=2940&q=80'
    />
</Animated.View>
```

Perhaps the issue is Animated the Image / View within a ScrollView?

**Comment by gkasdorf** [comment] 2023-10-20 20:48
@tyrauber Hmm. The quick snack that I threw together seems to prevent those loads whenever adjusting the *scale* on an Animated.View. However, adjusting the height/width does indeed cause those issues like you said. Looks like it might not be a solution for every case.

Anyway, it looks like the issue was assigned in the expo issue I linked above, so hopefully we will have a fix here soon.

**Comment by Latropos** [comment] 2023-10-23 06:51
I can confirm that the issue is caused with expo images, and indeed the fix is on way. I will close it here in favour of the above-mentioned expo PR.

**Closed by Latropos** 2023-10-23 06:51 UTC
Labels: Platform: iOS, Needs review, Repro provided
