### ISSUE TITLE
undefined is not an object (evaluating 'previousValue.toString')

### ISSUE THREAD

**Issue by purnadi-winarno** [software-mansion/react-native-reanimated#2531] opened 2021-10-13 08:32 UTC
### Expected behavior
app can run without error

## Package versions

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment] 2021-11-09 11:42
Closing due to not providing a reproduction.

**Closed by piaskowyk** 2021-11-09 11:42 UTC
Labels: 🧰needs-repro, 🐞 Bug, 🏠  Reanimated2, wait-for-reply
