### ISSUE TITLE
Error: Unrecognized operator abs

### ISSUE THREAD

**Issue by Vickthour** [software-mansion/react-native-reanimated#1116] opened 2020-08-13 02:09 UTC
This as been a 
![Screenshot_20200813-030701_Expo](https://user-images.githubusercontent.com/54726522/90086392-3d8caa00-dd12-11ea-947e-905e6d1d7c0d.jpg)

**Comment by jakub-gonet** [comment] 2020-08-13 06:46
Duplicate of #1007.

**Closed** 2020-08-13 06:47 UTC
