### ISSUE TITLE
Unable to resolve module `./abs`

### ISSUE THREAD

**Issue by phungthanhdong** [software-mansion/react-native-reanimated#1013] opened 2020-07-23 11:23 UTC
## Description
I installed react-native-reanimated as a dependency of react-native-router-flux (react-navigation), and I got this error when deploy to android:
```error: Error: Unable to resolve module `./abs` from `node_modules/react-native-reanimated/src/derived/index.js`: ```
## Already try:
- Remove node_modules and `npm install`
- Clean build, uninstall app, and reset bundler caches : `npm start --reset-cache`

### Screenshots
![device-2020-07-23-180605](https://user-images.githubusercontent.com/24285778/88280378-e9dd0100-cd0f-11ea-893c-c94e7d14b65a.png)
![Screen Shot 2020-07-23 at 6 04 24 PM](https://user-images.githubusercontent.com/24285778/88280387-ef3a4b80-cd0f-11ea-8590-eac260c4c5ad.png)

## Steps To Reproduce

1.Install native dependencies used by React Native Router (https://reactnavigation.org/docs/en/getting-started.html)
2.Install this component
`yarn add react-native-router-flux`
3. `react-native run android`
### Expected behavior
Runable with no error

### Actual behavior
Show error as above screenshot

## Snack or minimal code example
Used by react-navigation

## Package versions
- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 1.10.1
- react-navigation: 4.4.0
- react-navigation-redux-helpers: 4.0.1
- react-redux: 7.2.0
- react-native-router-flux: 4.2.0
- redux: 4.0.5

**Comment by jakub-gonet** [comment] 2020-07-23 11:36
Duplicate of #1007.

**Closed by jakub-gonet** 2020-07-23 11:36 UTC
Labels: 🐞 Bug

**Comment by phungthanhdong** [comment] 2020-07-24 03:10
Ah, my bad, I missed 2 minus `--` in reset cache command `npm start -- --reset-cache`
After cleanup build and reset cache, the error gone.
Thanks,
