### ISSUE TITLE
"react-native-reanimated": "^2.3.0-beta.*" android navigation goBack() fall to whitescreen without error

### ISSUE THREAD

**Issue by abramovks** [software-mansion/react-native-reanimated#2557] opened 2021-10-21 01:58 UTC
"react-native-reanimated": "^2.3.0-beta.1"
android
android navigation goBack() in scripts and device bottom button fall to white screen without error

"dependencies": {
    "@native-html/heuristic-table-plugin": "^0.6.0",
    "@react-native-async-storage/async-storage": "^1.15.7",
    "@react-native-community/push-notification-ios": "^1.10.0",
    "@react-native-firebase/app": "^12.8.0",
    "@react-native-firebase/auth": "^12.8.0",
    "@react-native-firebase/functions": "^12.8.0",
    "@react-native-firebase/messaging": "^12.8.0",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@reduxjs/toolkit": "^1.6.1",
    "@stream-io/flat-list-mvcp": "^0.10.1",
    "i18n-js": "^3.8.0",
    "lodash.memoize": "^4.1.2",
    "moment": "^2.29.1",
    "native-base": "^3.1.0",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-activestorage": "^1.0.0",
    "react-native-awesome-pin": "^1.3.2",
    "react-native-bidirectional-infinite-scroll": "^0.3.3",
    "react-native-exit-app": "^1.1.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-picker": "^4.1.1",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^2.1.1",
    "react-native-progress-bar-animated": "^1.0.6",
    "react-native-push-notification": "^8.1.0",
    "react-native-reanimated": "^2.3.0-beta.1",
    "react-native-render-html": "^6.1.0",
    "react-native-restart": "^0.0.22",
    "react-native-safe-area-context": "^3.3.0",
    "react-native-screens": "^3.6.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-sqlite-storage": "^5.0.0",
    "react-native-svg": "^12.1.1",
    "react-native-svg-uri": "^1.2.3",
    "react-native-touch-id": "^4.4.1",
    "react-native-vector-icons": "^8.1.0",
    "react-native-version-check": "^3.4.2",
    "react-native-view-pdf": "^0.11.1",
    "react-native-webview": "^11.13.0",
    "react-redux": "^7.2.5",
    "rn-fetch-blob": "^0.12.0",
    "styled-components": "^5.3.1",
    "styled-system": "^5.1.5"
  },

**Comment by piaskowyk** [comment] 2021-11-09 11:31
Duplicate of: https://github.com/software-mansion/react-native-reanimated/issues/2460

**Closed by piaskowyk** 2021-11-09 11:31 UTC
Labels: 🐞 Bug, 🏠  Reanimated2
