### ISSUE TITLE
useScrollViewOffset not working with RefreshControl

### ISSUE THREAD

**Issue by 01Boris** [software-mansion/react-native-reanimated#5817] opened 2024-03-21 08:26 UTC
### Description

On Android platform, when added `RefreshControl` or `refreshing` + `onRefresh` props, the `SharedValue` is not updated, or `useAnimatedStyle` not recalculated.

We use components from `reanimated` package as:

```tsx
  flatList: Animated.FlatList
  sectionList: Animated.createAnimatedComponent(SectionList)
  scrollView: Animated.ScrollView
```

Components has animated headers. The animations are handled with hooks:
```tsx
  const innerRef = useAnimatedRef<any>();
  const scrollY = useScrollViewOffset(innerRef);
  const headerStyle = useAnimatedStyle(() => ({...styles}))

  return <Component ref={innerRef} />;
```

The problem applies to all scrollables above. When the props are removed, animations are displayed correctly.

### Steps to reproduce

1. Create Scrollable element
2. Add any animated styling
3. Add pull to refresh functionality

### Snack or a link to a repository

https://snack.expo.dev/@01boris/moody-violet-donuts

### Reanimated version

3.8.1

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

None

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

Samsung A52, Android 14

### Acknowledgements

Yes

**Comment by tjzel** [comment] 2024-03-21 08:58
Duplicate of #57777

**Closed** 2024-03-21 08:58 UTC
Labels: Platform: Android, Repro provided

**Comment by stephendaddario** [comment] 2024-03-25 20:20
I am also seeing this issue when useScrollViewOffset is absent from the component/project.
