### ISSUE TITLE
Unexpected export specifier type

### ISSUE THREAD

**Issue by RichardBrowning** [software-mansion/react-native-reanimated#3359] opened 2022-07-05 05:50 UTC
## Description
... index.ts: Unexpected export specifier type

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-07-05 at 13 21 59](https://user-images.githubusercontent.com/46521212/177258341-ef9fe7f9-6d5e-4f82-9b71-4bdf076cb35e.png)

### Expected behavior

Unknown

### Actual behavior & steps to reproduce

Reports this error.
Console output:
```console
iOS Bundling failed 596ms
node_modules/react-native-reanimated/src/index.ts: /Users/Shared/GitHub/react-native-shared-element-transitions-uptodate/node_modules/react-native-reanimated/src/index.ts: Unexpected export specifier type
  5 | export * from './reanimated1';
  6 | export * from './reanimated2';
> 7 | export * as default from './Animated';
    |        ^^^^^^^^^^^^
  8 |
SyntaxError: /Users/Shared/GitHub/react-native-shared-element-transitions-uptodate/node_modules/react-native-reanimated/src/index.ts: Unexpected export specifier type
  5 | export * from './reanimated1';
  6 | export * from './reanimated2';
> 7 | export * as default from './Animated';
    |        ^^^^^^^^^^^^
  8 |
    at File.buildCodeFrameError (/Users/Shared/GitHub/react-native-shared-element-transitions-uptodate/node_modules/@babel/core/lib/transformation/file/file.js:249:12)
    at NodePath.buildCodeFrameError (/Users/Shared/GitHub/react-native-shared-element-transitions-uptodate/node_modules/@babel/traverse/lib/path/index.js:143:21)
    at /Users/Shared/GitHub/react-native-shared-element-transitions-uptodate/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:150:22
    at Array.forEach (<anonymous>)
    at /Users/Shared/GitHub/react-native-shared-element-transitions-uptodate/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:148:31
    at Array.forEach (<anonymous>)
    at getModuleMetadata (/Users/Shared/GitHub/react-native-shared-element-transitions-uptodate/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:96:27)
    at normalizeModuleAndLoadMetadata (/Users/Shared/GitHub/react-native-shared-element-transitions-uptodate/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:39:7)
    at rewriteModuleStatementsAndPrepareHeader (/Users/Shared/GitHub/react-native-shared-element-transitions-uptodate/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/helper-module-transforms/lib/index.js:77:54)
Warning: Invalid version react-native@0.69.1 for expo sdkVersion 45.0.0. Use react-native@0.68.2

```

## Snack or minimal code example

It appears that the issue emerges when importing react-native-reanimated.
```js
import Animated from 'react-native-reanimated';
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.69.1      |
| react-native-reanimated              |  2.9.1   |
| NodeJS                               |  v16.15.1  |
| Xcode                                | Version 13.4.1 (13F100) |
| Java                                 | 11.0.15 2022-04-19 |
| Gradle                               |  7.0.2  |
| expo                                 | 45.0.6 |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web (Not tested)

**Comment by musicode** [comment] 2022-07-06 10:15
+1, how to fix it?

**Comment by HeinZawHtet** [comment] 2022-07-07 07:02
use @babel/plugin-proposal-export-namespace-from plugin

**Comment by ddikodroid** [comment] 2022-07-11 07:38
duplicate of https://github.com/software-mansion/react-native-reanimated/issues/3364#issuecomment-1178584549?

**Comment by sbezerrarafa** [comment] 2022-07-11 12:51
someone managed to solve

**Closed** 2022-07-18 00:56 UTC
Labels: 🤖android, 🍎iOS, needs-review, repro-provided

**Comment by azks29** [comment] 2022-08-17 00:27
In all cases, after the installation completes, you must also add the Babel plugin to babel.config.js:
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};
After you add the Babel plugin, restart your development server and clear the bundler cache: expo start --clear.
Note: If you load other Babel plugins, the Reanimated plugin has to be the last item in the plugins array.

**Comment by azks29** [comment] 2022-08-17 00:27
https://docs.expo.dev/versions/latest/sdk/reanimated/#installation

**Comment by my-logic** [comment] 2022-10-23 14:32
> In all cases, after the installation completes, you must also add the Babel plugin to babel.config.js: module.exports = function(api) { api.cache(true); return { presets: ['babel-preset-expo'], plugins: ['react-native-reanimated/plugin'], }; }; After you add the Babel plugin, restart your development server and clear the bundler cache: expo start --clear. Note: If you load other Babel plugins, the Reanimated plugin has to be the last item in the plugins array.

Thank you!!!
