### ISSUE TITLE
Layout animation overlaps when triggered during previous animation

### ISSUE THREAD

**Issue by alexborton** [software-mansion/react-native-reanimated#4006] opened 2023-01-30 09:39 UTC
### Description

When using layout animation, if i trigger several changes in short succession (quicker than the animation takes to complete), the layout of the subsequent items is incorrect. It seems that the positioning of the items that came before (which may still be animating) are not taken into account. It's possible this is expected behaviour, but it's not desired.

https://user-images.githubusercontent.com/1439507/215441409-bd322271-7c0a-446a-82b6-a85741133eb7.MP4

### Steps to reproduce

- Create a Layout animation with an Entering, Exiting and Layout value.
- Trigger multiple additions to the layout in short succession (quicker than a single layout can complete)
- You should see that some, if not all, items are not correctly positioned

### Snack or a link to a repository

https://snack.expo.dev/@aborton/reanimated-layout-animation?platform=android

### Reanimated version

2.9.1

### React Native version

0.69.0 (Expo 46 + 47)

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by jwajgelt** [comment] 2023-02-06 11:31
Hi @alexborton, thanks for reporting the issue.
Layout animations are known to have issues on Reanimated 2.
Reanimated 3 contains a rewrite of the Layout Animations implementation which solves many of the issues present in v2. If it's possible, I'd recommend upgrading to the newest release candidate of v3 and seeing if the issue persist - at least for the attached example, I couldn't reproduce it in v3.

**Comment by alexborton** [comment] 2023-02-07 15:03
@jwajgelt interestingly the issue does seem to resolve on the latest RC with Android, but still persists with iOS. Is this expected at this point?

**Comment by jwajgelt** [comment] 2023-02-08 08:57
Sadly, you can't update the reanimated version in snacks, since the native parts of the library are bundled with the Expo SDK, so your snack will still use the old implementation.

Have you tried running your example with the latest RC locally, on a simulator or a real device?

**Comment by mccraveiro** [comment] 2023-08-01 09:49
I was facing the same bug on reanimated v2. Upgrading to v3 solve it!

**Comment by piaskowyk** [comment] 2023-08-01 11:09
So if @mccraveiro confirmed that it works with Reanimated 3, we can close this issue 🎉

**Closed by piaskowyk** 2023-08-01 11:09 UTC
Labels: Platform: Android, Platform: iOS, Needs review, Repro provided
