### ISSUE TITLE
[Android] Conditional views flicker with `react-navigation` + `react-native-reanimated` 

### ISSUE THREAD

**Issue by jjenzz** [software-mansion/react-native-reanimated#3855] opened 2022-12-12 13:09 UTC
### Description

In a fresh expo install (46.0.16), when using conditional state to switch what renders, the page will flicker when testing in Android emulator if `react-native-reanimated` is imported (the two views overlap).

If you slow down the following video you will be able to see the issue more easily. Towards the end of the video I comment out the `react-native-reanimated` import to demonstrate that the flicker goes away.

https://user-images.githubusercontent.com/175330/199777019-c6c9c320-fa57-428d-934c-09f2468e7882.mp4

I have also reported this on the react-navigation repo https://github.com/react-navigation/react-navigation/issues/10977

### Snapshot of the buggy frame

![CleanShot 2022-11-03 at 16 23 26](https://user-images.githubusercontent.com/175330/199777061-c9fa0de4-b893-4904-a4a2-a4239ef8d2f2.png)

### Steps to reproduce

```jsx
// App.js
import * as React from "react";
import { View, Pressable, Text } from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import Animated, { FadeIn } from "react-native-reanimated";

const Stack = createNativeStackNavigator();

function MyStack() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Screen" component={Screen} />
    </Stack.Navigator>
  );
}

function Screen() {
  const [isCopied, setCopied] = React.useState(false);
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Pressable onPress={() => setCopied((prev) => !prev)}>
        {isCopied ? (
          <View style={{ flexDirection: "row", alignItems: "center" }}>
            <View style={{ width: 16, height: 16, backgroundColor: "red" }} />
            <Text style={{ color: "red" }}>Copied</Text>
          </View>
        ) : (
          <View style={{ flexDirection: "row", alignItems: "center" }}>
            <Text style={{ color: "red" }}>1238172938719873</Text>
            <View style={{ width: 16, height: 16, backgroundColor: "red" }} />
          </View>
        )}
      </Pressable>
    </View>
  );
}

export default function App() {
  return (
    <NavigationContainer>
      <MyStack />
    </NavigationContainer>
  );
}
```

```jsx
// babel.config.js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: ["react-native-reanimated/plugin"],
  };
};
```

### Snack or a link to a repository

> **Note**: While I have provided a Snack, it cannot be reproduced there as the flicker happens too quickly for the Snack render. You must run the code locally in Android Emulator.

https://snack.expo.dev/@fungiblejen/stack-navigator-%7C-react-navigation

### Reanimated version

2.9.1 

### React Native version

0.69.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by calebpanza** [comment] 2022-12-15 15:26
We're experiencing a similar behavior on both Android and iOS

**Comment by calebpanza** [comment] 2022-12-15 19:56
We found setting Layout Animations to enabled on iOS worked for us

```js
// your App's index.js
import { enableLayoutAnimations } from 'react-native-reanimated';
enableLayoutAnimations(Platform.os === 'ios');
```

**Comment by graszka22** [comment] 2023-01-23 15:55
I tested your example with the following dependencies:
```
 "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "react": "18.2.0",
    "react-native": "0.71.1",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.19.0",
```
and the newest reanimated (main branch), fabric architecture and I couldn't reproduce it. Maybe it's fixed in the newest versions of the libraries? Here is my video:

https://user-images.githubusercontent.com/6280457/214084174-4ba85955-f772-436d-a6e7-c88dcc058f03.mp4

you can download it and watch frame by frame. On your video I can see the buggy frame if I watch it frame by frame.

**Comment by szydlovsky** [comment] 2024-06-25 15:52
I can confirm that 
```
"dependencies": {
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "react": "18.2.0",
    "react-native": "0.74.2",
    "react-native-reanimated": "^3.12.1",
    "react-native-safe-area-context": "^4.10.5",
    "react-native-screens": "^3.32.0"
  },
```
runs with no problems whatsoever. Thus, closing the issue

**Closed by szydlovsky** 2024-06-25 15:52 UTC
Labels: Platform: Android, Needs review, Repro provided
