### ISSUE TITLE
Not able to run the app

### ISSUE THREAD

**Issue by anujAnujMody** [software-mansion/react-native-reanimated#1111] opened 2020-08-12 11:28 UTC
I was setting up my project on my new workstation and suddenly I started getting this error.
`node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:171: error: cannot find symbol
              new GuardedRunnable(mContext.getExceptionHandler()) {
                                          ^
  symbol:   method getExceptionHandler()
  location: variable mContext of type ReactContext`

I am using this version '^1.12.0'

Please let me know what the issue is and how to fix it.

**Comment by terrysahaidak** [comment] 2020-08-12 11:57
Could you please fill the issue template?

**Comment by jakub-gonet** [comment] 2020-08-12 11:59
Duplicate of #1109

**Closed by jakub-gonet** 2020-08-12 11:59 UTC

**Comment by jakub-gonet** [comment] 2020-08-12 12:31
@anujAnujMody, do you use RN 0.59 by any chance?

**Comment by anujAnujMody** [comment] 2020-08-12 14:48
Yes i am using RN 0.59. I checked #1109 but still my issue is not fixed. Please can u tell me how to fix this?

**Comment by jakub-gonet** [comment] 2020-08-12 15:15
1.13.0 has been released few hours ago, upgrade react-native-reanimated.
