### ISSUE TITLE
2.2.0 Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libndk_translation_proxy_libhermes.so" not found

### ISSUE THREAD

**Issue by sclavijo93** [software-mansion/react-native-reanimated#2626] opened 2021-11-14 15:15 UTC
## Description
We recently updated reanimated to reanimated 2 and we are getting an error in Crashlytics, we can't reproduce this issue.

<img width="1285" alt="imagen" src="https://user-images.githubusercontent.com/19956031/141686971-dcabec92-baa7-4aa9-b4ad-a002c56639e4.png">

### Actual behavior & steps to reproduce
Install reanimated 2 and follow the instructions an then compile for production then the crash is shown in crashlytics.

## Snack or minimal code example
N/A the issue is on startup

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.2.0
- NodeJS: 14.17.5
- Xcode: N/A
- Java & Gradle:
    - java 15.0.1 2020-10-20
    - Java(TM) SE Runtime Environment (build 15.0.1+9-18)
    - Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
    - Gradle 6.7
    - Kotlin:       1.3.72
    - Groovy:       2.5.12
    - Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
    - JVM:          15.0.1 (Oracle Corporation 15.0.1+9-18)
    - OS:           Mac OS X 10.16 x86_64

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by pushpender-singh-ap** [comment] 2022-01-17 15:22
Same issue 
<img width="937" alt="Screenshot 2022-01-17 at 8 52 31 PM" src="https://user-images.githubusercontent.com/73298854/149796601-c55aa777-367c-4dea-b73c-9009d370069e.png">


```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libndk_translation_proxy_libjsi.so" not found
       at java.lang.Runtime.loadLibrary(Runtime.java:372)
       at java.lang.System.loadLibrary(System.java:1076)
       at com.swmansion.reanimated.NativeProxy.<clinit>(NativeProxy.java)
       at com.swmansion.reanimated.NodesManager.initWithContext(NodesManager.java)
       at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by pke** [comment] 2022-03-25 16:36
We are experiencing the same occationally on Android 8.0 devices.

**Comment by JShefferBeam** [comment] 2022-04-11 18:33
We have also seen this crash during google's review process.  
I see in the screenshot above, the device was a Rooted Nexus 5X which is one of the standard devices that google tests on. 
Do we know what they could be doing during the review process to trigger this?

**Comment by haveamission** [comment] 2022-10-20 22:39
Just saw this in crash analytics from Visual Studio App Center. Not sure what would cause it. Haven't been able to replicate.

**Comment by Latropos** [comment] 2023-11-15 10:06
Closing since we are unable to reproduce the error

**Closed by Latropos** 2023-11-15 10:06 UTC
Labels: Bug, Crash, bug-bash-jan22
