### ISSUE TITLE
Android crashes with modal React Native Reanimated: ^2.0.0-alpha.9.1

### ISSUE THREAD

**Issue by fufylev** [software-mansion/react-native-reanimated#1465] opened 2020-11-22 20:14 UTC
## Description
Android crashes with modal

### Whenever I try to open the Modal view app crashes without messages
FATAL EXCEPTION: main
Process: com.instaforex.android.forexcopy, PID: 6851
com.facebook.jni.CppException: Value is null, expected an Object

Error: Value is null, expected an Object
	at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(Native Method)
	at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:60)
	at com.facebook.react.views.modal.ShowEvent.dispatch(ShowEvent.java:29)
	at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:471)
	at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:448)
	at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:114)
	at com.facebook.react.views.modal.ReactModalHostManager$2.onShow(ReactModalHostManager.java:121)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1409)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Screenshots
![Снимок экрана 2020-11-23 в 01 12 53](https://user-images.githubusercontent.com/35691656/99915983-096d5000-2d29-11eb-8237-a7ad08e539b6.png)

## Steps To Reproduce
1. import Modal from 'react-native-modal';
2. Run Modal  

### Expected behavior
Open Modal
### Actual behavior
App crashes
### minimal code example
```
<Modal
                isVisible={langModalShow}
                onRequestClose={onModalsCloseHandler}
                hasBackdrop={true}
                animationIn="slideInUp"
                animationOut="slideOutDown"
                backdropTransitionInTiming={0}
                backdropTransitionOutTiming={0}
                onBackdropPress={onModalsCloseHandler}
                animationInTiming={250}
                animationOutTiming={250}>
                <Animated.View style={styles.modalContainer}>
                    <Animated.View style={styles.modalView}>
                        {langModalShow && (
                            <ModalContent data={langList} cb={onLangSubmitHandler} lang={lang} />
                        )}
                    </Animated.View>
                </Animated.View>
            </Modal>
```

## Package versions
- React: ^16.13.1
- React Native: ^0.63.2
- React Native Reanimated: ^2.0.0-alpha.9.1
- NodeJS: v12.18.2

**Comment by dhirajanand014** [comment] 2020-11-23 05:41
I too get the below error when i try open the modal in my app with the same version - 2.0.0-alpha.9.1

**FATAL EXCEPTION: main
Process: com.sdom, PID: 10028
com.facebook.jni.CppException: Value is null, expected an Object

Error: Value is null, expected an Object
	at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(Native Method)
	at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:60)
	at com.facebook.react.views.modal.ShowEvent.dispatch(ShowEvent.java:29)
	at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:471)
	at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:448)
	at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:114)
	at com.facebook.react.views.modal.ReactModalHostManager$2.onShow(ReactModalHostManager.java:121)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1399)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)**

**Comment by hoangtrucit** [comment] 2020-11-23 06:13
Duplicate of https://github.com/software-mansion/react-native-reanimated/issues/1447

**Comment by jakub-gonet** [comment] 2020-11-23 06:26
More likely a duplicate of #1444, but all of these are instances of the same problem.

**Closed by jakub-gonet** 2020-11-23 06:26 UTC
Labels: Reanimated2, 🐞 Bug
