### ISSUE TITLE
Fatal Exception: com.facebook.jni.CppException Maximum call stack size exceeded (native stack depth) RangeError: Maximum call stack size exceeded (native stack depth) at apply (native) at anonymous  on release android apk

### ISSUE THREAD

**Issue by NadeemKhanFh** [software-mansion/react-native-reanimated#5092] opened 2023-09-15 12:50 UTC
### Description

hey, i am facing this issue on release apk android. debug is working fine.

<img width="1173" alt="Screenshot 2023-09-15 at 5 45 34 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/124039561/c0eb10e6-bfd9-44dd-ae5a-e72b097e31ec">

### Steps to reproduce

1. make android release apk
2. install it
3. build crashes

### Snack or a link to a repository

no snack

### Reanimated version

3.5.1

### React Native version

0.71.12

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Release mode

### Device

Real device

### Device model

redme note 11 pro

### Acknowledgements

Yes

**Comment by manoj-makkuboy** [comment] 2023-09-15 13:07
https://github.com/software-mansion/react-native-reanimated/issues/5067 The patch is mentioned here but still no release.

**Comment by tjzel** [comment] 2023-09-15 15:13
Fixed in `3.5.2`.

**Closed by tjzel** 2023-09-15 15:13 UTC
Labels: Missing repro, Platform: Android, Needs review

**Comment by Vrunalbenke** [comment] 2023-10-09 13:19
> Fixed in `3.5.2`.

can u share how you this error,because i am also getting same error in release apk

**Comment by iamrohitagg** [comment] 2023-10-09 15:00
I am on the latest version(3.5.4) and getting the crash.

**Comment by tjzel** [comment] 2023-10-12 08:11
@Vrunalbenke It was fixed with #5087. Make sure you reset your bundler's cache after upgrading. If the issue persists, please attach some logs and preferably check if your `runOnJS` function (`node_modules/react-native-reanimated/src/reanimated2/threads.ts`) is the same as in the npm package.

**Comment by pabloluz** [comment] 2023-10-29 21:09
Updated to 3.5.4 and keep getting the same error in release APK.

Bundler's cache was reset and checked `runOnJS` function is the same as in the NPM package.

**Comment by tjzel** [comment] 2023-10-30 15:58
@pabloluz I believe this is fixed in https://github.com/software-mansion/react-native-reanimated/pull/5264. Please confirm if it's gone for you on our nightly version `react-native-reanimated@nightly`.

**Comment by pabloluz** [comment] 2023-10-31 11:44
> @pabloluz I believe this is fixed in #5264. Please confirm if it's gone for you on our nightly version `react-native-reanimated@nightly`.

I can confirm `react-native-reanimated@nightly` is working in prod, the exception I mentioned above is not happening anymore. Thank you very much @tjzel!

**Comment by Pingou** [comment] 2023-12-27 09:03
Hi all, did you all have the same stacktrace with the error appearing in apply()?
I am experiencing the same error since upgrading to react native 71 but the stacktrace is a bit different and occurs in render.

**Comment by tjzel** [comment] 2023-12-27 10:54
@Pingou This should be fixed. Feel free to open another issue with your error.

**Comment by LaGregance** [comment] 2024-09-07 07:46
I have the same issue using react-native-reanimated 3.14.0 and react-native 0.74.3. I can't reproduce by myself but I see the same error in the Crashlytics console (Android only).
