### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: JNI ERROR (app bug): jobject is an invalid JNI transition frame reference or invalid reference: 0x2433c4 (use of invalid jobject)

### ISSUE THREAD

**Issue by fnando** [software-mansion/react-native-reanimated#2665] opened 2021-11-26 22:30 UTC
## Description

I'm upgrading an app to react-native@0.66.5 and also other packages like react-native-reanimated@2.3.0-beta.4, but it looks like something is broken. I'm testing in a Google Pixel 6 (real device) running Android 12 (latest update). iOS Simulator works fine (didn't test in a real device, but I'd assume so).

`adb logcat` includes this output:

```
11-26 14:18:52.821 20626 20626 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-26 14:18:52.821 20626 20626 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI ERROR (app bug): jobject is an invalid JNI transition frame reference or invalid reference: 0x2433c4 (use of invalid jobject)
11-26 14:18:52.821 20626 20626 F DEBUG   :     in call to GetObjectClass
11-26 14:18:52.821 20626 20626 F DEBUG   :     from void com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(java.lang.String, com.facebook.react.bridge.WritableMap)'
11-26 14:18:52.821 20626 20626 F DEBUG   :     x0  0000000000000000  x1  0000000000004fc0  x2  0000000000000006  x3  0000007feb2238f0
11-26 14:18:52.821 20626 20626 F DEBUG   :     x4  fefeff7eea212449  x5  fefeff7eea212449  x6  fefeff7eea212449  x7  7f7f7f7fff7f7f7f
11-26 14:18:52.821 20626 20626 F DEBUG   :     x8  00000000000000f0  x9  00000076df3be0b0  x10 0000000000000000  x11 ffffff80fffffbdf
11-26 14:18:52.821 20626 20626 F DEBUG   :     x12 0000000000000001  x13 0000000000000179  x14 0000007feb222700  x15 ffffffffffffffff
11-26 14:18:52.821 20626 20626 F DEBUG   :     x16 00000076df45b050  x17 00000076df438cd0  x18 00000076f74f4000  x19 0000000000004fc0
11-26 14:18:52.821 20626 20626 F DEBUG   :     x20 0000000000004fc0  x21 00000000ffffffff  x22 0000000000000000  x23 0000000000000000
11-26 14:18:52.821 20626 20626 F DEBUG   :     x24 00000074442b63eb  x25 0000000000000001  x26 00000076f5eff14c  x27 0000007444c17000
11-26 14:18:52.821 20626 20626 F DEBUG   :     x28 b4000074672e4e70  x29 0000007feb223970
11-26 14:18:52.821 20626 20626 F DEBUG   :     lr  00000076df3eb82c  sp  0000007feb2238d0  pc  00000076df3eb85c  pst 0000000000001000
```

### Expected behavior

I should be able to open my app on Android and navigate through my app without crashes.

### Actual behavior & steps to reproduce

App crashes right away during boot.

## Package versions

- React Native: 0.66.5
- React Native Reanimated: 2.3.0-beta.4
- NodeJS: v14.18.1
- Xcode: 13.1
- Java & Gradle:

```
$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7281165, mixed mode)

$ which java
/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java

$ android/gradlew -version

------------------------------------------------------------
Gradle 6.9
------------------------------------------------------------

Build time:   2021-05-07 07:28:53 UTC
Revision:     afe2e24ababc7b0213ccffff44970aa18035fc0e

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (JetBrains s.r.o. 11.0.10+0-b96-7281165)
OS:           Mac OS X 12.0.1 x86_64
```

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by chrisarts** [comment] 2021-11-27 07:28
same problem in here.

**Comment by piaskowyk** [comment] 2021-11-30 12:04
Hey, could you provide a repo to reproduce your issue?

**Comment by Hirbod** [comment] 2021-12-03 11:06
I can confirm this error.

Expo Custom Dev Client (SDK43)

```
11-30 08:52:54.892 11559 11559 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI ERROR (app bug): jobject is an invalid JNI transition frame reference or invalid reference: 0x7333147bcca0 (use of invalid jobject)
11-30 08:52:54.892 11559 11559 F DEBUG   :     in call to GetObjectClass
11-30 08:52:54.892 11559 11559 F DEBUG   :     from void com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(java.lang.String, com.facebook.react.bridge.WritableMap)'
11-30 08:52:54.893 11559 11559 F DEBUG   :     rax 0000000000000000  rbx 0000000000002ca9  rcx 0000733545aae5cf  rdx 0000000000000006
11-30 08:52:54.893 11559 11559 F DEBUG   :     r8  00007332b475fe41  r9  00007332b475fe41  r10 00007ffd421f5290  r11 0000000000000203
11-30 08:52:54.894 11559 11559 F DEBUG   :     r12 000000000000000b  r13 0000000000000001  r14 00007ffd421f5288  r15 0000000000002ca9
11-30 08:52:54.894 11559 11559 F DEBUG   :     rdi 0000000000002ca9  rsi 0000000000002ca9
11-30 08:52:54.894 11559 11559 F DEBUG   :     rbp 0000733354769eb0  rsp 00007ffd421f5280  rip 0000733545aae5cf
```

**Comment by Hirbod** [comment] 2021-12-03 11:16
Ok, this is interesting.

When I trigger `expo run:android`, it will crash with this error. But when I open the app from the device after it has been installed, its running without a crash.

**Comment by Kudo** [comment] 2021-12-03 11:55
@Hirbod i'm curious if downgrade to reanimated 2.2 works for you?

it would be helpful if you can share a repository of [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). that would help reanimated team to repro the issue and troubleshooting. or at least attach more adb log including a stacktrace like [this](https://github.com/software-mansion/react-native-reanimated/issues/2291#issuecomment-905604198)

**Comment by Hirbod** [comment] 2021-12-03 12:22
@Kudo it was happening with 2.2.4 but I will also try to use the „shipped version“ 2.2.0 and will provide a better stacktrace.

**Comment by fernanditerahadi** [comment] 2021-12-03 16:03
<img width="1146" alt="Screenshot 2021-12-03 at 11 55 19 PM" src="https://user-images.githubusercontent.com/39233193/144633085-1166cdd3-a473-456d-8e5b-023b8ec656f3.png">

I had the similar issue on Android when developing the app locally on debug mode. However, I managed to "work-around" it, prevent the `JNI DETECTED ERROR IN APPLICATION` crash from happening, by excluding the shadowOffset field from the style object on Android

Not sure if this also works on release build as I haven't tested it

**Comment by mwegener-com** [comment] 2021-12-08 14:12
I have the same issue, fired by `<SafeAreaProvider>`: https://github.com/software-mansion/react-native-reanimated/issues/2710

**Comment by kmagiera** [comment] 2022-01-28 10:41
As @mwegener-com mentioned this seem to be the same problem as reported in #2710 so marking this issue to auto-close unless anyone thinks these two aren't related. I'd prefer to continue the discussion on #2710 which has a repro repository included and hence allows us to investigate it.

**Comment by iamdavidmartin** [comment] 2022-03-27 19:15
I encountered this error due to a NaN value as the "top" value in an absolutely positioned view. Giving it an appropriate value fixed this issue.

**Comment by edritech93** [comment] 2023-06-19 03:19
same issue on react-native-reanimated: "2.17.0"

**Comment by Latropos** [comment] 2023-10-23 08:21
Closing as a duplicate of https://github.com/software-mansion/react-native-reanimated/issues/2710

**Closed by Latropos** 2023-10-23 08:21 UTC
Labels: Bug, 🏠  Reanimated 2, Crash
