### ISSUE TITLE
[3.0.0-rc.0] Cannot read property 'CLAMP' of undefined

### ISSUE THREAD

**Issue by talaikis** [software-mansion/react-native-reanimated#3246] opened 2022-05-15 16:04 UTC
## Description

`Cannot read property 'CLAMP' of undefined` when using `Extrapolate.CLAMP`

### Actual behavior & steps to reproduce

Upgrade to v3 rc0

**Comment by piaskowyk** [comment] 2022-05-16 13:11
I have already checked it on two different applications and I am not able to reproduce your issue :/ Could you provide more information about your case?

**Comment by mitchellmcm27** [comment] 2022-05-25 19:02
There may be a namespacing or typing issue with `Animated.Extrapolate`. Typescript thinks it's an enum but it's actually defined as an object. Meanwhile, `Extrapolation` from the `interpolation` module is an enum.

Put this at the top of index.js

```js
import Animated, { Extrapolation } from "react-native-reanimated";
try {
  console.log(Animated.Extrapolate.CLAMP);
} catch (error) {
  console.warn(error); //  [TypeError: Cannot read property 'CLAMP' of undefined]
}
Animated.Extrapolate = Extrapolation;
console.log(Animated.Extrapolate.CLAMP); // 'clamp'
```

**Comment by huduarte** [comment] 2022-05-27 19:35
Same here, but in tests with jest

**Comment by jzxchiang1** [comment] 2022-05-28 18:19
I got this same issue with @gorhom/react-native-bottom-sheet@4.1.5

**Comment by jzxchiang1** [comment] 2022-05-28 18:32
> There may be a namespacing or typing issue with `Animated.Extrapolate`. Typescript thinks it's an enum but it's actually defined as an object. Meanwhile, `Extrapolation` from the `interpolation` module is an enum.
> 
> Put this at the top of index.js
> 
> ```js
> import Animated, { Extrapolation } from "react-native-reanimated";
> try {
>   console.log(Animated.Extrapolate.CLAMP);
> } catch (error) {
>   console.warn(error); //  [TypeError: Cannot read property 'CLAMP' of undefined]
> }
> Animated.Extrapolate = Extrapolation;
> console.log(Animated.Extrapolate.CLAMP); // 'clamp'
> ```

Aren't enums and objects accessed the same way in TS? Using the dot notation.

**Comment by jzxchiang1** [comment] 2022-05-28 18:52
I don't understand why this error exists, but it currently breaks multiple libraries.

Namely, `@gohom/bottom-sheet` and `react-native-redash`. Anyone know what's going on?

**Comment by mitchellmcm27** [comment] 2022-05-30 16:53
I'm not sure either, but enums are [more complicated](https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-compile-time) than just being compiled to JS objects.

`interpolation.ts` [exports](https://github.com/software-mansion/react-native-reanimated/blob/b4ee4ea9a1f246c461dd1819c6f3d48440a25756/src/reanimated2/interpolation.ts#L1) an **enum** called `Extrapolation`, which is rarely if ever used by libraries or end users. Most of us prefer to `import { Extrapolate } from "react-native-reanimated"`

`interpolateColor.ts` [exports](https://github.com/software-mansion/react-native-reanimated/blob/b4ee4ea9a1f246c461dd1819c6f3d48440a25756/src/reanimated2/interpolateColor.ts#L16) an **object** called `Extrapolate` with the same properties and values as the `enum Extrapolation`.

Both of these are exported (https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/index.ts)

Meanwhile `react-native-reanimated.d.ts` [exports](https://github.com/software-mansion/react-native-reanimated/blob/ecc29a84f810f63c0c653f7a3e796f2868e6aba6/react-native-reanimated.d.ts#L78) an **enum** called `Extrapolate`.

I don't understand how (or even if) this is causing the error, or the best way to fix it, but adding `Animated.Extrapolate = Extrapolation` at the top of my `index.js` seems to be a temporary workaround.

**Comment by HuuNguyen312** [comment] 2022-06-06 11:09
Before that, I used version 2.8.0. But after upgrading to 3.0.0, I got the same error
I am using this library: https://github.com/PedroBern/react-native-collapsible-tab-view

**Comment by thespacemanatee** [comment] 2022-06-10 10:21
Just wanted to chime in that we are also seeing the same issue and the workaround above works as well.

**Comment by mlecoq** [comment] 2022-06-27 19:56
for react-native-redash, a PR fixes the issue : https://github.com/wcandillon/react-native-redash/pull/493

More than using `Extrapolate`, it was using `Animated.Extrapolate` the cause of the issue

**Comment by JayFeldman12** [comment] 2022-06-27 20:07
My unit tests were failing for components that used snapPoint, even on the latest version of redash that fixes the problem with the app running. I was able to get around this by mocking snapPoint along with the other dependencies used in my project
```
jest.mock('react-native-redash', () => {
  return {
    snapPoint: jest.fn().mockImplementation((_value, _velocity, points) => points[0]),
    ReText: jest.requireActual('react-native').Text,
    withPause: jest.fn().mockImplementation((callback) => callback()),
  };
});```

Normally I'd use a jest.requireActual inside that mock to not need to specify the others manually, but in this case requiring the redash library by itself was triggering the same CLAMP of undefined error, because just requiring it made the engine try to process that line.

**Comment by mlecoq** [comment] 2022-06-28 07:25
> for react-native-redash, a PR fixes the issue : https://github.com/wcandillon/react-native-redash/pull/493
> 
> 
> 
> More than using `Extrapolate`, it was using `Animated.Extrapolate` the cause of the issue

Upgrade to react-native-redash 17.0.0 has fixed this issue in my case (forcing this version in resolutions for bottom-sheet)

**Comment by RichardLindhout** [comment] 2023-04-01 12:53
I still have this problem and all the above solutions won't work I'm on    "react-native-reanimated": "^3.0.2", + 

 "resolutions": {
    "react-native-reanimated": "3.0.2"
  },

**Comment by Latropos** [comment] 2023-10-30 15:55
Closing since @mitchellmcm27 has provided snack fixing this problem. You can also replace Extrapolate.CLAMP with string literal "clamp" or define your own enum with extrapolation keywords.

**Closed by Latropos** 2023-10-30 15:55 UTC
Labels: Missing repro, Needs review, Missing info
