### ISSUE TITLE
App Crashing intermittently with 3.5.1

### ISSUE THREAD

**Issue by gaurav-vij** [software-mansion/react-native-reanimated#5091] opened 2023-09-15 02:04 UTC
### Description

Our React Native version - 0.72.4.
Our App is working perfectly fine in **DEBUG** Mode.
However, in **release** mode, its crashing intermittently. e.g. Screen A - Works fine. After sometime, when we do any action on same Screen A, it crashes. Here are the errors in crashlytics

Crashed: Thread: SIGSEGV  0x0000007fc3231028
#00 pc 0x7fc3231028
#01 pc 0xe8238 libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
#02 pc 0xe7e6c libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
#03 pc 0xe3f50 libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
#04 pc 0xe3da4 libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
#05 pc 0xa6288 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#06 pc 0xa6790 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#07 pc 0x8b154 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#08 pc 0x8afc0 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#09 pc 0x8ae08 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#10 pc 0x745bc libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#11 pc 0x61800 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#12 pc 0x94fc4 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#13 pc 0x9a920 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#14 pc 0xa3730 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#15 pc 0xa3664 libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#16 pc 0xa35dc libreanimated.so (BuildId: fb31cc963742a2782342d1e12382d9adf377aa2c)
#17 pc 0x461754 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#18 pc 0x7a90d8c3f4
#19 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#20 pc 0x20a2b0 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#21 pc 0x7a90d8c3f4
#22 pc 0x7a90d84e76
#23 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#24 pc 0x20b074 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#25 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#26 pc 0x7a90d84e76
#27 pc 0x7a90d864d4
#28 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#29 pc 0x20a254 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#30 pc 0x7a90d864d4
#31 pc 0x7a90d8669e
#32 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#33 pc 0x20a254 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#34 pc 0x7a90d8669e
#35 pc 0x7a8ffabe7e
#36 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#37 pc 0x20b074 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#38 pc 0x7a8ffabe7e
#39 pc 0x20f540 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#40 pc 0x7a90d7a41a
#41 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#42 pc 0x20b074 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#43 pc 0x7a90d7a41a
#44 pc 0x7a90d83e5e
#45 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#46 pc 0x209398 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#47 pc 0x7a90d83e5e
#48 pc 0x7a90d83eac
#49 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#50 pc 0x20a254 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#51 pc 0x7a90d83eac
#52 pc 0x7a90d83c6c
#53 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#54 pc 0x20a254 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#55 pc 0x7a90d83c6c
#56 pc 0x7a90d838f8
#57 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#58 pc 0x20a254 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#59 pc 0x7a90d838f8
#60 pc 0x7a90d83492
#61 pc 0x20087c libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#62 pc 0x209334 libart.so (BuildId: 6fc1c03912861b04885c9f2953121b6b)
#63 pc 0x7a90d83492

### Steps to reproduce

1. Use version react-native-reanimated version 3.5.1 with react-native 0.72.4
2. Use productFlavors

### Snack or a link to a repository

NA

### Reanimated version

3.5.1

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

Release mode

### Device

None

### Acknowledgements

Yes

**Comment by gaurav-vij** [comment] 2023-09-15 02:11
Its a private app. so, would be difficult to share the snack link. everything worked fine with old version of 2.9.1. we recently initiated a fresh app with same react-native code as old one. We upgraded code and also all other plugins to latest one. and there it started crashing intermittently.

**Comment by gaurav-vij** [comment] 2023-09-15 03:05
I have shared the scenario where its failing

**Comment by gaurav-vij** [comment] 2023-09-15 05:58
Further update.... i downgraded react-native-reanimated to 3.4.2 and "hermes" to false, and it works like a charm. No crashes. This means, something related to 3.5.1 and hermes.

**Comment by xeroxoid** [comment] 2023-09-15 06:38
Can confirm that on v3.5.1 the app crashes on Release mode when entering any screen with animation and that reverting to 3.4.2 fixes the issue.

@gaurav-vij for me hermes did not need to be set to false.

**Comment by gaurav-vij** [comment] 2023-09-15 06:51
Yes. its like that. and 3.4.2 i tried with hermes disabled. and it worked like a charm

**Comment by tamdvyounetgroup** [comment] 2023-09-15 08:53
@gaurav-vij it's not working. ??

**Comment by tjzel** [comment] 2023-09-15 10:50
Duplicate of #5067. Fix already done in #5087.

**Comment by efstathiosntonas** [comment] 2023-09-15 10:50
this PR fixes it: https://github.com/software-mansion/react-native-reanimated/pull/5087 

duplicate of  https://github.com/software-mansion/react-native-reanimated/issues/5067 ,https://github.com/software-mansion/react-native-reanimated/issues/5075, https://github.com/software-mansion/react-native-reanimated/issues/5069

**Closed by tjzel** 2023-09-15 10:50 UTC
Labels: Missing repro, Platform: Android, Needs review, Missing info

**Comment by gaurav-vij** [comment] 2023-09-15 18:55
In which version the fix will be available, can you please share

**Comment by efstathiosntonas** [comment] 2023-09-15 18:58
@gaurav-vij version 3.5.2
