### ISSUE TITLE
RN 0.65.0 require some new listener methods on the Native Module when call the NativeEventEmitter. It shows the "new NativeEventEmmiter()..." warning.

### ISSUE THREAD

**Issue by wfern** [software-mansion/react-native-reanimated#2297] opened 2021-08-19 18:10 UTC
## Description

A lot of libraries, including this one is showing a warning with the message: "new NativeEventEmitter() was called with a non-null argument without the required `addListener/removeListeners` method." Like the image below:
![image](https://user-images.githubusercontent.com/4096003/130115408-137fd8b1-d059-4698-a6af-d5f221d0e578.png)

This warning is shown because of the commit [114be1d](https://github.com/facebook/react-native/commit/114be1d2170bae2d29da749c07b45acf931e51e2), which checks if the Native Module has the methods: `addListener` and `removeListeners`. These checks are necessary because of this commit [f5502fb](https://github.com/facebook/react-native/commit/f5502fbda9fe271ff6e1d0da773a3a8ee206a453), which tries to use the Native Module to notify subscriptions on Android. So I think this issue is only related to Android and the 0.65.0 release.

Doing some tests in **_another libraries_** with the old architecture I was able to fix it adding those methods in the Native Module in Java:
```
@ReactMethod
public void addListener(String eventName) {
  // Keep: Required for RN built in Event Emitter Calls.
}

@ReactMethod
public void removeListeners(Integer count) {
  // Keep: Required for RN built in Event Emitter Calls.
}
```

I don't know if this is the best method to handle this issue, but I think it's don't cause any trouble like was commented in this commit [f5502fb](https://github.com/facebook/react-native/commit/f5502fbda9fe271ff6e1d0da773a3a8ee206a453).

### Expected behavior
Do not show any warning in the console about the NativeEventEmitter.

### Actual behavior & steps to reproduce
Just build react-native 0.65.0 with this library and execute the most basic example in the docs.

## Snack or minimal code example
The first example in the docs: https://docs.swmansion.com/react-native-reanimated/docs/animations

## Package versions

- React Native: 0.65.0
- React Native Reanimated: 2.3.0-alpha.2
- NodeJS: 14.17.3
- Xcode:
- Java & Gradle: 11.0.10 / 6.9

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by RadiantF-pondok** [comment] 2021-08-20 03:16
may I ask you how to add those two methods in the Native Module in Java?

**Comment by Rubon72** [comment] 2021-08-20 20:27
Yes, big problem for me now

**Comment by arunim2405** [comment] 2021-08-21 06:05
Question, do these warnings affect the functionality of the library? If yes, how so?

**Comment by wfern** [comment] 2021-08-22 17:09
> Question, do these warnings affect the functionality of the library? If yes, how so?

I believe it **don't**, this changes in the react-native is just a new API. Just like was described in this [commit](https://github.com/facebook/react-native/commit/f5502fbda9fe271ff6e1d0da773a3a8ee206a453).

In my tests it just shows the warning but everything works fine. Including in another libraries.


> may I ask you how to add those two methods in the Native Module in Java?

I don't know if this is possible in this package because of the TurboModules in v2 but you can try to apply those methods using https://github.com/ds300/patch-package like was did in https://github.com/invertase/react-native-firebase/pull/5616 until the maintainers fix this.

**Comment by mikehardy** [comment] 2021-08-23 19:23
This is just a warning, however it's also easy to fix. I've fixed in react-native-firebase, netinfo, and react-native-device-info

This file https://github.com/software-mansion/react-native-reanimated/blob/master/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java

Needs these lines:

```java
  @ReactMethod
  public void addListener(String eventName) {
    // Keep: Required for RN built in Event Emitter Calls.
  }

  @ReactMethod
  public void removeListeners(Integer count) {
    // Keep: Required for RN built in Event Emitter Calls.
  }

```

**Comment by mikehardy** [comment] 2021-08-23 19:29
Unfortunately since this is packaged up as an aar there's no way to patch this using patch-package. I made a PR

**Closed** 2021-08-23 22:26 UTC
Labels: 🐞 Bug, 🏠  Reanimated2

**Comment by piaskowyk** [comment] 2021-08-23 22:28
Thanks for help for everyone 🙌

**Comment by kodeandoec** [comment] 2021-09-06 15:20
Some one have solve to issue?

**Comment by mikehardy** [comment] 2021-09-06 19:02
Hello from Cuenca @kodeandoec  👋 - the issue is solved, it's just waiting on a release. Subscribe to this repo with a custom subscription for releases and you'll get a notification when it ships. Until then you can LogBox ignore the warning https://reactnative.dev/docs/debugging#console-errors-and-warnings
