### ISSUE TITLE
crash ...reanimated2/hook/useAnimatedStyle.ts (185:0):1:1174

### ISSUE THREAD

**Issue by Norfeldt** [software-mansion/react-native-reanimated#3674] opened 2022-10-14 09:44 UTC
### Description

I'm very sorry that I can't provide a reproducible snack, but on Firebase Test Labs (run automatically on google play) I keep seeing this flaky crash 

```
at frame (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (185:0):1:1174)
``` 

I'm using EAS to build the project with plugins.

> package.json

```
    "moti": "^0.19.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-redash": "^18.1.0",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-svg": "^12.4.4",
```

I'm working very hard to see if I can narrow it down to what's causing the issue, but if you have any suggestions on what to look into, please say so.

### Steps to reproduce

<img width="566" alt="Screenshot 2022-10-14 at 11 46 42" src="https://user-images.githubusercontent.com/678806/195817142-b1c3c2e9-6deb-4a0f-a057-9df5d1657e95.png">

The click that caused this to break was

```
import * as React from 'react'
import { Keyboard, Platform, Pressable, PressableProps, ViewStyle } from 'react-native'

import Configuration from '~/constants/Configuration'

type Props = {
  callback?: () => void
  style?: ViewStyle
} & PressableProps

export function DismissKeyboard({ children, callback, style, ...props }: Props) {
  return (
    <Pressable
      accessibilityHint="Tryk her for at minimere tastaturet"
      accessibilityLabel="Minimere tastaturet"
      onPress={() => {
        Configuration.DEV && console.log('Dismiss keyboard')
        if (Platform.OS !== 'web') Keyboard.dismiss()
        callback?.()
      }}
      {...props}
      style={[{ flex: 1 }, style]}
      accessible
    >
      <>{children}</>
    </Pressable>
  )
}
```

this is the log I get from Firebase Test Lab:

```
10-14 02:34:10.939: W/ChimeraUtils(2515): Module com.google.android.gms.nearby_en has empty metadata display_name_string_id
10-14 02:34:10.940: W/gle.android.gm(2713): Suspending all threads took: 79.118ms
10-14 02:34:10.958: W/UiControllerImpl(7712): Waiting for: DELAY_HAS_PAST for 200 iterations.
10-14 02:34:10.968: E/unknown:ViewManager(7712): Error while updating prop transform
10-14 02:34:10.968: E/unknown:ViewManager(7712): java.lang.reflect.InvocationTargetException
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at java.lang.reflect.Method.invoke(Native Method)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:93)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:142)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:305)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.swmansion.reanimated.NodesManager.updateProps(NodesManager.java:588)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.swmansion.reanimated.NativeProxy.updateProps(NativeProxy.java:170)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.swmansion.reanimated.NativeProxy$AnimationFrameCallback.onAnimationFrame(Native Method)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:273)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.swmansion.reanimated.NodesManager.access$000(NodesManager.java:65)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:170)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.view.Choreographer.doFrame(Choreographer.java:693)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.os.Handler.handleCallback(Handler.java:873)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:7)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.os.Handler.handleCallback(Handler.java:873)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.os.Looper.loop(Looper.java:193)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at java.lang.reflect.Method.invoke(Native Method)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-14 02:34:10.968: E/unknown:ViewManager(7712): Caused by: java.lang.NumberFormatException: For input string: "undefinedNaN"
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at java.lang.Float.parseFloat(Float.java:451)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.TransformHelper.convertToRadians(TransformHelper.java:40)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.TransformHelper.processTransform(TransformHelper.java:79)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.BaseViewManager.setTransformProperty(BaseViewManager.java:359)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	at com.facebook.react.uimanager.BaseViewManager.setTransform(BaseViewManager.java:82)
10-14 02:34:10.968: E/unknown:ViewManager(7712): 	... 41 more
10-14 02:34:10.969: I/HermesVM(7712): JSI rethrowing JS exception: Exception in HostFunction: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTText
10-14 02:34:10.969: I/HermesVM(7712): Error: Exception in HostFunction: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTText
10-14 02:34:10.969: I/HermesVM(7712):     at _updateProps (native)
10-14 02:34:10.969: I/HermesVM(7712):     at anonymous (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (46:26):1:267)
10-14 02:34:10.969: I/HermesVM(7712):     at forEach (native)
10-14 02:34:10.969: I/HermesVM(7712):     at _f (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (46:26):1:229)
10-14 02:34:10.969: I/HermesVM(7712):     at _f (native)
10-14 02:34:10.969: I/HermesVM(7712):     at frame (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (185:0):1:1174)
10-14 02:34:10.970: I/HermesVM(7712): JSI rethrowing JS exception: Exception in HostFunction: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTText
10-14 02:34:10.970: I/HermesVM(7712): Error: Exception in HostFunction: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTText
10-14 02:34:10.970: I/HermesVM(7712):     at _updateProps (native)
10-14 02:34:10.970: I/HermesVM(7712):     at anonymous (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (46:26):1:267)
10-14 02:34:10.970: I/HermesVM(7712):     at forEach (native)
10-14 02:34:10.970: I/HermesVM(7712):     at _f (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (46:26):1:229)
10-14 02:34:10.970: I/HermesVM(7712):     at _f (native)
10-14 02:34:10.970: I/HermesVM(7712):     at frame (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (185:0):1:1174)
10-14 02:34:10.990: I/Robo(7712): Rethrowing the exception thrown by the app.
10-14 02:34:10.991: I/Robo(7712): java.lang.RuntimeException: Exception in HostFunction: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTText
10-14 02:34:10.991: I/Robo(7712): Error: Exception in HostFunction: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTText
10-14 02:34:10.991: I/Robo(7712):     at _updateProps (native)
10-14 02:34:10.991: I/Robo(7712):     at anonymous (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (46:26):1:267)
10-14 02:34:10.991: I/Robo(7712):     at forEach (native)
10-14 02:34:10.991: I/Robo(7712):     at _f (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (46:26):1:229)
10-14 02:34:10.991: I/Robo(7712):     at _f (native)
10-14 02:34:10.991: I/Robo(7712):     at frame (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (185:0):1:1174)
10-14 02:34:10.991: I/Robo(7712): 	at com.swmansion.reanimated.AndroidErrorHandler.raise(AndroidErrorHandler.java:6)
10-14 02:34:10.991: I/Robo(7712): 	at com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
10-14 02:34:10.991: I/Robo(7712): 	at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:24)
10-14 02:34:10.991: I/Robo(7712): 	at com.swmansion.reanimated.Scheduler$2.runGuarded(Scheduler.java:43)
10-14 02:34:10.991: I/Robo(7712): 	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
10-14 02:34:10.991: I/Robo(7712): 	at android.os.Handler.handleCallback(Handler.java:873)
10-14 02:34:10.991: I/Robo(7712): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:7)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
10-14 02:34:10.991: I/Robo(7712): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
10-14 02:34:10.991: I/Robo(7712): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-14 02:34:10.991: I/Robo(7712): 	at android.os.Handler.handleCallback(Handler.java:873)
10-14 02:34:10.991: I/Robo(7712): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 02:34:10.991: I/Robo(7712): 	at android.os.Looper.loop(Looper.java:193)
10-14 02:34:10.991: I/Robo(7712): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
10-14 02:34:10.991: I/Robo(7712): 	at java.lang.reflect.Method.invoke(Native Method)
10-14 02:34:10.991: I/Robo(7712): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-14 02:34:10.991: I/Robo(7712): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-14 02:34:10.991: I/Robo(7712): --------- beginning of crash
10-14 02:34:10.991: E/AndroidRuntime(7712): FATAL EXCEPTION: Thread-6
10-14 02:34:10.991: E/AndroidRuntime(7712): Process: investments.nord, PID: 7712
10-14 02:34:10.991: E/AndroidRuntime(7712): java.lang.RuntimeException: Exception in HostFunction: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTText
10-14 02:34:10.991: E/AndroidRuntime(7712): Error: Exception in HostFunction: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTText
10-14 02:34:10.991: E/AndroidRuntime(7712):     at _updateProps (native)
10-14 02:34:10.991: E/AndroidRuntime(7712):     at anonymous (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (46:26):1:267)
10-14 02:34:10.991: E/AndroidRuntime(7712):     at forEach (native)
10-14 02:34:10.991: E/AndroidRuntime(7712):     at _f (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (46:26):1:229)
10-14 02:34:10.991: E/AndroidRuntime(7712):     at _f (native)
10-14 02:34:10.991: E/AndroidRuntime(7712):     at frame (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (185:0):1:1174)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at com.swmansion.reanimated.AndroidErrorHandler.raise(AndroidErrorHandler.java:6)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:24)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at com.swmansion.reanimated.Scheduler$2.runGuarded(Scheduler.java:43)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at android.os.Handler.handleCallback(Handler.java:873)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:7)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at android.os.Handler.handleCallback(Handler.java:873)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at android.os.Looper.loop(Looper.java:193)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at java.lang.reflect.Method.invoke(Native Method)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-14 02:34:10.991: E/AndroidRuntime(7712): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Snack or a link to a repository

sorry

### Reanimated version

~2.9.1

### React Native version

0.69.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Build type

Release mode

### Device

Real device

### Device model

SM-G981U1, API Level 29

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2022-10-14 11:22
Hey, can you check if the issue is still present on 2.11.0?

**Comment by Norfeldt** [comment] 2022-10-14 13:21
@tomekzaw `npx expo install` does not allow me to go higher than `2.9.1`

**Comment by tomekzaw** [comment] 2022-10-14 13:27
@Norfeldt Oh, right, I didn't notice that you're using Expo managed workflow. 

The app crashes because of `at com.swmansion.reanimated.AndroidErrorHandler.raise(AndroidErrorHandler.java:6)` which doesn't behave correctly on Android. Error handling on Android was improved in #3558 and released in 2.11.0.

However, the root cause of this problem is `JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTText`. Currently I have no idea why it fails and it's difficult to debug it without repro 😢

**Comment by Norfeldt** [comment] 2022-10-14 13:46
Thanks, it's also pretty hard for me to reproduce the error consistently on firebase test lab

**Closed** 2022-11-09 11:16 UTC
Labels: Missing repro, Platform: Android, Needs review

**Comment by tomekzaw** [comment] 2022-11-09 20:35
Hey @Norfeldt, I'm sorry to hear this. I'll try to replicate this issue on my setup when I have some free time.

**Comment by rinku-k** [comment] 2023-09-08 07:12
I am not sure if this will be helpful, but my project is using reanimated 1.9.0 (We are migrating to new one soon), but this issue is only found in production and is not reproducible in devices. The stack traces and device trends are as follow - 

> Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTImageView
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1184)
       at android.view.Choreographer.doCallbacks(Choreographer.java:986)
       at android.view.Choreographer.doFrame(Choreographer.java:907)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1171)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8333)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)


<img width="554" alt="Screenshot 2023-09-08 at 12 39 53 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/14367488/954382fa-9afc-413a-8f18-1fc52001f30d">

I hope the above data can help with resolution.
