### ISSUE TITLE
Reanimated V2 app crashes at launch on android

### ISSUE THREAD

**Issue by aganjali** [software-mansion/react-native-reanimated#980] opened 2020-07-15 04:12 UTC
## Description
i just setup a project with rn 0.63 and added reanimated v2 everything is fine on ios but on android app crashes on launch with attached logcat output below.

### Screenshots
this is my MainApplication.java and MainActivity.java files
![app](https://user-images.githubusercontent.com/13061606/87502273-6d468480-c676-11ea-8b82-7129a1899071.png)
![activity](https://user-images.githubusercontent.com/13061606/87502322-8b13e980-c676-11ea-9c03-c3071c03fbb4.png)

and also this is output of logcat on crash
![logcat](https://user-images.githubusercontent.com/13061606/87502337-98c96f00-c676-11ea-9b2b-48efee677117.png)

### Expected behavior
No crash.

### Actual behavior
app crashes at launch 

## Snack or minimal code example

This is link to repository of my boilerplate app https://gitlab.com/aganjali/orbi-app
just clean android gradle, yarn and run!

## Package versions

- React: 16.13.1
- React Native: 0.63.0
- React Native Reanimated: 2.0.0-alpha.3

**Comment by sergchernata** [comment] 2020-07-15 14:16
Same error here.

```
2020-07-15 10:15:15.169 18101-18323/com.app E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.app, PID: 18101
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN5folly3f146detail15kEmptyTagVectorE" referenced by "/data/app/com.app-hje6k6CcGWG9-Ng9S-UEmQ==/lib/arm64/libreanimated.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.swmansion.reanimated.NativeProxy.<clinit>(NativeProxy.java:25)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage$NativeProxyProvider.get(ReanimatedJSIModulePackage.java:25)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage$NativeProxyProvider.get(ReanimatedJSIModulePackage.java:15)
        at com.facebook.react.bridge.JSIModuleHolder.getJSIModule(JSIModuleHolder.java:25)
        at com.facebook.react.bridge.JSIModuleRegistry.getModule(JSIModuleRegistry.java:26)
        at com.facebook.react.bridge.CatalystInstanceImpl.getJSIModule(CatalystInstanceImpl.java:668)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1267)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by SudoPlz** [comment] 2020-07-15 19:18
Same here, any ideas?

**Comment by flimble** [comment] 2020-07-16 08:10
Same here

**Comment by SudoPlz** [comment] 2020-07-16 11:28
[This ](https://github.com/software-mansion/react-native-reanimated/commit/188fafe833eab23b5a6d306916af2dc330772709) may be fixing the issue but I can't test because alpha 4 is not released yet, and cloning the repo fails (because of https://github.com/software-mansion/react-native-reanimated/issues/984)

**Comment by KoboBunny** [comment] 2020-07-17 14:00
I'm also having an issue with android after upgrading to React Native 0.63 but @SudoPlz your explanation for iOS was perfect and completely resolved my issue so thanks so much for posting the patch! 

I tried following the diffs you posted here about android on your "This" link @SudoPlz but I'm still running into issues.  What specifically did you change to get it to work?

Below is the error I'm getting now:

![Screen Shot 2020-07-17 at 8 59 46 AM](https://user-images.githubusercontent.com/66628216/87794182-4625b980-c814-11ea-9670-15fd18ae67b6.png)

**Comment by KoboBunny** [comment] 2020-07-17 14:02
@jakub-gonet  do you know when alpha.4 will be released?  It seems the tag is already created but it would be great to know when we can expect it!

**Comment by SudoPlz** [comment] 2020-07-17 14:18
@KoboBunny apologies for confusing you, I never got it to work, I'm still waiting for one of the maintainers of this repo to post an answer.

I just noticed that my "This" link contained a new .aar file for 0.63.0 and since we're facing a linker issue (which is probably because some method is missing from within those aar files I thought maybe the maintainers are already working on it and already have a fix - that was just an assumption)

alpha 4 exists indeed but I have no idea when they'll release it, we're both on the same boat here and I wish we could get someone from software-mansion to shed some light.

**Comment by terrysahaidak** [comment] 2020-07-17 18:50
alpha.4 has been released. also, it includes support for RN 0.63. could you test it and post back here?

**Comment by SudoPlz** [comment] 2020-07-17 19:05
I'll test in a couple of minutes and let you know, thanks for the heads up @terrysahaidak

**Comment by SudoPlz** [comment] 2020-07-17 21:39
Yaaaaaaay it looks like the issue is gone on alpha.4 thank you so much @terrysahaidak 
I don't have much time to test right now, but if anything else comes up I'll ping you.

I appreciate it.

**Comment by aganjali** [comment] 2020-07-17 23:19
> alpha.4 has been released. also, it includes support for RN 0.63. could you test it and post back here?

i setup a simple test as below
![image](https://user-images.githubusercontent.com/13061606/87837663-86834700-c8a9-11ea-8818-219ff768f425.png)

and i get this 
![image](https://user-images.githubusercontent.com/13061606/87837690-a0248e80-c8a9-11ea-968d-e2cfe8d17582.png)

**Comment by aganjali** [comment] 2020-07-17 23:27
> alpha.4 has been released. also, it includes support for RN 0.63. could you test it and post back here?

everything is fine! i can close this issue thank you.

**Closed** 2020-07-17 23:28 UTC
Labels: 🐞 Bug, 🤔 To verify
