### ISSUE TITLE
[iOS] Crashes in production

### ISSUE THREAD

**Issue by kesha-antonov** [software-mansion/react-native-reanimated#2341] opened 2021-08-30 14:39 UTC
Hi!

## Description

In dev everything works fine.
In production I have crashes on every app boot.

### Expected behavior

No crashes.

### Actual behavior & steps to reproduce

<img width="1136" alt="Screenshot 2021-08-30 at 17 38 57" src="https://user-images.githubusercontent.com/11584712/131356807-4690613e-6405-4f22-adb9-d5a8e6dc6adf.png">

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-alpha.2

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by jmysliv** [comment] 2021-08-31 06:30
Duplicate of #2327

**Closed by jmysliv** 2021-08-31 06:30 UTC
Labels: 🐞 Bug, 🏠  Reanimated2
