### ISSUE TITLE
Exception thrown while executing UI block: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

### ISSUE THREAD

**Issue by miodrage** [software-mansion/react-native-reanimated#183] opened 2019-02-06 12:29 UTC
## Reproduction
Issue happens only when running on iOS

We have a screen where we show an image. We use modified version of this [example.](https://github.com/kmagiera/react-native-reanimated/blob/master/Example/imageViewer/index.js)
Modified version can be found [here.](https://gist.github.com/miodrage/60b2d814db1696a7af90a23085788a78)

Issue happens when one navigate away from a screen where the touch handler is used and then navigate back to it using react-navigation's ```navigation.goBack();```.  See the output below.

Same happens if we use the imageViewer example without modifining it. 

This issue doesn't happen on Android.

## Issue screenshot - iOS
![image](https://user-images.githubusercontent.com/14963603/52336509-6b01e480-2a05-11e9-948c-41b6af32c52f.png)

## Console log
![image](https://user-images.githubusercontent.com/14963603/52336607-9e447380-2a05-11e9-9240-884e8b31869d.png)
![image](https://user-images.githubusercontent.com/14963603/52336631-b2887080-2a05-11e9-9875-6a49e34ce9c8.png)

### Output of node -v && npm -v && npm ls --prod --depth=1
```  
v11.6.0
6.5.0
capmo@0.0.1 /Users/miodrag/Desktop/pave/mobileapp
├─┬ @ambassify/fetch-retried@1.1.0
│ └── @ambassify/fetch@1.0.3
├─┬ @nozbe/watermelondb@0.8.0
│ ├── rambdax@0.21.0
│ ├── rxjs@6.3.2 deduped
│ ├── rxjs-compat@6.3.3
│ └── sql-escape-string@1.1.0
├─┬ @nozbe/with-observables@1.0.1
│ └── rxjs@6.3.2 deduped
├─┬ better-queue@3.8.10
│ ├── better-queue-memory@1.0.3 deduped
│ ├── node-eta@0.9.0
│ └── uuid@3.3.2 deduped
├── better-queue-memory@1.0.3
├─┬ color@3.1.0
│ ├── color-convert@1.9.3
│ └── color-string@1.5.3
├── date-fns@1.29.0
├─┬ es6-symbol@3.1.1
│ ├── d@1.0.0
│ └── es5-ext@0.10.46
├── events@2.1.0
├─┬ extract-files@2.1.1
│ └── @babel/runtime@7.1.2
├─┬ formik@1.2.0
│ ├── create-react-context@0.2.3
│ ├── deepmerge@2.1.1
│ ├── hoist-non-react-statics@2.5.5
│ ├── lodash.clonedeep@4.5.0
│ ├── lodash.topath@4.5.2
│ ├── prop-types@15.6.2 deduped
│ ├── UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0 || ^16.0.0
│ ├── react-fast-compare@1.0.0
│ ├── tslib@1.9.3
│ └── warning@3.0.0
├── lodash@4.17.11
├── moment@2.22.2
├─┬ moment-timezone@0.5.21
│ └── moment@2.22.2 deduped
├─┬ prop-types@15.6.2
│ ├── loose-envify@1.4.0
│ └── object-assign@4.1.1
├── ramda@0.25.0
├─┬ UNMET PEER DEPENDENCY react@16.6.0-alpha.8af6728
│ ├── loose-envify@1.4.0 deduped
│ ├── object-assign@4.1.1 deduped
│ ├── prop-types@15.6.2 deduped
│ └── scheduler@0.10.0
├─┬ UNMET PEER DEPENDENCY react-native@0.57.4
│ ├── @babel/runtime@7.1.2 deduped
│ ├── absolute-path@0.0.0
│ ├── art@0.10.3
│ ├── base64-js@1.3.0
│ ├── chalk@1.1.3
│ ├── commander@2.17.1
│ ├── compression@1.7.3
│ ├── connect@3.6.6
│ ├── create-react-class@15.6.3
│ ├── debug@2.6.9
│ ├── denodeify@1.2.1
│ ├── envinfo@5.10.0
│ ├── errorhandler@1.5.0
│ ├── escape-string-regexp@1.0.5
│ ├── event-target-shim@1.1.1
│ ├── fbjs@1.0.0
│ ├── fbjs-scripts@0.8.3
│ ├── fs-extra@1.0.0
│ ├── glob@7.1.3
│ ├── graceful-fs@4.1.11
│ ├── inquirer@3.3.0
│ ├── lodash@4.17.11 deduped
│ ├── metro@0.48.3
│ ├── metro-babel-register@0.48.3
│ ├── metro-core@0.48.3
│ ├── metro-memory-fs@0.48.3
│ ├── mime@1.6.0
│ ├── minimist@1.2.0
│ ├── mkdirp@0.5.1
│ ├── morgan@1.9.0
│ ├── node-fetch@2.2.0
│ ├── node-notifier@5.2.1
│ ├── npmlog@2.0.4
│ ├── opn@3.0.3
│ ├── optimist@0.6.1
│ ├── plist@3.0.1
│ ├── pretty-format@4.3.1
│ ├── promise@7.3.1
│ ├── prop-types@15.6.2 deduped
│ ├── react-clone-referenced-element@1.0.1
│ ├── react-devtools-core@3.4.2
│ ├── react-timer-mixin@0.13.4
│ ├── regenerator-runtime@0.11.1
│ ├── rimraf@2.6.2
│ ├── semver@5.5.1
│ ├── serve-static@1.13.2
│ ├── shell-quote@1.6.1
│ ├── stacktrace-parser@0.1.4
│ ├── ws@1.1.5
│ ├── xcode@1.0.0
│ ├── xmldoc@0.4.0
│ └── yargs@9.0.1
├─┬ react-native-datepicker@1.7.2
│ └── moment@2.22.2 deduped
├── react-native-elevated-view@0.0.6
├─┬ react-native-gesture-handler@1.0.7
│ ├── hoist-non-react-statics@2.5.5 deduped
│ ├── invariant@2.2.4
│ └── prop-types@15.6.2 deduped
├── react-native-image-pan-zoom@2.1.10
├── react-native-image-picker@0.26.10
├─┬ react-native-image-zoom-viewer@2.2.19
│ └── react-native-image-pan-zoom@2.1.10 deduped
├─┬ react-native-keyboard-aware-scroll-view@0.7.4
│ ├── prop-types@15.6.2 deduped
│ └── react-native-iphone-x-helper@1.2.0
├─┬ react-native-modal@6.5.0
│ ├── prop-types@15.6.2 deduped
│ └── react-native-animatable@1.3.0
├─┬ react-native-modal-dropdown@0.6.2
│ └── prop-types@15.6.2 deduped
├─┬ react-native-paper@2.0.1
│ ├── @callstack/react-theme-provider@1.0.3
│ ├── color@2.0.1
│ ├── create-react-context@0.2.3 deduped
│ ├── hoist-non-react-statics@2.5.5 deduped
│ ├── UNMET PEER DEPENDENCY react@^15.3.0 || ^16.0.0
│ └── react-lifecycles-compat@3.0.4
├─┬ react-native-pdf@5.0.9
│ ├── crypto-js@3.1.9-1
│ └── prop-types@15.6.2 deduped
├── react-native-reanimated@1.0.0-alpha.9
├── react-native-remote-svg@1.3.0
├── react-native-responsive-screen@1.1.10
├── react-native-screens@1.0.0-alpha.12
├── react-native-splash-screen@3.1.1
├── react-native-status-bar-height@2.1.0
├── react-native-typography@1.4.0
├─┬ react-native-vector-icons@5.0.0
│ ├── lodash@4.17.11 deduped
│ ├── prop-types@15.6.2 deduped
│ └── yargs@8.0.2
├─┬ react-navigation@2.12.1
│ ├── clamp@1.0.1
│ ├── create-react-context@0.2.3 deduped
│ ├── hoist-non-react-statics@2.5.5 deduped
│ ├── path-to-regexp@1.7.0
│ ├── query-string@6.1.0
│ ├── UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0 || ^16.0.0
│ ├── react-lifecycles-compat@3.0.4 deduped
│ ├── react-native-safe-area-view@0.9.0
│ ├── react-navigation-deprecated-tab-navigator@1.3.0
│ ├── react-navigation-drawer@0.5.0
│ ├── react-navigation-stack@0.2.3
│ └── react-navigation-tabs@0.6.0
├─┬ react-validator-prop-types@1.1.0
│ └── validator@3.43.0
├─┬ recompose@0.30.0
│ ├── @babel/runtime@7.1.2 deduped
│ ├── change-emitter@0.1.6
│ ├── fbjs@0.8.17
│ ├── hoist-non-react-statics@2.5.5 deduped
│ ├── react-lifecycles-compat@3.0.4 deduped
│ └── symbol-observable@1.2.0
├─┬ rn-fetch-blob@0.10.13
│ ├── base-64@0.1.0
│ └── glob@7.0.6
├─┬ rxjs@6.3.2
│ └── tslib@1.9.3 deduped
├─┬ styled-components@3.4.9
│ ├── buffer@5.2.1
│ ├── css-to-react-native@2.2.2
│ ├── fbjs@0.8.17 deduped
│ ├── hoist-non-react-statics@2.5.5 deduped
│ ├── prop-types@15.6.2 deduped
│ ├── react-is@16.5.2
│ ├── stylis@3.5.3
│ ├── stylis-rule-sheet@0.0.10
│ └── supports-color@3.2.3
├─┬ util@0.11.0
│ └── inherits@2.0.3
└── uuid@3.3.2

npm ERR! peer dep missing: react@^16.5.0, required by @nozbe/watermelondb@0.8.0
npm ERR! peer dep missing: react@^16.4.2, required by @nozbe/with-observables@1.0.1
npm ERR! peer dep missing: react@>=15, required by formik@1.2.0
npm ERR! peer dep missing: react@> 15.0.0, required by react-native-gesture-handler@1.0.7
npm ERR! peer dep missing: react@16.0.0-alpha.6, required by react-native-reanimated@1.0.0-alpha.9
npm ERR! peer dep missing: react@>=15, required by react-native-remote-svg@1.3.0
npm ERR! peer dep missing: react@>=16.0.0, required by react-native-testing-library@1.5.0
npm ERR! peer dep missing: react@^16.0.0, required by react-test-renderer@16.4.1
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by recompose@0.30.0
npm ERR! peer dep missing: react@>= 0.14.0 < 17.0.0-0, required by styled-components@3.4.9
npm ERR! peer dep missing: react-native@^0.56.0, required by @nozbe/watermelondb@0.8.0
npm ERR! peer dep missing: react-native@^0.44.1, required by react-native-reanimated@1.0.0-alpha.9
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by create-react-context@0.2.3
npm ERR! peer dep missing: react@^15.3.0 || ^16.0.0, required by @callstack/react-theme-provider@1.0.3
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by create-react-context@0.2.3
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by create-react-context@0.2.3
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by create-react-context@0.2.3
```

**Comment by vnlebaoduy** [comment] 2019-04-05 03:09
me too

**Comment by RAFDigital101** [comment] 2019-04-29 13:56
I had the same error when I was using values in an animated view that hadn't been properly initialised. Maybe that helps with your issue.

**Comment by farhanaslam5151** [comment] 2019-10-31 08:33
any update on this facing the same issue while using Facebook ads expo

**Comment by michalsek** [comment] 2019-12-19 17:00
Hi @miodrage, I've tried to reproduce the bug using image viewer example but i'm unable to. Could you provide minimal code example that reproduces the problem? Thanks!

**Comment by Jarred-Sumner** [comment] 2019-12-28 04:28
I've seen this bug a number of times (but it doesn't cause a crash). I believe it occurs when a component using an `Animated.Value` is unmounted before the `Animated.Value` update is propagated to the component. 

I notice it the most when a pan gesture recognizer updates the location of a component and then that component unmounts while moving it around.

If I had to guess, I would say this issue feels a little like forgetting to call `window.clearTimeout` on `componentWillUnmount` – maybe somewhere pending callbacks need to be cleared when a UIView is detached/unmounted?

**Comment by SmirnovM91** [comment] 2020-04-18 10:03
Hello, any updates?

**Comment by mvogttech** [comment] 2020-04-28 20:47
I am also getting this error using the Facebook Ads package.

**Comment by hoanghuychh** [comment] 2020-06-23 16:31
Try **reinstall** your app in devices

**Comment by jkadamczyk** [comment] 2020-07-24 12:13
Hey folks 👋 
We decided to close this issue because we were not able to reproduce it for a long period of time. If anyone of you will be able to provide a minimal reproduction of this issue, we will reopen it and work on it.
Have a nice day! 😄

**Closed by jkadamczyk** 2020-07-24 12:13 UTC
Labels: 🍎iOS, 🐞bug-bash-dec19, 🧰need-repro

**Comment by Bluewaves54** [comment] 2021-12-19 03:36
I have the same issue when using the package react-native-make-it-rain.

**Comment by nathan-poncet** [comment] 2022-12-08 16:11
I had the same error in my projet and i solved it by deleting two props (entering and exiting) in an <Animated.View> component.

**Comment by hitanshu-cybersurf** [comment] 2023-10-04 05:39
I am facing this issue from last 2-3 days so i will recommend to open this issue.
And if anyone have faced it and solved it anyhow, please let me know the solution.

**Comment by Hewr-Srood** [comment] 2023-10-09 13:06
@hitanshu-cybersurf  did find any way to fix this issue?

**Comment by hitanshu-cybersurf** [comment] 2023-10-09 13:28
> @hitanshu-cybersurf did find any way to fix this issue?

Yes, i just updated the version of react native, from 0.70+ to 0.71+

**Comment by Hewr-Srood** [comment] 2023-10-09 13:35
@hitanshu-cybersurf, thanks for the solution!
