### ISSUE TITLE
Transition behaves weird on Android

### ISSUE THREAD

**Issue by sgtechmthinh** [software-mansion/react-native-reanimated#449] opened 2019-10-31 03:02 UTC
react native ver0.59
I use ` Transitioning` and `Transition` to demonstrate appearance and disappearance of some elements smoothly

This is what I got on Android,
All children disappeared
![Screenshot_2019-10-31-10-00-30-914_com logivan shipper](https://user-images.githubusercontent.com/46363784/67915403-6ef21a00-fbc5-11e9-902a-69abcf168720.png)

If I wrap them from outside of this component, it looks like this
![Screenshot_2019-10-31-09-38-20-484_com logivan shipper](https://user-images.githubusercontent.com/46363784/67915433-8a5d2500-fbc5-11e9-8bd2-693b981f198a.png)

Here is my code
```
import React, { Component } from 'react';
import { View, Text, TouchableOpacity } from 'react-native';
import { Transition, Transitioning } from 'react-native-reanimated';

const { FIELDS } = ReduxFormConstants.FORM_NEW_ORDER;
const { flexDirectionRow, spaceBetween } = Common.styles;

const renderInputMaskTruckModel = fieldProps => (
  <InputButtonMask onPress={fieldProps.inputProps.onTouchStart}>
    <Input {...fieldProps} />
  </InputButtonMask>
);

class OrderCreationTrucksService extends Component {
  get truckType() {
    const { formValues } = this.props;
    return formValues?.truck_type;
  }

  render() {
    const { listTruckTypes, onGetTruckModels, loadingInfoGetTrucks } = this.props;
    const isSpecialTruckType = !!this.truckType && !this.truckType?.auto_suggest;

    return (
      <Transitioning.View
        transition={
          <Transition.Sequence>
            <Transition.Out type="scale" />
            <Transition.Change interpolation="easeInOut" />
            <Transition.In type="fade" />
          </Transition.Sequence>
        }
        ref={ref => (this.animation = ref)}
      >
        <View style={[flexDirectionRow, spaceBetween, styles.truckServiceHeader]}>
          <Text style={styles.sectionTitle}>{l10n.truck_services}</Text>
          <TouchableOpacity onPress={this.showModalTrucksDescription}>
            <Text style={styles.orangeText}>{l10n.truck_type_guide}</Text>
          </TouchableOpacity>
        </View>
        <Field
          name={FIELDS.TRUCK_TYPE}
          component={ChooseTruckTypesHorizontalList}
          trucksData={listTruckTypes}
          onPressItem={this.onChooseTruckType}
          selectedTruck={this.truckType}
          validate={[Validation.required]}
          getTruckModels={onGetTruckModels}
          loadingInfoGetTrucks={loadingInfoGetTrucks}
        />
        {isSpecialTruckType && (
          <View style={[styles.gutterTop15, styles.gutterHorizontal15]}>
            <Field
              renderRightComponent={() => (
                <Ionicons name="ios-arrow-down" style={styles.arrowIcon} color={Colors.black} />
              )}
              name={FIELDS.TRUCK_MODEL}
              component={renderInputMaskTruckModel}
              format={model => model?.full_dimensions}
              validate={[Validation.required]}
            />
          </View>
        )}
      </Transitioning.View>
    );
  }

  onChooseTruckType = truck => {
    const { change } = this.props;
    this.animation.animateNextTransition();
  };

export default OrderCreationTrucksService;

```

**Comment by todorone** [comment] 2019-11-11 07:42
Duplicate of #272

**Closed** 2019-12-19 17:12 UTC
Labels: 🐞bug-bash-dec19
