### ISSUE TITLE
onMomentumEnd of useAnimatedScrollHandler not fired for Android

### ISSUE THREAD

**Issue by itsramiel** [software-mansion/react-native-reanimated#5416] opened 2023-11-27 09:02 UTC
### Description

`onMomentumEnd` of `useAnimatedScrollHandler` is not fired for Android unless `onMomentumScrollEnd` is set on `Animated.ScrollView`

Previous related issues https://github.com/software-mansion/react-native-reanimated/issues/303, https://github.com/software-mansion/react-native-reanimated/issues/2735, and https://github.com/software-mansion/react-native-reanimated/issues/5058 but the issue is still valid

### Steps to reproduce

Run the following reproducible:
```
import {View} from 'react-native';
import Animated, {useAnimatedScrollHandler} from 'react-native-reanimated';

function App() {
  const onScroll = useAnimatedScrollHandler({
    onMomentumEnd: () => {
      console.log('end hook');
    },
  });

  return (
    <View style={{flex: 1}}>
      <Animated.ScrollView
        // uncomment the line under me for things to work
        // onMomentumScrollEnd={() => console.log('end inline')}
        onScroll={onScroll}>
        {Array.from({length: 20}).map((_, index) => (
          <View
            key={index}
            style={{
              height: 150,
              backgroundColor: 'cyan',
              marginVertical: 12,
              borderRadius: 4,
            }}
          />
        ))}
      </Animated.ScrollView>
    </View>
  );
}

export default App;
```

### Snack or a link to a repository

https://snack.expo.dev/@ramiel99/arrogant-violet-waffle

### Reanimated version

3.5.4

### React Native version

0.72.7

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2023-11-27 15:38
Duplicate of #303, duplicate of #2735, duplicate of #5008, should be fixed with #3948.

**Comment by itsramiel** [comment] 2023-11-27 16:49
@tomekzaw the PR been a draft for almost a year. Any plans to finalize it?

**Comment by tomekzaw** [comment] 2023-11-27 21:28
@itsramiel I wasn't particularly happy about the approach and I'll need to rethink it. Also, there's a one-liner workaround for this so it's not as urgent as other topics that we're currently working on.

**Comment by Iuriy-Budnikov** [comment] 2024-06-04 09:50
The same issue with ios :(

**Comment by szydlovsky** [comment] 2024-06-06 12:47
Hey @itsramiel @Iuriy-Budnikov, I believe the issue is already fixed on newer Reanimated versions (I'd suggest 3.10, 3.11 or 3.12)

**Closed by szydlovsky** 2024-06-06 12:47 UTC
Labels: Platform: Android, Needs review, Repro provided
