### ISSUE TITLE
makeShareableCloneRecursive Call Stack Size Exceeded

### ISSUE THREAD

**Issue by SamuelScheit** [software-mansion/react-native-reanimated#4177] opened 2023-03-06 17:00 UTC
### Description

I've switched from version 2.14.4 to the latest version 3.0.1 and get the error `Maximum call stack size exceeded` in the function `makeShareableCloneRecursive` from reanimated.

<div float="left">
  <img src="https://user-images.githubusercontent.com/34555296/223177813-00d3d7cf-e082-458a-9e4c-68b8255983e6.png" width="200" />
  <img src="https://user-images.githubusercontent.com/34555296/223177859-d8c72374-4511-44cd-9e4b-5a395a2f9cc6.png" width="200" />
</div>

### Steps to reproduce

I can't seem to isolate the issue, but it happened after upgrading to the latest version.
I've updated the Pods and reinstalled the App.
What could cause this kind of issue?

### Snack or a link to a repository

-

### Reanimated version

3.0.1

### React Native version

0.71.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone 12 mini

### Acknowledgements

Yes

**Comment by jb4e** [comment] 2023-03-06 18:05
We hit this as well when attempting to upgrade from v3 RC1. Haven't had a chance to dig in yet, but we will add more details if we can figure out a minimum repro.

**Comment by philipheinser** [comment] 2023-03-06 20:56
Added a log to the shareable clone and seeing this:

```
me": null, "_threadCount": 0, "displayName": "ReactRedux"}
 LOG  key $$typeof
 LOG  element Symbol(react.context)
 LOG  key _currentValue
 LOG  element null
 LOG  key _currentValue2
 LOG  element null
 LOG  key _threadCount
 LOG  element 0
 LOG  key Provider
 LOG  element {"$$typeof": Symbol(react.provider), "_context": {"$$typeof": Symbol(react.context), "Consumer": {"$$typeof": Symbol(react.context), "_context": [Circular]}, "Provider": [Circular], "_currentRenderer": {}, "_currentRenderer2": null, "_currentValue": null, "_currentValue2": null, "_defaultValue": null, "_globalName": null, "_threadCount": 0, "displayName": "ReactRedux"}}
 LOG  value {"$$typeof": Symbol(react.provider), "_context": {"$$typeof": Symbol(react.context), "Consumer": {"$$typeof": Symbol(react.context), "_context": [Circular]}, "Provider": [Circular], "_currentRenderer": {}, "_currentRenderer2": null, "_currentValue": null, "_currentValue2": null, "_defaultValue": null, "_globalName": null, "_threadCount": 0, "displayName": "ReactRedux"}}
 LOG  key $$typeof
 LOG  element Symbol(react.provider)
 LOG  key _context
 LOG  element {"$$typeof": Symbol(react.context), "Consumer": {"$$typeof": Symbol(react.context), "_context": [Circular]}, "Provider": {"$$typeof": Symbol(react.provider), "_context": [Circular]}, "_currentRenderer": {}, "_currentRenderer2": null, "_currentValue": null, "_currentValue2": null, "_defaultValue": null, "_globalName": null, "_threadCount": 0, "displayName": "ReactRedux"}
 LOG  value {"$$typeof": Symbol(react.context), "Consumer": {"$$typeof": Symbol(react.context), "_context": [Circular]}, "Provider": {"$$typeof": Symbol(react.provider), "_context": [Circular]}, "_currentRenderer": {}, "_currentRenderer2": null, "_currentValue": null, "_currentValue2": null, "_defaultValue": null, "_globalName": null, "_threadCount": 0, "displayName": "ReactRedux"}
 LOG  key $$typeof
 LOG  element Symbol(react.context)
 LOG  key _currentValue
 LOG  element null
 LOG  key _currentValue2
 LOG  element null
 LOG  key _threadCount
 LOG  element 0
 LOG  key Provider
 LOG  element {"$$typeof": Symbol(react.provider), "_context": {"$$typeof": Symbol(react.context), "Consumer": {"$$typeof": Symbol(react.context), "_context": [Circular]}, "Provider": [Circular], "_currentRenderer": {}, "_currentRenderer2": null, "_currentValue": null, "_currentValue2": null, "_defaultValue": null, "_globalName": null, "_threadCount": 0, "displayName": "ReactRedux"}}
 LOG  value {"$$typeof": Symbol(react.provider), "_context": {"$$typeof": Symbol(react.context), "Consumer": {"$$typeof": Symbol(react.context), "_context": [Circular]}, "Provider": [Circular], "_currentRenderer": {}, "_currentRenderer2": null, "_currentValue": null, "_currentValue2": null, "_defaultValue": null, "_globalName": null, "_threadCount": 0, "displayName": "ReactRedux"}}
```

**Comment by Montyc666** [comment] 2023-03-07 08:17
category:Ideas @3022819432=

**Comment by Montyc666** [comment] 2023-03-07 08:18
``category:Ideas @3022819432= [category:Ideas @3022819432= ](category:Ideas @3022819432= )

**Comment by pelayomartinez** [comment] 2023-03-07 17:41
Commenting to follow. Also getting this error on Expo development client

**Comment by andrewlo** [comment] 2023-03-09 18:01
It might be related to PanGestureHandler. When I remove PanGestureHandler from the screen where this error is happening, the error doesn't occur any more

**Comment by TomCorvus** [comment] 2023-03-09 19:05
Interesting @andrewlo, I'm using react-native-pager-view on the screen where this message appears.
Maybe a clue to reproduce this on minimal repo.

**Comment by azcarraga** [comment] 2023-03-09 20:59
In our case, I was able to narrow down to two different places where this error occurs. One was a Gesture.Pan.onEnd(), and the other was a useDerivedValue(). I narrowed down in both to a single line of code - and in both cases that line of code was referencing a prop from the containing component.

Could be coincidence, but @andrewlo @TomCorvus it might be worth checking if you can narrow down to the line of code inside the PanGestureHandler that's causing the failure.

I've still had no luck with a min repro. We had to stay on our previous build for now.

**Comment by Montyc666** [comment] 2023-03-12 08:07
@talkback
``

**Comment by surethink** [comment] 2023-03-27 02:41
got the same issue, any hero can fix it?

**Comment by SamuelScheit** [comment] 2023-03-28 18:07
I found out why the problem occurs.
```jsx
function Test(props) {
	const obj = {
		opacity: 1,
	}
	obj.test = obj; // make the object recursive

	const style = useAnimatedStyle(() => ({
		opacity: obj.opacity,
	}));
	return <Animated.View style={style} />
}
```

To workaround this issue you have to convert the variable to serializable value, e.g. with object destructuring:
```jsx
function Test(props) {
	const obj = {
		opacity: 1,
	}
	obj.test = obj; // make the object recursive

	const { opacity } = obj

	const style = useAnimatedStyle(() => ({
		opacity: opacity,
	}));

	return <Animated.View style={style} />
}
```

Reanimated V2 seems to automatically detect recursive objects and handle this edge case, but V3 does not.

**Comment by canpoyrazoglu** [comment] 2023-04-01 10:06
In my case the following code causes the same error:

```
    const [displayedChildren, setDisplayedChildren] = useState(props.children);
    const appearanceAnimation = useSharedValue(1);
    useEffect(() => {
        if(props.children != displayedChildren){
            appearanceAnimation.value = withTiming(0, {
                duration: TRANSITION_DURATION,
                easing: Easing.ease
            }, (finished) => {
                if(finished){
                    setDisplayedChildren(props.children);
                    appearanceAnimation.value = withTiming(1, {
                        duration: TRANSITION_DURATION
                    })
                }
            });
            
        }
    }, [props.children]);
```

I'm also new to Reanimated so I don't know how to solve it. First I though it was a recursive state update at my side, then I've seen this:

![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-04-01 at 13 05 21](https://user-images.githubusercontent.com/4348413/229279753-702e29be-a097-49c9-82d2-f6bac0bb29ec.png)

Any help to get rid of this would be appreciated.

**Comment by SudoPlz** [comment] 2023-04-06 18:52
I think the way to reproduce it is the following:

Example:
Assume that we have 2 class components, **Component A** and **Component B**.
    
- Component A contains Component B within its render function.
- Component A passes one of it's methods as a property to Component B

```
class ComponentA extends Component {
  doSomethingCool = () => {
    'worklet';
    // all the cool things
    return 'cool';
  }
  render() {
    return (<ComponentB
      doSomethingCoolProp={this.doSomethingCool}
    />)
  }
}
```

then in componentB you do:

```
class ComponentB extends Component {

  anotherFunc = () => {
    'worklet';
    const cool = this.props.doSomethingCoolProp();
  }

  whateverFunc() {
    runOnUI(anotherFunc)
  }
}
```

As soon as doSomethingCool is called we'll get the above error.

In my example `anotherFunc` is invoked by `react-native-gesture-handler`'s `Gesture.Pan().onEnd()` so I'm not running runOnUI manually, but I think it's done below the hood. Still that's when I get this error.

**Comment by TwistedMinda** [comment] 2023-04-08 19:24
For me it was popping when trying to install reanimated v3 with react-native < 0.71

Now that I've successfully migrated to 0.71.4 I don't have this error anymore -- no code changed

**Comment by SudoPlz** [comment] 2023-04-10 08:26
> For me it was popping when trying to install reanimated v3 with react-native < 0.71
> 
> Now that I've successfully migrated to 0.71.4 I don't have this error anymore -- no code changed

Definitely not our case. That's happening on our end and we're on 0.71.4 and reanimated v3.

**Comment by SudoPlz** [comment] 2023-04-10 08:28
Also, I noticed that sometimes, even converting a method from a const arrow function to an old school function like so:

```
class ComponentC extends Component {
  doSomethingCool = () => {
    'worklet';
    // this breaks
    return 'cool';
  }
  render() {
    return (<ComponentB
      doSomethingCoolProp={this.doSomethingCool}
    />)
  }
}
```

```
class ComponentC extends Component {
  function doSomethingCool() {
    'worklet';
    // this works
    return 'cool';
  }
  render() {
    return (<ComponentB
      doSomethingCoolProp={this.doSomethingCool}
    />)
  }
}
```

**Comment by TomCorvus** [comment] 2023-04-10 09:53
It happens with react-native-draggable-flatlist for me and this PR fixes the problem (https://github.com/computerjazz/react-native-draggable-flatlist/issues/462)
If this problem occurs with a third-party library, a fix is maybe needed to be fully compatible with rea 3.

**Comment by SudoPlz** [comment] 2023-04-10 14:53
> It happens with react-native-draggable-flatlist for me and this PR fixes the problem ([computerjazz/react-native-draggable-flatlist#462](https://github.com/computerjazz/react-native-draggable-flatlist/pull/462)) If this problem occurs with a third-party library, a fix is maybe needed to be fully compatible with rea 3.

so it looks like the main takeaway here is to avoid passing props from outside of the context of the `worklet` if I my understanding is correct.

We can only pass params through the function parameters, and not from the outer scope.

**Comment by LeviWilliams** [comment] 2023-04-10 15:56
Just chiming in here in case this helps somebody - when we upgraded to V3 we had these issues alongside the app just freezing. The issue in our case is that we were incorrectly modifying a shared value within `useDerivedValue` which causes an infinite loop as shared values will auto-update that worklet. Though, this somehow worked fine in v2. Example of what you shouldn't do:

```
const derived = useDerivedValue(() => {
...
sharedVal.value = 'whatever'
})
```

**Comment by canpoyrazoglu** [comment] 2023-04-10 16:15
> Also, I noticed that sometimes, even converting a method from a const arrow function to an old school function like so:
> 
> from:
> 
> ```
> class ComponentC extends Component {
>   doSomethingCool = () => {
>     'worklet';
>     // this breaks
>     return 'cool';
>   }
> }
> ```
> 
> to:
> 
> ```
> class ComponentC extends Component {
>   function doSomethingCool() {
>     'worklet';
>     // this works
>     return 'cool';
>   }
> }
> ```
> 
> makes the error go away. (but not always)

In my case I'm not using worklets at all (honestly I don't even know how they exactly work) but still get this.

**Comment by kmagiera** [comment] 2023-04-13 07:37
@LeviWilliams The issue with updates in useDerivedValue is resolved here https://github.com/software-mansion/react-native-reanimated/pull/4358 and should be included in next 3. release

**Comment by azcarraga** [comment] 2023-04-21 10:17
This appears to be fixed in 3.1 - I can no longer repro. Thank you!

**Closed** 2023-04-22 19:32 UTC
Labels: Missing repro, Platform: iOS, Needs review, Missing info

**Comment by thespacemanatee** [comment] 2023-07-06 17:40
Is anyone getting this issue again?

**Comment by devoren** [comment] 2023-07-11 17:53
@thespacemanatee me too, im getting this issue again

**Comment by a-eid** [comment] 2023-07-11 19:52
getting a similar issue as well.

**Comment by fr3nzy** [comment] 2023-07-23 12:05
I get this error when I'm running in debug mode, then using developer settings to change to release mode. 

I find rebuilding and using `react-native start --reset-cache` tends to fix this issue.

**Comment by datngotan-aavn** [comment] 2025-01-22 08:50
I got this crash on Production.
```
Fatal Exception: RCTFatalException: Unhandled JS Exception: RangeError: Maximum call stack size exceeded (native stack depth), js engine: hermes
Unhandled JS Exception: RangeError: Maximum call stack size exceeded (native stack depth), js engine: hermes, stack: makeShareableCloneRecursive@93197:29 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@94499:125 get value@92905:28 makeShareableCloneRecursive@93244:41 anonymous@93198:46 makeShareableCloneRecursive@93197:29 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@94499:125 get value@92905:28 makeShareableCloneRecursive@93244:41 anonymous@93198:46 makeShareableCloneRecursive@93197:29 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@94499:125 get value@92905:28 makeShareableCloneRecursive@93244:41 anonymous@93198:46 makeShareableCloneRecursive@93197:29 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@94499:125 get value@92905:28 makeShareableCloneRecursive@93244:41 anonymous@93198:46 makeShareableCloneRecursive@93197:29 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@94499:125 get value@92905:28 makeShareableCloneRecursive@93244:41 anonymous@93198:46 makeShareableCloneRecursive@93197:29 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@94499:125 makeShareableCloneRecursive@93244:41 anonymous@93198:46 makeShareableCloneRecursive@93197:29 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@94499:125 get value@92905:28 makeShareableCloneRecursive@93244:41 anonymous@93198:46 makeShareableCloneRecursive@93197:29 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@94499:125 get value@92905:28 makeShareableCloneRecursive@93244:41 anonymous@93198:46 makeShareableCloneRecursive@93197:29 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@94499:125 get value@92905:28 makeShareableCloneRecursive@93244:41 makeShareableCloneRecursive@93251:54 makeShareableCloneRecursive@93251:54 anonymous@93198:46 makeShareableCloneRecursive
```
