### ISSUE TITLE
Javascript worklet error In file: /build/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (29:27)

### ISSUE THREAD

**Issue by techpanga** [software-mansion/react-native-reanimated#2267] opened 2021-08-10 12:24 UTC
Seeing runtime error **RuntimeException:** Javascript worklet error In file: /build/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (29:27)

android app crashing by throwing this error.

"expo": "~42.0.1",
    "expo-application": "~3.2.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-reanimated": "~2.2.0",

## Affected platforms

- [ x] Android

**Comment by jmysliv** [comment] 2021-08-10 13:12
Hi @techpanga, can you provide some more information to help us resolve this issue?
- more detailed description of when the error happened
- code example and steps on how can we reproduce this error

**Comment by techpanga** [comment] 2021-08-11 12:22
Hi @jmysliv , Thank you for response.

Issue is occurring at the starting screen of the app...
In android on emulator, no issues.
In android on device, debug build no issues.
In android on production release mode, app is being crashed throwing this error in sentry.

`java.lang.RuntimeException: Javascript worklet error
In file: /build/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/UpdateProps.ts (29:27)
    at com.swmansion.reanimated.AndroidErrorHandler.raise(AndroidErrorHandler.java:6)
    at com.swmansion.reanimated.Scheduler.triggerUI(Scheduler.java)
    at com.swmansion.reanimated.Scheduler.access$100(Scheduler.java:9)
    at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:21)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

I am trying to locate which animation is causing this problem.

**Comment by techpanga** [comment] 2021-08-12 22:46
Hi All

I do not see issue in debug mode. I see issue in production deployment.

Thank you

**Comment by techpanga** [comment] 2021-08-14 14:19
Hi @jmysliv 

`(props)=>{
    const [disabled,setDisabled] = React.useState(false);
    const [event,setEvent] = React.useState(undefined);
    const scale = useSharedValue(1);
    const pressed = useSharedValue(false);
    const shadows = [
        [2,0.25,3.84,5],
        [1,0.18,1,1],
        [0,0,0,0],
    ]
    const shadow = props.flat?shadows[2]:shadows[0];
    const s1 = useSharedValue(shadow[0]);
    const s2 = useSharedValue(shadow[1]);
    const s3 = useSharedValue(shadow[2]);
    const s4 = useSharedValue(shadow[3]);
    const handlePress = (e)=>{
        if(disabled){return true;}
        setDisabled(true);
        props.onPress && props.onPress(e);
    }
    const translateY = useSharedValue(0);
    const scaleAgain = useSharedValue(1);
    const eventHandler = useAnimatedGestureHandler({
        onStart: (event, ctx) => {
          cancelAnimation(pressed);
          s1.value = withSpring(shadows[1][0]);
          s2.value = withSpring(shadows[1][1]);
          s3.value = withSpring(shadows[1][2]);
          s4.value = withSpring(shadows[1][3]);
          if(props.animation==='jump'){
              translateY.value = withSequence(withTiming(-10,{duration:500}),withTiming(0,{duration:500}));
              scaleAgain.value = withSequence(withTiming(1.5,{duration:500}),withTiming(1,{duration:500}));
          }else{
                translateY.value = withSequence(withTiming(-4,{duration:100}),withTiming(0,{duration:100}));
                scaleAgain.value = withSequence(withTiming(1.005,{duration:100}),withTiming(1,{duration:100}));
          }
        },
        onEnd: (event, ctx) => {
          s1.value = withSpring(shadow[0]);
          s2.value = withSpring(shadow[1]);
          s3.value = withSpring(shadow[2]);
          s4.value = withSpring(shadow[3]);
          runOnJS(handlePress)();
        },
      });
    React.useEffect(()=>{
        if(disabled){
            const timeoutTracker=setTimeout(()=>setDisabled(false),props.disableTimeout||4000);
            return ()=>timeoutTracker && clearTimeout(timeoutTracker);
        }
    },[disabled]);
    
    const uas = useAnimatedStyle(()=>{
        return {
            shadowOffset: {
                width: 0,
                height: s1.value,
            },
            shadowOpacity: s2.value,
            shadowRadius: s3.value,
            elevation: s4.value,
            transform: [{ scale: pressed.value?withRepeat(withSequence(withSpring(1.3,{
            damping:7
        }),withSpring(1)),2,false):1}]};
    });
    
    const uasJumper = useAnimatedStyle(()=>{
        return {transform:[{translateY:translateY.value},{scale:scaleAgain.value}]}
    })
    return <TapGestureHandler onGestureEvent={eventHandler}>
            <Animated.View style={[{position:'relative',margin:2,shadowColor: "#000"},props.style,props.containerStyle,uas,uasJumper]}>{(typeof props.children === 'string')?<Animated.Text  allowFontScaling={false} style={[{fontSize:18,fontWeight:'600'},props.textStyle]}>{props.children}</Animated.Text>:props.children}</Animated.View>
    </TapGestureHandler>;
}`

Looks like this piece of code is causing the error on android production. Still trying to figure it out why part.

This was working in android dev mode, iOS (prod and dev)

Any help is appreciated.

**Comment by jmysliv** [comment] 2021-08-16 06:30
@techpanga I see that you are using nested style property `shadowOffset` which isn't yet supported (#2257) and seems to crash the android application, see this issue -> #2040. Check if it'll work if you change it to something like this:
```js
shadowOffset: Platform.OS === "ios" ? { width: 0, height: s1.value } : undefined,
```
Let me know if it worked!

**Comment by techpanga** [comment] 2021-08-17 13:22
Thank you @jmysliv

**Comment by jmysliv** [comment] 2021-08-18 06:24
@techpanga No problem. I'm gonna close this issue then, cause it's probably a duplicate of #2040.

**Closed by jmysliv** 2021-08-18 06:24 UTC
Labels: 🐞 Bug, 🏠  Reanimated2
