### ISSUE TITLE
Build failed with RN 0.72.0 + react-native-reanimated 3.3.0 Android

### ISSUE THREAD

**Issue by vincemavill** [software-mansion/react-native-reanimated#4726] opened 2023-07-13 04:42 UTC
### Description

Build failed on Android,

I am using windows with Android studio simulator
NDK version: 23.1.7779620
React Native version: 0.72.0
react-native-reanimated: 3.3.0

Error message below

node_modules/react-native-reanimated/Common/cpp/Fabric/ReanimatedUIManagerBinding.cpp.o cannot be safely placed under this directory. The build may not work correctly. ninja: error: manifest 'build.ninja' still dirty after 100 tries

### Steps to reproduce

RN 0.72.0 + react-native-reanimated 3.3.0 IOS is working fine
Tried to build for Android and got the build failed error.

### Snack or a link to a repository

none

### Reanimated version

3.3.0

### React Native version

0.72

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Device model

Any

### Acknowledgements

Yes

**Comment by tjzel** [comment] 2023-07-13 15:25
hi @vincemavill, could you try with NDK 23.2.8568313?

**Comment by chakup** [comment] 2023-07-13 19:37
> hi @vincemavill, could you try with NDK 23.2.8568313?

Not the OP however I am experiencing the same issue. My project runs RN version 0.72.3. I just tried chaking the NDK version from 23.1.7779620 to 23.2.8568313 and I still receive the same error.

`[1/2] Re-running CMake... -- Configuring done -- Generating done -- Build files have been written to: C:/Users/react-native-client/node_modules/react-native-reanimated/android/.cxx/Debug/4439j593/arm64-v8a C++ build system [build] failed while executing: @echo off "C:\\Users\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^ -C ^ "C:\\Users\\react-native-client\\node_modules\\react-native-reanimated\\android\\.cxx\\Debug\\4439j593\\arm64-v8a" ^ reanimated from C:\Users\react-native-client\node_modules\react-native-reanimated\android ninja: error: manifest 'build.ninja' still dirty after 100 tries * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 1m 3s.`

**Comment by vincemavill** [comment] 2023-07-14 04:12
@tjzel hi sir, I tried NDK 23.2.8568313, but still the same error. :(

**Comment by fukemy** [comment] 2023-07-14 04:21
Do you tried to put the project in other driver? Eg: D, E. May be some problem with accessing in C driver
Other solution, remove all space from project, driver name,..

**Comment by vincemavill** [comment] 2023-07-14 05:45
@fukemy hello sir, i dont know if that is the solution cause my other RN projects are on desktop. they are running fine.

**Comment by JoseRivas-HOD** [comment] 2023-07-17 17:38
I get the same error when running `gradlew assembleRelease`
```
  C++ build system [build] failed while executing:
      @echo off
      "C:\\...\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "C:\\...\\node_modules\\react-native-reanimated\\android\\.cxx\\RelWithDebInfo\\s7071p43\\armeabi-v7a" ^
        reanimated
    from C:\...\node_modules\react-native-reanimated\android
  ninja: error: manifest 'build.ninja' still dirty after 100 tries
```

**Comment by JuuRousse** [comment] 2023-07-24 07:53
The same issue on RN 0.72.2 and react-native-reanimated 3.3.0

**Comment by vaibhavdeshmukh0703** [comment] 2023-07-24 12:10
The same issue on RN 0.72.2 and react-native-reanimated 3.3.0

../node_modules/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModuleSpec.cpp.o

    cannot be safely placed under this directory.  The build may not work
    correctly.


  ninja: error: manifest 'build.ninja' still dirty after 100 tries

**Comment by logicallydimp23** [comment] 2023-07-25 22:48
```
> Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
C/C++: ninja: Entering directory `/Users/username/Documents/eHasp-Mobile/node_modules/react-native-reanimated/android/.cxx/Debug/2l6o3w1p/arm64-v8a'
C/C++: ld: error: undefined symbol: _Unwind_Resume
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ld: error: undefined symbol: _Unwind_Resume
```

getting this error using M1 on Ventura 13.5

```
  >>> did you mean: __Unwind_Resume
  >>> defined in: /opt/homebrew/opt/llvm/lib/libunwind.a
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
 ```

**Comment by revealer409** [comment] 2023-07-26 12:12
**facing same issue when building app** 

    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7", 
![RN_ISSUE](https://github.com/software-mansion/react-native-reanimated/assets/48885797/d221ac7b-bfc4-4f55-9e1b-43a6cba4c7bb)

    "react-native": "0.72.1",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-reanimated": "^3.4.0",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.23.0"

**Comment by tjzel** [comment] 2023-07-26 18:19
I just built a fresh RN 0.72.3 App with Reanimated 3.3.0 on Windows with NDK 23.2.8568313 and there were no problems.

What you can do (if you haven't tried yet) is invalidating Android Studio's cache:
File -> Invalidate Caches... -> (tick all, just to be sure) Invalidate and Restart

If this doesn't help I'm afraid without an actual repro it's going to be extremely hard to fix/investigate this issue.

**Comment by revealer409** [comment] 2023-07-26 20:47
Finally build successfully 👍 

![image](https://github.com/software-mansion/react-native-reanimated/assets/48885797/8e38567a-e50b-4b01-9693-c3c83e285515)


here are some changes I have made:
Packages & dependencies 
"@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "react": "18.2.0",
    "react-native": "0.72.1",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-reanimated": "^3.0.0-rc.3",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.23.0"

steps:
1. uninstall  "react-native-reanimated" and then install this version of **RNR  3.0.0-rc.3**
2. Installed ndk version "23.1.7779620"
3. added **ndk** path in **local.properties** file under **android**    like below
ndk.dir=C\:\\Users\\kashif\\AppData\\Local\\Android\\sdk\\ndk\\23.1.7779620

- move project to main drive like D\:  because **RNR** CMAKE  PATH characters should be less than 250.

EXCEPTIONAL Chcange  

 minSdkVersion  from 21 to 23 as i was using status bar so that requires min SDK v=23

Build succeeded. 💯

**Comment by revealer409** [comment] 2023-07-27 05:46
Now its also working with 
  "react-native-reanimated": "^3.4.0",

**Comment by logicallydimp23** [comment] 2023-07-27 06:41
> ```
> > Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
> C/C++: ninja: Entering directory `/Users/username/Documents/eHasp-Mobile/node_modules/react-native-reanimated/android/.cxx/Debug/2l6o3w1p/arm64-v8a'
> C/C++: ld: error: undefined symbol: _Unwind_Resume
> C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ld: error: undefined symbol: _Unwind_Resume
> ```
> 
> getting this error using M1 with macOS Ventura 13.5
> 
> ```
>   >>> did you mean: __Unwind_Resume
>   >>> defined in: /opt/homebrew/opt/llvm/lib/libunwind.a
>   clang++: error: linker command failed with exit code 1 (use -v to see invocation)
>   ninja: build stopped: subcommand failed.
> ```

if you encounter this issue on mac, just uninstall llvm `brew uninstall llvm`

**Comment by bfricka** [comment] 2023-07-27 19:47
> hi @vincemavill, could you try with NDK 23.2.8568313?
Changing NDK won't work because reanimated doesn't respect `ndkVersion`. Need to modify the build.gradle similar to:

```groovy
android {
  ndkVersion safeExtGet('ndkVersion', DEFAULT_NDK_VERSION)
```

**Comment by Koykoy200078** [comment] 2023-08-04 02:45
still having this problem, unsolved😢

**Comment by Koykoy200078** [comment] 2023-08-16 01:40
I don't know why but it's working now

**Comment by Gabriel-Mariano** [comment] 2023-08-16 20:06
@Koykoy200078 Como você conseguiu? essa versão  "react-native-reanimated":  "^3.4.1", está funcionando bem só no ios, mas no android estou tendo problemas.

**Comment by diegodorado** [comment] 2023-08-25 16:38
I got this issue on a mac, but it works ok on a linux machine.
Digging for some time, guided by a comment about uninstalling llvm (which, if you do, it works, but...) I found that the default behaviour of the ndk is to pass the LDFLAGS env var to the compiler

I had on my mac system set to `LDFLAGS="-L/opt/homebrew/opt/llvm/lib"` for some reason I do not remember.

The workaround I found is to unset it before compiling android, like

```
export LDFLAGS=""
yarn android
```


And that did it for me, although a little unconfortable to communicate.
Note: you need to clean your gradle project to test this out.

**Comment by GrantBartlett** [comment] 2023-08-29 15:30
I had a long path to the project when getting this error. Moving to `C:/Dev/Project` as opposed to something like `C:/Dev/Folder/Folder/Folder/Project` fixed this issue for me.  Maybe it helps others in the meantime.

**Comment by MDAkramSiddiqui** [comment] 2023-10-07 05:40
> > ```
> > > Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
> > C/C++: ninja: Entering directory `/Users/username/Documents/eHasp-Mobile/node_modules/react-native-reanimated/android/.cxx/Debug/2l6o3w1p/arm64-v8a'
> > C/C++: ld: error: undefined symbol: _Unwind_Resume
> > C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> > ld: error: undefined symbol: _Unwind_Resume
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > getting this error using M1 with macOS Ventura 13.5
> > ```
> >   >>> did you mean: __Unwind_Resume
> >   >>> defined in: /opt/homebrew/opt/llvm/lib/libunwind.a
> >   clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> >   ninja: build stopped: subcommand failed.
> > ```
> 
> if you encounter this issue on mac, just uninstall llvm `brew uninstall llvm`

Worked for me, I uninstalled llvm 16 and then it started working.

**Comment by edgardanielgd** [comment] 2023-10-07 13:28
Windows 11
React Native: 0.72.5
react-native-gesture-handler: ^2.13.1
react-native-reanimated: ^3.5.4

In fact moving project to a simplier path (in my case D:/HabitusMobile ) solved the problem

**Comment by Koykoy200078** [comment] 2023-10-09 08:41
> Como você conseguiu? essa versão "react-native-reanimated": "^3.4.1", está funcionando bem só no ios, mas no android estou tendo problemas.

Eu fiz isso depois que eu limpar minhas janelas eu acho que está no Visual Studio 2019 e o cmake fazendo com que ele conflitar um com o outro

**Comment by Koykoy200078** [comment] 2023-10-09 08:42
i did it after i clean my windows i think it lies on the visual studio 2019 and the cmake making it conflict each other

**Comment by Nikituh** [comment] 2023-10-14 12:28
> if you encounter this issue on mac, just uninstall llvm `brew uninstall llvm`

🎉 This also solved the issue for me!

But it's not really a proper solution, is it? I need `llvm` on my command line as well and this shouldn't cause a react-native dependency to completely break my project.

**Comment by cctv1005s** [comment] 2023-10-19 15:03
> > ```
> > > Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
> > C/C++: ninja: Entering directory `/Users/username/Documents/eHasp-Mobile/node_modules/react-native-reanimated/android/.cxx/Debug/2l6o3w1p/arm64-v8a'
> > C/C++: ld: error: undefined symbol: _Unwind_Resume
> > C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> > ld: error: undefined symbol: _Unwind_Resume
> > ```
> > 
> > 
> > getting this error using M1 with macOS Ventura 13.5
> > ```
> >   >>> did you mean: __Unwind_Resume
> >   >>> defined in: /opt/homebrew/opt/llvm/lib/libunwind.a
> >   clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> >   ninja: build stopped: subcommand failed.
> > ```
> 
> if you encounter this issue on mac, just uninstall llvm `brew uninstall llvm`

Works for me, exactly works for  `ld: error: undefined symbol: _Unwind_Resume`

**Comment by Latropos** [comment] 2023-10-30 15:48
Closing, since I can confirm that solutions listed above are valid

**Comment by milon27** [comment] 2023-11-02 18:07
RN 0.72.3 + react-native-reanimated 3.4.1 Android

build succesfull with android studio. 
but if run `react native run android` got this error

note: I am using pnpm mono-repo. 

![image](https://github.com/software-mansion/react-native-reanimated/assets/44096479/2ed5df7a-d833-4a81-b281-3f1f7d7b3702)

**Comment by Latropos** [comment] 2023-12-15 12:15
Closing since we are unable to reproduce this problem on our end

**Closed by Latropos** 2023-12-15 12:15 UTC
Labels: Missing repro, Platform: Android, Needs review

**Comment by revealer409** [comment] 2023-12-19 07:02
@milon27  issue might be with your project **Path**  move project to E:/pnpm-workspace-vite
because long path also create issues with **CMAKE**

**Comment by Happends** [comment] 2024-01-09 00:32
Can confirm (on windows 11) that minimizing characters in path solved the issue.
am however unsure why this is not displayed as an error message. Can't a solution be to check path length before trying to compile with ninja?

**Comment by Shahanshah-TA** [comment] 2024-02-08 15:44
> Finally build successfully 👍
> 
> ![image](https://private-user-images.githubusercontent.com/48885797/256356832-8e38567a-e50b-4b01-9693-c3c83e285515.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDcyNjMsIm5iZiI6MTcwNzQwNjk2MywicGF0aCI6Ii80ODg4NTc5Ny8yNTYzNTY4MzItOGUzODU2N2EtZTUwYi00YjAxLTk2OTMtYzNjODNlMjg1NTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE1NDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYzEyNzhhMjZhNDliMjE3NzkxODFlMWEyY2FkNjJkNWRlMjczOGNhOTBhNjhiZWNmODk4N2ExZDA4YzFiMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E8o7nMSb8lvpvBkMEk66EeT-LmwG_7phqOPUJb3hPiY)
> 
> here are some changes I have made: Packages & dependencies "@react-navigation/drawer": "^6.6.3", "@react-navigation/native": "^6.1.7", "react": "18.2.0", "react-native": "0.72.1", "react-native-gesture-handler": "^2.12.0", "react-native-reanimated": "^3.0.0-rc.3", "react-native-safe-area-context": "^4.7.1", "react-native-screens": "^3.23.0"
> 
> steps:
> 
> 1. uninstall  "react-native-reanimated" and then install this version of **RNR  3.0.0-rc.3**
> 2. Installed ndk version "23.1.7779620"
> 3. added **ndk** path in **local.properties** file under **android**    like below
>    ndk.dir=C:\Users\kashif\AppData\Local\Android\sdk\ndk\23.1.7779620
> 4. **move project to main drive like D: ProjectDirectoryName\ because RNR** CMAKE  PATH characters should be less than 250.
> 5. add this in babelconfig.js
>    plugins: [
>    'react-native-reanimated/plugin' ]
>    EXCEPTIONAL Chcange
> 
> minSdkVersion from 21 to 23 as i was using status bar so that requires min SDK v=23
> 
> Build succeeded. 💯

dude Thanks a lot. 
I have been using mac from starting and now company have given me Windows and I didn't had any idea that keeping my project on Desktop will cause this issue. You D directory suggestion worked for me after spending 2 days. Thanks a lot again.

**Comment by SethArchambault** [comment] 2024-04-05 16:00
> > ```
> > > Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
> > C/C++: ninja: Entering directory `/Users/username/Documents/eHasp-Mobile/node_modules/react-native-reanimated/android/.cxx/Debug/2l6o3w1p/arm64-v8a'
> > C/C++: ld: error: undefined symbol: _Unwind_Resume
> > C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> > ld: error: undefined symbol: _Unwind_Resume
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > getting this error using M1 with macOS Ventura 13.5
> > ```
> >   >>> did you mean: __Unwind_Resume
> >   >>> defined in: /opt/homebrew/opt/llvm/lib/libunwind.a
> >   clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> >   ninja: build stopped: subcommand failed.
> > ```
> 
> if you encounter this issue on mac, just uninstall llvm `brew uninstall llvm`

Ah thank you, that did it!

**Comment by ArslanNaveed007** [comment] 2024-04-30 19:17
npm remove react-native-reanimated

after running this command its working fine

**Comment by merapi** [comment] 2024-05-07 20:49
> > ```
> > > Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
> > C/C++: ninja: Entering directory `/Users/username/Documents/eHasp-Mobile/node_modules/react-native-reanimated/android/.cxx/Debug/2l6o3w1p/arm64-v8a'
> > C/C++: ld: error: undefined symbol: _Unwind_Resume
> > C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> > ld: error: undefined symbol: _Unwind_Resume
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > getting this error using M1 with macOS Ventura 13.5
> > ```
> >   >>> did you mean: __Unwind_Resume
> >   >>> defined in: /opt/homebrew/opt/llvm/lib/libunwind.a
> >   clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> >   ninja: build stopped: subcommand failed.
> > ```
> 
> if you encounter this issue on mac, just uninstall llvm `brew uninstall llvm`

OMG I spent days on it, anybody can explain what happened here?

**Comment by VisheshG8** [comment] 2024-05-26 17:44
> I had a long path to the project when getting this error. Moving to `C:/Dev/Project` as opposed to something like `C:/Dev/Folder/Folder/Folder/Project` fixed this issue for me. Maybe it helps others in the meantime.

Thanks alot , It worked , Yes might be because windows has a limit of  256 max . and it is exceeding it causes the error . It doesn't mention this error which cause us to not find the direct reason . Hope this helps someone .

**Comment by vikrantnegi** [comment] 2024-05-31 06:30
> I had a long path to the project when getting this error. Moving to `C:/Dev/Project` as opposed to something like `C:/Dev/Folder/Folder/Folder/Project` fixed this issue for me. Maybe it helps others in the meantime.

This fixed the issue on windows. Thanks

**Comment by ameerhamzaWAL** [comment] 2024-10-29 12:46
This also solved the issue for me!

rm -rf android/.cxx android/app/.cxx android/app/build node_modules
yarn install

**Comment by aman08singh** [comment] 2024-10-30 13:34
Just for testing purposes:

Uninstall the react-native-reanimated library.
Build the project.

or

Without installing react-native-reanimated, follow steps from: https://www.nativewind.dev/getting-started/react-native

**Comment by alferth-gonzalez** [comment] 2024-11-01 19:20
If you encounter compilation errors due to CMake and dependency installation, follow these steps:

If you don’t have a `CMakeLists.txt` file in `android/app`, this may indicate an issue related to the CMake configuration or automatically generated autolinking by React Native. I suggest the following additional steps:

Regenerate autolinking: Without a **CMakeLists.txt** file, the autolinking system may be generating files incorrectly. Try deleting the generated autolinking files and re-running the setup:

`rm -rf android/app/build/generated`

Reinstall dependencies: Ensure all necessary dependencies are correctly reinstalled:

```
rm -rf node_modules
npm install
```

Temporarily disable autolinking for react-native-screens and react-native-safe-area-context: Some packages may have configuration issues with the autolinking system. You can disable autolinking for these packages and add them manually.

Create a react-native.config.js file in the root of the project (if it doesn’t already exist) and add the following to disable autolinking for these modules:


```
module.exports = {
  dependencies: {
    'react-native-screens': {
      platforms: {
        android: null,
      },
    },
    'react-native-safe-area-context': {
      platforms: {
        android: null,
      },
    },
  },
};
```

Manually add react-native-screens and react-native-safe-area-context to the project: After disabling autolinking, manually add the dependencies in android/settings.gradle:

```
include ':react-native-screens'
project(':react-native-screens').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-screens/android')

include ':react-native-safe-area-context'
project(':react-native-safe-area-context').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-safe-area-context/android')
```

And in android/app/build.gradle, add the dependencies in the dependencies section:

```
implementation project(':react-native-screens')
implementation project(':react-native-safe-area-context')
```

Perform a clean build: Run a complete clean and rebuild of the project:

```
cd android
./gradlew clean
cd ..
npx react-native run-android
```

These steps should prevent the autolinking system from generating incorrect CMake configuration files and allow the project to compile correctly.

**Comment by kmno** [comment] 2024-11-03 11:59
> If you encounter compilation errors due to CMake and dependency installation, follow these steps:
> 
> If you don’t have a `CMakeLists.txt` file in `android/app`, this may indicate an issue related to the CMake configuration or automatically generated autolinking by React Native. I suggest the following additional steps:
> 
> Regenerate autolinking: Without a **CMakeLists.txt** file, the autolinking system may be generating files incorrectly. Try deleting the generated autolinking files and re-running the setup:
> 
> `rm -rf android/app/build/generated`
> 
> Reinstall dependencies: Ensure all necessary dependencies are correctly reinstalled:
> 
> ```
> rm -rf node_modules
> npm install
> ```
> 
> Temporarily disable autolinking for react-native-screens and react-native-safe-area-context: Some packages may have configuration issues with the autolinking system. You can disable autolinking for these packages and add them manually.
> 
> Create a react-native.config.js file in the root of the project (if it doesn’t already exist) and add the following to disable autolinking for these modules:
> 
> ```
> module.exports = {
>   dependencies: {
>     'react-native-screens': {
>       platforms: {
>         android: null,
>       },
>     },
>     'react-native-safe-area-context': {
>       platforms: {
>         android: null,
>       },
>     },
>   },
> };
> ```
> 
> Manually add react-native-screens and react-native-safe-area-context to the project: After disabling autolinking, manually add the dependencies in android/settings.gradle:
> 
> ```
> include ':react-native-screens'
> project(':react-native-screens').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-screens/android')
> 
> include ':react-native-safe-area-context'
> project(':react-native-safe-area-context').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-safe-area-context/android')
> ```
> 
> And in android/app/build.gradle, add the dependencies in the dependencies section:
> 
> ```
> implementation project(':react-native-screens')
> implementation project(':react-native-safe-area-context')
> ```
> 
> Perform a clean build: Run a complete clean and rebuild of the project:
> 
> ```
> cd android
> ./gradlew clean
> cd ..
> npx react-native run-android
> ```
> 
> These steps should prevent the autolinking system from generating incorrect CMake configuration files and allow the project to compile correctly.

**This works.**

**Comment by Parmar-Bansi** [comment] 2025-01-22 13:33
> Configure project :react-native-reanimated
Android gradle plugin: 8.6.0
Gradle: 8.10.2

> Task :react-native-reanimated:buildCMakeRelWithDebInfo[arm64-v8a] FAILED
C/C++: ninja: error: mkdir(src/main/cpp/reanimated/CMakeFiles/reanimated.dir/D_/react-native/Future-homes/LeadPantherApp/node_modules/react-native-reanimated/Common): No such file or directory

any idea about my issue guide me

**Comment by Sandervg03** [comment] 2025-02-06 07:49
If anyone still needs this. This issue is caused by the path to your file being too long. If you have your project stored in for example: "C:\Users\RootUser\OneDrive\Desktop\Coding\Projects\My-First-React-Native-Project", this path name is considered to be too big. If you simply drag the project into a different directory closer to the root (making the file path shorter), you won't have any issues. (For example: "C:\Projects\My-First-React-Native-Project")

Hope this helps!

**Comment by ali-farhad** [comment] 2025-03-29 09:01
2025 and the issue was long path on windows.  I moved my project in the root of "C" and builds started working flawlessly !

**Comment by huynhhq** [comment] 2025-05-01 02:35
> rm -rf android/.cxx android/app/.cxx android/app/build node_modules

it worked for me. Thanks so much

**Comment by tomekzaw** [comment] 2025-05-01 12:06
Hi all, we added **"Building for Android on Windows"** troubleshooting guide to Reanimated docs. Please consult this page if you face any build errors for Android devices when building your app on Windows.

➡️ **https://docs.swmansion.com/react-native-reanimated/docs/guides/building-on-windows**

If the problem still persists, feel free to re-open the issue or submit a new one.
