### ISSUE TITLE
error: Error: Unable to resolve module `./Easing` from `node_modules\react-native-reanimated\src\Animated.js`:

### ISSUE THREAD

**Issue by keshav-optisol** [software-mansion/react-native-reanimated#1943] opened 2021-04-19 08:35 UTC
## Package versions

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by jakub-gonet** [comment] 2021-04-19 10:39
Duplicate of #1896.

**Closed by jakub-gonet** 2021-04-19 10:39 UTC
Labels: 🏠  Reanimated2, 🐞 Bug
