### ISSUE TITLE
Missing export TimingAnimation, application crash

### ISSUE THREAD

**Issue by Spit-Biagio** [software-mansion/react-native-reanimated#1102] opened 2020-08-10 12:42 UTC
## Description

crash on ios, Unable to resolve module TimingAnimation:

error: Error: Unable to resolve module `./animations/TimingAnimation` from `node_modules/react-native-reanimated/src/Animated.js`

### Screenshots
![Simulator Screen Shot - iPhone 11 - 2020-08-10 at 14 36 02](https://user-images.githubusercontent.com/47725236/89783216-dbb42080-db16-11ea-9b6c-782f15da479f.png)

## Steps To Reproduce

1. update to latest version on packages.json
2. npm install
3. npx pod-install
4 npx react-native run-ios

## Snack or minimal code example

i just update the new version
react-native-reanimated is used from react navigation 5, probably they need to update if u change something, but idk probably is a error on reanimated only

## Package versions

    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-reanimated": "^1.11.0",

**Comment by jakub-gonet** [comment] 2020-08-10 12:54
It's probably related to cache, `Animated.js` doesn't export this module anymore.

Try using resetting watchman & metro cache:
```
watchman watch-del-all
yarn start --reset-cache
```

If it doesn't help please reply.

**Comment by lumberman** [comment] 2020-08-10 22:03
Proposed solution didn't help.

**Comment by jakub-gonet** [comment] 2020-08-11 06:14
@lumberman, @Spit-Biagio 

Could you please provide output of the following commands?

1. `cat node_modules/react-native-reanimated/src/Animated.js`
2. `ls node_modules/react-native-reanimated/src/animations`

You can also try cleaning your repo like described by those two comments:

1. https://github.com/software-mansion/react-native-reanimated/issues/1007#issuecomment-662438323
2. https://github.com/software-mansion/react-native-reanimated/issues/1007#issuecomment-664439070

**Comment by jakub-gonet** [comment] 2020-08-11 10:37
I was unable to reproduce it in the new project, so I'm closing it until more info is provided.

**Closed by jakub-gonet** 2020-08-11 10:37 UTC
Labels: 🛠build-or-config-issue
