### ISSUE TITLE
undefined is not an object (evaluating '_toConsumableArray(Array(length)).map')

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#1257] opened 2020-09-21 08:11 UTC
## Description

I've been receiving the error `undefined is not an object (evaluating '_toConsumableArray(Array(length)).map')` and I have no idea where it comes from. I've tried to not render anything but the error still persists. It must be one of the worklets (`useDerivedValue`, `useAnimatedStyle`) because it's being thrown async (after the render func returns)

### Screenshots

![Simulator Screen Shot - iPhone 11 - 2020-09-21 at 09 52 53](https://user-images.githubusercontent.com/15199031/93744769-ad842f00-fbf2-11ea-963f-b2f32230ce88.png)

## Steps To Reproduce

Working on a repro.

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.6

**Comment by mrousavy** [comment] 2020-09-21 08:15
My bad, I've noticed I've used the spread operator (`...`) in a custom hook. For anyone else wondering; spread operators aren't supported in worklets (yet?).

**Comment by jakub-gonet** [comment] 2020-09-21 11:00
I've got the impression that some work was dedicated to fix spread operators. Could you please provide some reproduction example so we can test that?

**Comment by mrousavy** [comment] 2020-09-21 11:53
@jakub-gonet It's still listed under [Known problems and limitations](https://docs.swmansion.com/react-native-reanimated/docs/next#known-problems-and-limitations) 🤔 

Here's the code that was causing issues:

```ts
// ...
	return useDerivedValue(() =>
		[...Array(length)].map((_, index) => {
			const thisTranslateX = -(width * index);
			return interpolate(
				translateX.value,
				[thisTranslateX - width - width, thisTranslateX - width, thisTranslateX, thisTranslateX + width],
				[0, onlyUseExactEdge ? 0 : 1, 1, 0],
				Extrapolate.CLAMP,
			);
		}),
	);
```

**Comment by jakub-gonet** [comment] 2020-09-21 12:11
I talked with @karol-bisztyga and seems like this may be a limitation of Hermes (or we use it in a strange way) on Android. One way to fix it would be to replace Hermes with JSC but we don't plan to support this for now (we may do that in the future though).

I'll close this for now - docs mention it and keeping this open only clutters issues list. Doing some debugging on this or providing simpler repro would be helpful for us if you want to help.

**Closed by jakub-gonet** 2020-09-21 12:11 UTC
Labels: Reanimated2, 🐞 Bug

**Comment by mrousavy** [comment] 2020-09-21 12:13
I'll finish my implementation, then I'll help debug this. Would be good to support this on hermes since RN 0.64 will ship with hermes opt-in on iOS.

**Comment by jakub-gonet** [comment] 2020-09-21 12:19
For the future reference: work-arounding this can be achieved by changing `[...Array(N)]` to `Array(N).fill()`

**Comment by terrysahaidak** [comment] 2020-09-21 17:25
For some reason spread and rest operators works for me with latest releases of both Reanimated and React Native. I'll double check
