### ISSUE TITLE
Please report: Excessive number of pending callbacks: 501

### ISSUE THREAD

**Issue by rahulje9** [software-mansion/react-native-reanimated#1103] opened 2020-08-10 14:35 UTC
I'm stuck at this issue since this literally makes the app stuck. does anyone have any idea whether what's causing the issue?
I was on React Native version 0.61.5 and React Navigation 4.x, and I updated the project to RN 0.63.2 and React Navigation 5.x and I'm getting this error.

![Screenshot 2020-08-10 at 8 04 51 PM](https://user-images.githubusercontent.com/22475675/89794503-c2c26400-db44-11ea-8d04-1ba30897f3e8.png)

- React: "16.13.1",
- React Native: "0.63.2",
- React Native Reanimated:  "^1.9.0",

**Comment by jakub-gonet** [comment] 2020-08-10 14:38
Duplicate of #654

Please provide some repro, we can't take any action without that.

**Closed by jakub-gonet** 2020-08-10 14:38 UTC
Labels: 🐞 Bug
