### ISSUE TITLE
 Multiple versions detected - Symlinks don't work anymore

### ISSUE THREAD

**Issue by enchorb** [software-mansion/react-native-reanimated#4583] opened 2023-06-16 13:08 UTC
### Description

Getting the error ` Multiple versions of Reanimated were detected` for any version of gesture handler above `3.1.0`. on Android. Runs fine on iOS.

It counts symlinks as a multiple version now which many monorepo providers do (ie. Nrwl).

```
* What went wrong:
Execution failed for task ':react-native-reanimated:assertNoMultipleInstances'.
> 
 [react-native-reanimated] Multiple versions of Reanimated were detected. Only one instance of react-native-reanimated can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/troubleshooting#multiple-versions-of-reanimated-were-detected
  
  Conflict between: 
  - /Users/name/Documents/Code/company/apps/mobile/app_name/node_modules/react-native-reanimated
  - /Users/name/Documents/Code/company/node_modules/react-native-reanimated
```

The same issue also happens for gesture handler versions above `2.9.0`

```
* What went wrong:
Execution failed for task ':react-native-gesture-handler:assertNoMultipleInstances'.
> 
  [react-native-gesture-handler] Multiple versions of Gesture Handler were detected. Only one instance of react-native-gesture-handler can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting#multiple-instances-of-gesture-handler-were-detected 
  
  Conflict between: 
  - /Users/name/Documents/Code/company/apps/mobile/app_name/node_modules/react-native-gesture-handler
  - /Users/name/Documents/Code/company/node_modules/react-native-gesture-handler
```

### Steps to reproduce

Set up Nx starter RN project with gesture handler

### Snack or a link to a repository

N/A

### Reanimated version

Above 3.1.0

### React Native version

0.71.11

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment] 2023-06-16 14:43
I am not sure if this is a bug or the expected behaviour @tomekzaw, you should probably delete the symlink

**Comment by meypod** [comment] 2023-07-05 04:46
I'm also experiencing this on trying to move a mono repo
for now excluding the task from gradle using `-x :react-native-reanimated:assertNoMultipleInstances` is what I do

**Comment by chunghn** [comment] 2023-07-10 09:58
I encountered the above issue with IOS build, while Android build works fine.

```
    "react-native-gesture-handler": "~2.9.0",
    "react-native-reanimated": "~2.14.4",
```

**Comment by zahinafsar** [comment] 2023-08-17 16:27
Facing the same issue. Did anyone find any solution at least any patch or temporary trick?

**Comment by tomekzaw** [comment] 2023-08-21 20:33
@Eli-Nathan In PR #4914 we get rid of this check in favor of a different approach. This will be available in 3.5.0 soon.

**Comment by Latropos** [comment] 2023-09-29 14:09
Closing since https://github.com/software-mansion/react-native-reanimated/pull/4914 is already merged

**Closed by Latropos** 2023-09-29 14:09 UTC
Labels: Missing repro, Platform: Android, Needs review

**Comment by Eli-Nathan** [comment] 2023-10-17 09:26
@tomekzaw I have version 3.5.4 but the multiple instance check still seems to be present.
Have the changes from https://github.com/software-mansion/react-native-reanimated/pull/4914 been released?

**Comment by Latropos** [comment] 2023-10-17 10:03
No, they haven't been released yet. New release will be soon (within a week or two).

**Comment by KonKarakaxidis** [comment] 2023-10-26 10:24
How can I use this for expo projects? `disableMultipleInstancesCheck`
