### ISSUE TITLE
react-native-reanimated should not be specifying dev dependencies as peer dependencies / dependencies

### ISSUE THREAD

**Issue by hendryems** [software-mansion/react-native-reanimated#3770] opened 2022-11-15 00:31 UTC
### Description

When investigating node resolution issues of react-native-reanimated in our project, we noticed that the package.json of the react-native-reanimated library has several issues:

1. "@babel/core": "^7.0.0-0" specified as a peer dependency
2. "@babel/preset-typescript" & "@babel/plugin-transform-object-assign" specified as a direct dependency
3. "@types/invariant" specified as a direct dependency

Issue 1 was what was causing different versions of react-native-reanimated to be used in our app. However, in general, @babel and @types packages ought to only be required during build, not runtime, so they should be specified as devDependencies (also specified in babel documentation) and not peerDependencies nor dependencies.

### Steps to reproduce

Code inspection

### Snack or a link to a repository

n/a

### Reanimated version

2.10.0

### React Native version

0.69.2

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2022-11-15 11:37
Hey @hendryems, thanks for submitting this issue.

> 1. "@babel/core": "^7.0.0-0" specified as a peer dependency

Reanimated comes with a Babel plugin that transforms functions marked as worklets (see plugin.js). That's why we require any version of @babel/core to be present in the project. One thing I wonder about is whether we should use `>=7.0.0-0` instead of `^7.0.0-0`. However, at this point we are a bit afraid of making any changes to package.json because it may lead to unexpected side effects, especially taking into consideration the current state of npm/yarn, different versions etc. 

> Issue 1 was what was causing different versions of react-native-reanimated to be used in our app.

Can you please provide more context here, e.g. paste the output of `npm ls react-native-reanimated` and `yarn why react-native-reanimated`?

> 2. "@babel/preset-typescript" & "@babel/plugin-transform-object-assign" specified as a direct dependency

These plugins are used by the Babel plugin. I agree that formally they should be declared as dev dependencies, but in such case they wouldn't be automatically installed in user projects (i.e. RN apps), so that's why we made them direct.

> 3. "@types/invariant" specified as a direct dependency

This is correct. We should make it a dev dependency. However, there is only one occurrence of `invariant` in our codebase, so we will probably remove the dependency on invariant package and refactor the code not to use it.

**Comment by hendryems** [comment] 2022-11-16 06:30
> Reanimated comes with a Babel plugin that transforms functions marked as worklets (see plugin.js). That's why we require any version of @babel/core to be present in the project. 

> However, are you positive that this also applies to libraries (see explanation above)?

I'm not actually; so perhaps you can help clarity it for me, could @babel/core a devDependency in the project, or does it need to be a direct dependency in this case?

> Can you please provide more context here, e.g. paste the output of npm ls react-native-reanimated and yarn why react-native-reanimated?

We're using pnpm but the equivalent of list on react-native-reanimated looks something like this:

```
app@0.0.1 /Users/hendryems/src/Devices/App

dependencies:
@react-navigation/drawer 5.12.9
└── react-native-reanimated 2.10.0 peer
@react-navigation/material-top-tabs 5.3.19
└── react-native-reanimated 2.10.0 peer
react-native-reanimated 2.10.0

lib-virtual@0.0.1 /Users/hendryems/src/Devices/LibVirtual

dependencies:
@app-client/app-lib 1.0.0-hendryems-001-02
└─┬ @app-client/todo-list 1.0.0-hendryems-001-02
  ├── react-native-reanimated 2.10.0
  └─┬ react-native-redash 18.1.0
    └── react-native-reanimated 2.10.0 peer
```

The issue we had was that @bable/core is specified as a dependency in Devices/App/package.json but not in @app-client/app-lib / @app-client/todo-list resulting in different resolution of react-native-reanimated. E.g. here's pnpm's lock file entries:

```
  /react-native-reanimated/2.10.0_mldsjrse6etchkkw5u7rgf3kxu:
    resolution: {integrity: sha1-7VO+Zru1U7W16T6T70IXyHuMc9s=}
    peerDependencies:
      '@babel/core': ^7.0.0-0
      react: '*'
      react-native: '*'
    dependencies:
      '@babel/core': 7.15.0
      '@babel/plugin-transform-object-assign': 7.18.6_@babel+core@7.15.0
      '@babel/preset-typescript': 7.18.6_@babel+core@7.15.0
      '@types/invariant': 2.2.35
      invariant: 2.2.4
      lodash.isequal: 4.5.0
      react: 18.0.0
      react-native: 0.69.2_dsr5wz7k5f7o5xpo77g7ejjgbu_jiywbl72ik4xnc7esghhwkd7eq
      setimmediate: 1.0.5
      string-hash-64: 1.0.3
    transitivePeerDependencies:
      - supports-color
    dev: false

  /react-native-reanimated/2.10.0_hjakclh6gc5ezh5mlxr7sfkgle:
    resolution: {integrity: sha1-7VO+Zru1U7W16T6T70IXyHuMc9s=}
    peerDependencies:
      '@babel/core': ^7.0.0-0
      react: '*'
      react-native: '*'
    dependencies:
      '@babel/plugin-transform-object-assign': 7.18.6
      '@babel/preset-typescript': 7.18.6
      '@types/invariant': 2.2.35
      invariant: 2.2.4
      lodash.isequal: 4.5.0
      react: 18.0.0
      react-native: 0.69.2_dsr5wz7k5f7o5xpo77g7ejjgbu_react@18.0.0
      setimmediate: 1.0.5
      string-hash-64: 1.0.3
    transitivePeerDependencies:
      - supports-color
    dev: false
```

The latter,  `/react-native-reanimated/2.10.0_hjakclh6gc5ezh5mlxr7sfkgle`, didn't have the @babel/core dependency and was referenced in @app-client/todo-list. We were able to have both resolved to the same when we added @bable/core 7.15.0 as a dependency to @app-client/app-lib.

I did also observe that we'll need to keep the version of @babel/core used in App and @app-client/app-lib the same as well (which further adds maintenance overheads because they're in separate repos), otherwise they won't resolve to the same react-native-reanimated either.

I would also state that I do not understand pnpm (or npm?) enough to say if the above is expected or not, but it wasn't intuitive, to me. It seemed, to me, this won't have been an issue in the first place if react-native-reanimated doesn't have @babel/core specified as a peer dependency, hence this ticket (and looking more closely on the package.json, the other entries looked like errors as well).

Hopefully that helps clarify the context better!

**Comment by tomekzaw** [comment] 2022-11-16 09:13
Hey, thanks for your response. I'm still not sure if I understand the context correctly. Since you use pnpm, you probably have a monorepo, right? Can you please prepare a minimal reproducible example so I can have the full picture of the issue? I think a simple monorepo (no source code, only package.json files) should easily replicate the issue.

> could @babel/core be a devDependency in the project, or does it need to be a direct dependency in this case?

In which project exactly, react-native-reanimated? Technically, we should declare a direct dependency on @babel/core but in the past we've had some issues related to @babel/core being installed more than once and the current solution just works.

> resulting in different resolution of react-native-reanimated
> otherwise they won't resolve to the same react-native-reanimated either

Are you sure that installing different versions of react-native-reanimated was indeed caused by the presence of the dependency on @babel/core?

> We're also looking to make react-native-reanimated a peer dependency to @app-client/todo-list. Maybe that's the more proper fix?

First, I'd like to state that I'm not an npm/yarn/pnpm expert, but here's what I think. If use react-native-reanimated in your app directly, you should declare it as a direct dependency (see [here](https://github.com/Expensify/App/blob/6456bec297da828806bd7a48d55e99870d025dc6/package.json#L106)). If you have a library that uses react-native-reanimated, you should also declare reanimated as a direct dependency (see [here](https://github.com/gorhom/react-native-bottom-sheet/blob/54abf0c0832d1451dfe11be212fc5f938ff5c5fd/package.json#L65)). For some reason, @gorhom/react-native-bottom-sheet also declares a peerDependency on react-native-reanimated (see [here](https://github.com/gorhom/react-native-bottom-sheet/blob/54abf0c0832d1451dfe11be212fc5f938ff5c5fd/package.json#L73)). Maybe this helps.

Let me also explain why react-native-reanimated requires only a single version of the package to be installed in the project. Most JS libraries work fine when two or more instances (versions) are installed. However, Reanimated also comes with native code (C++/Java/Obj-C) that gets compiled so there can be only one version of each native function.
Additionally, Reanimated injects some objects into the main RN JS runtime, so when two versions of Reanimated are installed, one of them overwrites the bindings of the other. That's why we added a check that runs on pod install / Gradle Sync to detect whether more than one version of Reanimated is used in the project.

**Comment by hendryems** [comment] 2022-11-17 23:07
> Can you please prepare a minimal reproducible example so I can have the full picture of the issue? 

Yeah, let me work on stripping that down to a min repo. I need some additional time; we have a pretty big repo and it gets complex.

> Are you sure that installing different versions of react-native-reanimated was indeed caused by the presence of the dependency on @babel/core?

To be clear, this is actually due to the different instances of the react-native-reanimated library (not different versions). I looked and it might actually be [PNPM's way of resolving](https://pnpm.io/how-peers-are-resolved) this. So if we don't have the same version of @babel/Core specified, we'll end up with:

```
react-native-reanimated@2.10.0_@babel+Core@7.15.0
react-native-reanimated@2.10.0_@babel+Core@7.16.0
```

> If you have a library that uses react-native-reanimated, you should also declare reanimated as a direct dependency (see [here](https://github.com/gorhom/react-native-bottom-sheet/blob/54abf0c0832d1451dfe11be212fc5f938ff5c5fd/package.json#L65)). For some reason, @gorhom/react-native-bottom-sheet also declares a peerDependency on react-native-reanimated (see [here](https://github.com/gorhom/react-native-bottom-sheet/blob/54abf0c0832d1451dfe11be212fc5f938ff5c5fd/package.json#L73)).

react-native-bottom-sheet actually declares it as a peerDependency as well as a devDependency (not direct dependency). I tried that out and it works as well. Its useful to put as a devDependency so that it can be referenced during unit testing and/or in Visual Studio Code, etc as part of development. The peer dependency part is to make sure that any consumer of react-native-bottom-sheet need to explicitly resolve the react-native-reanimated (and its peer dependencies) requirement.

> Let me also explain why react-native-reanimated requires only a single version of the package to be installed in the project.

Right, that makes a lot of sense and I can see now why react-native-bottom-sheet, as a library, chose to not consume react-native-reanimated as a direct dependency and requires the consuming app to do this resolution explicitly. I think I'm convinced now that we ought to be following that approach as well because the consumption is done from our library, @app-client/todo-list, not the app itself.

**Comment by hendryems** [comment] 2023-01-04 03:31
@tomekzaw , apologies for the delay.

This is not quite representative of our repo (it actually multiple monorepros using different tooling, etc) but I think this at least illustrates the peer dependency resolution of pnpm: https://github.com/hendryems/repro-pnpm-rn-reanimated-devDependencies

As stated in my previous comment, I think I'm starting to better understand that what we really want is a "dev Peer dependency" (e.g. if you are using react-native-reanimated, you need to have @babel/core in your devDependency because the transform part requires that tooling as part of the build; but not at runtime), when expressed as a peerDependency, it ran into pnpm's peer dependencies resolution mechanism that resulted in multiple copies of the react-native-reanimated library being included in the app.

**Comment by Latropos** [comment] 2023-09-22 08:03
Closing since #3788 is merged

**Closed by Latropos** 2023-09-22 08:03 UTC
Labels: Platform: Android, Platform: iOS, Needs review, Repro provided
