### ISSUE TITLE
Style prop with multiple useAnimatedStyle is not getting merged

### ISSUE THREAD

**Issue by intergalacticspacehighway** [software-mansion/react-native-reanimated#3209] opened 2022-05-03 04:52 UTC
## Description
We upgraded reanimated to 2.8.0 from 2.4.1 and saw a weird issue. The issue is mainly arising with passing multiple `useAnimatedStyle` as array in style prop. It doesn't happen in 2.4.1. I think it might have been introduced in 2.5.0.

Also, this happens **only**  when the Animated component is used in the react native screen's header elements as shown in video.

In the video, `animatedStyle2` is overriding `animatedStyle` instead of getting merged in the header. Also, the style gets merged on a fast refresh. So maybe it doesn't merge on the first mount 🤔 

https://user-images.githubusercontent.com/23293248/166405063-55101e88-aece-4c39-8b98-71b8bce7129e.mov

### Expected behavior
- Multiple animated styles should merge when used with react native screen's header elements

### Actual behavior & steps to reproduce
- Multiple animated styles gets overridden by last animated style when used with react native screen's header elements

## Snack or minimal code example
- Here's the [repo with minimal example](https://github.com/intergalacticspacehighway/reanimated-style-merge-repro/blob/master/App.js), App.js includes the code from the screen recording.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |      0.68.1   |
| react-native-reanimated         |    2.8.0         |
| NodeJS                               |      16.3.1   |
| Xcode                                |     13.3.1    |
| Java                                 |      11.0.13   |
| Gradle                               |      7.3.3   |
| expo                                 |      x   |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by Titozzz** [comment] 2022-06-22 10:42
I can reproduce this outside of header elements

**Comment by jevgeni-geimanen-bolt** [comment] 2022-08-01 14:23
Reproduced somewhat similar in `2.4.1`. Downgrade to `2.3.3` helped.

Originally, issue appears while using [react-native-bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet)

[This particular style](https://github.com/gorhom/react-native-bottom-sheet/blob/c7f2ce26fdaf525951b70b76cd857e0b63cb4865/src/components/bottomSheet/BottomSheet.tsx#L1160) does not get properly merged.
```
    const containerAnimatedStyle = useAnimatedStyle(
      () => ({
        opacity: Platform.OS === 'android' && animatedIndex.value === -1 ? 0 : 1,
        transform: [
          {
            translateY: animatedPosition.value,
          },
        ],
      }),
      [animatedPosition, animatedIndex]
    );
```

From time to time it's stuck on `opacity=0`

What's interesting, replacing it with `opacity: Platform.OS === 'android' && animatedIndex.value === -1 ? 0.5 : 1,`, gets animation stuck on `opacity=0.5`

and replacing `0` with `Math.random()/1000` like following:

```opacity: Platform.OS === 'android' && animatedIndex.value === -1 ? Math.random() / 1000 : 1,```

fixes the problem. Which hints that there is some problem with re-memoization, because of constant `0`/`0.5` values.

Checking [2.3.3...2.4.1](https://github.com/software-mansion/react-native-reanimated/compare/2.3.3...2.4.1) diff reveals [this change](https://github.com/software-mansion/react-native-reanimated/commit/a345d853d51ba9910187ab5cfa006b6e590f51f1), which potentially does look like possible place of issue introduced

**Comment by marksyzm** [comment] 2023-03-13 21:30
I'm finding this with different properties such as width, height, positioning. Currently running 2.14.4 - I appreciate you're still working on this though!

**Comment by szydlovsky** [comment] 2024-06-26 10:45
Hey! As of now (3.12.1) - the issue is long gone!

**Closed by szydlovsky** 2024-06-26 10:45 UTC
Labels: Platform: Android, Platform: iOS, Needs review, Repro provided
