### ISSUE TITLE
Cant find variable _setGlobalConsole_f with expo

### ISSUE THREAD

**Issue by yonjuukyuu** [software-mansion/react-native-reanimated#2048] opened 2021-05-26 08:37 UTC
Hi,
"expo": "~40.0.0",
react-native-reanimated": "^2.1.0",

Im getting this _setglobalConsole_f error as well for a while now, have try the reset cash and reinstalle modules noone seem to work, is there a workaround this yet ?

I do have the plugin in babel config too.

Babel.config.js
`module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};
`

Started happening after i upgraded from version 1. something

**Comment by brentvatne** [comment] 2021-05-27 16:22
update to expo sdk 41, sdk 40 uses rc version of reanimated that is very out of date

**Comment by jmysliv** [comment] 2021-08-12 12:08
Duplicate of #1546

**Closed by jmysliv** 2021-08-12 12:08 UTC
Labels: 🐞 Bug, 🏠  Reanimated2
