### ISSUE TITLE
Error on android version 5.1 Attempt to invoke virtual method 'boolean  com.swmansion.reanimated.layoutReanimation.RealLayoutAnimator.isLayoutAnimationEnabled()' on a null object reference

### ISSUE THREAD

**Issue by Waseem6409** [software-mansion/react-native-reanimated#2773] opened 2021-12-20 18:41 UTC
## Description

I installed v2 from beginning when i was starting a project, it has been 2 months that i am working on it and when i now starting validating it on every version I got an error on the android version 5.1, I tried to downgrade packages and check but still have the same issue and i don't have a workaround as its used by my main navigations packages, it is working on latest android version

![Screenshot_1640025525](https://user-images.githubusercontent.com/50287765/146816609-5e2eb7b7-e497-41e4-a168-c47c1eafb70c.png)

### Expected behavior

It should work on android 5.1 and others without any error

### Actual behavior & steps to reproduce

Install react navigations, stack, drawer and react-native-reanimated v2

## Package versions

All v2

- React Native: 0.66.3
- React Native Reanimated: All v2 
- NodeJS: latest
- Java & Gradle: latest

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by FabianoCastro** [comment] 2021-12-20 23:10
The same problem

**Comment by Waseem6409** [comment] 2021-12-21 04:35
> The same problem

I hope it is fixed sooner than the other issues, because its breaking everything and reanimated package is compulsory package in react navigations etc, so cant also change it

**Comment by ahaseeb001** [comment] 2021-12-21 09:30
To Solve Attempt to invoke interface method boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled() on a null object reference Error Just need to update react-native-reanimated in your Package.json file. you just need to use 2.2.4 version of react-native-reanimated. So just remove this package and install “react-native-reanimated”: “^2.2.4”. Now Your error should be solved.

**Comment by Waseem6409** [comment] 2021-12-21 09:42
> To Solve Attempt to invoke interface method boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled() on a null object reference Error Just need to update react-native-reanimated in your Package.json file. you just need to use 2.2.4 version of react-native-reanimated. So just remove this package and install “react-native-reanimated”: “^2.2.4”. Now Your error should be solved.

As stated in the issue, i have tested all version  starting to latest, it works on android 10 and others but not on 5.1, Kindly check before making comments

**Comment by WilliamAlexander** [comment] 2021-12-21 19:40
Yup same problem

**Comment by Weibienaole** [comment] 2021-12-22 03:15
> 
i has the same problem,it successful solved my problem.

**Comment by upendrapratapbind** [comment] 2021-12-22 05:18
Attempt to invoke virtual method 'boolean com.swmansion.reanimated.layoutReanimation.RealLayoutAnimator.isLayoutAnimationEnabled()' on a null object reference
getting this error when i install react-native-reanimated

**Comment by Waseem6409** [comment] 2021-12-22 07:16
@jakub-gonet  @piaskowyk  @Szymon20000  @karol-bisztyga @osdnk  @kmagiera  @wcandillon  guys kindly check this out, need help urgent

**Comment by Only-IceSoul** [comment] 2021-12-22 19:12
Same problem with expo 44

**Comment by robschwitzer** [comment] 2021-12-22 22:28
Has anyone been able to run their apps successfully with a workaround? I've gone through a bunch of versions of this library now and all of them crash at runtime with the same error.

**Comment by WilliamAlexander** [comment] 2021-12-23 01:01
> 

"react-native-reanimated": "2.2.4", for me is fine

**Comment by Weibienaole** [comment] 2021-12-23 06:16
react-native-reanimated@2.2.4 for android: opening debug will cause a crash. finally i find the cause of collapse:  https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/installation  -> android -> 2. Plug Reanimated in MainApplication.java
This addition will cause a crash
![image](https://user-images.githubusercontent.com/61195608/147196628-bb5947f3-d8fa-4705-8036-320fbe220d1b.png)

But i dont know why. so far, I have removed this plugin

**Comment by huseyiniriss** [comment] 2021-12-23 21:04
Firstly, i removed reanimated library with package manager [npm, yarn...] 
`yarn remove react-native-reanimated`

After, i installed reanimated v2.2.4.
`yarn add react-native-reanimated@2.2.4`

its work for me

**Comment by Only-IceSoul** [comment] 2021-12-24 00:23
> Same problem with expo 44

just emulator.

**Comment by danmaas** [comment] 2021-12-24 15:06
This code in the constructor in ReanimatedNativeHierarchyManager.java looks a little odd to me... If an exception is thrown it looks like mReaLayoutAnimator can be left null? Maybe that's the cause of these crashes?

2.2.4 doesn't have this code which would explain why it works better.

```
public class ReanimatedNativeHierarchyManager extends NativeViewHierarchyManager {
  private HashMap<Integer, ArrayList<View>> toBeRemoved = new HashMap();
  private HashMap<Integer, Runnable> cleanerCallback = new HashMap();
  private LayoutAnimationController mReaLayoutAnimator = null;
  private HashMap<Integer, Set<Integer>> mPendingDeletionsForTag = null;

  public ReanimatedNativeHierarchyManager(
      ViewManagerRegistry viewManagers, ReactApplicationContext reactContext) {
    super(viewManagers);
    Class clazz = this.getClass().getSuperclass();
    try {
      Field field = clazz.getDeclaredField("mLayoutAnimator");
      field.setAccessible(true);
      Field modifiersField = Field.class.getDeclaredField("accessFlags");
      modifiersField.setAccessible(true);
      modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);
      mReaLayoutAnimator = new ReaLayoutAnimator(reactContext, this);
      field.set(this, mReaLayoutAnimator);

      Field pendingTagsField = clazz.getDeclaredField("mPendingDeletionsForTag");
      pendingTagsField.setAccessible(true);
      Field pendingTagsFieldModifiers = Field.class.getDeclaredField("accessFlags");
      pendingTagsFieldModifiers.setAccessible(true);
      pendingTagsFieldModifiers.setInt(field, field.getModifiers() & ~Modifier.FINAL);
      mPendingDeletionsForTag = new HashMap<Integer, Set<Integer>>();
      pendingTagsField.set(this, mPendingDeletionsForTag);

    } catch (NoSuchFieldException | IllegalAccessException e) {
      e.printStackTrace();
    }
    setLayoutAnimationEnabled(true);
  }
```

**Comment by SConaway** [comment] 2021-12-25 05:13
If you use ProGuard, adding `-keep class com.swmansion.** {*;}` to `/android/app/proguard-rules.pro` seems to fix this issue. It looks like some classes are being removed that are needed, specifically `com.swmansion.reanimated.layoutReanimation.RealLayoutAnimator`. If someone else confirms this works, I can make a PR adding that as an instruction in the docs.

**Comment by akshat-infusion** [comment] 2021-12-25 06:30
Not working in "react-native-reanimated": "^2.2.4"

**Comment by kristijantomic** [comment] 2021-12-25 06:49
@SConaway i can confirm that after adding to proguard the rule i successfully installed prod build with gradle installRelease on Huawei P smart Z.

**Comment by danmaas** [comment] 2021-12-25 19:35
I don't use ProGuard and I was experiencing the error with 2.3.1. Just launched a test with 2.2.4 now, will report back here if it helps.

**Comment by SConaway** [comment] 2021-12-26 21:20
Check #2725 for the docs fix.

**Comment by Only-IceSoul** [comment] 2021-12-26 22:37
> Same problem with expo 44
with expo-dev-client
expo run:android

**Comment by piaskowyk** [comment] 2021-12-27 13:16
⚠️⚠️⚠️
> If you use ProGuard, adding `-keep class com.swmansion.** {*;}` to `/android/app/proguard-rules.pro` seems to fix this issue. It looks like some classes are being removed that are needed, specifically `com.swmansion.reanimated.layoutReanimation.RealLayoutAnimator`. If someone else confirms this works, I can make a PR adding that as an instruction in the docs.

credits: @SConaway 

I think https://github.com/software-mansion/react-native-reanimated/pull/2725 should resolve the issue, but if anyone still have this issue - please provide any repo to reproduce it 🙏

**Comment by Only-IceSoul** [comment] 2021-12-27 15:44
> Check #2725 for the docs fix.

Not working with expo dev client.  sdk44

**Comment by piaskowyk** [comment] 2021-12-27 20:17
@Only-IceSoul Could you prepare a repo to reproduce the issue?

**Comment by cnhongwei** [comment] 2021-12-28 00:27
> @Only-IceSoul Could you prepare a repo to reproduce the issue?

https://github.com/cnhongwei/reanimated-problem

Created by expo sdk44.
```
npm install -g expo-cli
npm install
expo start
```
An error will occur while running on Android 5.0 emulator.

![Screenshot_1640651125](https://user-images.githubusercontent.com/2978404/147515366-3554add1-c198-48fb-862f-dafd100e4234.png)

No problem while running on Android 7.0 emulator
![Screenshot_1640651195](https://user-images.githubusercontent.com/2978404/147515434-b17517f1-5979-4722-9afa-2268bf3a8d57.png)

**Comment by cnhongwei** [comment] 2021-12-28 01:00
> @Only-IceSoul Could you prepare a repo to reproduce the issue?

in ReanimatedNativeHierarchyManager
```java
      Field modifiersField = Field.class.getDeclaredField("accessFlags");  // throw a exception while running Android 5.0.  mReaLayoutAnimator can't initialize
      modifiersField.setAccessible(true);
      modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);
      mReaLayoutAnimator = new ReaLayoutAnimator(reactContext, this);
```

**Comment by Waseem6409** [comment] 2021-12-30 12:31
> ️️️
> 
> > If you use ProGuard, adding `-keep class com.swmansion.** {*;}` to `/android/app/proguard-rules.pro` seems to fix this issue. It looks like some classes are being removed that are needed, specifically `com.swmansion.reanimated.layoutReanimation.RealLayoutAnimator`. If someone else confirms this works, I can make a PR adding that as an instruction in the docs.
> 
> credits: @SConaway
> 
> I think #2725 should resolve the issue, but if anyone still have this issue - please provide any repo to reproduce it

I am not using ProGuard and i tried all v2 versions but nothing worked, i had to downgrade to version 1 in order to work

**Comment by dayaki** [comment] 2021-12-31 11:03
Current version `2.3.1` did not work with proguard rules activated, downgrading to `2.2.4` and enabling Proguard with the rules stated above worked for me.

**Comment by mmmoussa** [comment] 2022-01-07 04:27
Currently using v2.3.1 in a production app. Have crash reports for a small segment of users experiencing this, mostly running Android 5.x with a few running Android 6.0. We don't use proguard and already have the rule suggested in #2725 in our proguard rules, with no observed difference. We were previously using v2.2.4 without issue.

**Comment by piaskowyk** [comment] 2022-01-07 18:08
I going to deal with this issue next week. If I will be able to reproduce it I fix it soon. I will notify you about the progress.

**Comment by Only-IceSoul** [comment] 2022-01-07 18:14
I only have this problem with expo dev client, android 5,6,7,8,9,etc

**Comment by giautm** [comment] 2022-01-16 18:44
For anyone running to this issue, you can download `react-native-reanimated-2.0.0-alpha.tgz` from [this action](https://github.com/giautm/react-native-reanimated/actions/runs/1704246104).

Then following installation steps at here to workaround: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#using-main-branch-builds. Until the PR #2847 get merged

**Comment by EvanBacon** [comment] 2022-01-17 17:46
@giautm thanks for the resources! Planning on adding a better mechanism for packagingOptions in the next release https://github.com/expo/expo/pull/15863 -- As mentioned [here](https://github.com/expo/config-plugins/issues/31#issuecomment-1009387444) you can make the operation a bit safer in the meantime by using the inline operation which would ensure the plugin doesn't break other plugins that are setting the packagingOptions.

**Comment by giautm** [comment] 2022-01-17 20:30
> @giautm thanks for the resources! Planning on adding a better mechanism for packagingOptions in the next release [expo/expo#15863](https://github.com/expo/expo/pull/15863) -- As mentioned [here](https://github.com/expo/config-plugins/issues/31#issuecomment-1009387444) you can make the operation a bit safer in the meantime by using the inline operation which would ensure the plugin doesn't break other plugins that are setting the packagingOptions.

I just ran into that issue when using my custom patch. It does not exist on the official build, so I think if one some facing the same issue they can fix it via the plugin. :3. Good to know there is another way to do that, ;)

**Comment by christophemenager** [comment] 2022-01-21 08:38
I do have the same issue in production,  with version 2.3.1 of react-native-reanimated. 
Only visible on versions 5.1, 5.0.1, 5.0.2, android only

**Comment by Aryk** [comment] 2022-01-22 08:23
@giautm  - I implemented the fix here: https://github.com/software-mansion/react-native-reanimated/issues/2773#issuecomment-1013930054

The build compiled fine. However, only after I added this change now my app on Android 9 (Galaxy S8) is crashing on bootup from an app kill every time with this error:

`Error while updating property 'flexShrink' in shadow node of type: AndroidSwipeRefreshLayout`
`method com.facebook.react.uimanager.LayoutShadowNode.setFlexShrink argument 1 has type float, got null`

Details:
https://sentry.io/share/issue/d9312106e0164578bcc95835fb5b9b9a/

This happens on app bootup and the app immediately exits. 

On my dev build it works fine on Android.

The standalone on Android also works if I login and don't kill the app. Once I kill and reopen it, I get an error.

**Comment by Aryk** [comment] 2022-01-22 10:41
Ok, I think it was related to this change but also not emptying my /android folder before building it on eas. It's working now.

**Comment by minaairsupport** [comment] 2022-01-22 16:20
I have the same issue downgrade to version 2.2.4 fixed it

**Comment by giautm** [comment] 2022-01-22 18:18
For everyone fixed issue by the chosen downgrade, It will crash on Expo Go/iOS because non-compatible native APIs

**Closed** 2022-01-25 11:50 UTC
Labels: 🐞 Bug, 🏠  Reanimated2

**Comment by SamiChab** [comment] 2022-02-03 02:44
Downgrading to v2.2.4 didn't help. But installing the fix did the trick:
`yarn add software-mansion/react-native-reanimated#2847/head`

**Comment by ayushmng** [comment] 2022-02-04 01:15
> If you use ProGuard, adding `-keep class com.swmansion.** {*;}` to `/android/app/proguard-rules.pro` seems to fix this issue. It looks like some classes are being removed that are needed, specifically `com.swmansion.reanimated.layoutReanimation.RealLayoutAnimator`. If someone else confirms this works, I can make a PR adding that as an instruction in the docs.

**Comment by Md-Mudassir47** [comment] 2022-02-04 07:35
> Downgrading to v2.2.4 didn't help. But installing the fix did the trick: `yarn add software-mansion/react-native-reanimated#2847/head`

Build is failing in android after installing the specific commit
<img width="1019" alt="Screenshot 2022-02-04 at 1 05 01 PM" src="https://user-images.githubusercontent.com/85115578/152489827-345fc6d5-3047-41e1-ba75-3973c6948db3.png">

**Comment by NobodyButMe-Haiya** [comment] 2022-02-04 11:55
try empty project error the same thing. even with latest head. Downgrade to 2.2.4 work but gesture handler complain old.

**Comment by SergioAN007** [comment] 2022-02-10 00:28
react-native-reanimated v. 2.4.1 fix this issue. Thanks

**Comment by cskeppstedt** [comment] 2022-03-13 22:08
> -keep class com.swmansion.** {*;}
> 
> Adding this line on Proguard file resolved my issue, Thank you soo much man for saving my 5th day😅

To anyone who needs to modify proguard rules in a managed expo project: you can use a config plugin. I've created a gist with a working solution: https://gist.github.com/cskeppstedt/d44f043d7c621c4c800a66c9656b1d87

**Comment by Yashg2910** [comment] 2022-04-04 06:02
Hi all, I am running the app on Expo 44. I don't have proguard. I have tried react-native-reanimated 2.2.4 and even the 2.4.1 version. I still get the same error in expo dev environment. Any updates on that?

**Comment by cskeppstedt** [comment] 2022-04-22 10:38
@Yashg2910 you can also check this out, someone extended my gist with a config plugin that also modifies the MainActivity which fixed the issue for them: https://github.com/software-mansion/react-native-reanimated/issues/2702#issuecomment-1096282710
