### ISSUE TITLE
useAnimatedProps not working properly for G svg component

### ISSUE THREAD

**Issue by acollazomayer** [software-mansion/react-native-reanimated#4317] opened 2023-03-31 08:22 UTC
### Description

G component not being able to be animated when using animated Props. Initial value of animated Props work however when they change its not being updated on screen.

Here is a repo with the issue replicated. Please note that this behaviour was working before updating to the latest version of the library.
https://github.com/acollazomayer/ReanimatedSVGBug

### Steps to reproduce

1. git clone https://github.com/acollazomayer/ReanimatedSVGBug
2. cd ReanimatedSVGBug
3. yarn
4. cd ios && pod install
5. yarn react-native run-ios
6. Press on the white circle as the slider indicator
7. Slide through the circle

### Snack or a link to a repository

the library. https://github.com/acollazomayer/ReanimatedSVGBug

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2023-03-31 08:55
Hey @acollazomayer, thanks for reporting this issue. @WoLewicki who is a maintainer of react-native-svg promised to take a look at it.

**Comment by hadnet** [comment] 2023-03-31 19:13
@tomekzaw  @WoLewicki Hey guys, just wanted to give a heads up that there's an issue with the type return of useAnimatedProps, so I can just avoid opening an issue fro this. The return type of that hook is just Partial<T>, but I think it should be Partial<AnimatedProps<T>>. Only returning Partial, TypeScript throws a type error.

**Comment by acollazomayer** [comment] 2023-04-15 12:16
@WoLewicki did you had the chance to take a look at this issue? Thanks

**Comment by WoLewicki** [comment] 2023-04-17 13:20
@acollazomayer can you provide the versions of libraries on which it worked? I see you use `x` and `y` props as the animated ones, which are parsed on `render` on the JS side to create the `matrix` prop: https://github.com/software-mansion/react-native-svg/blob/d31ffdb762d34171fd934ac97b031ccf5e0b645d/src/lib/extract/extractProps.ts#L89. I am not sure if it could have ever worked with `react-native-reanimated` since it does indeed you the `render` method only on the initial render. I may be missing something though.

**Comment by acollazomayer** [comment] 2023-04-18 13:17
@WoLewicki Sure!
 "react-native-svg": "12.1.0",
 "react-native": "0.71.4",
 "react-native-reanimated": "2.14.4",

**Comment by WoLewicki** [comment] 2023-04-19 10:22
I tested the repo and it seems that it broke with the first RC of `react-native-reanimated`, and it works with 2.x version of it even with the newest RN and RNSVG, so I am afraid there is not much to be done on the side of RNSVG unfortunately.

**Comment by Latropos** [comment] 2023-04-24 12:03
Duplicate of #3321

**Comment by acollazomayer** [comment] 2023-05-20 10:38
@WoLewicki @tomekzaw. Then the issue is on the `react-native-reanimated` side? Is there a possible workaround to it?

**Comment by fedpre** [comment] 2023-06-28 18:22
Any updated solution for this? I am having the same issue where the useAnimatedProps on an SVG component doesn't update the fill prop (I want to interpolate the color from white to back when scrolling).

**Comment by Mungus-zz** [comment] 2023-07-07 20:47
Trying to use react-native-reanimated with react-native-skia and facing this same issue. Specifically, I am getting a TypeScript error when trying to use the animatedProps prop of the Animated.createAnimatedComponent function from react-native-reanimated. The error message indicates that the type of the paint property in animatedProps is not compatible with the expected type.

Error Message: The error message is: "Type 'Partial<{ r: number; cx: number; cy: number; paint: { color: string; antiAlias: boolean; alpha: number; }; }>' is not assignable to type 'Partial<AnimateProps<SkiaProps<CircleProps>>>'."

Attempts to Resolve the Issue: I have tried several approaches to resolve this issue, including using useAnimatedStyle instead of animatedProps, but none of these approaches have worked. 

Any updates on this? Thanks

**Closed** 2023-08-04 12:37 UTC
Labels: Platform: iOS, Needs review, Repro provided
