### ISSUE TITLE
Exception thrown while executing UI block: 'parentNode' is a required parameter

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-reanimated#1318] opened 2020-10-06 15:35 UTC
## Description

While working on React Native Gallery Toolkit, I've got this error.

I'm not sure how to reproduce it in some playground, not sure what exactly causes it:

<details>

```
Exception thrown while executing UI block: 'parentNode' is a required parameter

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1192
-[REANodesManager performOperations]
-[REANodesManager onAnimationFrame:]
CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)
display_timer_callback(__CFMachPort*, void*, long, void*)
__CFMachPortPerform
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
__CFRunLoopDoSource1
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0
```

</details>

### Screenshots

![image](https://user-images.githubusercontent.com/7809008/95223233-057d8100-0802-11eb-9aa6-23c1b5cdd3c8.png)

## Steps To Reproduce

1. Clone this repo https://github.com/terrysahaidak/react-native-gallery-toolkit
2. Switch to tr-lightbox branch and run the Example project
3. Navigate to Lightbox => Shared Element Transition
4. Open/close image a few times in a row.

The error might occur after a few reloading or immediately. 

### Expected behavior

Should not throw the error.

### Actual behavior

Throws an error but still works if I just close it.

## Snack or minimal code example

1. Clone this repo https://github.com/terrysahaidak/react-native-gallery-toolkit
2. Switch to tr-lightbox branch and run the Example project

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: 2.0.0-alpha.7

**Comment by drewandre** [comment] 2020-10-06 19:37
Just chiming in here to say that I also started seeing this on 2.0.0-alpha.7 when attempting to run a portal-based image transition across the screen and fast-refreshing several times in a row. I'll try to find a reliable way to reproduce, but for me it seemed to only happen when the transitions were happening in rapid succession.

**Comment by Orgil** [comment] 2020-10-07 06:51
Also having exact same issue

**Comment by JulianoLoren** [comment] 2020-10-07 15:03
facing the same issue

**Comment by JB-CHAUVIN** [comment] 2020-10-13 15:21
Same issue goes for me, reanimated version 2.0.0-alpha.7.

**Comment by terrysahaidak** [comment] 2020-10-13 15:30
The fix here is to disable TurboModules for all the modules except Reanimated. Its landed in master, should be available with the new release. I will keep this issue open until.

**Comment by JB-CHAUVIN** [comment] 2020-10-14 13:24
> The fix here is to disable TurboModules for all the modules except Reanimated. Its landed in master, should be available with the new release. I will keep this issue open until.

Do you know when the next reanimated alpha 8 will be released ?

**Comment by terrysahaidak** [comment] 2020-10-14 19:02
You can apply this patch in the meantime:
https://github.com/rainbow-me/rainbow/blob/develop/patches/react-native%2B0.63.2.patch

Also, make sure to remove this line
https://github.com/software-mansion-labs/reanimated-2-playground/blob/master/ios/Reanimated2Playground/AppDelegate.mm#L51

**Comment by JB-CHAUVIN** [comment] 2020-10-15 08:08
> You can apply this patch in the meantime:
> https://github.com/rainbow-me/rainbow/blob/develop/patches/react-native%2B0.63.2.patch
> 
> Also, make sure to remove this line
> https://github.com/software-mansion-labs/reanimated-2-playground/blob/master/ios/Reanimated2Playground/AppDelegate.mm#L51

Great !!! Thanks you very much @terrysahaidak it is working :-)

**Comment by mealgen-master** [comment] 2020-10-29 00:24
I downgraded the React-native version to 63.2 and commented out the IOS settings, but the error is still the same.

**Comment by karol-bisztyga** [comment] 2020-11-02 07:09
As alpha 8 is out you can try using it.

**Comment by terrysahaidak** [comment] 2020-11-02 07:11
I will use it for a few days and let know if it's fixed with alpha.8

**Comment by Alexandredc** [comment] 2020-11-07 00:02
facing the same problem on alpha.8 but don't know how to reproduce it 🤷🏻‍♂️

**Comment by terrysahaidak** [comment] 2020-11-07 13:45
> facing the same problem on alpha.8 but don't know how to reproduce it 🤷🏻‍♂️

do you use expo? did you try to clean and rebuilid the project?

**Comment by Benzer1406** [comment] 2020-11-07 15:27
Having the same issue with RN `0.61.2` and `"react-native-reanimated": "^1.13.1"`

**Comment by terrysahaidak** [comment] 2020-11-07 15:38
> Having the same issue with RN `0.61.2` and `"react-native-reanimated": "^1.13.1"`

could you create reproducing example?

**Comment by Benzer1406** [comment] 2020-11-07 15:42
@terrysahaidak  Honestly, probably not, I'm not sure why it started to break, but I did not use to have issues with it. But it is engrained in my app repo, not sure how I could reproduce that. I quickly tried to install `react-native-reanimated` `v: alpha8` but couldn't run `pod install`, it was telling me: `[!] Unable to find a specification for React-callinvoker depended upon by RNReanimated`

**Comment by Alexandredc** [comment] 2020-11-08 08:40
> > facing the same problem on alpha.8 but don't know how to reproduce it 🤷🏻‍♂️
> 
> do you use expo? did you try to clean and rebuilid the project?

No, I'm not using expo

**Comment by JB-CHAUVIN** [comment] 2020-11-08 09:48
Hello, facing the same problem in Alpha 8. I thought it was solved but it’s not 😢

**Comment by miversen** [comment] 2020-11-13 10:11
I'm also facing this issue with Alpha 8

**Comment by Benzer1406** [comment] 2020-11-15 14:13
Just updated to RN `0.63.3` and tried all different kinds of versions of `react-native-reanimated`: `1.3.0`, `1.13.1`, `2.0.0-alpha8` and none worked.

**Comment by Benzer1406** [comment] 2020-11-15 14:13
@terrysahaidak Your links you posted above do not work.

**Comment by terrysahaidak** [comment] 2020-11-15 15:39
alpha.8 has this solved. please make sure to undo all the installation guide things from previous versions and clear the cache before the build.

**Closed** 2020-11-15 21:26 UTC
Labels: Reanimated2, 🐞 Bug

**Comment by mym0404** [comment] 2020-11-20 06:25
This is reproduced on `alpha.9`

**Comment by mym0404** [comment] 2020-11-21 04:15
In my case, I fixed this issue by converting react-native `Animated` API to `Reanimated 2` API.

**Comment by JB-CHAUVIN** [comment] 2020-11-24 10:36
Still got this issue : 
![image](https://user-images.githubusercontent.com/8957878/100083071-46306880-2e49-11eb-8570-0602a0e8bc26.png)

**Comment by mym0404** [comment] 2020-11-27 09:01
This is reproduced on `rc.0` too in iOS when my device is rotated from portrait to landscape.
![image](https://user-images.githubusercontent.com/33388801/100430697-77739780-30da-11eb-9c6f-31a843178e79.png)
![image](https://user-images.githubusercontent.com/33388801/100430747-88bca400-30da-11eb-842c-291e3412e738.png)

**Comment by karol-bisztyga** [comment] 2020-11-27 10:03
Hello everyone!
I've noticed some activity here, some people still seem to have this problem.
As this issue is closed I think the best thing you can do if you're facing this is either open a new one or reopen this one.

With that said, posting a screen with this error occurring or just saying that you have this problem, gives us nothing. If you decide to reopen the issue/open a new issue connected to this one, please provide a reproducing example and some more information regarding the circumstances in which this happens(is it a fresh rn app, and if it's not then what's the background, like did you move from rea 1 to rea2 or what, what are packages modules, stuff like that).

Thank you for the cooperation, if there's a problem I'm happy to help! ✌️

**Comment by kmagiera** [comment] 2020-11-27 12:53
hey @mym0404 and @JB-CHAUVIN – any change you can share your code for us to try and reproduce the crash? If not maybe you can describe at what stage the crash happens, e.g., at app startup / when starting some animation / when instantiating some components on the screen.

**Comment by mym0404** [comment] 2020-11-27 14:24
@kmagiera The issue was gone after start new metro server and application. I don't know the exact reason. But sometimes, it happened at device orientation change(portrait -> landscape). I am not paying attention to this issue now because it is not reproduced after that.
Thank you for your concerns

**Comment by kmagiera** [comment] 2020-12-04 15:41
Just submitted #1501 which addresses the issue we think was causing the crash. If some of you are still experiencing it can you please try out this patch to see if it resolves the issue for you?

**Comment by levinhky** [comment] 2024-01-17 08:26
how can you solved this, i faced this issue too
