### ISSUE TITLE
Error: [Reanimated] The native part of Reanimated doesn't seem to be initialized

### ISSUE THREAD

**Issue by Kosntantin** [software-mansion/react-native-reanimated#5219] opened 2023-10-12 08:10 UTC
### Description

I am getting the following error 
```
Error: [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
  - not rebuilding the app after installing or upgrading Reanimated
  - trying to run Reanimated on an unsupported platform
  - running in a brownfield app without manually initializing the native library, js engine: hermes
```
whenever I call createDrawerNavigator from @react-navigation/drawer.

`"dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/drawer": "^6.6.4",
    "@react-navigation/native": "^7.37.1",
    "@react-navigation/native-stack": "^6.1.0",
    "@react-navigation/stack": "^6.3.17",
    "@shopify/flash-list": "1.4.3",
    "@types/react-native-modern-datepicker": "^1.0.1",
    "axios": "^0.27.2",
    "expo": "^49.0.13",
    "expo-application": "~5.3.0",
    "expo-asset": "~8.10.1",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.11",
    "expo-device": "~5.4.0",
    "expo-file-system": "~15.4.4",
    "expo-font": "~11.4.0",
    "expo-linking": "~5.0.2",
    "expo-localization": "~14.3.0",
    "expo-secure-store": "~12.3.1",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-web-browser": "~12.3.2",
    "mobx-react-lite": "^4.0.5",
    "posthog-react-native": "^2.7.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.5",
    "react-native-barcode-svg": "^0.0.15",
    "react-native-calendars": "^1.1300.0",
    "react-native-element-dropdown": "^2.10.0",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-get-random-values": "~1.9.0",
    "react-native-hyperlink": "^0.0.19",
    "react-native-open-maps": "^0.4.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-web": "~0.19.6",
    "uuid": "^8.3.2",
    "react-native-reanimated": "~3.4.0"
  },`

### Steps to reproduce

Call createDrawerNavigator<RootStackParamList>()

### Snack or a link to a repository

https://snack.expo.io/)

### Reanimated version

3.4.0

### React Native version

0.72.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Latropos** [comment] 2023-10-12 12:18
Hi! Some over people had reanimated bugs when calling `createDrawerNavigator` too!
Please read these two issues and try all the fixes suggested in the threads:
* https://github.com/software-mansion/react-native-reanimated/issues/4940
* https://github.com/software-mansion/react-native-reanimated/issues/3796

**Comment by Kosntantin** [comment] 2023-10-13 16:35
I added the plugin correctly, so sadly those two threads do not help me.

**Comment by tomekzaw** [comment] 2023-10-14 18:02
@Kosntantin Can you confirm that you have rebuilt the native part of the app after installing Reanimated?

**Comment by Kosntantin** [comment] 2023-10-15 06:58
Yes, both with `expo prebuild --clean` and with `npm run android -c`

**Comment by macrozone** [comment] 2023-11-15 20:54
I have the same problem after upgrading from 3.1.0 to 3.5.4

after pod install, the podfile.lock has only removed lines, no changed ones. seems like all pods are rempoved

**Comment by Latropos** [comment] 2024-03-05 10:07
Closing since we are unable to reproduce the problem

**Closed by Latropos** 2024-03-05 10:07 UTC
Labels: Missing repro, Platform: Android, Platform: iOS, Needs review

**Comment by anup-a** [comment] 2024-03-29 13:34
This usually happens in a monorepo setup when there are two different version of `react-native-animated` is installed across packages.
