### ISSUE TITLE
Animated node with ID 2 already exists

### ISSUE THREAD

**Issue by VKBobyr** [software-mansion/react-native-reanimated#1072] opened 2020-08-05 01:44 UTC
## Description

Getting an `Animated node with ID 2 already exists` error on start after upgrading `expo` to `^38.0.9`.
There have been a few issues like this, but most seemed to have been resolved by upgrading `react-native-reanimated` to version `^1.9.0`. Unfortunately this doesn't work for me.

##  Package versions

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "clean": "rm -rf node_modules yarn.lock && yarn install"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "axios": "^0.19.2",
    "expo": "^38.0.9",
    "expo-mail-composer": "~8.2.1",
    "expo-splash-screen": "^0.3.1",
    "firebase": "7.9.0",
    "lodash": "^4.17.19",
    "material-colors": "^1.2.6",
    "native-base": "^2.13.13",
    "prop-types": ">=15.5.10",
    "react": "16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-cheerio": "^1.0.0-rc.4",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-modal": "^11.5.6",
    "react-native-phone-call": "^1.0.9",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-skeleton-content": "^1.0.18",
    "react-navigation": "^4.4.0",
    "react-navigation-drawer": "^2.5.0",
    "typescript": "~3.9.5",
    "typescript-eslint": "^0.0.1-alpha.0",
    "valid-url": "^1.0.9"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@typescript-eslint/eslint-plugin": "^3.6.1",
    "@typescript-eslint/parser": "^3.6.1",
    "eslint": "7.4.0",
    "eslint-config-airbnb": "18.2.0",
    "eslint-plugin-import": "2.22.0",
    "eslint-plugin-jsx-a11y": "6.3.1",
    "eslint-plugin-react": "7.20.3",
    "eslint-plugin-react-hooks": "4.0.6"
  },
  "private": true
}

```

### What I've tried:
1. Removing `node_modules` and running `yarn install`
2. Running `expo upgrade`
3. Running `expo install react-native-gesture-handler react-native-reanimated react-native-safe-area-context`

**Comment by jakub-gonet** [comment] 2020-08-05 09:56
Try running commands described in [this comment](https://github.com/software-mansion/react-native-reanimated/issues/1007#issuecomment-662438323).

Please provide some code example or more logs as well, because this issue isn't really actionable for us in this form.

Closing until then.

**Closed by jakub-gonet** 2020-08-05 09:56 UTC
Labels: Reanimated2, 🐞 Bug

**Comment by fahelmoreira** [comment] 2020-09-20 11:24
Does anyone know how to fix this? on reanimated 2

**Comment by jakub-gonet** [comment] 2020-09-20 12:39
This is most likely caused by two instances of reanimated running simultaneously. Please provide some reproduction example.

**Comment by fahelmoreira** [comment] 2020-09-20 16:22
Yeah! that was exactly what it was! thanks!

**Comment by nitinvarda** [comment] 2021-05-10 14:57
In My case, I have another package that has `react-native-reanimated` as a dependency with a specific version.
![Screenshot 2021-05-10 201713](https://user-images.githubusercontent.com/56512897/117679307-c8c99c00-b1cd-11eb-9e2d-b42507199f71.png)
 but in my project, `react-native-reanimated` has a higher version. 
later when I installed the same version as mentioned above in the dependency
![Screenshot 2021-05-10 202017](https://user-images.githubusercontent.com/56512897/117679530-fd3d5800-b1cd-11eb-8061-13ae0c9c60da.png)

the issue got resolved, hope this helps someone.

**Comment by riamon-v** [comment] 2022-02-17 16:08
Hello,

Sorry to bring that up, but I can't find a way to fix my problem for now.

I created my own npm package with react-native-reanimated as dependency
I made a bare expo app and installed with yarn my custom package locally.

This works great on IOS. However I got the error mention in this issue on Android.
`Animated node with ID 2 already exists`

Here is a quick look of my `package.json` and `yarn.lock` in both the App and the Custom Package

#### yarn.lock

| App  | Package |
|---|---|
| <img width="819" alt="Screenshot 2022-02-17 at 17 00 17" src="https://user-images.githubusercontent.com/19188004/154520327-0cc2a6de-8ad0-4281-85c2-c315df30b8b6.png"> | <img width="812" alt="Screenshot 2022-02-17 at 17 00 37" src="https://user-images.githubusercontent.com/19188004/154520400-6fdf8d59-36f7-48c1-9a48-392dbd176280.png">|

#### package.json

| App  | Package |
|---|---|
| <img width="789" alt="Screenshot 2022-02-17 at 17 04 31" src="https://user-images.githubusercontent.com/19188004/154521185-fcd4cea6-8bc0-44df-ba2b-46c3953dab56.png"> |  <img width="650" alt="Screenshot 2022-02-17 at 17 03 57" src="https://user-images.githubusercontent.com/19188004/154521075-11c5f170-6cea-445d-a485-8f390210330f.png"> |

* I tried also to remove react-native-reanimated in the app (which made no sense in my head). Got the same error.
* I tried to move react-native-reanimated as peerDependencies in the custom package (which made no sense in my head). The package did not build as expected.

Do you guys have any idea what it could be ?

**Comment by riamon-v** [comment] 2022-02-19 17:10
> > For me the version of reanimated installed are matching.
> 
> It's not a matter of matching or not, the real issue here is that you most likely have two versions of Reanimated listed in `yarn.lock` (or it's conflicting with Reanimated shipped with Expo).
> 
> This can happen when two packages list incompatible versions so yarn tries resolving it by installing the next Reanimated package instance in node_modules local to the package requesting incompatible version.
> 
> This isn't the problem with pure JS libraries (if they don't overwrite global) but if the native library needs to be initialized once it'll crash. This is what's happening with Reanimated.
> 
> You can try using yarn [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to install only one version. If expo ships one then you can pin that specific version of it (or remove reanimated entirely) and see if it helps.

I can't find a way around that. I tried using `yarn resolutions` like you mentionned. Didn't work.
I removed react-native-reanimated from my `package.json` as well, didn't work.

I don't understand where the problem could come from actually.
I tried to remove `node-modules/react-native-reanimated/` on my own, of course the app crashed,
Then I tried to remove `node-modules/my-custom-package/node-modules/react-native-reanimated` and the app kinda worked.

Problem is I need `react-native-reanimated` as dependency, not juste as peer dependency, in my custom package for it to build properly.

I think I don't really get why there is apparently "two instance" of reanimated running

**Comment by likern** [comment] 2022-02-23 20:36
@Karthik-B-06
As soon as I installed this library https://github.com/Karthik-B-06/react-native-segmented-control and tried to use a basic example from documentation https://github.com/Karthik-B-06/react-native-segmented-control I've _immediately got this error_.

While I have _dependency_ in my `package.json`
```json
"react-native-reanimated": "=2.3.1"
```
and library itself _has the same dependency_ https://github.com/Karthik-B-06/react-native-segmented-control/blob/main/package.json.

I also checked `yarn.lock` after installation - _there is only one reanimated library_.
_As soon as I deleted this library everything **continued working**._

I hope this might help in reproducing error.

Also _nothing like cleaning caches from other issues helped_.

**Comment by likern** [comment] 2022-02-23 20:37
So I believe it's not related to caches.

**Comment by likern** [comment] 2022-02-23 20:57
Hmm, strange. I've taken implementation directly from https://github.com/Karthik-B-06/react-native-segmented-control/blob/main/src/index.tsx and put it into my source code and **it starts working**.

**Comment by jakub-gonet** [comment] 2022-02-23 22:11
\cc @tomekzaw since I don't work on Reanimated anymore
