### ISSUE TITLE
Can't be used with React Navigation/Drawer V6

### ISSUE THREAD

**Issue by efefurkankarakaya** [software-mansion/react-native-reanimated#2301] opened 2021-08-20 08:20 UTC
## Description
Can't be used with Drawer Navigator in React Navigation.

### Expected behavior
Able to create and use Drawer Navigator with no exception.

### Actual behavior & steps to reproduce

Just trying to create Drawer object.
```
import {createDrawerNavigator} from '@react-navigation/drawer';
const Drawer = createDrawerNavigator();
```

And it throws an error.
```
 ERROR  TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

## Snack or minimal code example
```
// source: https://reactnavigation.org/docs/drawer-based-navigation

import * as React from 'react';
import {Button, View} from 'react-native';
import {createDrawerNavigator} from '@react-navigation/drawer';
import {NavigationContainer} from '@react-navigation/native';

function HomeScreen({navigation}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Button
        onPress={() => navigation.navigate('Notifications')}
        title="Go to notifications"
      />
    </View>
  );
}

function NotificationsScreen({navigation}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Button onPress={() => navigation.goBack()} title="Go back home" />
    </View>
  );
}

const Drawer = createDrawerNavigator(); // error

export default function App() {
  return (
    <NavigationContainer>
      <Drawer.Navigator initialRouteName="Home">
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="Notifications" component={NotificationsScreen} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
}
```

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.2.0
- React Navigation Drawer: 6.1.4
- React Navigation Native: 6.0.2
- React Navigation Gesture Handler: 1.10.3
- NodeJS: v16.6.2
- Xcode:
- Java & Gradle: 11.0.12

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

## Temporary Resolve Method

It works with `"react-native-reanimated": "^1.13.2"`.

**Comment by piaskowyk** [comment] 2021-08-24 10:54
Hey @efefurkankarakaya  
We are working on a solution to this problem.

**Comment by 0nlyDev** [comment] 2021-09-07 01:07
> Hey @efefurkankarakaya
> We are working on a solution to this problem.

Stuck at this for weeks.. any temporary solution?

**Comment by efefurkankarakaya** [comment] 2021-09-16 08:30
> > Hey @efefurkankarakaya
> > We are working on a solution to this problem.
> 
> Stuck at this for weeks.. any temporary solution?

Temporary solution as I mentioned the main post is 

> It works with "react-native-reanimated": "^1.13.2".

**Comment by KodeMunkie** [comment] 2021-09-16 11:22
The workaround isn't really suitable for me as I needed to have the latest version of reanimated for other components I was using. Regrettably I had to remove this component altogether due to incompatibility - I've since gone for a UI Kitten bottom nav bar.

**Comment by 0nlyDev** [comment] 2021-09-16 14:45
@efefurkankarakaya @KodeMunkie update, 2.2.1 solved this issue for me.

From my package.json:

```
   "@react-navigation/drawer": "^6.1.4",
   "@react-navigation/native": "^6.0.2",
   "@react-navigation/stack": "^6.0.7",
   "react-native": "0.65.1",
   "react-native-reanimated": "^2.2.1",
```

**Comment by efefurkankarakaya** [comment] 2021-09-16 21:30
> @efefurkankarakaya @KodeMunkie
> Update: 2.2.1 solved this issue for me.
> 
> From my package.json:
> 
> ```
>    "@react-navigation/drawer": "^6.1.4",
>    "@react-navigation/native": "^6.0.2",
>    "@react-navigation/stack": "^6.0.7",
>    "react-native": "0.65.1",
>    "react-native-reanimated": "^2.2.1",
> ```

Could you share gesture handler version too?

**Comment by 0nlyDev** [comment] 2021-09-17 23:47
> Could you share gesture handler version too?
Sure thing:
`"react-native-gesture-handler": "^1.10.3",`

**Comment by piaskowyk** [comment] 2021-11-09 14:18
It really looks like a problem with the cache. I wasn't able to reproduce this issue :/ Could you prepare a repo with reproduction? Without this repo, I can't help you, unfortunately.

**Comment by efefurkankarakaya** [comment] 2021-11-09 18:00
> It really looks like a problem with the cache. I wasn't able to reproduce this issue :/ Could you prepare a repo with reproduction? Without this repo, I can't help you, unfortunately.

Actually, I've just tried it again and this error still exist with the newest version of React Native and React Navigation.

Error log:
```
error: Error: Unable to resolve module ./Transitioning from /home/efk/Desktop/env/testProject/node_modules/react-native-reanimated/src/Animated.js: 

None of these files exist:
  * node_modules/react-native-reanimated/src/Transitioning(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native-reanimated/src/Transitioning/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import { Image, ScrollView, Text, View } from 'react-native';
  2 | import createAnimatedComponent from './createAnimatedComponent';
  3 | import {
  4 |   addWhitelistedNativeProps,
    at ModuleResolver.resolveDependency (/home/efk/Desktop/env/testProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:107:15)
    at DependencyGraph.resolveDependency (/home/efk/Desktop/env/testProject/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/home/efk/Desktop/env/testProject/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/home/efk/Desktop/env/testProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /home/efk/Desktop/env/testProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/home/efk/Desktop/env/testProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/home/efk/Desktop/env/testProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/home/efk/Desktop/env/testProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 7)
```

Full `package.json` of current status.
```
{
  "name": "testproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "react": "17.0.2",
    "react-native": "0.66.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.2.4",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

But it doesn't throw an error with `react-native-reanimated@1.13.2`, works well.

```
{
  "name": "testproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "react": "17.0.2",
    "react-native": "0.66.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
Full package.json of working situation is above.

By the way this project does not have anything but App.js and I've already specified where I took it from the code but of course, I'll share it as a repository.

Working version @1.13.2 reproduction: https://github.com/efefurkankarakaya/react-native-reanimated-1.13.2-reproduction
Faulty / not working version reproduction: https://github.com/efefurkankarakaya/react-native-reanimated-reproduction

**Comment by durac** [comment] 2021-12-01 09:19
Clearing the cache after upgrading from `react-native-reanimated@1.13.2` helped in my case:
Just run `npm start -- --reset-cache` and the error disappeared.

**Comment by belaziv** [comment] 2022-01-25 09:19
I tried exactly the versions mentioned above, but nothing helped 
Does it require special settings in Java for it to work?
Or any another idea?

**Comment by InterstateTAT** [comment] 2022-01-26 14:52
I'm also running into an issue with the React Navigation/Drawer V6. I receive no errors, just a white screen for the drawer when using the following versions. Changing reanimated version to 2.2.0 I run into a red screen of errors.

Reverting back to version seems to work for now:	"react-native-reanimated": "1.13.3",


    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "6.2.4",
    "@react-navigation/stack": "^6.0.11",
	"react-native": "0.66.4",
	"react-native-reanimated": "^2.3.1",
	"react-native-gesture-handler": "2.1.1",

**Comment by efefurkankarakaya** [comment] 2022-01-26 14:57
@piaskowyk Is there any relevant update? I've shared the example projects to reproduce it approximately 3 months ago and the new comments shows us the error still persist.

**Comment by belaziv** [comment] 2022-01-27 07:50
@InterstateTAT  make sure that the libraries have really been updated on the Java side
`autolinking` solved the issue for me

**Comment by kmagiera** [comment] 2022-01-28 10:02
To sum up: I understand that the repo where the issue can be reproduced is here: https://github.com/efefurkankarakaya/react-native-reanimated-reproduction

Can you update the issue description such that all up-to-date information is in one place?

**Comment by Ngomana** [comment] 2022-02-04 22:24
Why does the previous version `react-native-reanimated": "^1.13.2` work perfectly while the new version is a hot mess...
Respectfully

**Comment by likern** [comment] 2022-02-17 16:36
Is this still issue for new versions? I can't easily switch back to `1.*` version.

**Comment by Ngomana** [comment] 2022-02-17 17:02
Yes it's the new versions that have problem

**Comment by Ngomana** [comment] 2022-02-17 17:02
> Is this still issue for new versions? I can't easily switch back to `1.*` version.

Yes it's the new versions that have problem

**Comment by likern** [comment] 2022-02-17 19:12
Does anyone know, will RN2 work with older V5 version of React Navigation?

**Comment by ppritesh** [comment] 2022-02-20 06:43
How to solve this error ?

**Comment by PercentageCorporation** [comment] 2022-03-18 23:19
I have this issue:
"react-native": "0.67.3",
"@react-navigation/native": "^6.0.8",
"@react-navigation/native-stack": "^6.5.0",
"@react-navigation/drawer": "^6.3.1",
"react-native-reanimated": "^2.4.1",
"react-native-gesture-handler": "^2.3.2",

**Comment by himaniChaine** [comment] 2022-03-31 08:56
i have issue with     
"@react-navigation/drawer": "^6.3.3",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.2",
    "@react-navigation/stack": "^6.1.1",
    "@types/react-native": "^0.67.3",
    "react-native-reanimated": "^2.5.0",
    "react-native-gesture-handler": "^2.3.2",

**Comment by bimix** [comment] 2022-04-11 12:56
Works with `"react-native-reanimated": "^2.2.4" `but not with `2.6.0`

**Comment by Manil-SoftNEP** [comment] 2022-06-06 09:17
This worked for me.

1. `npm i react-native-reanimated`
2. Add `plugins: ['react-native-reanimated/plugin'],` below presets in '_<your_app_root_folder>_/babel.config.js'.
3. Add `import 'react-native-gesture-handler';` to the top of '_<your_app_root_folder>_/App.js'.
4. Reset the cache using `npx react-native start --reset-cache`.

**Comment by shahnawaz-pabon** [comment] 2023-03-03 18:37
I was using `"@react-navigation/drawer": "^6.6.0"` with `"react-native-reanimated": "^3.0.0"`. These were the fixes for me:

```sh
npm uninstall react-native-reanimated
npm install react-native-reanimated@2.2.4
npx react-native start --reset-cache
```

**Comment by andib0** [comment] 2023-05-17 09:25
same issue

**Comment by piaskowyk** [comment] 2023-05-17 12:45
@ironic833 @andib0  I have just tested it on my Example app in Reanimated repository (Rea 3.1.0 and React Native 0.71) and it works without any problems. Could you provide me a reproduction? Without this I can't help unfortunately.

**Comment by andib0** [comment] 2023-05-21 14:33
@piaskowyk all good, the issue seemed to be something from my end.

**Comment by worldpeacez0991** [comment] 2023-06-16 02:49
Seems to be duplicate of issue (Possible workaround are mentioned in this link) :
https://github.com/react-navigation/react-navigation/issues/11391

**Comment by harshithvemulas** [comment] 2023-06-16 17:34
expo install react-native-gesture-handler

If we do an expo install instead of npm install it will select the react-native-gesture-handler version it needs and the problem got solved.

Please read the following docs https://docs.swmansion.com/react-native-gesture-handler/docs/installation and I followed this repo https://github.com/worldpeacez0991/rnDrawerNavigation.git

    "@react-navigation/bottom-tabs": "^6.5.3",
    "@react-navigation/drawer": "^6.5.7",
    "@react-navigation/native": "^6.1.2",
    "@react-navigation/native-stack": "^6.9.8",
    "@react-navigation/stack": "^6.3.16",
    "expo": "~48.0.18",
    "expo-dev-client": "~2.2.1",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-drawer-layout": "^3.2.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-reanimated": "~2.14.4",

Thank you



Thank you

**Comment by harshithvemulas** [comment] 2023-06-16 17:35
expo install react-native-gesture-handler

If we do an expo install instead of npm install it will select the react-native-gesture-handler version it needs and the problem got solved.

Please read the following docs https://docs.swmansion.com/react-native-gesture-handler/docs/installation and I followed this repo https://github.com/worldpeacez0991/rnDrawerNavigation.git

"@react-navigation/bottom-tabs": "^6.5.3",
"@react-navigation/drawer": "^6.5.7",
"@react-navigation/native": "^6.1.2",
"@react-navigation/native-stack": "^6.9.8",
"@react-navigation/stack": "^6.3.16",
"expo": "~48.0.18",
"expo-dev-client": "~2.2.1",
"react": "18.2.0",
"react-native": "0.71.8",
"react-native-drawer-layout": "^3.2.0",
"react-native-gesture-handler": "~2.9.0",
"react-native-reanimated": "~2.14.4",
Thank you

**Comment by kacperkapusciak** [comment] 2023-06-21 06:40
Locking the conversation as different comments mention unreleated problems throughout the years and months of developments which is counterproductive on our side.

**Closed by kacperkapusciak** 2023-06-21 06:40 UTC
Labels: Bug, 🏠  Reanimated 2, bug-bash-jan22
