### ISSUE TITLE
withSpring doesn't work inside recursive worklet

### ISSUE THREAD

**Issue by DanijelBojcic** [software-mansion/react-native-reanimated#2590] opened 2021-11-01 08:50 UTC
## Description
I have a drag and sort list and every time the active item overlaps another item I want to push it down in the list. When I push down one item I need to reorder the whole list so I need to call the same function recursively.

### Expected behavior
`withSpring` should work inside recursive worklets.

### Actual behavior & steps to reproduce
Calling `withSpring` inside a recursive worklet freezes the app.
## Snack or minimal code example

```
function reorder(
  values: Array<DLCAnimatedItemConfig>,
  id: number,
  x: number,
  y: number,
  width: number,
  height: number,
) {
  "worklet";

  values.forEach(function (c) {
    if (
      c.id !== id &&
      doOverlap(
        { x, y },
        { x: x + width, y: y + height },
        { x: Math.floor(c.left.value + c.width.value * 0.25), y: Math.floor(c.top.value + c.height.value * 0.25) },
        { x: c.left.value + c.width.value * 0.75, y: c.top.value + c.height.value * 0.75 },
      )
    ) {
      const closestRow = Math.round(y / DLMConstants.ROW_HEIGHT);

      c.top.value = withSpring(closestRow * DLMConstants.ROW_HEIGHT + height); // this freezes the app
      reorder(values, c.id, c.left.value, c.top.value, c.width.value, c.height.value);
    }
  });
}
```

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.2.1
- NodeJS:
- Xcode: 13.1
- Java & Gradle:

## Affected platforms

- [ ] Android // not tested
- [x] iOS
- [ ] Web // not tested

**Comment by piaskowyk** [comment] 2022-01-14 12:28
Duplicate of: https://github.com/software-mansion/react-native-reanimated/issues/2277

**Closed by piaskowyk** 2022-01-14 12:28 UTC
Labels: 🐞 Bug, 🏠  Reanimated2
