### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'worklet.__workletHash.toString')

### ISSUE THREAD

**Issue by caopeng000** [software-mansion/react-native-reanimated#2592] opened 2021-11-02 03:57 UTC
## Package versions

- React Native: 0.64.2
- React Native Reanimated: ^2.3.0-beta.2
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [1 ] Android
- [ ] iOS
- [ ] Web

` ERROR TypeError: undefined is not an object (evaluating 'worklet.__workletHash.toString')

This error is located at:
in BottomSheetGestureHandlersProvider (at BottomSheet.tsx:1552)
in BottomSheet (created by BottomSheet)
in RCTView (at View.js:34)
in View (at BasicExamples.tsx:90)
in Unknown (at SceneView.tsx:126)
in StaticContainer
in EnsureSingleNavigator (at SceneView.tsx:118)
in SceneView (at useDescriptors.tsx:210)
in RCTView (at View.js:34)
in View (at CardContainer.tsx:280)
in RCTView (at View.js:34)
in View (at CardContainer.tsx:278)
in RCTView (at View.js:34)
in View (at CardSheet.tsx:33)
in CardSheet (at Card.tsx:557)
in RCTView (at View.js:34)
in View (at createAnimatedComponent.js:217)
in AnimatedComponent (at createAnimatedComponent.js:278)
in AnimatedComponentWrapper (at Card.tsx:536)
in PanGestureHandler (at GestureHandlerNative.tsx:14)
in PanGestureHandler (at Card.tsx:530)
in RCTView (at View.js:34)
in View (at createAnimatedComponent.js:217)
in AnimatedComponent (at createAnimatedComponent.js:278)

**Comment by piaskowyk** [comment] 2021-11-09 11:01
Hey, could you provide an example code to reproduce this issue?

**Comment by kludger1** [comment] 2021-11-13 04:38
`import React, {useCallback, useMemo, useRef} from 'react';
import {View, Text, StyleSheet} from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const App = () => {
  // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  // renders
  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;
`

This causes the error

**Comment by kludger1** [comment] 2021-11-13 04:42
`import React, {useCallback, useMemo, useRef} from 'react';
import {View, Text, StyleSheet} from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const App = () => {
  // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  // renders
  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;
`


This causes the error

**Comment by piaskowyk** [comment] 2021-11-30 14:06
Unfortunately, I am closing this issue because I can't reproduce it. If someone prepares a repo with reproduction of this issue post it here and we will reopen the issue.

**Closed by piaskowyk** 2021-11-30 14:06 UTC
Labels: 🧰needs-repro, 🐞 Bug, 🏠  Reanimated2
