### ISSUE TITLE
[Android] onMomentumBegin/ -End not being called in Animated.ScrollView

### ISSUE THREAD

**Issue by alexco2** [software-mansion/react-native-reanimated#2735] opened 2021-12-13 00:58 UTC
## Description

onMomentumEnd is not being called anymore since Version 2.3.0 in `Animated.ScrollView`. An animated `FlatList` or `SecionList` (with `createAnimatedComponent`) still calls `onMomentumEnd`. Am I doing something wrong in my code? In Version 2.2.4 it still worked.
This causes a bug in this library as well: https://github.com/PedroBern/react-native-collapsible-tab-view/issues/221

### Expected behavior
I expect onMomentumEnd to be called like in version 2.2.4 and lower.

### Actual behavior & steps to reproduce
Scroll the screen of the code I provided. "onMomentumEnd" will not be printed in the console.

## Snack or minimal code example

```
import React from 'react';
import { View } from 'react-native';
import Animated, { useAnimatedScrollHandler,  useSharedValue } from 'react-native-reanimated';

export default function App() {
  const translationY = useSharedValue(0);
  const isScrolling = useSharedValue(false);

  const scrollHandler = useAnimatedScrollHandler({
    onScroll: (event) => {
      translationY.value = event.contentOffset.y;
    },
    onBeginDrag: (e) => {
      isScrolling.value = true;
      console.log('onBeginDrag');
    },
    onEndDrag: (e) => {
      isScrolling.value = false;
      console.log('onEndDrag');
    },
    onMomentumEnd: () => {
      console.log('onMomentumEnd');
    },
  });

  return (
    <View style={{flex:1}} >
      <Animated.ScrollView
        onScroll={scrollHandler}
        scrollEventThrottle={16}>
          <View style={{height:250, width:300, backgroundColor:"red"}}></View>
          <View style={{height:250, width:300, backgroundColor:"blue"}}></View>
          <View style={{height:250, width:300, backgroundColor:"yellow"}}></View>
          <View style={{height:250, width:300, backgroundColor:"purple"}}></View>
          <View style={{height:250, width:300, backgroundColor:"green"}}></View>
      </Animated.ScrollView>
    </View>
  );
}

```

## Package versions

- React Native: 0.64.3
- React Native Reanimated: 2.3.0
- NodeJS: 16.6.2
- Xcode: - Just tested on android
- Java & Gradle: I tested in expo SDK 44 beta

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by alexco2** [comment] 2021-12-15 10:59
Just as a small update. Tried it with version 2.3.1. The bug is still there

**Comment by alexco2** [comment] 2021-12-21 10:46
@piaskowyk 
Did you have a chance to test my snippet? Can I support you somehow? Others seem to have the problem as well: https://github.com/PedroBern/react-native-collapsible-tab-view/issues/221#issuecomment-997474612

**Comment by Omelyan** [comment] 2021-12-26 15:57
Not only onMomentumEnd but also onMomentumBegin is not called either.

**Comment by Omelyan** [comment] 2021-12-26 20:27
Here's a way to get around with it.

1. declare own useAnimatedScrollHandler hook:
`const useAnimatedScrollHandler = (scrollHandlers, dependencies) => {
  const { context, doDependenciesDiffer } = useHandler(scrollHandlers, dependencies);

  const {
    onScroll,
    onMomentumScrollEnd,
    // etc.
  } = scrollHandlers;

  return useEvent(
    event => {
      'worklet';

      const { eventName } = event;

      if (onScroll && eventName.endsWith('onScroll')) {
        onScroll(event, context);
      } else if (onMomentumScrollEnd && eventName.endsWith('onMomentumScrollEnd')) {
        onMomentumScrollEnd(event, context);
      } // else if etc.
    },
    undefined, // here's a magic
    doDependenciesDiffer,
  );
};`

2. use it like before:
`const onScroll = useAnimatedScrollHandler({
    onScroll: () => {
      console.log('onScroll');
    },

    onMomentumScrollEnd: () => {
      console.log('onMomentumScrollEnd');
    },
  });`

3. pass it to onScroll and (!) **onMomentumScrollEnd** props:
`<ReanimatedScrollView onScroll={onScroll} onMomentumScrollEnd={onScroll}></ReanimatedScrollView>`

**Comment by Omelyan** [comment] 2021-12-26 20:50
Here's a way to get around with it.
1. declare own useAnimatedScrollHandler hook:
```js
const useAnimatedScrollHandler = (scrollHandlers, dependencies) => {
  const { context, doDependenciesDiffer } = useHandler(scrollHandlers, dependencies);

  const {
    onScroll,
    onMomentumScrollEnd,
    // etc.
  } = scrollHandlers;

  return useEvent(
    event => {
      'worklet';

      const { eventName } = event;

      if (onScroll && eventName.endsWith('onScroll')) {
        onScroll(event, context);
      } else if (onMomentumScrollEnd && eventName.endsWith('onMomentumScrollEnd')) {
        onMomentumScrollEnd(event, context);
      } // else if etc.
    },
    undefined,
    doDependenciesDiffer,
  );
};
```

2. use it like before:
```js
const onScroll = useAnimatedScrollHandler({
  onScroll: () => {
    console.log('onScroll');
  },

  onMomentumScrollEnd: () => {
    console.log('onMomentumScrollEnd');
  },
});
```

3. pass it to onScroll and (!) **onMomentumScrollEnd** props:
```js
<ReanimatedScrollView onScroll={onScroll} onMomentumScrollEnd={onScroll}></ReanimatedScrollView>
```

**Comment by fhugoduarte** [comment] 2021-12-27 19:37
Guys, passing a function to **onMomentumScrollEnd prop** works for me. The onMomentumScrollEnd is called using the `useAnimatedScrollHandler` hook, as expected.

```js
  const handleScrollHandler = useAnimatedScrollHandler({
    onMomentumScrollEnd: () => {
      // has called
    }
  })

  function handleMomentumScrollEnd() {
    // workaround reanimated 2.3 momentum scroll is not called
  }
  
  <Animated.ScrollView onScroll={handleScrollHandler}  onMomentumScrollEnd={handleMomentumScrollEnd}  />
  ```

**Comment by alexco2** [comment] 2021-12-27 21:25
@fhugoduarte Are you sure you are running rea 2.3.0? Could you try my code snippet?

**Comment by fhugoduarte** [comment] 2021-12-27 22:27
> @fhugoduarte Are you sure you are running rea 2.3.0? Could you try my code snippet?

From my package.json:  `"react-native-reanimated": "~2.3.1",` ` "react-native": "0.64.3",`

**Comment by Omelyan** [comment] 2021-12-27 22:37
> > @fhugoduarte Are you sure you are running rea 2.3.0? Could you try my code snippet?
> 
> From my package.json: `"react-native-reanimated": "~2.3.1",` ` "react-native": "0.64.3",`

The issue affects Android

**Comment by BabuStack** [comment] 2021-12-28 08:15
@alexco2 Even I was facing the same issue and after spending hours of debugging I found that, if we add `onMomentumScrollEnd` prop to the FlatList or ScrollView, then `onMomentumEnd` handler was triggered correctly
This is what I did:
```JS
<Animated.ScrollView
  ref={ref}
  onMomentumScrollEnd={() => {}}
  {...otherProps}
/>
```

**Comment by danilichev** [comment] 2022-01-26 20:34
I've got this bug too (reanimated 2.3.1). Unfortunately, the previous workaround didn't help me.  In my case, I needed to handle the change of the current item in my horizontal ScrollView. I've solved it with a set of reanimated hooks, so maybe it can be helpful for someone:

```js
const offsetX = useSharedValue(0);

  const currentIndex = useDerivedValue(
    () => Math.round(offsetX.value / galleryWidth),
    [galleryWidth],
  );

  useAnimatedReaction(
    () => currentIndex.value,
    (index, prevIndex) => {
      if (index !== prevIndex && typeof onChangeItem === 'function') {
        runOnJS(onChangeItem)(items[index]);
      }
    },
    [currentIndex, items, onChangeItem],
  );

  const onScroll = useAnimatedScrollHandler({
    onScroll: event => {
      offsetX.value = event.contentOffset.x;
    },
  });
```

**Comment by alexco2** [comment] 2022-03-22 19:04
Just as an information. The issue still persists with version 2.5.0.
@piaskowyk do you have any updates on the progress of this bug?

**Comment by jp-23** [comment] 2022-03-30 01:59
I experience this issue on iOS with version 2.5.0.  Here are the details:
- onEndDrag works on simulator but not on device.
- onMomentumEnd does not work on simulator or device.

**Comment by andreialecu** [comment] 2022-04-04 17:14
Hello maintainers, what would it take to get some attention to this? (🙏 @piaskowyk)

It's blocking users of `react-native-collapsible-tab-view` from upgrading to RN 0.68 because Reanimated versions above 2.3.0 break the library due to this bug.

**Comment by hirbod** [comment] 2022-04-06 21:26
I can confirm this issues.

**Comment by alexco2** [comment] 2022-04-06 22:12
@piaskowyk it would be amazing if we could have an update on the progress of this issue :)

**Comment by Spejbl** [comment] 2022-04-20 12:26
Just leaving a comment to bring more attention to this 🙏 It's also a blocker for us to upgrade to RN 0.68

**Comment by andreialecu** [comment] 2022-04-20 12:29
Everyone affected by this, don't forget to upvote the top post. Perhaps it helps get it more visibility.

**Comment by alexco2** [comment] 2022-04-25 13:39
Hello @kmagiera @piaskowyk @Szymon20000,
this issue is now the third most interacted issue (regarding thumbs up) in rea. Could you give us an update on the current state? Is there anything we could do to support you in solving this issue? Thanks :)

**Comment by hirbod** [comment] 2022-05-04 02:38
@piaskowyk sorry to be the 20th person who pings you here, but this issue really needs some hands on to get resolved. It is actually a huge blocker :/

Can we do something to get some traction here?

**Comment by alexco2** [comment] 2022-05-04 08:09
> @piaskowyk sorry to be the 20th person who pings you here, but this issue really needs some hands on to get resolved. It is actually a very annoying blocker :/
> 
> Can we do something to get some traction here? Obviously nobody here has enough native knowledge to provide a PR.

I reall agree. I think it is not to much to ask for at least a small update so the community knows how to handle this issue. Also the amount of reactions clearly show a big interest in this issue. Sorry for pinging all of you, but @piaskowyk does not seem to be responsible for this issue anymore.

@kmagiera @Szymon20000 @jkadamczyk

**Comment by andreialecu** [comment] 2022-05-04 08:47
I just found out something interesting.

Seems that if I add an empty `onMomentumScrollEnd` handler to the `ScrollView`, it starts firing the event and the repro at the very top starts logging `onMomentumEnd`

<img width="172" alt="Screenshot 2022-05-04 at 11 46 07" src="https://user-images.githubusercontent.com/697707/166649317-4b239974-02e7-49f9-b651-661f45d65dba.png">

Example:

```tsx
<Animated.ScrollView onScroll={scrollHandler} 
scrollEventThrottle={16} 
// add this:
onMomentumScrollEnd={()=>{}}>
```

Can anyone else confirm this? Note that it also seems to log `onMomentumEnd` three times, so something is weird with it.

**Comment by alexco2** [comment] 2022-05-04 09:26
> @alexco2 Even I was facing the same issue and after spending hours of debugging I found that, if we add `onMomentumScrollEnd` prop to the FlatList or ScrollView, then `onMomentumEnd` handler was triggered correctly This is what I did:
> 
> ```js
> <Animated.ScrollView
>   ref={ref}
>   onMomentumScrollEnd={() => {}}
>   {...otherProps}
> />
> ```

@andreialecu 
So basically what @BabuStack found out, right? At least for @danilichev this workaround did not help. I will try this workaround later today and give you feedback. But apparently this is a somewhat hacky workaround.

**Comment by andreialecu** [comment] 2022-05-04 09:31
Indeed, yes, I missed that comment. I didn't really look into this until today so it seems I stumbled upon the same fix.

It does seem to fix the repro, and based on the code in `react-native-collapsible-tab-view` that uses `onMomentumEnd` it should be good enough even if it's called multiple times.

I'm working on testing it myself in a real app soon.

**Comment by alexco2** [comment] 2022-05-04 10:06
@andreialecu if you release a patch for react-native-collapsible-tab-view I can test it as well in my current production app.
I hope this issue gets resolved anyway soon so we don't need any workarounds :)

**Comment by andreialecu** [comment] 2022-05-04 10:07
I don't think there's a need to patch it, you can just try `<Tabs.ScrollView ... onMomentumScrollEnd={() => {}} />`

**Comment by alexco2** [comment] 2022-05-07 21:58
@andreialecu even with the workaround, there are still issues. Scrollview for example does not snap anymore.

**Comment by andreialecu** [comment] 2022-05-07 22:02
Try `react-native-collapsible-tab-view@rc`

https://github.com/PedroBern/react-native-collapsible-tab-view/pull/255

Let's move this discussion over there as to not hijack this thread. 🙂

**Comment by henrymoulton** [comment] 2022-08-18 11:41
Just ran into this, the workaround works but would be good to understand if there's anything we can do to help solve this.

**Comment by szydlovsky** [comment] 2024-06-25 13:00
Hi everyone! Latest Reanimated versions have it fixed by now!

**Closed by szydlovsky** 2024-06-25 13:00 UTC
Labels: Platform: Android, Bug, 🏠  Reanimated 2, Repro provided, bug-bash-jan22
