### ISSUE TITLE
v3.4.1 crash _clearAnimationConfigForTag

### ISSUE THREAD

**Issue by fukemy** [software-mansion/react-native-reanimated#4836] opened 2023-07-28 04:40 UTC
### Description

<img width="1413" alt="Screenshot 2023-07-28 at 11 37 46" src="https://github.com/software-mansion/react-native-reanimated/assets/8202437/d96e4bd8-0fc7-4467-987f-07771c18d2d8">

I checked viewtag = nil but still run into this block:
<img width="1064" alt="Screenshot 2023-07-28 at 11 39 26" src="https://github.com/software-mansion/react-native-reanimated/assets/8202437/dbeece08-a166-4018-b755-1e8440803df5">

### Steps to reproduce

1. Install v3.4.1
2. run pod install
3. run app

### Snack or a link to a repository

https://snack.expo.dev

### Reanimated version

3.4.1

### React Native version

0.72.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Ipad gen7

### Acknowledgements

Yes

**Comment by fukemy** [comment] 2023-07-28 04:41
I also installed `react-native-screens 3.23.0`

**Comment by yenpn** [comment] 2023-07-28 04:50
i same issue.

**Comment by windduong** [comment] 2023-07-28 07:38
I same issue on IOS, work fine on android!

**Comment by yenpn** [comment] 2023-07-28 07:46
> I same issue on IOS, work fine on android!

work fine after downgrade to ver 3.3.0

**Comment by david-tabaka-guesty** [comment] 2023-07-28 11:44
Same issue. For me, it's reproducing only with Chrome Debugger turned on.

**Comment by tjzel** [comment] 2023-07-28 12:51
Hi, if so many people have this issue maybe someone can throw in a repro? 😅

**Comment by ethanneff** [comment] 2023-07-30 04:44
had to downgrade to `3.3.0`. too many crashes on `3.4.1`

**Comment by suhailpahmin** [comment] 2023-07-31 05:26
is there any update on this issue? I'm getting the same crashes.

these are my versions
```
    "react": "18.2.0",
    "react-native": "0.72.3",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "react-native-reanimated": "^3.4.1",
```

**Comment by ipoogleduck** [comment] 2023-08-01 06:59
I'm still getting the same crash after downgrading to version 3.3.0. Any updates or help would be appreciated!

**Comment by tjzel** [comment] 2023-08-01 07:45
Please post a repro so we can investigate this issue 🙏

**Comment by kunger97** [comment] 2023-08-01 08:44
> 

clash after call `navigation.goBack();`
with
```
@babel/core@7.22.9
@babel/preset-env@7.22.9
@babel/runtime@7.22.6
@expo/vector-icons@13.0.0
@ouroboros/react-native-picker@0.3.1
@react-native-async-storage/async-storage@1.19.1
@react-native-community/eslint-config@3.2.0
@react-navigation/native-stack@6.9.13
@react-navigation/native@6.1.7
@tsconfig/react-native@2.0.3
@types/jest@29.5.3
@types/react-test-renderer@18.0.0
@types/react@18.2.17
babel-jest@29.6.2
eslint@8.46.0
expo-barcode-scanner@12.5.3
expo-secure-store@12.3.1
expo-splash-screen@0.18.2
expo@48.0.20
jest@29.6.2
jsencrypt@3.3.2
lodash@4.17.21
metro-react-native-babel-preset@0.73.9
moment@2.29.4
prettier@2.8.8
prop-types@15.8.1
react-native-actions-sheet@0.8.29
react-native-gesture-handler@2.12.0
react-native-reanimated@3.4.1
react-native-root-toast@3.4.1
react-native-safe-area-context@4.7.1
react-native-screens@3.23.0
react-native@0.71.12
react-test-renderer@18.2.0
react@18.2.0
typescript@4.8.4
uuid@9.0.0

```

**Comment by suhailpahmin** [comment] 2023-08-01 09:16
yep, mine is the same as @kunger97 , but I've downgraded to 3.3.0 and it's working now

**Comment by david-tabaka-guesty** [comment] 2023-08-01 09:20
@tjzel I am encountering a consistent crash whenever I use the "Debug with Chrome" feature and navigate to another screen. This happens on a newly initialized project, and the error is reproducible. Here are the step-by-step details of how to reproduce the issue:

Steps to reproduce:

1. Initialize a new project with the latest RN version.
2. Add `@react-navigation/native`, `react-native-screens`, `react-native-safe-area-context`, and `@react-navigation/native-stack packages`.
3. The newest version of `react-native-reanimated` is then added.
4. Disable Hermes so that the Chrome Debugger can function.
5. Next, create a simple `NativeStack`.
6. Enable the "Debug with Chrome" feature.
7. Then, simply navigate to another screen and then back (the crash happens here).

Every single time I navigate back, the app crashes without fail, and it also crashes the moment I disable the "Debug with Chrome" feature.

This is a major issue for us because our team heavily relies on the React Native Debugger and we literally can't use it at the moment for the newly created project. Could you please look into it? Thanks.

Here is my dependencies list:
```
"dependencies": {
    "@react-navigation/native": "6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-reanimated": "3.4.1",
    "react-native-safe-area-context": "4.7.1",
    "react-native-screens": "3.23.0"
  }
```

`App.tsx` file:
```tsx
import React from 'react';
import { Button, SafeAreaView, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import {
  createNativeStackNavigator,
  NativeStackScreenProps,
} from '@react-navigation/native-stack';

const Home = ({ navigation: { navigate } }: NativeStackScreenProps<any>) => {
  return (
    <SafeAreaView>
      <Text>Main screen</Text>

      <Button title="Go to details" onPress={() => navigate('Details')} />
    </SafeAreaView>
  );
};
const Details = ({ navigation: { goBack } }: NativeStackScreenProps<any>) => {
  return (
    <SafeAreaView>
      <Text>Main screen</Text>

      <Button title="Go back" onPress={goBack} />
    </SafeAreaView>
  );
};

const NativeStack = createNativeStackNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <NativeStack.Navigator>
        <NativeStack.Screen name={'Home'} component={Home} />
        <NativeStack.Screen name={'Details'} component={Details} />
      </NativeStack.Navigator>
    </NavigationContainer>
  );
};

export default App;
```

**Comment by piaskowyk** [comment] 2023-08-01 10:44
@david-tabaka-guesty thank you for providing the reproduction! 🙏 I have an idea how to solve this issue. I will post a PR soon.

**Comment by tjzel** [comment] 2023-08-01 12:52
If you need a temporary workaround you can put
`import 'react-native-reanimated'`
somewhere early in your JS code, if you don't import anything from `react-native-reanimated` already

**Comment by tjzel** [comment] 2023-08-01 13:31
@caixingyue This is a known issue that with release of `3.4.0` we accidentally stopped exporting those utility types, they will be restored once #4847 is merged and released in `3.4.2`.

**Comment by atulsharmaTFT** [comment] 2023-08-03 07:36
Is there any update on this error ... i m facing this issue while navigating from one screen to another from Drawer. 
I tried with  3.4.1 , 3.3.0, 3.2.0 nothing worked in my case... any suggestion?

<img width="913" alt="Screenshot 2023-08-03 at 1 04 00 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/94036900/e381f7cc-76e8-42d9-9a05-9f58d1daabd2">

**Comment by caixingyue** [comment] 2023-08-03 07:48
> Is there any update on this error ... i m facing this issue while navigating from one screen to another from Drawer. I tried with 3.4.1 , 3.3.0, 3.2.0 nothing worked in my case... any suggestion?
> 
> <img alt="Screenshot 2023-08-03 at 1 04 00 PM" width="913" src="https://user-images.githubusercontent.com/94036900/258036773-e381f7cc-76e8-42d9-9a05-9f58d1daabd2.png">

Temporary solution, add an introduction to index.js or App.ts

import 'react-native-reanimated'

**Comment by dariusbiro** [comment] 2023-08-03 07:54
> Is there any update on this error ... i m facing this issue while navigating from one screen to another from Drawer. I tried with 3.4.1 , 3.3.0, 3.2.0 nothing worked in my case... any suggestion?
> 
> <img alt="Screenshot 2023-08-03 at 1 04 00 PM" width="913" src="https://user-images.githubusercontent.com/94036900/258036773-e381f7cc-76e8-42d9-9a05-9f58d1daabd2.png">

Another temporary solution I found (but I don't think it's better then the one @caixingyue suggested) is to just disable the chrome deubugging for now.

**Comment by tjzel** [comment] 2023-08-03 08:18
This issue is under investigation. 

@sebasgarcia29  I can't guarantee that it will be released in `3.4.2` which will be either tomorrow or next week - in that case it would be released in `3.4.3` not long after.

**Comment by Acetyld** [comment] 2023-08-03 12:51
import 'react-native-reanimated'
 worked for now.

**Closed** 2023-08-04 10:03 UTC
Labels: Missing repro, Platform: iOS, Needs review

**Comment by lucasAmarall** [comment] 2023-08-07 03:57
> import 'react-native-reanimated' worked for now.

Way to go!
It was unbelievable how long it took me to find this and realize it wasn't any error in my code!

**Comment by SMKH-PRO** [comment] 2023-08-07 22:38
:*( this error cost me sleepless nights!

Same error in 3.4.2

**Comment by piaskowyk** [comment] 2023-08-08 07:18
This fix hasn't released yet. It will be available in 3.5.0

**Comment by fargo31** [comment] 2023-08-08 08:31
add in babel.config.json 
  "plugins": [
    "react-native-reanimated/plugin"
  ]. 

https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#babel-plugin
don't forget : npm start -- --reset-cache

This works for me

**Comment by david-tabaka-guesty** [comment] 2023-08-08 11:27
For some reason, `import 'react-native-reanimated'` doesn't work in our case, so we're still waiting for a fix 🙏🏻.

**Comment by tjzel** [comment] 2023-08-08 12:58
You can use current nightly version that has it fixed, `yarn add react-native-reanimated@nightly`.

**Comment by abhi1897-bit** [comment] 2023-08-10 12:34
This is an issue in latest react native reanimated , putting
`import 'react-native-gesture-handler'
import 'react-native-reanimated'` in index.js file at the very top level resolves the error .

**Comment by david-tabaka-guesty** [comment] 2023-08-11 11:16
@tjzel thanks a lot, `nightly` version works as expected!🙏🏻

**Comment by dennis-gonzales** [comment] 2023-08-20 15:26
I  was able to reproduce the issue still on version `3.4.2`.

importing `react-native-reanimated` in index.js does fixes the issue albeit a temporary fix.

but since the post has been declared closed I'm assuming the fix is going to be released soon.

**Comment by suretarget** [comment] 2023-08-20 22:19
@dennis-gonzales 

> This fix hasn't released yet. It will be available in 3.5.0

**Comment by kushal-mobiledev** [comment] 2023-08-20 23:38
> had to downgrade to `3.3.0`. too many crashes on `3.4.1`

This worked.

**Comment by deva2f** [comment] 2023-08-23 11:17
I am facing the same error for 3.4.2 ,3.3.0.

**Comment by deva2f** [comment] 2023-08-23 11:29
> import 'react-native-reanimated'

Tried with importing but its also failing to solve the issue

**Comment by abhi1897-bit** [comment] 2023-08-25 03:46
> 



> This is an issue in latest react native reanimated , putting `import 'react-native-gesture-handler' import 'react-native-reanimated'` in index.js file at the very top level resolves the error .



> > import 'react-native-reanimated'
> 
> Tried with importing but its also failing to solve the issue

**Comment by abhi1897-bit** [comment] 2023-08-25 03:47
> > import 'react-native-reanimated'
> 
> Tried with importing but its also failing to solve the issue

https://github.com/software-mansion/react-native-reanimated/issues/4836#issuecomment-1673134646

**Comment by dangnguyen1004** [comment] 2023-09-06 03:52
> If you need a temporary workaround you can put `import 'react-native-reanimated'` somewhere early in your JS code, if you don't import anything from `react-native-reanimated` already

Amazing work around

**Comment by gibo77** [comment] 2023-09-10 03:18
When you do `yarn add react-native-reanimated@nightly `
you need to remove the` import 'react-native-reanimated'` from your index.js.
This works for me, but only in iOS debug mode. 
If I change to iOS Release mode in Xcode, app will crash when the page changes with React Native Navigation.

Xcode Crash Report below. Crash trigger only.

Thread 3 Crashed::  Dispatch queue: com.facebook.react.ExceptionsManagerQueue
0   libsystem_kernel.dylib        	    0x7ff8376f4202 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff83774cee6 pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff800131e58 abort + 130
3   libc++abi.dylib               	    0x7ff80025a5f2 abort_message + 241
4   libc++abi.dylib               	    0x7ff80024c7cb demangling_terminate_handler() + 267
5   libobjc.A.dylib               	    0x7ff800032182 _objc_terminate() + 96
6   libc++abi.dylib               	    0x7ff800259a4b std::__terminate(void (*)()) + 6
7   libc++abi.dylib               	    0x7ff800259a06 std::terminate() + 54
8   libdispatch.dylib             	    0x7ff80013d0ed _dispatch_client_callout + 28
9   libdispatch.dylib             	    0x7ff800144b23 _dispatch_lane_serial_drain + 1008
10  libdispatch.dylib             	    0x7ff8001457ef _dispatch_lane_invoke + 400
11  libdispatch.dylib             	    0x7ff800152475 _dispatch_workloop_worker_thread + 873
12  libsystem_pthread.dylib       	    0x7ff837749c55 _pthread_wqthread + 327
13  libsystem_pthread.dylib       	    0x7ff837748bbf start_wqthread + 15


Below are the dependencies.

 "@react-native-community/slider": "^4.4.2",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "babel": "^6.23.0",
    "base64-js": "^1.5.1",
    "buffer": "^6.0.3",
    "react": "^18.2.0",
    "react-native": "^0.71.7",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-reanimated": "^3.5.0-nightly-20230909-073b64568",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.25.0",
    "react-native-size-matters": "^0.4.0",
    "react-native-udp": "^4.1.7",
    "react-native-vector-icons": "^10.0.0",
    "react-native-wifi-reborn": "^4.7.0",
    "upgrade": "^1.1.0"

**Comment by Ahmed-Imam** [comment] 2023-09-11 15:18
any update on this ?? still getting the issue on 
```
    "react-native-gesture-handler": "^2.12.1",
    "react-native-reanimated": "^3.3.0",
    "react-native-reanimated-carousel": "^3.5.1",
     "react-native": "0.69.4",

```

**Comment by Ahmed-Imam** [comment] 2023-09-11 15:22
@piaskowyk have you found a solution for this issue? If you could share the solution or the PR, we could apply a patch until it's officially released

**Comment by piaskowyk** [comment] 2023-09-11 18:41
Today we released version that contains the fix, you should update your Reanimated to 3.5.0

**Comment by Inayat567** [comment] 2024-07-21 05:35
Still I am getting same issue
Tried all above solutions => nothing work for me 🥲

app crashing when I replace or reset navigation 

code :
          navigation.replace(screens.BottomTab, {
                screen: screens.Home,
              });
              
or 

      navigation.reset({
          routes: [{name: screens.SignIn}],
          index: 0,
        });

 "react-native": "0.73.6",
 "react-native-reanimated": "3.9.0",
 "react-native-screens": "^3.29.0",
 
 
 
 Thanks for help in Advance!

**Comment by elangovansword** [comment] 2024-09-16 14:52
> > Still I am getting same issue Tried all above solutions => nothing work for me 🥲
> > app crashing when I replace or reset navigation
> > code :
> > ```
> >       navigation.replace(screens.BottomTab, {
> >             screen: screens.Home,
> >           });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```
> >   navigation.reset({
> >       routes: [{name: screens.SignIn}],
> >       index: 0,
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > "react-native": "0.73.6", "react-native-reanimated": "3.9.0", "react-native-screens": "^3.29.0",
> > Thanks for help in Advance!
> 
> Need help please I am also facing same situation

In my case 'event-emitter' is caused the issue, Without event emitter observers it is working.
