### ISSUE TITLE
Execution failed for task ':react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a]

### ISSUE THREAD

**Issue by s1tony** [software-mansion/react-native-reanimated#6718] opened 2024-11-17 19:19 UTC
### Description

While performing Release Build of my React Native App, I receive the following exception (note, Debug build works):

* What went wrong:
Execution failed for task ':react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `K:\Source\collections-source\Collections\node_modules\react-native-reanimated\android\.cxx\RelWithDebInfo\1y5e2947\armeabi-v7a'
  [0/2] Re-checking globbed directories...
  [1/37] Building CXX object src/main/cpp/worklets/CMakeFiles/worklets.dir/8d227a0f38aeddc6df1e837bbfea0aa8/Common/cpp/worklets/Tools/JSLogger.cpp.o
  [2/37] Building CXX object src/main/cpp/worklets/CMakeFiles/worklets.dir/541c11f770471cf339ab8fba0254f9a2/cpp/worklets/Tools/ReanimatedVersion.cpp.o
  [3/37] Building CXX object src/main/cpp/worklets/CMakeFiles/worklets.dir/5dd35182adbe3968ab437dcaf80f2671/WorkletRuntime/ReanimatedRuntime.cpp.o
  ninja: build stopped: .

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\Tony\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "K:\\Source\\collections-source\\Collections\\node_modules\\react-native-reanimated\\android\\.cxx\\RelWithDebInfo\\1y5e2947\\armeabi-v7a" ^
        reanimated ^
        worklets
    from K:\Source\collections-source\Collections\node_modules\react-native-reanimated\android
  ninja: error: mkdir(src/main/cpp/reanimated/CMakeFiles/reanimated.dir/K_/Source/collections-source/Collections/node_modules/react-native-reanimated/Common): No such file or directory

### Steps to reproduce

1. npm start -- --reset-cache
2. npm run android-coin-release

### Snack or a link to a repository

https://github.com/s1tony/Collections2

### Reanimated version

3.16.1

### React Native version

0.76.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

Samsung S22

### Acknowledgements

Yes

**Comment by tjzel** [comment] 2024-11-20 13:08
Hi @s1tony, can you check if a clean rebuild the project in Android Studio helps? This might be a cache issue.

**Comment by s1tony** [comment] 2024-11-20 15:03
Hi @tjzel, I build from the command line, not with Android Studio, and this is what I have tried:

npm start -- --reset-cache
./gradlew clean (In android dir)


Same result:

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\Tony\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "K:\\Source\\collections-source\\Collections\\node_modules\\react-native-reanimated\\android\\.cxx\\RelWithDebInfo\\1y5e2947\\armeabi-v7a" ^
        reanimated ^
        worklets
    from K:\Source\collections-source\Collections\node_modules\react-native-reanimated\android
  ninja: error: mkdir(src/main/cpp/reanimated/CMakeFiles/reanimated.dir/K_/Source/collections-source/Collections/node_modules/react-native-reanimated/Common): No such file or directory

**Comment by tjzel** [comment] 2024-11-21 07:48
`./gradlew clean` is not exactly a full clean. Sometimes I have to do `git clean -Xdf` because `./gradlew clean` fails to execute.

> src/main/cpp/reanimated/CMakeFiles/reanimated.dir/K_/Source/collections-source/Collections/node_modules/react-native-reanimated/Common
This is indeed a very weird path. Unfortunately I'm not familiar with the quirks of building React Native on Windows.

You can try ` ./gradlew --console verbose --no-build-cache -d assembleDebug` to get more compilation logs.

**Comment by s1tony** [comment] 2024-11-21 13:29
I even tried to delete and reinstall node_modules, but to no avail.

**Comment by tjzel** [comment] 2024-11-21 14:00
I was just looking into it @2004durgesh, it seems to be that since we get on CI:

<img width="392" alt="Screenshot 2024-11-21 at 15 00 17" src="https://github.com/user-attachments/assets/633ee5df-6b63-4ce4-bbe8-51814a0818c2">

Good catch!

**Comment by tjzel** [comment] 2024-11-22 16:55
I managed to get the same issue on our CI 🥳 

https://github.com/software-mansion/react-native-reanimated/actions/runs/11976521423/job/33392382262

**Comment by 2004durgesh** [comment] 2024-12-07 13:44
@tjzel sorry for tagging you , but any progress or work around
Thanks

**Comment by tjzel** [comment] 2024-12-09 09:45
@2004durgesh The only workaround that would work is shortening the paths I think. We're waiting for the fix in React Native.

**Comment by bondarenkod** [comment] 2024-12-09 10:10
Copy of my comment from the already closed as duplicate issue:

1. Check for the libraries versions:
`"react-native-reanimated": "3.16.3"`
` "realm": "^12.14.0", // I have it, it requires some kind old ndk version, so I decided to bump its version`
 
 2. Install cmake 3.31.0 via Android Studio. And only this version. I've removed all the rest of cmake versions.  
 3. Remove all the ndk except the last version one, install the latest version.  // again, it could be related to the realm which I have in use
 4. Enable long path on windows, reboot: ``` New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force ```
 5. execute in the project from the root path: `git clean -xfd && git submodule foreach --recursive git clean -xfd`
 6. in the same terminal window execute:
 6.1 `$Env:CMAKE_VERSION = '3.31.0'`
 6.2 `yarn react-native build-android --mode Release`
 
 
<img width="577" alt="image" src="https://github.com/user-attachments/assets/3f8385d8-ea39-4a5b-8edc-0850ba866ce2">


It seems like helped me.

**Comment by 2004durgesh** [comment] 2024-12-09 13:54
@tjzel thanks for mentioning this out, and @bondarenkod appreciate the info! It works perfectly. The only tweak I had to make was updating `android/gradle.properties` by adding:

```
android.abbis=arm64-v8a,x86,x86_64  
reactNativeArchitectures=arm64-v8a,x86,x86_64  
```

and removing `armeabi-v7a`, as the build was failing specifically for that architecture. Everything else cleared without issues. 🚀

**Comment by tjzel** [comment] 2024-12-13 11:48
Since our [CI started to pass](https://github.com/software-mansion/react-native-reanimated/actions/runs/12303585746/job/34339024152) I think it's fixed on the newest release of React Native 0.76.5 and no workarounds are needed.

Could you please confirm @s1tony @2004durgesh @bondarenkod?

**Comment by 2004durgesh** [comment] 2024-12-13 12:14
Yup, it works 👍

**Comment by Bosseskompis** [comment] 2024-12-13 12:24
Is there a planned fix to address this issue for users on older versions, or is it recommended to rely on the provided workaround?

**Comment by tjzel** [comment] 2024-12-13 12:46
@Bosseskompis WDYM? I assume this regression was made in React Native 0.76 so it doesn't affect older versions.

**Closed by tjzel** 2024-12-13 12:46 UTC
Labels: Platform: Android, Repro provided

**Comment by Bosseskompis** [comment] 2024-12-13 13:14
Strangely, I'm seeing this error on 0.73.6

**Comment by 2004durgesh** [comment] 2024-12-13 13:43
@Bosseskompis what is the version of Reanimated you are using?  
Make sure you follow this [Compatibility Guide](https://docs.swmansion.com/react-native-reanimated/docs/guides/compatibility).  

Also, are you using **bare React Native** or **Expo with Dev Client**?  

Try doing this: [Issue Comment](https://github.com/software-mansion/react-native-reanimated/issues/6718#issuecomment-2528019529) (just my above reply 😋)

**Comment by Mahmoudkhoder01** [comment] 2024-12-26 19:14
I had the same issue, tried everything, this is my dependencies below:
`"dependencies": {
    "@expo/vector-icons": "^14.0.3",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-navigation/native": "^7.0.0",
    "axios": "^1.7.7",
    "expo": "^52.0.23",
    "expo-constants": "~17.0.3",
    "expo-font": "~13.0.1",
    "expo-linear-gradient": "~14.0.1",
    "expo-linking": "~7.0.3",
    "expo-router": "~4.0.11",
    "expo-secure-store": "~14.0.0",
    "expo-splash-screen": "~0.29.16",
    "expo-status-bar": "~2.0.0",
    "expo-system-ui": "~4.0.5",
    "expo-updates": "~0.26.10",
    "expo-web-browser": "~14.0.1",
    "i18n-js": "^4.4.3",
    "mobx": "^6.13.3",
    "mobx-react": "^9.1.1",
    "moti": "^0.29.0",
    "nativewind": "^2.0.11",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.5",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-keyboard-controller": "^1.14.0",
    "react-native-reanimated": "^3.16.6",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.4.0",
    "react-native-toast-message": "^2.2.1",
    "react-native-web": "~0.19.13",
    "styled-components": "^4.4.1"
  },`

**Comment by s1tony** [comment] 2025-01-05 18:17
I am in tears, as I just tried a Release build with React Native 0.76.5 and React Native Reanimated 3.16.6.  It failed with the same error:

        "K:\\Source\\collections-source\\Collections2\\node_modules\\react-native-reanimated\\android\\.cxx\\RelWithDebInfo\\1n216o13\\armeabi-v7a" ^
        reanimated ^
        worklets
    from K:\Source\collections-source\Collections2\node_modules\react-native-reanimated\android
  ninja: error: mkdir(src/main/cpp/reanimated/CMakeFiles/reanimated.dir/K_/Source/collections-source/Collections2/node_modules/react-native-reanimated/Common): No such file or directory

**Comment by josegiufrida** [comment] 2025-01-06 13:50
I was able to solve this problem by using a shorter directory.
**But using a [Directory Junction](https://superuser.com/a/343079), to avoid moving my entire project.**

Open a CMD (as Administrator) and type:
`mklink /J "C:\shorter-path" "C:\your-very-long-project-path"`

Now run your build command from that path:
```
cd C:\shorter-path
npm run build
```

This is the simplest solution I found.

**Comment by s1tony** [comment] 2025-01-06 13:59
I copied my project to a new directory path with one letter and it built successfully!  I am going to try the Directory Junction also - thanks for the tip @josegiufrida.

**Comment by s1tony** [comment] 2025-01-06 15:20
Alas, the Directory Junction did not work for me, but copying my project to a shorter directory path did work.

**Comment by shreysaroch** [comment] 2025-01-10 18:41
I'm facing this issue on mac with 0.75.1 rn version and 3.15.5 react-native-reanimated

**Comment by matheuscostadesign** [comment] 2025-01-28 12:13
Apparently, the issue occurs because the project is inside a folder named "React," for example: `C:\Development\React\my-app\...`

When moving the project to a folder that does not contain the word "React" (e.g., `C:\Development\my-app\...)`, the application compiled and worked normally.

This issue occurs with the React Native Reanimated library.

Even after updating the package to the latest version (`3.16.7`), the problem persists.

The current solution is to move the project to a folder without the word "React" or to a shorter path (e.g., `C:\my-app`), as many suggest this also resolves the issue.

**Comment by zpzxgcr** [comment] 2025-02-25 05:56
> `./gradlew clean`在处理 React Native 时，并不是完全彻底的清理。有时我不得不这样做，`git clean -Xdf`因为`./gradlew clean`执行失败。
> 
> > src/main/cpp/reanimated/CMakeFiles/reanimated.dir/K_/Source/collections-source/Collections/node_modules/react-native-reanimated/Common
> 
> 这确实是一条非常奇怪的路径。不幸的是，我不熟悉在 Windows 上构建 React Native 的怪癖。
> 
> 您可以尝试` ./gradlew --console verbose --no-build-cache -d assembleDebug`获取更多的编译日志。

nice

**Comment by tomleejumah** [comment] 2025-03-11 10:46
> Strangely, I'm seeing this error on 0.73.6

me too on .76.1

**Comment by tjzel** [comment] 2025-03-11 13:04
You can see our troubleshooting guide for building on Windows https://docs.swmansion.com/react-native-reanimated/docs/guides/building-on-windows/

**Comment by tomleejumah** [comment] 2025-03-16 08:02
im now getting error Cannot read properties of undefined (reading 'handle').
TypeError: Cannot read properties of undefined (reading 'handle')
after the update 
here is my package.json 

 "dependencies": {
    "@emotion/react": "^11.13.3",
    "@emotion/styled": "^11.13.0",
    "@fortawesome/free-solid-svg-icons": "^6.6.0",
    "@fortawesome/react-fontawesome": "^0.2.2",
    "@react-native-async-storage/async-storage": "^2.0.0",
    "@react-native-firebase/app": "^21.4.1",
    "@react-native-firebase/messaging": "^21.4.1",
    "@react-native-segmented-control/segmented-control": "^2.5.6",
    "@react-navigation/bottom-tabs": "^7.0.3",
    "@react-navigation/native": "^7.0.2",
    "@react-navigation/native-stack": "^7.0.2",
    "@react-navigation/stack": "^7.0.2",
    "axios": "^1.7.7",
    "moment": "^2.30.1",
    "react": "18.3.1",
    "react-native": "0.76.5",
    "react-native-gesture-handler": "^2.21.0",
    "react-native-ionicons": "^4.6.5",
    "react-native-paper": "^5.12.5",
    "react-native-permissions": "^5.1.0",
    "react-native-push-notification": "^8.1.1",
    "react-native-safe-area-context": "^4.14.0",
    "react-native-screens": "^4.1.0",
    "react-native-svg": "^15.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.3",
    "@babel/runtime": "^7.25.0",
    "@react-native-community/cli": "latest",
    "@react-native-community/cli-platform-android": "15.0.0",
    "@react-native-community/cli-platform-ios": "15.0.0",
    "@react-native/babel-preset": "0.76.1",
    "@react-native/eslint-config": "0.76.1",
    "@react-native/metro-config": "0.76.1",
    "@react-native/typescript-config": "0.76.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "connect": "^3.7.0",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }

**Comment by cw-nikhilnaik** [comment] 2025-03-19 06:10
facing same issue on RN 0.77.1

**Comment by tomleejumah** [comment] 2025-03-19 07:36
> facing same issue on RN 0.77.1

fixed by updating metro to :
"metro": "^0.82.0",
    "metro-config": "^0.82.0",
    "metro-core": "^0.82.0",
    "metro-react-native-babel-preset": "^0.77.0",

then switched to RN 0.76.7

those versions are stable

**Comment by cw-nikhilnaik** [comment] 2025-05-25 14:03
> Copy of my comment from the already closed as duplicate issue:
> 
> 1. Check for the libraries versions:
>    `"react-native-reanimated": "3.16.3"`
>    ` "realm": "^12.14.0", // I have it, it requires some kind old ndk version, so I decided to bump its version`
> 2. Install cmake 3.31.0 via Android Studio. And only this version. I've removed all the rest of cmake versions.
> 3. Remove all the ndk except the last version one, install the latest version.  // again, it could be related to the realm which I have in use
> 4. Enable long path on windows, reboot: `New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force`
> 5. execute in the project from the root path: `git clean -xfd && git submodule foreach --recursive git clean -xfd`
> 6. in the same terminal window execute:
>    6.1 `$Env:CMAKE_VERSION = '3.31.0'` // globalb env var could work as well according to the [Task :react-native-reanimated:buildCMakeRelWithDebInfo[arm64-v8a] FAILED during assembleRelease #6661 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/6661#issuecomment-2517193808)
>    6.2 `yarn react-native build-android --mode Release`
> 
> <img alt="image" width="577" src="https://private-user-images.githubusercontent.com/3184414/391966828-3f8385d8-ea39-4a5b-8edc-0850ba866ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDgxODE5NDUsIm5iZiI6MTc0ODE4MTY0NSwicGF0aCI6Ii8zMTg0NDE0LzM5MTk2NjgyOC0zZjgzODVkOC1lYTM5LTRhNWItOGVkYy0wODUwYmE4NjZjZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MjVUMTQwMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNmNjY0Y2NjOTFiZTk5ODEzZDU3N2I5NjhjNWQ1MDFiZGJhM2MwYzI2M2MyMGY5ZDAwY2U4NzBlNjk2ZWJkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.K3xXXQfELG0c0kTr-0nRxtomi8rgXoDutxTrr6kW6hQ">
> It seems like helped me.

cmake 3.31.0 fixed my problem
