### ISSUE TITLE
react-native-reanimated:downloadBoost downloads boost_1_76_0.tar.gz file everytime i run the app. 

### ISSUE THREAD

**Issue by sbalajime** [software-mansion/react-native-reanimated#3638] opened 2022-10-03 09:11 UTC
### Description

My react-native version is 0.70.1. I have installed react-native-reanimated v.2.10.0 . Whenever i run the app in android, the downloadBoost process takes few minutes to download the boost_1_76_0.tar.gz file which is more than 120+MB. This happens both in debug mode and release mode. Is this supposed to run everytime? or have i missed some configuration during installation?
![Screenshot 2022-10-03 at 2 26 27 PM](https://user-images.githubusercontent.com/7464278/193540027-95a55104-b8c4-4ab6-bf6f-ab7a21faa784.png)

### Steps to reproduce

The file download starts whenever i run `react-native run-android` or `gradlew assembleRelease`.

### Snack or a link to a repository

Nill

### Reanimated version

2.10.0

### React Native version

0.70.1

### Platforms

Android

### Workflow

React Native (without Expo)

### Device

Android emulator

### Device model

Android Emulator (Android 11)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2022-10-03 13:48
Duplicate of #3523, will be fixed in #3602.

**Comment by dilipchandima** [comment] 2022-10-18 08:08
This file is not available now - https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
failing the build by a timeout

**Comment by ChenTianSaber** [comment] 2022-10-18 08:28
> 

same

**Comment by vitalyiegorov** [comment] 2022-10-18 08:30
same

**Comment by fanzhiri** [comment] 2022-10-18 10:58
same

**Comment by tomekzaw** [comment] 2022-10-18 11:01
Duplicate of #3523, fixed in #3602 and released in 2.11.0.

**Closed by tomekzaw** 2022-10-18 11:01 UTC
Labels: Platform: Android

**Comment by varshith5c** [comment] 2023-06-26 06:07
I am still facing this issue. Any solutions would be helpful. @tomekzaw 
https://github.com/software-mansion/react-native-reanimated/pull/3602#issuecomment-1606704523

**Comment by MohammedKarman80** [comment] 2023-07-23 17:34
same issue

**Comment by slash006** [comment] 2023-12-31 12:46
Hi there, 
I have a similar issue with building the application - it seems that the resource at the link https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz is unavailable.
