### ISSUE TITLE
Unexpected token: operator (=)

### ISSUE THREAD

**Issue by fatihhidiroglu** [software-mansion/react-native-reanimated#4872] opened 2023-08-03 09:07 UTC
### Description

When I want to buy bundle on Android and IOS, I get the following error.
My version react-native-reanimated is 3.4.0

`error node_modules/react-native-reanimated/src/reanimated2/animation/util.ts: Unexpected token: operator (=) in file node_modules/react-native-reanimated/src/reanimated2/animation/util.ts at 153:21.
`

Code with error

    animation.current =
           (animation.__prefix ?? '') +
           animation.current +
           (animation.__suffix ?? '');

### Steps to reproduce

1. Package installed ver yarn install done.
2. `"npx react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ./ios/main.jsbundle"`
command is executed.
3. Finally i can't get bundle and i get react-native-reanimated '**Unexpected token: operator**' error.

### Snack or a link to a repository

-

### Reanimated version

3.4.0

### React Native version

0.70.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Latropos** [comment] 2023-08-04 07:45
Duplicate of https://github.com/software-mansion/react-native-reanimated/issues/4825

**Comment by Latropos** [comment] 2023-08-04 07:48
This bug is already solved, however the fix will only be available in next release, please try this fix: https://github.com/facebook/react-native/issues/31704#issuecomment-859199856, or downgrade `react-natvie-reanimated`.

**Closed** 2023-08-04 08:34 UTC
Labels: Missing repro, Platform: Android, Platform: iOS, Needs review, Missing info
