### ISSUE TITLE
Debug Mode is not working : Failed to print error:  Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by Akilramki** [software-mansion/react-native-reanimated#4263] opened 2023-03-23 10:07 UTC
### Description

While Debug the App

console.assert is not a function

RCTFatal
-[RCTCxxBridge handleError:]
__21-[RCTCxxBridge start]_block_invoke
invocation function for block in facebook::react::(anonymous namespace)::RCTObjcExecutor::RCTObjcExecutor(id<RCTJavaScriptExecutor>, void (NSError*) block_pointer, std::__1::shared_ptr<facebook::react::MessageQueueThread>, std::__1<facebook::react::ExecutorDelegate>)
__58-[RCTWebSocketExecutor _executeJSCall:arguments:callback:]_block_invoke
-[RCTWebSocketExecutor webSocket:didReceiveMessage:]
__33-[RCTSRWebSocket _handleMessage:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
![simulator_screenshot_EF15469B-D9C0-48AD-A9EA-A15A9DE66451](https://user-images.githubusercontent.com/105835418/227169508-9fdcb8b5-105d-43f5-a99a-39a606995831.png)

_pthread_wqthread
start_wqthread

### Steps to reproduce

Error:
1.console.assert is not a function 
2.Failed to print error:  Cannot read properties of undefined (reading 'apply')

### Snack or a link to a repository

https://stackoverflow.com/questions/75689543/starting-debugger-error-console-assert-is-not-a-function

### Reanimated version

^3.0.2

### React Native version

0.71.4

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements
![e6j9D](https://user-images.githubusercontent.com/105835418/227170758-5a9c2178-a1d4-4c00-80f9-e0e219d7b9a8.png)

Yes

**Comment by JerakRus** [comment] 2023-03-27 10:26
https://github.com/software-mansion/react-native-reanimated/issues/3951

**Comment by Latropos** [comment] 2023-09-22 07:49
Closing as a duplicate of #3951

**Closed by Latropos** 2023-09-22 07:49 UTC
Labels: Missing repro, Platform: Android, Platform: iOS, Needs review
