### ISSUE TITLE
Error: Unable to resolve module ./reanimated1 from node_modules/react-native-reanimated/src/Animated.js

### ISSUE THREAD

**Issue by nithiniLeaf** [software-mansion/react-native-reanimated#2686] opened 2021-12-03 09:57 UTC
Need to fix this issue in which this file is invisible ./reanimated1.

## Package versions

"react": "17.0.2",
"react-native": "0.66.3",
"react-native-reanimated": "^1.13.3",

## Affected platforms

- [x] Android
- [x] iOS
- [x] Web

**Comment by piaskowyk** [comment] 2021-12-07 18:41
Duplicate of https://github.com/software-mansion/react-native-reanimated/issues/2687

**Closed by piaskowyk** 2021-12-07 18:41 UTC
Labels: 🐞 Bug, 🏠  Reanimated2
