### ISSUE TITLE
React Native 0.71.0 - Failed to print error:  Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by rililive** [software-mansion/react-native-reanimated#3951] opened 2023-01-16 01:55 UTC
### Description

console object missing `assert` and other methods. This causes the debugger to break. Can no longer to make websocket connections or hot module reload while developing.

### Steps to reproduce

1. Upgrade to react-native@0.71.0
2. Install `"react-native-reanimated": "3.0.0-rc.10",`
3. Run app in ios simulator

### Snack or a link to a repository

[https://github.com/rili-live/therr-app/tree/main/TherrMobile](https://github.com/rili-live/therr-app/tree/main/TherrMobile)

### Reanimated version

3.0.0-rc.10

### React Native version

0.71.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by rililive** [comment] 2023-01-16 15:35
I have created the following patch and the issue seems to be solved for development.

```
diff --git a/node_modules/react-native-reanimated/lib/module/reanimated2/initializers.js b/node_modules/react-native-reanimated/lib/module/reanimated2/initializers.js
index 591a763..e3f72a2 100644
--- a/node_modules/react-native-reanimated/lib/module/reanimated2/initializers.js
+++ b/node_modules/react-native-reanimated/lib/module/reanimated2/initializers.js
@@ -104,6 +104,7 @@ export function initializeUIRuntime() {
     // @ts-ignore TypeScript doesn't like that there are missing methods in console object, but we don't provide all the methods for the UI runtime console version
 
     global.console = {
+      assert: runOnJS(capturableConsole.assert),
       debug: runOnJS(capturableConsole.debug),
       log: runOnJS(capturableConsole.log),
       warn: runOnJS(capturableConsole.warn),
diff --git a/node_modules/react-native-reanimated/src/reanimated2/initializers.ts b/node_modules/react-native-reanimated/src/reanimated2/initializers.ts
index 9b7efdb..a0f88ee 100644
--- a/node_modules/react-native-reanimated/src/reanimated2/initializers.ts
+++ b/node_modules/react-native-reanimated/src/reanimated2/initializers.ts
@@ -106,6 +106,7 @@ export function initializeUIRuntime() {
     // setup console
     // @ts-ignore TypeScript doesn't like that there are missing methods in console object, but we don't provide all the methods for the UI runtime console version
     global.console = {
+      assert: runOnJS(capturableConsole.assert),
       debug: runOnJS(capturableConsole.debug),
       log: runOnJS(capturableConsole.log),
       warn: runOnJS(capturableConsole.warn),

```

**Comment by tomekzaw** [comment] 2023-01-18 11:23
Thanks @rililive for the patch, can you please submit a PR with this change?

**Comment by GeorgeNiotis** [comment] 2023-03-07 20:13
same here

**Comment by lid3rs** [comment] 2023-03-12 16:40
Verifying, after adding missing "assert" problem was solved.

**Comment by rrebelo1** [comment] 2023-03-15 09:57
Hello, Thanks for the fix @rililive.
Please can you provide a patch to the project maintainers? @rililive 
Or are any plans to release this soon?
Thanks

**Comment by rrebelo1** [comment] 2023-03-15 11:17
We are still facing this issue even when we apply the patch.
We actually don't see the error but out app becomes unusable and we can't print AsyncStorage for example.
Is there any plans to have a fix for this?

**Comment by lid3rs** [comment] 2023-03-15 11:32
> 

Are u sure it's related, have no such problems.

**Comment by clementnv** [comment] 2023-03-15 22:33
I have the same problem with react-native 0.71.4 and react-native-reanimated 3.0.2

**Comment by ManjodhSaran** [comment] 2023-03-16 05:55
> Verifying, after adding missing "assert" problem was solved.

how to do this ?

**Comment by ManjodhSaran** [comment] 2023-03-16 05:56
> I have the same problem with `react-native 0.71.4` and r`eact-native-reanimated 3.0.2` when **Debug with Chrome** is activated.

react-native-reanimated is causing lot of issues

**Comment by ManjodhSaran** [comment] 2023-03-16 06:05
`react-native-reanimated: "^2.14.4"` shifted to this version will solve your problem
  **Worked for me**
  
```
  rm -rf node_modules/
  rm -rf yarn.lock
  yarn
  yarn start --reset-cache
  yarn ios // yarn android
```

**Comment by DanielGannage** [comment] 2023-03-16 21:03
@ManjodhSaran This does not work on both IOS/Android in Mac/Windows respectively. I have tried deleting those folders/files you have mentioned. I have tried for both 2.14.4 and 3.0.2 versions of reanimated and i still cannot get the chrome debugger to work - it will crash whenever i click 'debug' in the developer menu. RN 0.71.4

**Comment by ManjodhSaran** [comment] 2023-03-17 06:34
> @ManjodhSaran This does not work on both IOS/Android in Mac/Windows respectively. I have tried deleting those folders/files you have mentioned. I have tried for both 2.14.4 and 3.0.2 versions of reanimated and i still cannot get the chrome debugger to work - it will crash whenever i click 'debug' in the developer menu. RN 0.71.4

this is not debugger solution,
As newer version of `react-native-animated ` cause unexpected errors.

**Comment by mohamedshrif995** [comment] 2023-03-22 15:20
react-native-reanimated: "^2.14.4" shifted to this version will solve your problem
 use this version and
1-yarn
2-cd ios 
3-pod install 
4-cd ..
5- yarn start --reset-cache (it is very important step)
6-make sure you close the bundler and close app 
7-run new build from xcode

**Comment by parthjdabhi** [comment] 2023-03-23 04:01
@mohamedshrif995 Yeah this is already running fine, Do you know what is an issue with latest v3.0 ??

**Closed** 2023-04-18 16:07 UTC
Labels: Missing repro, Platform: iOS, Needs review

**Comment by mingcnjs** [comment] 2023-04-21 08:27
Still facing the same issue on 0.71.6 with 3.1.0

**Comment by HARSHVDARJI** [comment] 2023-04-21 08:42
> `react-native-reanimated: "^2.14.4"` shifted to this version will solve your problem **Worked for me** **_TESTED_**
> 
> ```
>   rm -rf node_modules/
>   rm -rf yarn.lock
>   yarn
>   yarn start --reset-cache
>   yarn ios // yarn android
> ```

WORKING FOR ME

**Comment by valery-lavrik** [comment] 2023-05-10 12:01
> `react-native-reanimated: "^2.14.4"` shifted to this version will solve your problem **Worked for me** **_TESTED_**
> 
> ```
>   rm -rf node_modules/
>   rm -rf yarn.lock
>   yarn
>   yarn start --reset-cache
>   yarn ios // yarn android
> ```

This option does not suit me because other libraries need the latest version of react-native-reanimated.

Are there any other options?

**Comment by mohamedshrif995** [comment] 2023-05-16 12:04
> @mohamedshrif995 Yeah **2.14.4** is already running fine. @ManjodhSaran already mentioned this in comment before, but do you know what is an issue with latest v3.0.2 ??

it work now with last version

**Comment by valery-lavrik** [comment] 2023-05-17 05:12
> > @mohamedshrif995 Yeah **2.14.4** is already running fine. @ManjodhSaran already mentioned this in comment before, but do you know what is an issue with latest v3.0.2 ??
> 
> it work now with last version

It only works with the disabled debug mode. Try to turn on the debug mode and reproduce any error

**Comment by piaskowyk** [comment] 2023-05-17 12:20
What do you mean with `disabled debug mode`? You mean JS bundle or application build?

**Comment by valery-lavrik** [comment] 2023-05-17 13:01
> What do you mean with `disabled debug mode`? You mean JS bundle or application build?

I mean press D in the terminal and select "enable debugging"

**Comment by piaskowyk** [comment] 2023-05-18 14:58
Did you try to use Flipper instead?

**Comment by piaskowyk** [comment] 2023-05-18 15:08
I have tried on iOS emulator.

**Comment by valery-lavrik** [comment] 2023-05-18 15:10
> I have tried on iOS emulator.

I have a problem reproducing on android

**Comment by piaskowyk** [comment] 2023-05-18 16:02
Ok, I reproduced this error on Android. Here is the fix: https://github.com/software-mansion/react-native-reanimated/pull/4474 - works for me 🎉

**Comment by onmotion** [comment] 2023-05-18 16:12
I think the cause is that we redefine global console object with `runOnJs` but RNDebugger (Chrome) is using the same in js context
```js
global.console = {
      assert: runOnJS(capturableConsole.assert),
      debug: runOnJS(capturableConsole.debug),
      ...
```

I have no idea how does it work under the hood, but is it possible to use your own kinda `jsConsole` instead of redefine global object?

**Comment by onmotion** [comment] 2023-05-18 16:15
> Ok, I reproduced this error on Android. Here is the fix: #4474 - works for me 🎉

wow you fixed the issue while I was writing my message :) thanks!

**Comment by valery-lavrik** [comment] 2023-05-18 17:37
> Ok, I reproduced this error on Android. Here is the fix: #4474 - works for me 🎉

Thank you very much!  I've been struggling with this for a long time.  When can I expect a release with a fix?

**Comment by bobbyrinaldy** [comment] 2023-05-19 08:43
@piaskowyk so, what version do i need to use to apply the chrome debugger on Android for now ? the Main branch ?

**Comment by piaskowyk** [comment] 2023-05-19 10:29
Yes, installing the main branch is the best option, but you can just create a local patch-package file also.

**Comment by bobbyrinaldy** [comment] 2023-05-19 10:38
still facing the issues when i tried to use the main branch [here](https://github.com/software-mansion/react-native-reanimated/pull/4474#issuecomment-1554262633)

1. remove the current version by `yarn remove react-native-reanimated`
2. update the `package.json` like below
```
{
...
"react-native-reanimated": "https://github.com/software-mansion/react-native-reanimated.git",
...
}
```
3. do `yarn install`
4. re run `yarn android`
5. turn on `Debug` on android simulator
6. Got error when reloading
![image](https://github.com/software-mansion/react-native-reanimated/assets/27556560/c64d8275-4481-484c-adc4-3f24fa64d58b)

idk if this the same error or no

**Comment by piaskowyk** [comment] 2023-05-19 12:03
just to be sure try to clear metro cache - `yarn start --reset-cache`
