### ISSUE TITLE
web: useAnimatedGestureHandler not working

### ISSUE THREAD

**Issue by hosseinmd** [software-mansion/react-native-reanimated#1406] opened 2020-11-02 12:13 UTC
## Description
That is working on android, but on the web the gesture event is not called

## Steps To Reproduce

1.
```js
const gestureHandler = useAnimatedGestureHandler(
      {
        onStart: (_, ctx: any) => {
          //notCalled
        },
        onActive: (event, ctx) => {
          //notCalled
        },
        onEnd: (_) => {
          //notCalled
        },
      },
      [],
    );
```
## Package versions

- React: 17.0.1
- React Native: 0.63.1
- React Native Reanimated: 2.0.0-alpha.8
- React Native Gesture Handler: 1.8.0
- NodeJS: 12

**Comment by terrysahaidak** [comment] 2020-11-02 12:37
Hi! Could you please provide reproducing repository?

**Comment by hosseinmd** [comment] 2020-11-02 15:01
In the repo, I added the gesture handler to blue box and logged into the event but nothings logged.
https://github.com/hosseinmd/test-reanimated2

**Comment by hosseinmd** [comment] 2020-11-02 15:08
This pull request is related to the web, but not directly to this bug.
https://github.com/software-mansion/react-native-gesture-handler/pull/1220
https://github.com/software-mansion/react-native-reanimated/pull/1378
https://github.com/software-mansion/react-native-reanimated/pull/1402

**Comment by karol-bisztyga** [comment] 2020-11-04 08:52
Hey!
Indeed it does not work in your case, I think the problem might be that you haven't enabled reanimated's babel plugin as stated [in the docs](https://docs.swmansion.com/react-native-reanimated/docs/installation#babel-plugin). [The tool you're using](https://github.com/facebook/create-react-app#get-started-immediately) apparently hides babel configuration.

So my guess is that you'd probably need to do `yarn eject` and then add it manually(I got an error doing `yarn eject` in my local environment but decided to not spend more time on this as it's unrelated - web works fine for other tools designed for creating RN app - check [the playground](https://github.com/software-mansion-labs/reanimated-2-playground)).

**Comment by hosseinmd** [comment] 2020-11-04 09:07
I added the babel plugin in config-override.

**Comment by hosseinmd** [comment] 2020-11-04 09:52
The playground has packages versions that are not updated.
I update packages in this PR https://github.com/software-mansion-labs/reanimated-2-playground/pull/23
Now useAnimatedGestureHandler not working

**Comment by karol-bisztyga** [comment] 2020-11-04 11:13
> The playground has packages versions that are not updated.
> I update packages in this PR [software-mansion-labs/reanimated-2-playground#23](https://github.com/software-mansion-labs/reanimated-2-playground/pull/23)
> Now useAnimatedGestureHandler not working

There's a [known bug in RNGH](https://github.com/software-mansion/react-native-gesture-handler/issues/1164#issuecomment-684013868) and as the issue is still open I assume it's not been fixed by now. So for know please just leave `react-native-web` as it is(as well as `react-dom` - otherwise you'll end up with errors).

**Comment by karol-bisztyga** [comment] 2020-11-04 11:24
After doing the following changes in your repo, it works:
```
"react-dom": "^16.13.1",
"react-native-web": "^0.12.3",
"react-native-gesture-handler": "1.8.0",
```

**Comment by hosseinmd** [comment] 2020-11-04 11:36
Because of pressable and modal in react-native-web 0.14 we can't downgrade to 0.12. we need another solution.

**Comment by karol-bisztyga** [comment] 2020-11-04 11:45
I understand but this is a problem with RNGH, not reanimated.

**Comment by ElForastero** [comment] 2020-11-28 19:35
The issue in RNGH was fixed, but handler still doesn't work on web.

**Comment by ElForastero** [comment] 2020-11-28 20:49
@karol-bisztyga 

Well, I finally made it working on both iOS and Web by manually defining handlers for PanGestureHandler.

`useAnimatedGestureHandler` works well in native but seems like does absolutely nothing in web environment. Spend a while trying to understand the source of the problem, but with no success.

```ts
  const y = useSharedValue(0);
  const startY = useSharedValue(0);

  const gestureHandler = ({ nativeEvent: e }) => {
    'worklet';
    if (e.state === State.ACTIVE) {
      console.log('active');
      y.value = startY.value + e.translationY;
    }
  };

  const gestureStateHandler = ({ nativeEvent: e }) => {
    'worklet';
    if (e.state === State.BEGAN) {
      console.log('began');
      startY.value = y.value;
    }

    if (e.state === State.END) {
      console.log('end');
      y.value = withSpring(0);
    }
  };

return (
<PanGestureHandler onHandlerStateChange={gestureStateHandler} onGestureEvent={gestureHandler}>
        <Animated.View style={[animatedStyle]} />
</PanGestureHandler>
)
```

**Comment by karol-bisztyga** [comment] 2020-12-09 10:24
@ElForastero thanks, I will open a new issue from this and soon push the fix 🙌

**Closed** 2020-12-10 14:16 UTC
Labels: Reanimated2, 🐞 Bug, 🧭web

**Comment by Krummelz** [comment] 2023-08-28 21:35
This issue seems to have raised its head again, but managed to get it working using the above workaround, as below. I've been following along the Expo tutorial to create your [first app](https://docs.expo.dev/tutorial/gestures/) and ran into this on the gestures step. 


    const translateX = useSharedValue(0);
    const translateY = useSharedValue(0);

    // borrowed this from your own source code
    const State = {
        UNDETERMINED: 0,
        FAILED: 1,
        BEGAN: 2,
        CANCELLED: 3,
        ACTIVE: 4,
        END: 5,
      };

    const gestureHandler = ({ nativeEvent: e }) => {
        if (e.state === State.ACTIVE) {
            translateX.value = e.translationX + e.target.translateX;
            translateY.value = e.translationY + e.target.translateY;
        }
    };
    const gestureStateHandler = ({ nativeEvent: e }) => {
        if (e.state === State.BEGAN) {
            e.target.translateX = translateX.value;
            e.target.translateY = translateY.value;
        }
    };

    return (
        <PanGestureHandler onGestureEvent={gestureHandler} onHandlerStateChange={gestureStateHandler}>
            <AnimatedView style={[containerStyle, { translateX: 0, translateY: 0, top: -350 }]}>
                ...the rest of my components
            </AnimatedView>
        </PanGestureHandler>
    );

My package.json dependencies are:

    "dependencies": {
      "@expo/vector-icons": "^13.0.0",
      "@expo/webpack-config": "^19.0.0",
      "expo": "~49.0.7",
      "expo-image-picker": "~14.3.2",
      "expo-status-bar": "~1.6.0",
      "react": "18.2.0",
      "react-dom": "18.2.0",
      "react-native": "0.72.4",
      "react-native-gesture-handler": "~2.12.0",
      "react-native-reanimated": "~3.3.0",
      "react-native-web": "~0.19.8"
    },
    "devDependencies": {
      "@babel/core": "^7.20.0",
      "@babel/plugin-proposal-export-namespace-from": "^7.18.9"
    },

**Comment by crispiestsquid** [comment] 2023-10-13 14:15
@karol-bisztyga This still isn't working, as mentioned by @Krummelz above when following the tutorial on Expo's site.

```
const onDrag = useAnimatedGestureHandler({
    onStart: (event, context) => {
      context.translateX = translateX.value;
      context.translateY = translateY.value;
      console.log('onStart', context.translateX, context.translateY);
    },
    onActive: (event, context) => {
      translateX.value = event.translationX + context.translateX;
      translateY.value = event.translationY + context.translateY;
      console.log('onActive', event, context);
    },
  });
  ```
  
  Given this onDrag function and rendering this:
  ```
  <PanGestureHandler onGestureEvent={onDrag}>
      <AnimatedView style={[containerStyle, { top: -350 }]}>
        <TapGestureHandler onGestureEvent={onDoubleTap} numberOfTaps={2}>
          <AnimatedImage
            source={stickerSource}
            resizeMode="contain"
            style={[imageStyle, { width: imageSize, height: imageSize }]}
          />
        </TapGestureHandler>
      </AnimatedView>
    </PanGestureHandler>
```
    
you will not see any logs for onStart when running on Web. I do see the onActive logs but context is undefined in them. Can we reopen this issue?

**Comment by xiezhuojin** [comment] 2023-11-02 07:58
> @karol-bisztyga This still isn't working, as mentioned by @Krummelz above when following the tutorial on Expo's site.
> 
> ```
> const onDrag = useAnimatedGestureHandler({
>     onStart: (event, context) => {
>       context.translateX = translateX.value;
>       context.translateY = translateY.value;
>       console.log('onStart', context.translateX, context.translateY);
>     },
>     onActive: (event, context) => {
>       translateX.value = event.translationX + context.translateX;
>       translateY.value = event.translationY + context.translateY;
>       console.log('onActive', event, context);
>     },
>   });
> ```
> 
> Given this onDrag function and rendering this:
> 
> ```
> <PanGestureHandler onGestureEvent={onDrag}>
>     <AnimatedView style={[containerStyle, { top: -350 }]}>
>       <TapGestureHandler onGestureEvent={onDoubleTap} numberOfTaps={2}>
>         <AnimatedImage
>           source={stickerSource}
>           resizeMode="contain"
>           style={[imageStyle, { width: imageSize, height: imageSize }]}
>         />
>       </TapGestureHandler>
>     </AnimatedView>
>   </PanGestureHandler>
> ```
> 
> you will not see any logs for onStart when running on Web. I do see the onActive logs but context is undefined in them. Can we reopen this issue?

It will work if you assign onDrag to PanGestureHandler's onBegan prop.

**Comment by xiezhuojin** [comment] 2023-11-02 08:06
> It will work if you assign onDrag to PanGestureHandler's onBegan prop.

A single way to fix the [first app](https://docs.expo.dev/tutorial/gestures/) example is just assign onDrag to PanGestureHandler's onBegan prop.

**Comment by xiezhuojin** [comment] 2023-11-02 08:06
> This issue seems to have raised its head again, but managed to get it working using the above workaround, as below. I've been following along the Expo tutorial to create your [first app](https://docs.expo.dev/tutorial/gestures/) and ran into this on the gestures step.
> 
> ```
> const translateX = useSharedValue(0);
> const translateY = useSharedValue(0);
> 
> // borrowed this from your own source code
> const State = {
>     UNDETERMINED: 0,
>     FAILED: 1,
>     BEGAN: 2,
>     CANCELLED: 3,
>     ACTIVE: 4,
>     END: 5,
>   };
> 
> const gestureHandler = ({ nativeEvent: e }) => {
>     if (e.state === State.ACTIVE) {
>         translateX.value = e.translationX + e.target.translateX;
>         translateY.value = e.translationY + e.target.translateY;
>     }
> };
> const gestureStateHandler = ({ nativeEvent: e }) => {
>     if (e.state === State.BEGAN) {
>         e.target.translateX = translateX.value;
>         e.target.translateY = translateY.value;
>     }
> };
> 
> return (
>     <PanGestureHandler onGestureEvent={gestureHandler} onHandlerStateChange={gestureStateHandler}>
>         <AnimatedView style={[containerStyle, { translateX: 0, translateY: 0, top: -350 }]}>
>             ...the rest of my components
>         </AnimatedView>
>     </PanGestureHandler>
> );
> ```
> 
> My package.json dependencies are:
> 
> ```
> "dependencies": {
>   "@expo/vector-icons": "^13.0.0",
>   "@expo/webpack-config": "^19.0.0",
>   "expo": "~49.0.7",
>   "expo-image-picker": "~14.3.2",
>   "expo-status-bar": "~1.6.0",
>   "react": "18.2.0",
>   "react-dom": "18.2.0",
>   "react-native": "0.72.4",
>   "react-native-gesture-handler": "~2.12.0",
>   "react-native-reanimated": "~3.3.0",
>   "react-native-web": "~0.19.8"
> },
> "devDependencies": {
>   "@babel/core": "^7.20.0",
>   "@babel/plugin-proposal-export-namespace-from": "^7.18.9"
> },
> ```

A single way to fix the [first app](https://docs.expo.dev/tutorial/gestures/) example is just assign onDrag to PanGestureHandler's onBegan prop.
