### ISSUE TITLE
Type erros in react-native-reanimated.d.ts

### ISSUE THREAD

**Issue by lfjnascimento** [software-mansion/react-native-reanimated#3081] opened 2022-03-17 18:25 UTC
## Description

Many type errors are thrown when `skipLibCheck` is false and you run `yarn type:check`

### Expected behavior

Should not return type errors when running `yarn type:check` with  `skipLibCheck` as false

### Actual behavior & steps to reproduce

In the react-native-reanimated repository
Set  `skipLibCheck` in tsconfig.json to `false` > run `yarn type:check`

## Snack or minimal code example

https://github.com/software-mansion/react-native-reanimated

## Package versions

n/a

## Affected platforms

- [x] Android
- [x] iOS
- [x] Web

Errors log: [erros.txt](https://github.com/software-mansion/react-native-reanimated/files/8289166/erros.txt)

**Comment by marf** [comment] 2022-03-21 12:12
Same error here

**Comment by haveneersrobin** [comment] 2022-03-22 07:53
Duplicate of https://github.com/software-mansion/react-native-reanimated/issues/3087 which contains a bit more information :)

**Closed** 2022-03-22 10:02 UTC
Labels: 🧰needs-repro, 🤖android, 🍎iOS, 🧭web, needs-review, needs-more-info
