### ISSUE TITLE
 ReferenceError: Can't find variable: _setGlobalConsole, after upgrading to `-rc.2`.

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-reanimated#1640] opened 2021-01-15 23:36 UTC
## Description

getting the following error after upgrading to `2.0.0-rc.2` from `2.0.0-rc.1`

### Screenshots

![Screen Shot 2021-01-16 at 1 34 20 AM](https://user-images.githubusercontent.com/19273413/104788498-f744e680-579a-11eb-9071-772ca97e41fe.png)

## Steps To Reproduce

- upgrade to rc.2 
- install the latest rc `rc.2`

### Expected behavior

it should work as before.

### Actual behavior

it throws an error `ReferenceError: Can't find variable: _setGlobalConsole`

## Snack or minimal code example

N/A

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: ^2.0.0-rc.2
- NodeJS: v14.15.3

**Comment by chakrihacker** [comment] 2021-01-16 13:28
Did you update the pods and reinstall the app?

**Comment by a-eid** [comment] 2021-01-16 13:31
Yes the issue happens on both android & IOS after upgrading & on fresh projects.

**Comment by a-eid** [comment] 2021-01-18 15:27
@chakrihacker yes, I just verified that again, the issue persists on ios & android.

**Comment by a-eid** [comment] 2021-01-22 13:22
@karol-bisztyga if a reproduce repo is needed please let me know.

**Comment by a-eid** [comment] 2021-01-22 17:33
After further investigation, this only happens when using `react-native-navigation` indeed.

**Comment by hakanpinar** [comment] 2021-01-22 19:58
Hey, I'm facing the same issue. When will it be fixed?

I think there is a problem between reanimated and react native 5. Can you someone help us?

Thanks

**Comment by angrypie** [comment] 2021-01-23 04:24
Hey @karol-bisztyga @hakanpinar, maybe not related but for me it was babel plugin misconfiguration (react-native-reanimated/plugin).

Found that plugin sets up `_setGlobalConsole` here:
https://github.com/software-mansion/react-native-reanimated/blob/fd5c6ad5524adf603a75acfda46438b4e2031a2a/plugin.js#L32-L34

**Comment by ezos86** [comment] 2021-01-23 20:18
> const globals = new Set([

so did modifying the plugin.js work for you?

**Comment by ezos86** [comment] 2021-01-23 20:18
> Hey @karol-bisztyga @hakanpinar, maybe not related but for me it was babel plugin misconfiguration (react-native-reanimated/plugin).
> 
> Found that plugin sets up `_setGlobalConsole` here:
> https://github.com/software-mansion/react-native-reanimated/blob/fd5c6ad5524adf603a75acfda46438b4e2031a2a/plugin.js#L33-L36

So did modifying the plugin.js work for you?

**Comment by angrypie** [comment] 2021-01-23 21:46
> So did modifying the plugin.js work for you?

No, I mean plugin should be configured in your `babel.config.js` (it's actually stated in the docs).

**Comment by sundaleek** [comment] 2021-01-24 14:40
hi @a-eid do you want iOS dev job in Tambov company? Please contact t.me/sundaleek

**Comment by Yandamuri** [comment] 2021-01-25 05:33
@angrypie my  `react-native-reanimated/plugin` exactly as you mentioned here. But still I ma getting the error. Any alternatives?

**Comment by angrypie** [comment] 2021-01-25 08:38
@Yandamuri 
1. You didn't mention the `MainApplication.java` ?
2. Someone mention that `react-native start --reset-cache` soled issue.

**Comment by karol-bisztyga** [comment] 2021-01-25 08:50
Hi
This is a duplicate of https://github.com/software-mansion/react-native-reanimated/issues/1546
Please, read what's there(are you using expo?) and let me know if the problem's gone or not.

**Comment by Yandamuri** [comment] 2021-01-25 09:13
@angrypie 
1. I have done all changes in `MainApplication.java' as mentioned in docs.
2. `react-native start --reset-cache` -- this solution didn't work for me
3. my `babel.config.js` looks like this,

        module.exports = {
               presets: ['module:metro-react-native-babel-preset'],
               plugins: [[
		         "babel-plugin-transform-remove-imports", {
			"test": ['react-toastify', 'exceljs']
		         }
	       ],
	       'react-native-reanimated/plugin'
             ]
       };

Can you please correct me if I am wrong?

**Comment by Yandamuri** [comment] 2021-01-25 09:15
@karol-bisztyga I had already gone through this issue and their solutions didn't work for me. And I am not using expo

**Comment by angrypie** [comment] 2021-01-25 10:23
@Yandamuri config is ok. I also went through [this steps to clean cache](https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d), before noticed my config issue, might be helpful.

**Comment by Yandamuri** [comment] 2021-01-27 06:23
@angrypie this is great. Now it is working fine after so much of struggle.

**Comment by karol-bisztyga** [comment] 2021-01-27 07:09
@a-eid @hakanpinar can you check if that works for you?

**Comment by a-eid** [comment] 2021-01-28 18:52
> @a-eid @hakanpinar can you check if that works for you?

Hey sorry for the late reply, I will try this out by morning & let you know. 

Thank you

**Comment by karol-bisztyga** [comment] 2021-01-29 07:29
@a-eid https://github.com/software-mansion/react-native-reanimated/issues/1640#issuecomment-766713089

**Comment by a-eid** [comment] 2021-01-29 08:20
@karol-bisztyga for some reason I can no longer reproduce this bug, please close this issue when appropriate, I'll report back if I encounter this again.

thank you.

**Comment by karol-bisztyga** [comment] 2021-01-29 10:03
Ok I see, please let me know if it happens again and I'll reopen.

**Closed by karol-bisztyga** 2021-01-29 10:03 UTC
Labels: 🏠  Reanimated2, 🐞 Bug

**Comment by PedroBern** [comment] 2021-01-30 00:28
@karol-bisztyga I'm facing the same issue with expo. Both in rc.1 and rc.2. Tried all the steps to clean the cache but didn't work.

**Comment by karol-bisztyga** [comment] 2021-02-01 08:51
@PedroBern please try rc0(explained [here](https://github.com/software-mansion/react-native-reanimated/issues/1546#issuecomment-749448029))

**Comment by Yandamuri** [comment] 2021-02-16 09:02
@angrypie Can you please have a look at [this issue](https://github.com/software-mansion/react-native-reanimated/issues/1127#issuecomment-779688041) if you have time?

**Comment by sauhardo2020** [comment] 2021-05-12 17:47
**_### Ok so can someone tell me how to fix this issues please i need to know the solution_**

**Comment by Yandamuri** [comment] 2021-05-13 03:35
@sauhardo2020 Have you tried this solution?

> @Yandamuri config is ok. I also went through [this steps to clean cache](https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d), before noticed my config issue, might be helpful.

**Comment by sauhardo2020** [comment] 2021-05-13 17:40
Yes!, I have tried this but still it is giving the same error looks like its a problem with reanimated 2 but i cant find the right solution so i need some help for this

**Comment by sauhardo2020** [comment] 2021-05-13 17:44
also can you tell me if this issues is fixed in older version because i have a project i need to complete

**Comment by sauhardo2020** [comment] 2021-05-13 17:44
a

**Comment by michaldobiezynski** [comment] 2021-05-20 18:33
it might sound crazy but try creating a new project with `npx crna --template with-reanimated2` - reanimated will work in that

**Comment by francislow** [comment] 2021-06-24 05:37
1) delete the 'node_modules' folder
2) ran 'npm cache clean --force'
3) npm install
4) npm start --clear-cache

*I did this and it works for me

**Comment by sauhardo2020** [comment] 2021-06-24 10:09
Thanks!!

**Comment by simranss** [comment] 2023-05-24 07:45
I still cannot solve this issue, and I am using react-naviagtion.

**Comment by piaskowyk** [comment] 2023-05-24 12:44
It is quite strange because we removed this function more than a year ago 😅 If you still face this issue you need to clear the cache.

**Comment by valery-lavrik** [comment] 2023-06-08 08:56
I also ran into this problem today
![image](https://github.com/software-mansion/react-native-reanimated/assets/8047999/3d15f9b1-1b4a-45e9-9280-284de069db3a)

**Comment by yunesdelivery** [comment] 2023-07-19 01:58
> Eu também tive esse problema hoje ![imagem](https://user-images.githubusercontent.com/8047999/244325003-3d15f9b1-1b4a-45e9-9280-284de069db3a.png)

How did you manage to solve it?

**Comment by valery-lavrik** [comment] 2023-07-19 05:10
@yunesdelivery   
The problem turned out to be version incompatibility
react-native-reanimated
react-native-vision-camera
react-native

To make everything work, I use the following versions:
```
    "react-native": "0.70.10",
    "react-native-reanimated": "^2.12.0",
    "react-native-vision-camera": "^2.15.2",
```
