### ISSUE TITLE
RELEASE ONLY: E/unknown:NativeViewHierarchyManager: Unable to update properties for view tag xxxx

### ISSUE THREAD

**Issue by frankoprifti** [software-mansion/react-native-reanimated#4231] opened 2023-03-15 10:25 UTC
### Description

On the Release build this error is happening a lot. The modals on my app are not opening a lot of times. The error can be seen in the logcat: 
`
E/unknown:NativeViewHierarchyManager: Unable to update properties for view tag 3395
    com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 3395 could not be found.
        at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:111)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:138)
        at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:281)
        at com.swmansion.reanimated.NodesManager.updateProps(NodesManager.java:354)
        at com.swmansion.reanimated.nativeProxy.NativeProxyCommon.updateProps(NativeProxyCommon.java:97)
        at com.swmansion.reanimated.nativeProxy.AnimationFrameCallback.onAnimationFrame(Native Method)
        at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:245)
        at com.swmansion.reanimated.NodesManager.access$000(NodesManager.java:42)
        at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:142)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`
        
      
  I was able to reproduce this on the Example app from this package and after playing around playing the animations i started seeing this error appear on the logs and the app was crashing, animations stuck etc.
        NOTE: THIS IS ONLY HAPPENING IN RELEASE BUILD NOT DEV
### Steps to reproduce

1. Clone react-native-reanimated
2. cd react-native-reanimated -> yarn to install modules
3. cd Example -> yarn to install modules
4. Open the project in Android Studio
5. Build a **release** version and open it in the emulator
6. Play around with the animations, faster you play more errors you are going to see

### Snack or a link to a repository

https://github.com/frankoprifti/react-native-reanimated-BUG/tree/main/Example

### Reanimated version

2.x.x - 3.0.2

### React Native version

0.70.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Release mode

### Device

Android emulator

### Device model

Android Emulator and Any android Real Device. Tested on Pixel6a and Pixel 4a and Samsung s20

### Acknowledgements

Yes

**Comment by frankoprifti** [comment] 2023-03-15 10:26
There is no need for a GitHub repository under my name where the bug is happening even on your Example app provided

**Comment by Latropos** [comment] 2023-03-20 13:17
@frankoprifti Thank you for submitting this issue. What was the example that made the app crash?
Could you please describe how did the crash look like? Or even upload a recording?

**Comment by frankoprifti** [comment] 2023-03-20 13:20
On the example app it sometimes stuck the animations and you cannot do anything until you close and reopen it or the animation doesnt show at all
. In my app it doesn't show a bottom sheet and you have to try multiple times until you get to show

**Comment by mmmoussa** [comment] 2023-03-26 03:40
@piaskowyk since upgrading to v3 we are seeing a lot of stuck animations in our app as well in production on Android devices. In particular we are seeing many reports from Samsung devices, especially those running One UI 5.1, though we do not believe the issue is isolated to those devices or that OS. The animations are simple cases where we have a shared value (using `useSharedValue`) which is used along with `withTiming` and `useAnimatedStyle` to adjust a width or height property of a view.

**Comment by ranaavneet** [comment] 2023-04-03 12:16
Hi @piaskowyk - we have been facing this in our release version as well. Is there any ETA for the fix?

**Comment by ranaavneet** [comment] 2023-05-03 09:03
Hey @piaskowyk , just bumping this up. Is there any progress on this? We are still stuck on 3.0.0.rc10 due to this bug.

**Comment by frankoprifti** [comment] 2023-07-19 14:01
The screenshot i have added here https://github.com/software-mansion/react-native-reanimated/issues/4231#issuecomment-1477520665 shows the animation stuck. It should be a modal opened on the app but there is not and the app is stuck

**Comment by piaskowyk** [comment] 2023-07-20 08:57
What I'm doing wrong that I'm unable to reproduce it? Here is screen record:
https://drive.google.com/file/d/1cLag3VcoNdUoXehTWe0qgGOwRUPAqo-8/view?usp=sharing

**Comment by frankoprifti** [comment] 2023-07-20 09:16
It only happens on a release build, not while debugging @piaskowyk

**Comment by piaskowyk** [comment] 2023-07-25 05:11
Correct me if I am wrong but I think I used release build 🤔
<img width="279" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/ff265371-3a27-4257-b27e-df05ef84e3dd">

**Comment by piaskowyk** [comment] 2024-05-13 08:25
Fixed with https://github.com/software-mansion/react-native-reanimated/pull/5767, changes will be available in the next release - 3.12.0

**Closed by piaskowyk** 2024-05-13 08:25 UTC
Labels: Platform: Android, Needs review, Repro provided
