### ISSUE TITLE
"Cannot read property 'length' of undefined" in MapperRegistry.ts

### ISSUE THREAD

**Issue by pottercomuneo** [software-mansion/react-native-reanimated#3799] opened 2022-11-22 10:29 UTC
### Description

I'm using `react-native-reanimated` because of `react-navigation`. I had to upgrade `react-navigation` to `v6`, then I also upgraded reanimated.
Everything works fine, but now when I add a drawer I get:
`Cannot read property 'length' of undefined` in `MapperRegistry.ts`, row 51
If I edit `MapperRegistry.ts` to check if the `mapper` is `undefined` first, then no errors and the app works except that the drawer won't toggle (which of course I need to achieve)
What is it that is happening? I tried and searched everywhere, it seems like I'm the only one with this issue. Could it even be bad usage from `react-navigation`? Anyway I would expect this case to be handled.
Thanks!

### Steps to reproduce

1. Add a drawer from `react-navigation`
2. Run the app

### Snack or a link to a repository

-

### Reanimated version

2.10.0

### React Native version

0.69.4

### Platforms

iOS

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by pottercomuneo** [comment] 2022-11-22 21:21
I got further information: line 51 is checking the length of `node.mapper.outputs`, but the position of `outputs` is not there!
Printing `node.mapper` I got:
<img width="601" alt="Schermata 2022-11-22 alle 22 19 22" src="https://user-images.githubusercontent.com/23405442/203423286-0084ed24-6d55-4f87-bf04-b3032830abd4.png">
So `outputs` is actually more nested. And also the `dirty` property, checked on line 34.
What's happening?

**Comment by VinhKyiT** [comment] 2022-12-30 03:41
I got same issue with react-native@0.68.5 and reanimated@2.12.0

**Comment by quicksilverr** [comment] 2023-01-16 07:05
Yeah, facing the same issue. Were you able to solve it @pottercomuneo ?

**Comment by pottercomuneo** [comment] 2023-01-16 10:04
> Yeah, facing the same issue. Were you able to solve it @pottercomuneo ?

No, @quicksilverr ! By now I had to rethink my app removing the Drawers!

**Comment by damassi** [comment] 2023-01-17 19:04
Also running into this issue on `react-native@0.66`. But **not** running into this on `react-native@0.69`

**Comment by damassi** [comment] 2023-01-19 02:07
**Update 2:** We were able to track the issue down to using `babel/preset-env` in our babel config file! Once we removed it, this issue went away.

**Comment by piaskowyk** [comment] 2023-05-18 15:06
Interesting because the `MapperRegistry.ts` file is used only on web implementation. Do you face this error on the mobile or web version of react-native?

**Comment by damassi** [comment] 2023-05-18 15:50
Mobile!

**Comment by piaskowyk** [comment] 2023-05-18 16:11
Is it possible for you to create reproduction? It seems like a problem with the application config.

**Comment by Latropos** [comment] 2023-11-07 16:17
Closing, since we have removed file `MapperRegistry.ts`, so ww will not reproduce it anyway. Probably the problem is already fixed 😎

**Closed by Latropos** 2023-11-07 16:17 UTC
Labels: Missing repro, Platform: iOS, Needs review, Missing info
