### ISSUE TITLE
Android build error "extra properties extension"

### ISSUE THREAD

**Issue by Adichilla** [software-mansion/react-native-reanimated#2627] opened 2021-11-15 06:33 UTC
## Description

Installed the latest version and tried to build it one Android studio following error occurred

Caused by: groovy.lang.MissingPropertyException: Cannot get property 'react' on extra properties extension as it does not exist

What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
Cannot get property 'react' on extra properties extension as it does not exist

**1.9.0** version is shown the different error

node_modules/react-native-reanimated/android/build.gradle' line: 99
A problem occurred configuring project ':react-native-reanimated'.
Cannot add task 'androidSourcesJar' as a task with that name already exists

```
task androidSourcesJar(type: Jar) {
        classifier = 'sources'
        from android.sourceSets.main.java.srcDirs
        include '**/*.java'
 }
```

**2.2.1** version is shown the different error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.

Where:
Build file '/Users/apple/Desktop/meet-master/node_modules/react-native-reanimated/android/build.gradle' line: 67

```
if(project.ext.react.enableHermes) {
    engine = "hermes"
}
```

What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
Cannot get property 'react' on extra properties extension as it does not exist

2: Task failed with an exception.

Where:
Build file '/Users/apple/Desktop/meet-master/android/build.gradle' line: 117

```
task jitsiAndroidSourcesJar(type: Jar) {
    classifier = 'sources'
    from android.sourceSets.main.java.source
}
```

What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
Could not get unknown property 'android' for task ':react-native-reanimated:jitsiAndroidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.

### Expected behavior

Android studio build it successfully

### Actual behavior & steps to reproduce

npm i react-native-reanimated@2.2.2 or ant mentioned version
Manually link the library for Android or auto-link the library
Opening the project in native tool Android studio throws this build error

Facing the same errors while trying on a different version
 - 1.9.0, 2.0.0
 - 2.2.0, 2.2.4

## Package versions

- React Native: 0.63.4
- React Native Reanimated: 2.0.0, 2.2.0, 2.2.1, 2.2.4
- NodeJS: 14.17.6
- Xcode: 12 iOS SDK 14.2
- Java & Gradle: 1.8.0_271 & 6.8

Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0

## Affected platforms

- [x] Android
- [ ] iOS

**Comment by adamonkey** [comment] 2021-11-19 20:28
@Adichilla I simply re-added the hermes settings to 'android/app/build.gradle' (with hermes disabled) and it fixed it. I think it comes with the default React project, but I removed it. 

https://reactnative.dev/docs/hermes

**Comment by Adichilla** [comment] 2021-11-21 05:25
@adamonkey
There is no code is available in the project build.gradle file
So added manually and checked 

```
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
    }
}

project.ext.react = [
    entryFile: "index.js",
    enableHermes: true
]

ext {
```

faced the same issue even after cleaning and  Invalidate cache and restart

```
Caused by: groovy.lang.MissingPropertyException: Cannot get property 'react' on extra properties extension 
as it does not exist
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'android' 
for task ':react-native-reanimated:jitsiAndroidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.
```


I was trying to setup Jitsi ReactNative project - **https://github.com/jitsi/jitsi-meet**

**Comment by adamonkey** [comment] 2021-11-21 18:27
@Adichilla It looks like you added 
```
project.ext.react = [
    entryFile: "index.js",
    enableHermes: true
]
```
to the root 'build.gradle' file, not the 'app/build.gradle' file. Could that be the issue?

**Comment by Adichilla** [comment] 2021-11-22 02:16
@adamonkey 
You're Right adding in project app/build.gradle is the correct step 

Seems like no use in enabling Hermes

```
Build file '/Users/apple/Downloads/jitsi-meet-master/android/build.gradle' line: 115

A problem occurred configuring project ':react-native-reanimated'.
> Could not get unknown property 'android' for task ':react-native-reanimated:jitsiAndroidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':react-native-reanimated'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:75)
```
	
Error showing in project gradle file I have this code 

```
task jitsiAndroidSourcesJar(type: Jar) {
   classifier = 'sources'
   from android.sourceSets.main.java.source
}
```

**Comment by adamonkey** [comment] 2021-11-22 02:33
@Adichilla Sorry, I am not too familiar with this bug and jitsi-meet.

**Comment by Adichilla** [comment] 2021-11-22 03:03
@adamonkey Thanks for your support
Will check

**Comment by Adichilla** [comment] 2022-01-05 11:36
No fix as of now @arinjay-d11

**Comment by arinjay-d11** [comment] 2022-01-05 11:44
Can you send me the link of the ticket , so that I can follow the same?

**Comment by Adichilla** [comment] 2022-01-05 11:59
@arinjay-d11 
https://community.jitsi.org/t/android-build-error-extra-properties-extension-react-native-reanimated/107767/4

**Comment by arinjay-d11** [comment] 2022-01-05 12:01
@Adichilla  Thanks

**Comment by GustavoMelo40** [comment] 2022-01-05 13:11
I have the same problem, waiting for the solution...

**Comment by harish-pulimi** [comment] 2022-01-20 09:28
Same issue, is it fixed? Thanks

**Comment by arinjay-d11** [comment] 2022-01-20 10:01
@Adichilla
We somehow found the fix for this . We need to add the hermes dependencies in all the modules for which reanimated gradle is looking for it.

Step 1 : Please print "project.name" before the if block in **build.gardle( :react-native-reanimated)** and in the loop

**println  project.name
if(project.ext.react.enableHermes) {
    engine = "hermes"
}**

Step 2 , Sync or rebuild it , you will see all the modules which are using by the reanimated gradle.

Step 2 Add below dependencies in build.gradle of each module's which are printing.
**project.ext.react = [
    enableHermes: true
]**

For eg. if it is printing app , sample , abc  so for all three modules's we need to add enableHermes Dependencies.
build.gradle(app) , build.gradle(sample) , build.gradle(abc)

have verified with reanimated versions 2.2.0 , 2.2.4, 2.3.1
Let me know if it works.

**Comment by Adichilla** [comment] 2022-01-20 13:38
@arinjay-d11 
Thanks for the workaround

**Comment by arinjay-d11** [comment] 2022-01-20 13:41
@Adichilla Did it work?

**Comment by Adichilla** [comment] 2022-01-20 13:47
@arinjay-d11 
Not tried yet stuck on some other work

**Comment by harish-pulimi** [comment] 2022-01-20 14:16
Worked for me, thank you

**Comment by harish-pulimi** [comment] 2022-01-20 16:04
But now getting a different error, not sure if this is related or a totally different issue..
    "react-native": "0.63.4",
    "react-native-reanimated": "^2.2.0",
    
FAILURE: Build failed with an exception.

* Where:
Build file '..../node_modules/react-native-reanimated/android/build.gradle' line: 71

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.

**Comment by arinjay-d11** [comment] 2022-01-21 11:40
@harish-pulimi  In build.gradle(:react-native-reanimated) make below changes :
1.  find  getCurrentFlavor()  method  ,find below line :
 Pattern pattern = Pattern.compile("(assemble|bundle|install|generate)(\\w*)(Release|Debug)")
**Change (\\w*) to (\\w+)**

2. you need to exclude all other modules which are checking for the same :  find below if block and exclude the module name which are priniting in above solution except your main module.
 **if(project.getProperties().get("android") && Integer.parseInt(minor) < 65)**
For eg : your main module is app and some other module doesn't need the reanimated , like "abc" then above if condition can be changed as below 
  **if(project.getProperties().get("android") && Integer.parseInt(minor) < 65 && !project.name.equalsIgnoreCase("abc"))**


Hope this helps.

**Comment by harish-pulimi** [comment] 2022-01-21 11:48
Awesome, that worked. Thanks a lot for your quick response.

**Comment by SherMish** [comment] 2022-01-23 11:43
> @Adichilla We somehow found the fix for this . We need to add the hermes dependencies in all the modules for which reanimated gradle is looking for it.
> 
> Step 1 : Please print "project.name" before the if block in **build.gardle( :react-native-reanimated)** and in the loop
> 
> **println project.name if(project.ext.react.enableHermes) { engine = "hermes" }**
> 
> Step 2 , Sync or rebuild it , you will see all the modules which are using by the reanimated gradle.
> 
> Step 2 Add below dependencies in build.gradle of each module's which are printing. **project.ext.react = [ enableHermes: true ]**
> 
> For eg. if it is printing app , sample , abc so for all three modules's we need to add enableHermes Dependencies. build.gradle(app) , build.gradle(sample) , build.gradle(abc)
> 
> have verified with reanimated versions 2.2.0 , 2.2.4, 2.3.1 Let me know if it works.

I get the error during building, so how can I view the printing if the error occurs during build?

**Comment by SherMish** [comment] 2022-01-23 12:00
> 2\. f(project.getProperties().get("android") && Integer.parseInt(minor) < 65

Just the main module (react-native-reanimated) has the following if statement..

**Comment by SherMish** [comment] 2022-01-23 12:01
> @harish-pulimi In build.gradle(:react-native-reanimated) make below changes :
> 
> 1. find  getCurrentFlavor()  method  ,find below line :
>    Pattern pattern = Pattern.compile("(assemble|bundle|install|generate)(\w*)(Release|Debug)")
>    Change "(//w*)" to "(//w+)"
> 2. you need to exclude all other modules which are checking for the same :  find below if block and exclude the module name which are priniting in above solution except your main module.
>    **if(project.getProperties().get("android") && Integer.parseInt(minor) < 65)**
>    For eg : your main module is app and some other module doesn't need the reanimated , like "abc" then above if condition can be changed as below
>    **if(project.getProperties().get("android") && Integer.parseInt(minor) < 65 && !project.name.equalsIgnoreCase("abc"))**
> 
> Hope this helps.

Just the main module (react-native-reanimated) has the following if statement..

**Comment by arinjay-d11** [comment] 2022-01-24 07:41
> > @Adichilla We somehow found the fix for this . We need to add the hermes dependencies in all the modules for which reanimated gradle is looking for it.
> > Step 1 : Please print "project.name" before the if block in **build.gardle( :react-native-reanimated)** and in the loop
> > **println project.name if(project.ext.react.enableHermes) { engine = "hermes" }**
> > Step 2 , Sync or rebuild it , you will see all the modules which are using by the reanimated gradle.
> > Step 2 Add below dependencies in build.gradle of each module's which are printing. **project.ext.react = [ enableHermes: true ]**
> > For eg. if it is printing app , sample , abc so for all three modules's we need to add enableHermes Dependencies. build.gradle(app) , build.gradle(sample) , build.gradle(abc)
> > have verified with reanimated versions 2.2.0 , 2.2.4, 2.3.1 Let me know if it works.
> 
> I get the error during building, so how can I view the printing if the error occurs during build?
println project.name + "Any Identifier for discriminate", When It is getting build, you will be getting the build process step by step by clicking on build. find your identifier. which you print.

**Comment by arinjay-d11** [comment] 2022-01-24 07:42
> 

Yes you only need this change in build.gardle( :react-native-reanimated)

**Comment by arinjay-d11** [comment] 2022-01-24 07:43
@harish-pulimi In build.gradle(:react-native-reanimated) make below changes :

find getCurrentFlavor() method ,find below line :
Pattern pattern = Pattern.compile("(assemble|bundle|install|generate)(\w*)(Release|Debug)")
Change "(//w*)" to "(//w+)"
you need to exclude all other modules which are checking for the same : find below if block and exclude the module name which are priniting in above solution except your main module.
if(project.getProperties().get("android") && Integer.parseInt(minor) < 65)
For eg : your main module is app and some other module doesn't need the reanimated , like "abc" then above if condition can be changed as below
if(project.getProperties().get("android") && Integer.parseInt(minor) < 65 && !project.name.equalsIgnoreCase("abc"))
Hope this helps.

Just the main module (react-native-reanimated) has the following if statement..

****
Yes you only need this change in build.gradle(:react-native-reanimated)

**Comment by piaskowyk** [comment] 2022-01-28 10:46
Can anyone provide a repro to reproduce this issue?

**Comment by Tipoo** [comment] 2022-03-26 12:27
> Download latest jitsi-meet
cd jitsi-meet/android
./gradlew

This should fail with error.
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/oldmonk/softwares/jitsi-meet/node_modules/react-native-reanimated/android/build.gradle' line: 179

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Cannot get property 'react' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Build file '/home/oldmonk/softwares/jitsi-meet/android/build.gradle' line: 123

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> Could not get unknown property 'android' for task ':react-native-reanimated:jitsiAndroidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

```

**Comment by dlgmltjr0925** [comment] 2022-06-02 07:48
I also had the same problem.
There are 3 projects under the root project, only one is React Native project.

It was confirmed that the build was successful by modifying as follows.

```gradle
// react-native-reanimated:2.8.0
// {projectRoot}/node_modules/react-native-reanimated/android/build.gradle line: 170

if (project.ext.has("react") && project.ext.react.enableHermes) { // <- Added project.ext.has("react") && 
    runtimeType = "hermes"
}
```

**Comment by Latropos** [comment] 2023-10-12 14:42
Closing, since I assume that the inactivity here means that the problem doesn't happen in newer versions Reanimated. In fact Reanimated 2.2 is very old and I encourage to use a newer version instead.

**Closed by Latropos** 2023-10-12 14:42 UTC
Labels: Build or config issue, Bug, bug-bash-jan22
