### ISSUE TITLE
Interactable.js snapTo() doesn't snap when dragging

### ISSUE THREAD

**Issue by samfriend** [software-mansion/react-native-reanimated#281] opened 2019-05-11 04:35 UTC
When you call interactable.snapTo() while dragging, the interactable failed to snap to the index (nothing happen). The snapTo() only works while we are not interacting the interactable.

Is it possible to override any gesture and snap the interactable if we are dragging the interactable? 

Thanks

**Comment by nomi9995** [comment] 2019-05-16 03:10
@samfriend  yeah I know this is because you are using snappoints dynamic. I think this is the problem is in reanimated Interactable not in wix Interactable

**Comment by jakub-gonet** [comment] 2019-12-19 15:14
Hi, @samfriend,
sorry for the late response

Unfortunately `Interactable.js` is not actively maintained and it's not in the scope  of Reanimated. However, we may consider extracting it to standalone library in the future.

I'll close this, as it's probably outdated, but you can provide your solution if you managed to solve that or create a PR fixing that problem :>

**Closed by jakub-gonet** 2019-12-19 15:14 UTC
Labels: 🐞bug-bash-dec19
