### ISSUE TITLE
V2: Crash when using useAnimatedStyle

### ISSUE THREAD

**Issue by HrantAbrahamyan** [software-mansion/react-native-reanimated#1270] opened 2020-09-23 16:54 UTC
## Description

Hi, I got this crash in native code: 
undefined is not an object (evaluating 'Object.keys(oldStyle)')

keys@[native code]
styleDiff
[native code]
styleUpdater
[native code]
_f
[native code]

reanimated::REAIOSErrorHandler::raiseSpec()
    REAIOSErrorHandler.mm:17
reanimated::ErrorHandler::raise()::'lambda'()::operator()()
decltype(std::__1::forward<reanimated::ErrorHandler::raise()::'lambda'()&>(fp)()) std::__1::__invoke<reanimated::ErrorHandler::raise()::'lambda'()&>(reanimated::ErrorHandler::raise()::'lambda'()&)
void std::__1::__invoke_void_return_wrapper<void>::__call<reanimated::ErrorHandler::raise()::'lambda'()&>(reanimated::ErrorHandler::raise()::'lambda'()&)
std::__1::__function::__alloc_func<reanimated::ErrorHandler::raise()::'lambda'(), std::__1::allocator<reanimated::ErrorHandler::raise()::'lambda'()>, void ()>::operator()()
std::__1::__function::__func<reanimated::ErrorHandler::raise()::'lambda'(), std::__1::allocator<reanimated::ErrorHandler::raise()::'lambda'()>, void ()>::operator()()
std::__1::__function::__value_func<void ()>::operator()() const
std::__1::function<void ()>::operator()() const
reanimated::Scheduler::triggerUI()
invocation function for block in reanimated::REAIOSScheduler::scheduleOnUI(std::__1::function<void ()>)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0

### Screenshots

![image](https://user-images.githubusercontent.com/36418107/94044022-aa4d9680-fdde-11ea-89bc-1d536797bba4.png)

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: ^2.0.0-alpha.5

**Comment by jakub-gonet** [comment] 2020-09-23 18:43
Could you please provide a code snippet that is crashing?

**Comment by terrysahaidak** [comment] 2020-09-23 19:12
I had this too and was happening because of some changes in Hooks.js code by prettier.

I think upgrading to the latest version of Reanimated should fix this

**Comment by HrantAbrahamyan** [comment] 2020-09-24 07:27
@jakub-gonet I'm using this lib you can see code here https://github.com/rainbow-me/react-native-animated-charts

**Comment by HrantAbrahamyan** [comment] 2020-09-24 09:12
@terrysahaidak Same error with latest version of reanimated

**Comment by terrysahaidak** [comment] 2020-09-24 09:14
Make sure to remove previous node modules before installing as well as clear all the possible caches.

**Comment by HrantAbrahamyan** [comment] 2020-09-24 09:47
@terrysahaidak I did but the same result
Now I have "2.0.0-alpha.6", what's wrong in steps?
1. Removed node_modules, yarn.lock
2. Removed Pods folder, Podfile.lock, myproj.xcworkspace
3. yarn && npx pod-install && yarn ios

**Comment by terrysahaidak** [comment] 2020-09-24 09:52
Did you run the packager with `--reset-cache`? Also, make sure to clean the watchman cache as well.

**Comment by HrantAbrahamyan** [comment] 2020-09-24 10:10
No, just I do it and there is no change, I think the problem not placed in the cache.

**Comment by HrantAbrahamyan** [comment] 2020-09-24 10:12
![image](https://user-images.githubusercontent.com/36418107/94132222-0a404d80-fe70-11ea-9781-a31d49660208.png)

**Comment by jakub-gonet** [comment] 2020-09-24 10:19
We can't help you without reproducing repo. 

Please provide one, closing until then.

**Closed by jakub-gonet** 2020-09-24 10:19 UTC
Labels: Reanimated2, 🐞 Bug

**Comment by yolpsoftware** [comment] 2020-09-26 15:18
@HrantAbrahamyan did you find the cause of that?

It indeed seems to be a caching issue. When I tried to isolate the problem, it vanished in a new repo, although all files were identical.

However, I still have not found which cache it is and how to reset it. It happens in iOS debug mode, both from macOS and Windows, and also in the iOS simulator. Overall, I have three workstations, and it happens on all four.

Any ideas?
