### ISSUE TITLE
Not working in Stack Navigation

### ISSUE THREAD

**Issue by yaokaoya** [software-mansion/react-native-reanimated#2572] opened 2021-10-25 02:23 UTC
## Package versions

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by kacperkapusciak** [comment] 2021-11-09 11:26
Closing due to not providing a reproduction.

**Closed by kacperkapusciak** 2021-11-09 11:26 UTC
Labels: 🧰needs-repro, 🐞 Bug, 🏠  Reanimated2
