### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException (AnimationsManager.java) v2.3.0-beta.2

### ISSUE THREAD

**Issue by pronevich** [software-mansion/react-native-reanimated#2508] opened 2021-10-07 19:04 UTC
## Description

Stack trace from Crashlytics, Android 11, Redmi Note 9 Pro:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.WindowManager android.app.Activity.getWindowManager()' on a null object reference
       at com.swmansion.reanimated.layoutReanimation.AnimationsManager.prepareDataForAnimationWorklet(AnimationsManager.java:340)
       at com.swmansion.reanimated.layoutReanimation.AnimationsManager.onViewRemoval(AnimationsManager.java:116)
       at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.dfs(ReanimatedNativeHierarchyManager.java:119)
       at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.dfs(ReanimatedNativeHierarchyManager.java:127)
       at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.dfs(ReanimatedNativeHierarchyManager.java:127)
       at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.dfs(ReanimatedNativeHierarchyManager.java:127)
       at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.dfs(ReanimatedNativeHierarchyManager.java:127)
       at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.dfs(ReanimatedNativeHierarchyManager.java:127)
       at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.dfs(ReanimatedNativeHierarchyManager.java:127)
       at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.deleteView(ReanimatedNativeHierarchyManager.java:106)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:482)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:230)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:914)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:983)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-beta.2

## Affected platforms

- [x] Android

**Comment by amitkumar3968** [comment] 2021-10-12 21:25
try  doing changes as per link
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#android
enablehermes
editing Mainapplication.java

**Comment by michaelknoch** [comment] 2021-10-12 23:58
changes from the docs are applied. It doesn't seem to always crash. I can reliably reproduce this on our CI but not on local devices so far, I'll keep investigating @amitkumar3968

**Comment by pronevich** [comment] 2021-10-14 14:19
@amitkumar3968 looks like issue exists also in other projects without several jsi modules. Later I will try to return only reanimated module as per docs for the test.

**Comment by amitkumar3968** [comment] 2021-10-19 05:52
i am also facing issues with this version, not crash.
Seems like we have to switch to latest version or move to another library. 
WIP

**Comment by kkafar** [comment] 2022-01-28 10:54
Hey @pronevich!
Can you (or anyone) confirm this crash occurs on latest release version & reanimated is [installed properly](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#android)?

**Comment by pronevich** [comment] 2022-01-28 11:00
@kkafar I will update the project and look at the result, then give you feedback

**Comment by pronevich** [comment] 2022-02-08 08:19
@kkafar I don't see this crash in Crashlytics, but after update to the stable version has risen this issue:

```
Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException: Trying to resolve view with tag 913 which doesn't exist
       at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveView(NativeViewHierarchyManager.java:102)
       at com.facebook.react.uimanager.UIManagerModule.resolveView(UIManagerModule.java:964)
       at com.swmansion.reanimated.layoutReanimation.AnimationsManager.removeLeftovers(AnimationsManager.java:236)
       at com.swmansion.reanimated.layoutReanimation.AnimationsManager.lambda$scheduleCleaning$0$AnimationsManager(AnimationsManager.java:286)
       at com.swmansion.reanimated.layoutReanimation.-$$Lambda$AnimationsManager$wJRqdL09xrx99sALjL4PPWgrOyU.run(:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by kinigitbyday** [comment] 2022-02-24 18:22
@kkafar are there any plans to release a version with the merged fix soon? It's causing quite a few crashes in my app and I'd prefer to pull in an explicitly released version.

**Comment by elGatoMantocko** [comment] 2022-02-28 18:14
Is there a reason a patch with this change hasn't been released yet @kkafar? It's been almost three weeks and we are definitely seeing crashes in our app related to this and we can't get a build working with a git sha.

**Comment by kkafar** [comment] 2022-03-17 13:08
I won't give you specifics, but release is coming within days.

However as was mentioned above you can build reanimated from source, [which is extremely easy right now](https://github.com/software-mansion/react-native-reanimated/pull/2933).

**Comment by limaAniceto** [comment] 2022-03-21 10:33
@kkafar Just to share some insights regarding this crash:
1. At Mixcloud we've recently introduced reanimated 2, and we made use of the latest [SHA in master](https://github.com/software-mansion/react-native-reanimated/commit/d6d5f966a44b96ec3b1396a2a2d7c93b6a7abcf2)

2. We have followed/confirmed the [steps regarding the installation](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#android) and they are correct.

3. We still see the crashes as you can see in this screen-capture from firebase: 
![image](https://user-images.githubusercontent.com/2905749/159244028-7cbd104b-55e2-438a-8d59-5424540674ae.png)

I'd like to kindly ask if you could reopen this issue as it seems that it persists despite https://github.com/software-mansion/react-native-reanimated/pull/2982

**Comment by alexfoxy** [comment] 2022-05-26 07:14
We are also seeing this issue in our crashlytics:

<img width="1192" alt="Screenshot 2022-05-26 at 08 12 43" src="https://user-images.githubusercontent.com/151772/170437307-e3f9d323-0a0c-4c51-a294-828d21c750d6.png">

RN: 0.67.3
reanimated: 2.4.1
react-navigation: 6.1.1

**Comment by nickcruz** [comment] 2022-07-26 01:00
@alexfoxy are you still seeing that error? Maybe [`2.8.0`](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.8.0) fixed it for you? It includes this fix:
https://github.com/software-mansion/react-native-reanimated/pull/3162

Which seems to be the NPE you're seeing

**Comment by alexfoxy** [comment] 2022-12-05 08:39
@nickcruz Yes it seems fixed for us at least 🙏

**Closed** 2023-09-05 12:47 UTC
Labels: Bug, 🏠  Reanimated 2, Crash, Wait for reply, bug-bash-jan22
