### ISSUE TITLE
Invalid `RNReanimated.podspec` file: no implicit conversion of nil into Array

### ISSUE THREAD

**Issue by RohyAlboony** [software-mansion/react-native-reanimated#3790] opened 2022-11-17 12:38 UTC
### Description

After upgrading my expo app from expo v45 to v47
Changed react-native-reanimated version from 2.8.0 to 2.12.0

### Steps to reproduce

I try exceute this command 'eas build ' on android and ios
android is done without any problem
but ios build show errors :
![‏‏لقطة الشاشة (105)](https://user-images.githubusercontent.com/75141130/202448167-fb400010-c615-454f-b0ab-93eb45953c4a.png)

### Snack or a link to a repository

i not have

### Reanimated version

2.12.0

### React Native version

0.70.5

### Platforms

iOS

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2022-11-17 20:31
Hey, sorry for the inconvenience. Can you check if #3774 resolves the issue for you?

**Comment by RohyAlboony** [comment] 2022-11-17 21:04
> Hey, sorry for the inconvenience. Can you check if #3774 resolves the issue for you?

I looked at it before but I didn't understand what the solution is, what should I do?
thanks for your efforts

**Comment by tomekzaw** [comment] 2022-11-17 21:08
@RohyAlboony just manually apply [these](https://github.com/software-mansion/react-native-reanimated/pull/3774/files) changes in your `node_modules/react-native-reanimated/scripts/reanimated_utils.rb`

**Comment by RohyAlboony** [comment] 2022-11-17 21:20
> @RohyAlboony just manually apply [these](https://github.com/software-mansion/react-native-reanimated/pull/3774/files) changes in your `node_modules/react-native-reanimated/scripts/reanimated_utils.rb`

What does that do?
My project works in the case of local development
My problem occurs when uploading to Expo servers
And they don't take node_modules folder from me

**Comment by tomekzaw** [comment] 2022-11-17 21:26
Oh, right. In such case I think you can use [patch-package](https://www.npmjs.com/package/patch-package).

**Comment by RohyAlboony** [comment] 2022-11-17 21:36
> Oh, right. In such case I think you can use [patch-package](https://www.npmjs.com/package/patch-package).

I'm currently for workflow I've downgraded to v46 of expo and react-native-reanimated to v2.9.1 and it's fine
In your opinion, should I wait for the problem to be resolved in the main source code to then perform the update process, or do I update from now and use patch-package

**Comment by RohyAlboony** [comment] 2022-11-18 00:00
> There were some improvements between v2.9.1 and v2.12.0 but if Reanimated v2.9.1 works fine for you, then it definitely can wait and there's no need to patch it now.

Okay
Thank you very match

**Comment by ledesmaromeo** [comment] 2023-01-09 01:55
Hi all 👋  This could be a possible duplicate of issue [3574](https://github.com/software-mansion/react-native-reanimated/issues/3754).

But I'm going to post the solution that fixed this issue on my machine on this thread as well just in case:

1. `brew uninstall cocoapods`
2. `gem install cocoapods -v 1.10.1` (I'm using `rbenv` to manage my Ruby versions by the way)
3. Navigate to the `ios` directory
4. `pod install`

Hope this helps you too! 🤞

**Comment by piaskowyk** [comment] 2023-01-12 08:58
Should be fixed in 2.14.0 and in 3.0.0-rc.10

**Closed by piaskowyk** 2023-01-12 08:58 UTC
Labels: Missing repro, Platform: iOS, Needs review
