### ISSUE TITLE
error while running the iOS app on Macos M1

### ISSUE THREAD

**Issue by solitarysp** [software-mansion/react-native-reanimated#5969] opened 2024-05-02 10:43 UTC
### Description

Actual behavior & steps to reproduce
The app crashes on launch with the following error

/node_modules/react-native-reanimated/apple/LayoutReanimation/REAScreensHelper.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNReanimated' from project 'Pods').

Info:

System:
  OS: macOS 13.6
  CPU: (10) arm64 Apple M1 Pro
  Memory: 273.19 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: ~/.nvm/versions/node/v18.16.1/bin/node
  Yarn:
    version: 1.19.0
    path: ~/.nvm/versions/node/v18.16.1/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.1/bin/npm
  Watchman:
    version: 2023.09.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /Users/levanthanh/.sdkman/candidates/java/current/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Start run debug

### Snack or a link to a repository

no

### Reanimated version

3.5.0 to 3.10.0

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

None

### Build type

Debug app & production bundle

### Device

iOS simulator

### Device model

Iphone X

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2024-05-05 16:41
@solitarysp Thanks for reporting this issue.

It looks like duplicate of #5882 so I'm gonna close this one.

**Closed by tomekzaw** 2024-05-05 16:41 UTC
Labels: Missing repro, Platform: Android, Platform: iOS, Missing info
