### ISSUE TITLE
Reanimated breaks Realm on Android

### ISSUE THREAD

**Issue by limpbrains** [software-mansion/react-native-reanimated#2028] opened 2021-05-17 10:39 UTC
## Description

After adding Realm to `reanimated-2-playground` project and switching off Hermes (Realm doesn't support it) app starts crashing when Realm saves data.

### Expected behavior

Both packages should work fine together

### Actual behavior & steps to reproduce

App crashes with error like
```
A/libc: Fatal signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0 in tid 6328 (mqt_js), pid 6272 (llet.bluewallet)
```

## Snack or minimal code example

I've created a fork of playground to make it easy to reproduce https://github.com/limpbrains/reanimated-2-playground

App crashes here
```
const realm = await Realm.open({
  path: 'myrealm',
  schema: [TaskSchema],
});

let task1, task2;
realm.write(() => {
  task1 = realm.create('Task', {
    _id: 1,
    name: 'go grocery shopping',
    status: 'Open',
  });
  task2 = realm.create('Task', {
    _id: 2,
    name: 'go exercise',
    status: 'Open',
  });
  console.log(`created two tasks: ${task1.name} & ${task2.name}`);
});
```

Emulator was created by this script:
```
sdkmanager "system-images;android-28;default;x86_64"
echo no | sdkmanager --licenses
echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_API_29_AOSP --force --package "system-images;android-28;default;x86_64"
printf "\nhw.lcd.height=1334\nhw.lcd.width=750\nhw.lcd.density=320\nskin.name=750x1334" >> ~/.android/avd/Pixel_API_29_AOSP.avd/config.ini
```

## Package versions

- React Native: 0.63.4
- React Native Reanimated: 2.1.0 
- NodeJS: 14.16.1
- Java: openjdk version "12.0.1" 2019-04-16

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by somebody32** [comment] 2021-05-21 10:59
I would link another issue with realm and reanimated 2 here: https://github.com/software-mansion/react-native-reanimated/issues/1424, maybe it would be easier to debug them together

**Comment by klandell** [comment] 2021-08-24 15:57
Are there any updates on this? Based on my previous experiences with Realm, the issue is probably on their side and may never be fixed, but just wondering if anyone has any leads on this issue. The incompatibility between Realm and Reanimated v2 is a pretty big blocker in my app.

**Comment by Obhenimen** [comment] 2021-09-03 15:07
The issue is from realm library. Currently, realm does not support Hermes....or let me say the support for hermes on realm is still on going. Since the reanimated 2 library depends on hermes, it won't be possible to use reanimated 2 with realm.
Remedy: You can either use the reanimated library version 1x which would work fine with realm or you use another database like watermelon DB together with the reanimated 2x library. The choice is yours

**Comment by liamjones** [comment] 2021-09-03 16:31
> the reanimated 2 library depends on hermes
Not true, JSC also works since 2.2.0 but there's still a conflict - see https://github.com/realm/realm-js/issues/3837

**Comment by j-piasecki** [comment] 2022-01-28 10:15
Hi! Are you still experiencing this problem after upgrading the libraries?

**Comment by liamjones** [comment] 2022-01-31 09:02
FYI Realm have apparently fixed it from their side but it's only on their pre-release Hermes branch atm: https://github.com/realm/realm-js/issues/3837#issuecomment-1025494411

Note, while it is the Hermes branch, they've confirmed it fixes things for the JSC too: https://github.com/realm/realm-js/issues/3837#issuecomment-1025509204

**Comment by j-piasecki** [comment] 2022-02-09 12:09
In that case, I will close this issue.

**Closed by j-piasecki** 2022-02-09 12:09 UTC
Labels: 🐞 Bug, 🏠  Reanimated2, bug-bash-jan22
