### ISSUE TITLE
[ios][bug] Huge issue with LayoutAnimation - Single `Animated.View` with `layout` prop is enough to break un-mounting and de-allocation of any View which has been popped/swiped-back/closed/destroyed via navigation

### ISSUE THREAD

**Issue by hirbod** [software-mansion/react-native-reanimated#3124] opened 2022-04-01 00:47 UTC
## Description

@piaskowyk @kmagiera

I have found a serious bug with LayoutAnimation. I have been trying to investigate the problem for several days, which is why videos that were in a screen or modal that I closed (goBack/pop/swipe to dismiss) still played even though everything was un-mounted and destroyed. The same is true for cameras (Green Light Indicator is no longer out).

It is sufficient to have a single `Reanimated.View` / `createAnimatedComponent` ANYWHERE in the app which uses `layout, entering or exiting` prop from Reanimated. Once a single `View` with that prop has been mounted (no matter where), no element that is in a navigation stack will be unmounted anymore, even if the layout hierarchy and lifecycle methods reports that it has been unmounted (eg cleanup function of `useEffect`). When you remove something conditionally on the screen (eg. with `useState`), un-mounting works fine. But it looks like a single use of `LayoutAnimation` is enough to break element un-mounting / de-allocation when closing Navigators, because (this is my guess) LayoutAnimation is still "watching all of them (or snapshotting?)" in order to be able to animate the layout, even when those views are in different screens. Maybe RNS is also an issue here?

I also did some tests, such as setting breakpoints at the deallocate function of expo-av. The methods were never called when `layout, entering` or `exiting` were present and mounted anywhere in the app. But if no `Reanimated.View` with `layout` was used the breakpoints triggered.

I have also created a video as well as a repro which can be tested with Expo Go.

### Expected behavior

Views should correctly un-mount and deallocate once a Navigation screen has been dismissed / popped etc, even when using `LayoutAnimation`.

### Actual behavior & steps to reproduce

To test my findings, simply grab my repro, spin it up, open Tab One and tap on the info icon at the top (headerRight) - as many times as you like. The video will start and stop as soon as the modal has been closed. But if you now switch to Tab two, which mounts a `Reanimated.View` with `layout={Layout}`, (imported from REA) and you now simply return to Tab one, you will notice that the video will continue to run as soon as you open and close the modal and it will start multiple videos until the App crashes eventually. If you remove `layout` from Tab two, you can open and close the modal 1000x and it will work fine. Please note that you need to restart the app when you add or remove `layout`, fast-refresh is not enough.

I provided a repro and all informations in my issue + in my repro App as `Text`.
Here is also a Video showing the issue (watch with audio please)

### Watch with audio

https://user-images.githubusercontent.com/504909/161172649-3d2b600d-41fb-47ec-87bd-89c69f55fe15.mp4

## Snack or minimal code example

https://github.com/hirbod/react-reanimatad-layoutanimation-bug

And this single `layout` prop is enough to trigger the issue (once mounted):
https://github.com/hirbod/react-reanimatad-layoutanimation-bug/blob/main/screens/TabTwoScreen.tsx#L7

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.64.3    |
| react-native-reanimated              |   2.5.0   (but breaks with any version that has LayoutAnimation)   |
| Xcode                                |   13.3      |
| expo                                 |  SDK 44       |

## Affected platforms

- [ ] Android
- [X] iOS
- [ ] Web

Here is a cross link to RNS, since I am not sure if RNS or REA is the root issue:
https://github.com/software-mansion/react-native-screens/issues/1379

**Comment by adgarcia** [comment] 2022-04-01 04:19
Nice timing; we ran into this bug about 2 hours ago. Like you said any exit/enter/layout prop anywhere breaks anything in a navigation stack everywhere.

**Comment by LeviWilliams** [comment] 2022-04-01 19:38
Thank you so much for posting this, we have been racking our brains at why all kinds of random things in our app stopped working when we added reanimated v2 (images, svgs, other animations, etc). As soon as we remove the entering/exiting props across the application everything works as normal.

Weirdly enough in our case iOS is not affected but Android in. This is a massive blocker for us, anyway we could get some eyes on this when you guys have some time? @j-piasecki

**Comment by RMG0** [comment] 2022-04-01 19:57
I am facing the same issue like when we use entering/exiting/layout prop from reanimated V2 some of the ui views goes invisible. Thanks for investigating this and bringing this up as this is hard to debug and find the root cause. When I commented all entering/exiting/layout props, it works perfectly. A huge blocking for our case as we added many animations and now this adds visibility issue for other UIs.
Also, this is for android only in my case
It would be great if someone can look into this.

**Comment by hirbod** [comment] 2022-04-01 20:41
Glad that my findings helped you. I searched 15 hours without sleep until I found this issue :D 
I did not encounter bugs on Android though, at least in my specific scenario.

**Comment by hirbod** [comment] 2022-04-01 20:48
I think it would be helpful if you guys could also provide a failing repro on Android, this might help to get both issues resolved. I kinda feel like this won't be an easy fix though.

**Comment by LeviWilliams** [comment] 2022-04-01 21:32
@hirbod I'll try to get a minimum repro on Android out asap. We're using exiting/entering in a much larger capacity than just on some lists so we would have to rewrite lots of this with normal react native animations. Would be unfortunate with all the benefits reanimated brings. Also surprised this has not been reported sooner, seems like a severe issue to me.

**Comment by hirbod** [comment] 2022-04-01 21:38
I mean, there are alternatives, like https://moti.fyi which use reanimated under the hood without LayoutAnimation (but be careful, they also added support for LayoutAnimation from REA as well).
Its pretty straightforward to animate (also entering/exiting) with AnimatePresence, but there is no comparison to LayoutAnimation (specially how easy it is to use).

The issue is severe, I think the feature is just "too new" and not adopted widely enough. Thats why nobody had complaints so far. And I think its pretty hard to find the root cause when things start acting weird (like elements not un-mounting). I would've been curious if I had a LayoutAnimation on a `Video`, but for me it was a Button inside a invisible (but mounted) tab.

**Comment by pairohit305** [comment] 2022-04-01 21:58
I am too facing the same issue on android 
![image](https://user-images.githubusercontent.com/36040318/161346669-44c3ffc3-d9c4-441a-b124-9ab942b01cb6.png)

**Comment by hirbod** [comment] 2022-04-01 22:08
I think thats something different @pairohit305. We should try not to mix up different issues.

**Comment by RMG0** [comment] 2022-04-01 22:11
@pairohit305 , this is a different(crash) issue so lets not mix this with thread
Thank you

**Comment by piaskowyk** [comment] 2022-04-05 20:15
@hirbod Hey, I have just started to investigate it. This is a priority issue, I will notify you about progress.

**Comment by hirbod** [comment] 2022-04-05 20:17
@piaskowyk thank you very much! Appreciated.

**Comment by mateioprea** [comment] 2022-04-06 15:25
I'm also affected by this. I've created a view with a hardcoded height and tried to layout animate only that view using 

```
if ( [targetValues[@"height"] isEqualToNumber:@329] ) {}
```
in - onViewCreate:() in REAAnimationsManager. 

and it works. the unmounted views are deallocated. 
This is visible when using AVPlayer and Navigation.reset().

**Comment by LeviWilliams** [comment] 2022-04-06 15:51
In our case, we were able to resolve some of our issues by reordering the hierarchy. We realized that lots of views using zIndex were affected and what was happening was the views were being rendered in the wrong order causing them to be fully under the root views (????). Still, we observed odd mounting/unmounting behaviour while fixing this and reordering things, certain orders worked and certain didn't. Also to be clear these affected views had no relation to any form of layout animations and were even in different navigation stacks.

**Comment by hirbod** [comment] 2022-04-06 18:30
We need to clearly distinguish between all the other errors reported here:

1) My error is related to iOS - un-mounting and de-allocation of views, most likely there 
is something in REA and RNS causing this
2) Similar/related issues reported in this thread for Android (still missing a reproduction for this)
3) Another report for iOS, with reproduction, most likely related:  
https://github.com/software-mansion/react-native-reanimated/issues/3093
Duplication of Nodes, especially when react-native-svg is used.

All of this might be related or isolated issues.

**Comment by LeviWilliams** [comment] 2022-04-06 21:53
Following up here as we have reproduced what @hirbod initially reported. Our iOS app is affected by an RTMP stream never releasing even when unmounted, similar problem to what is displayed in the reproduction. 

We can still try to reproduce the zIndex hierarchy issue in a repo if necessary. We've currently spent a whole pile of time debugging all these issues so reproduction has been a little delayed so far.

**Comment by piaskowyk** [comment] 2022-04-07 21:53
Good news, I found the cause of the issue today and I know how to resolve it.

**Comment by hirbod** [comment] 2022-04-07 22:59
This one specific or all of them? :)

**Comment by RMG0** [comment] 2022-04-07 23:12
I hope root issue fix would all case :) 
Thank you for all efforts

**Comment by nhanders** [comment] 2022-04-12 15:14
> * Similar/related issues reported in this thread for Android (still missing a reproduction for this)

@hirbod #2906 provides an android repro for the android issues reported here, but it seems like a separate issue to what is being addressed in PR #3157.

**Comment by hirbod** [comment] 2022-04-12 17:41
@piaskowyk there are plenty reports for Android as well. Hopefully we can get all of them sorted :)
Thanks for providing a repro, I am sure thats helpful.

**Comment by bfricka** [comment] 2022-05-04 01:21
This thread relates to iOS, but it seems to occur on Android as well. I've been working on a very inefficient `ScrollView` (to be replaced later by something fast), and it exposed this issue quickly. Navigating to a few of these views is enough to hang the app, and removing layout animations from a single, completely unrelated component, fixes this.

I'm not sure how to concretely provide a reproduction case on Android, but I can certainly verify that removing the one and only layout animation we're currently using fixes it.

If there's anything I can do to help, please let me know.

**Comment by hirbod** [comment] 2022-05-04 02:36
LayoutAnimation is undergoing a rewrite, since fixing this issue seems to be something bigger. I think parts of it are cpp, so chances might be that they will fix issues on android as well - but I have to deep knowledge about that. There haven't been any acknowledgments towards android so far, there are also some pretty annoying scrollview issues (android only) going on with reanimated.

**Comment by michbil** [comment] 2022-05-06 12:18
@hirbod Yeah, my comment is mainly for somebody, who has issue on android.

**Comment by bfricka** [comment] 2022-05-07 02:43
@michbil I'm using 2.8.0 on Android and this issue is not fixed for me. Everything I mentioned in my original reply stands.

**Comment by lyqht** [comment] 2022-05-13 12:11
Using 2.8.0, layout animation is very laggy on Android, while the following error is thrown on iOS.

```
Exception thrown while executing UI block: RCTScrollView may only contain a single subview, the already set subview looks like: <RCTScrollContentView: 0x7fdb56279760; reactTag: 11115; frame = (0 0; 0 0); layer = <CALayer: 0x6000036ad000>>


__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1201
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.498
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

**Comment by ziyoshams** [comment] 2022-05-23 14:54
@hirbod thank you for  digging into this. I was so lost when i had this exact issue with a video.

**Comment by the-mad** [comment] 2022-06-06 12:37
Hello 👋 any news on this ? I'm still facing this issue with version 2.8.0 on iOS 15.5 (RN version 0.66.4).

**Comment by ddikodroid** [comment] 2022-06-26 06:03
Okay, turns out some people are facing the same issue. When I use LayoutAnimation, my loading skeleton stuck/freeze on the screen even the loading state is false.

**Comment by mercpls** [comment] 2022-06-28 18:44
Still having this issue, our tab navigator explodes, and an entire screens visuals don't render.

**Comment by Titozzz** [comment] 2022-07-07 19:51
> reanimated

I can confirm seeing the exact same stack trace on iOS (rea 2.8.0)

**Comment by geoapostolidis** [comment] 2022-07-25 12:03
is there any news with that ?

**Comment by anhnch** [comment] 2022-08-01 04:42
For me, all I need to replicate is just an 
```typescript
import Animated from 'react-native-reanimated';
```
When I go to any screen and go back (by navigation back, or programmatically navigation.goBack()), the screen is not responding to touch/scroll. The screen is still functioning properly, but you simply can't do anything. No error, no log, nothing. When I inspect the layout, there's no component on top covering below.

Because the problem occurs when navigating and react-navigation does use react-native-reanimated, so I think it's incompatibility with react-navigation. This is a serious blocking issue.
```
Platform: iOS (Android is FINE)
iOS: 14.7
React Native: 0.68.2
Packages
react-native-reanimated: 2.9.1
react-native-gesture-handler: 2.5.0
react-native-safe-area-context: 4.3.1
@react-navigation/drawer: 6.4.3
@react-navigation/native: 6.0.11
@react-navigation/stack: 6.2.2
react-native-screens: 3.15.0
```

**Comment by BalogunofAfrica** [comment] 2022-08-03 09:34
Had this same issue for a long time.

Importing and calling `enableLayoutAnimations` in `App.tsx` fixed it for me


```tsx
import { enableLayoutAnimations } from "react-native-reanimated";
...
function App() {
...
    enableLayoutAnimations(true);
...
}
```


Related isssue: https://github.com/software-mansion/react-native-reanimated/issues/2758

**Comment by hirbod** [comment] 2022-08-03 11:53
This might fix A issue, not THE root issue.

> Had this same issue for a long time.
> 
> Importing and calling `enableLayoutAnimations` in `App.tsx` fixed it for me
> 
> ```tsx
> import { enableLayoutAnimations } from "react-native-reanimated";
> ...
> function App() {
> ...
>     enableLayoutAnimations(true);
> ...
> }
> ```
> 
> Related isssue: #2758

**Comment by jrhager84** [comment] 2022-08-03 19:27
I'm having the same issue.

**Comment by jrhager84** [comment] 2022-08-15 02:14
> Good news, I found the cause of the issue today and I know how to resolve it.

Did you ever get it resolved? I still have the issue

**Comment by ddikodroid** [comment] 2022-08-15 12:01
> Did you ever get it resolved? I still have the issue

have you tried to add

```
enableScreen()
```

from react-native-screen

**Comment by jrhager84** [comment] 2022-08-16 03:22
> > Did you ever get it resolved? I still have the issue
> 
> have you tried to add
> 
> ```
> enableScreen()
> ```
> 
> from react-native-screen

It does not work. I've tried every combo of `enableScreens()` and `enableLayoutAnimations()` to no avail. Just adding an animated view with an entering prop ANYWHERE will break it. It's VERY frustrating and seems to be a rather large problem. Is there any headway on this???

**Comment by hirbod** [comment] 2022-08-16 07:44
LayoutAnimations are still being rewritten. Follow the status here

**Comment by ShadReyes** [comment] 2022-09-15 19:09
For me, using reanimated v2.10.0, I was only running into problems on Android. I was able to fix the issue by replacing "LayoutAnimation.Create(...)" with a hard coded object. Something with LayoutAnimationConfig must be broken. I also experienced the navigation issue on Android as discussed by @hirbod

`LayoutAnimation.configureNext(
      {
        duration: 500,
        create: {
          type: LayoutAnimation.Types.easeInEaseOut,
          property: LayoutAnimation.Properties.opacity,
        },
        update: {
          type: LayoutAnimation.Types.easeInEaseOut,
        },
      }
      // LayoutAnimation.create(500, LayoutAnimation.Types.easeInEaseOut, LayoutAnimation.Properties.opacity)
    );`

**Comment by hirbod** [comment] 2022-09-16 08:14
@ShadReyes you're referring to react-native core LayoutAnimations, has nothing to do with the one by reanimated

**Comment by arnaspeciukonis123** [comment] 2022-09-21 05:44
@hirbod Big thanks for documenting this issue, had my head wrapped around this issue combined with react native video lib. 

Currently, our team just removed all instances of LayoutAnimations and now react native video player instance removes itself on back navigation.

Waiting to see if that rewrite fixes the issue.

**Comment by davidskaarup** [comment] 2022-10-06 09:08
It seems like the is no activity in the rewrite branch since early July. We basically cannot use layout animation in its current state and I suspect many are in the same situation.
Is there any workaround we can do to be able to use layoutanimation until a rewrite/fix is out?

**Comment by hirbod** [comment] 2022-11-18 10:19
FYI: Reanimated V3 RC6 includes the all new LayoutAnimation rewrite. I think its time to close this issue, right @piaskowyk ? :)

**Comment by paullinator** [comment] 2022-11-28 05:08
@hirbod  LayoutAnimations with V3 RC6 seem even more broken. I get screen corruption and frozen UI as soon as layout animations are enabled. I haven't filed an issue yet, but wondering if anyone else is seeing this with RC6

**Comment by hirbod** [comment] 2022-11-28 15:00
@paullinator I am currently on vacation and did not test the RC, I was just spreading the news. Filing issues with repos and videos is helpful, as SWM asked for testers and reports!

**Comment by caolong0204** [comment] 2023-01-18 09:12
waiting for  resolve :((

**Comment by TomasSestak** [comment] 2023-01-24 13:18
Cant use the functionality at all until this is fixed

**Comment by zhelezkov** [comment] 2023-01-27 23:17
I guess #3865 is supposed to fix this one?
Faced same issue in our project, will try to validate if it still persist

**Comment by iway1** [comment] 2023-02-01 03:20
So this isn't getting fixed ever in v2? (That's what it seems like reading this thread)

If so, the API should be marked as deprecated and the recommendation should be to not use it in v2 at least. Pretty scary to have an API that can just brick an app with no error message

**Comment by iway1** [comment] 2023-02-01 03:23
probably should mark the API as "not safe for use" or something until the rewrite is finished considering it can just brick an app with no error message - I've been using the API quite a lot and had no idea it had this problem until it happened to me.

**Comment by ziyoshams** [comment] 2023-02-01 03:26
> probably should mark the API as "not safe for use" or something until the rewrite is finished considering it can just brick an app with no error message - I've been using the API quite a lot and had no idea it had this problem until it happened to me.

Have you tried the latest RC? It has the rewrite.

**Comment by iway1** [comment] 2023-02-01 03:28
@ziyoshams no but I'm not super comfortable migrating my apps to an RC

**Comment by ziyoshams** [comment] 2023-02-01 03:33
@iway1 don't migrate. See if the new layout rewrite fixes your issues.

**Comment by iway1** [comment] 2023-02-03 18:36
@ziyoshams turns out mine had nothing to do with this issue

**Comment by Bowlerr** [comment] 2023-02-15 10:50
Any news on this one?

**Comment by nateshmbhat** [comment] 2023-03-05 11:43
any update on this issue ?

**Comment by hirbod** [comment] 2023-03-05 12:57
Reanimated v3 was released three days ago. All of these issues should be fixed.

**Comment by kirbi96** [comment] 2023-03-14 10:01
resolve for me after update to 3.2.0 version

**Closed** 2023-05-18 18:39 UTC
Labels: Important, Platform: iOS, Needs review, Repro provided

**Comment by piaskowyk** [comment] 2023-05-19 08:13
@hirbod glad to read it 😊

**Comment by dFelinger** [comment] 2023-11-21 06:19
Using @react-navigation/native-stack with react-native-vision-camera when I navigate back from stack screen with camera there is green dot on iOS still active. What am I doing wrong? react-native-reanimated is in the project with version 3.5.4

**Comment by vargajacint** [comment] 2023-11-21 06:29
@dFelinger I think you missed this:

```
function App() {
  const isFocused = useIsFocused()
  const appState = useAppState()
  const isActive = isFocused && appState === "active"

  return <Camera {...props} isActive={isActive} />
}

```

**Comment by dFelinger** [comment] 2023-11-21 14:29
In **@react-navigation/native-stack** page is not rendering on out even if I use useIsFocused - isFocused is never in false state.
