### ISSUE TITLE
[iOS] Bad scroll performance on reanimated vs react-native

### ISSUE THREAD

**Issue by lindesvard** [software-mansion/react-native-reanimated#309] opened 2019-06-11 09:02 UTC
Did notice some bad performance when doing a simple onScroll and translateY on a Animated.ScrollView and Animated.View. 

The transition is very "sluggish" on the Animated.View *when* using reanimated. Haven't seen this issue before. Tried exact same example with react-native's animated api and there it works smoothly.

Here is a streamable and a comparison: https://streamable.com/rsayg
Have also created a repo with this example (it's more noticeable when running on a device): https://github.com/lindesvard/reanimated-scroll-perf

Versions: 
```
"react": "16.8.3"
"react-native": "0.59.9"
"react-native-gesture-handler": "^1.3.0"
"react-native-reanimated": "^1.0.1"
```

Tried this on: sim (iphone x) and device iphone 6s

edit: This is only on momentum scroll what I have noticed

**Comment by terrysahaidak** [comment] 2019-06-11 09:04
Duplicate of https://github.com/kmagiera/react-native-reanimated/issues/160

**Comment by lindesvard** [comment] 2019-06-12 07:27
Feels like this issue is a quite big dealbreaker? @kmagiera, @osdnk Have you looked at this issue? Or might now what causing this? Would love to help in some way but don't know where to start/look.

**Comment by mickejohansson** [comment] 2019-06-12 07:28
ons 12 juni 2019 kl. 09:27 skrev Carl-Gerhard Lindesvärd <
notifications@github.com>:

**Comment by Strate** [comment] 2020-06-03 18:18
I can say that same issue exists for android. I've tried to implement stiky list elements, and reactr-native's Animated works much more smooth than reanimated

**Closed** 2020-11-20 12:06 UTC
Labels: Performance, 🍎iOS

**Comment by Strate** [comment] 2020-11-23 19:27
@jakub-gonet sorry for ping, but I have a question - is it closed as "resolved", or "wont fix", or "cant reproduce"?

**Comment by jakub-gonet** [comment] 2020-11-23 19:58
I was under impression this was a duplicate of #160. Let me know if that's not the case.

**Comment by Strate** [comment] 2020-11-23 20:46
@jakub-gonet looks like duplicate, thank u.
