### ISSUE TITLE
Cannot read property 'useSharedValue' of undefined

### ISSUE THREAD

**Issue by ZeroPie** [software-mansion/react-native-reanimated#3197] opened 2022-04-26 23:05 UTC
## Description

```
new nativeeventemitter() requires a non-null argument
TypeError: Cannot read property 'useSharedValue' of undefined
```
![Screenshot 2022-04-26 at 17 16 02](https://user-images.githubusercontent.com/8741666/165401611-58d80276-4e07-457a-a002-e37c576d5ebf.png)

![Screenshot 2022-04-26 at 18 09 17](https://user-images.githubusercontent.com/8741666/165407278-b7cba6f7-049f-46d4-8cf2-fc82b9ef66b1.png)

### Expected behavior
useSharedValue works

### Actual behavior & steps to reproduce
```package.json
"react-native-reanimated": "^2.8.0",
"react-native": "0.66.1",
```
``` babel.config.js
module.exports = {
  presets: ['module:metro-react-native-babel-preset', 'module:react-native-dotenv'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src/'],
      },
    ],
    'react-native-reanimated/plugin',
  ],
```

## Snack or minimal code example

```home.tsx
import { useSharedValue } from 'react-native-reanimated';

export default function Home() {
  
  const width = useSharedValue(50);
 ...
  return (
    <>
        ...
    </>
  );
}
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |^0.66.1 |
| react-native-reanimated     |^2.8.0 |
| NodeJS                               | 16.13.1 |
| Xcode                                | 13.1 |
| Java                                 | 8.0.292.hs-adpt|
| Gradle                               |7.4.1|
| expo                                 | --- |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by TusharShahi** [comment] 2022-11-11 07:45
Affects android too. I am using a mac.

**Comment by opensourcecheemsburgers** [comment] 2023-01-14 02:52
I spent hours trying various fixes for this problem on Android. For me, the solution was to manually link Reanimated.

In your project's `settings.gradle` file, add:

```
include ':react-native-reanimated'
project(':react-native-reanimated').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-reanimated/android')
```

In your **app's** `build.gradle` file, add:

```
implementation project(':react-native-reanimated')
```

In your `MainApplication`.java file, import and link the package:

```
import com.swmansion.reanimated.ReanimatedPackage
```

```java
@Override
protected List<ReactPackage> getPackages() {
	return Arrays.asList(new ReanimatedPackage());
}
```

**Comment by Latropos** [comment] 2023-12-14 16:06
Closing, it looks that this problem was caused by invalid configuration. Luckily we have improved our documentation to make it easier for our users to use our library

**Closed by Latropos** 2023-12-14 16:06 UTC
Labels: Missing repro, Platform: iOS, Needs review
