### ISSUE TITLE
Keyframe.ts: Container is falsy & configureProps is not a function

### ISSUE THREAD

**Issue by maluramichael** [software-mansion/react-native-reanimated#3429] opened 2022-08-01 10:38 UTC
## Description

```sh
node_modules/react-native-reanimated/src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts: 
/Users/michael/development/lulububu/jackle-heidi-app/node_modules/react-native-reanimated/src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts: Container is falsy

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

I updated the dependencies of our project to the latest reanimated version and since then i get the Error `Container is falsy` in the Keyframe.ts.

## Snack or minimal code example

https://snack.expo.dev/@endless90/thankful-truffles

Hard to recreate because we don't use expo. In the preview everything works as expected.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    ^0.68.2     |
| react-native-reanimated              |    ^2.9.1     |
| NodeJS                               |    v17.2.0     |
| Xcode                                |   Version 13.4.1 (13F100)      |
| Java                                 |    openjdk 11.0.15 2022-04-19     |
| Gradle                               |     x    |
| expo                                 |     x    |

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by tomekzaw** [comment] 2022-08-02 13:10
Hello @maluramichael! Thanks for submitting this issue.

First, please clear your application cache with `yarn start --reset-cache`.

If this doesn't help, please try the solution from this issue:
* https://github.com/facebook/react-native/issues/30581

**Comment by maluramichael** [comment] 2022-08-03 12:17
Thanks @tomekzaw that helped. But now i get another error only on android.

![image](https://user-images.githubusercontent.com/1489383/182605263-7b0a79c3-aa7b-4fdd-9ad7-2892321d98b7.png)

Will the library be autolinked or do i have to add it to the list of Packages?

```
public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost =
            new ReactNativeHost(this) {
                @Override
                public boolean getUseDeveloperSupport() {
                    return BuildConfig.DEBUG;
                }

                @Override
                protected List<ReactPackage> getPackages() {
                    long size = 50 * 1024L * 1024L;
                    ReactDatabaseSupplier.getInstance(getApplicationContext()).setMaximumSize(size);

                    @SuppressWarnings("UnnecessaryLocalVariable")
                    List<ReactPackage> packages = new PackageList(this).getPackages();
                    // Packages that cannot be autolinked yet can be added manually here, for example:

                    return packages;
                }

                @Override
                protected String getJSMainModuleName() {
                    return "index";
                }
            };
```

I added the lib to my build.gradle under depdendencies

```sh
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'com.google.firebase:firebase-analytics:21.1.0'
    implementation 'com.android.support:support-annotations:28.0.0'

    implementation project(':react-native-inappbrowser-reborn')
    implementation project(':react-native-maps')
    implementation project(':react-native-touch-through-view')
    implementation project(':react-native-screens')
    implementation project(':lottie-react-native')
    implementation project(":react-native-android-keyboard-adjust")
    implementation project(':react-native-svg')
    implementation project(':react-native-device-info')
    implementation project(':react-native-reanimated')
```

**Comment by tomekzaw** [comment] 2022-08-03 13:09
> Will the library be autolinked or do i have to add it to the list of Packages?

Reanimated 2.9.1 is automatically linked on Android, you don't need to edit Java files like in older versions.

> I added the lib to my build.gradle under depdendencies

This is also done by autolinking mechanism and thus not necessary.

**Comment by maluramichael** [comment] 2022-08-07 00:14
Hey @tomekzaw i think i tried everything but i still get the Container is falsy error. Can you give me hint on how to debug the error?

I even forced the version in all packages to reanimated 2.9.1.

```
"devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.3.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "22.4.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "detox": "^18.23.1",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.4.0",
    "gulp-debug": "^4.0.0",
    "gulp-image-resize": "^0.13.0",
    "gulp-rename": "^1.2.2",
    "jest": "22.4.2",
    "jetifier": "^1.6.4",
    "lodash": "^4.17.21",
    "lottie-ios": "^3.2.3",
    "lottie-react-native": "^5.1.3",
    "metro-react-native-babel-preset": "^0.72.0",
    "react-native-animated-pagination-dot": "^0.3.2",
    "react-native-haptic-feedback": "^1.14.0",
    "react-native-pager-view": "^6.0.0-rc.2",
    "react-native-reanimated": "2.9.1",
    "react-native-touch-through-view": "github:LulububuApps/react-native-touch-through-view",
    "react-test-renderer": "^16.3.0-alpha.1",
    "redux-immutable-state-invariant": "^2.1.0",
    "run-sequence": "^2.2.1"
},
```
```
"dependencies": {
    "@babel/plugin-transform-flow-strip-types": "^7.3.4",
    "@react-native-community/async-storage": "^1.6.2",
    "@react-native-community/datetimepicker": "^3.0.9",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "apisauce": "^1.1.1",
    "autobind-decorator": "^2.4.0",
    "axios-curlirize": "^1.3.7",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-app": "^7.0.1",
    "babel-preset-react-native": "^5.0.2",
    "babel-preset-stage-2": "^6.24.1",
    "build-url": "^2.0.0",
    "fs": "0.0.1-security",
    "fsevents": "^1.2.4",
    "glob": "^7.1.3",
    "gulp-imagemin": "^4.1.0",
    "gulp-zip": "^5.0.1",
    "immutability-helper": "^3.0.1",
    "jsonfile": "^4.0.0",
    "mocha": "^5.2.0",
    "moment": "^2.24.0",
    "prop-types": "^15.6.2",
    "react": "17.0.2",
    "react-native": "^0.68.2",
    "react-native-android-keyboard-adjust": "github:LulububuApps/react-native-android-keyboard-adjust",
    "react-native-animatable": "^1.3.1",
    "react-native-animated-overlay": "0.0.10",
    "react-native-cli": "^2.0.1",
    "react-native-collapsible": "^1.5.2",
    "react-native-confetti": "^0.1.0",
    "react-native-deep-linking": "^2.2.0",
    "react-native-device-info": "^5.5.4",
    "react-native-dialogs": "^1.0.2",
    "react-native-geocoding": "^0.5.0",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-i18n": "github:LulububuApps/react-native-i18n#feature/SKELETONRN-603-update-skeleton",
    "react-native-image-gallery": "git+ssh://git@github.com/ever-digital/react-native-image-gallery.git#master",
    "react-native-in-app-notification": "^3.1.0",
    "react-native-inappbrowser-reborn": "^3.5.1",
    "react-native-linear-gradient": "^2.5.3",
    "react-native-maps": "0.27.1",
    "react-native-masked-text": "^1.6.5",
    "react-native-modal-datetime-picker": "^9.1.0",
    "react-native-orientation": "github:LulububuApps/react-native-orientation#feature/SKELETONRN-602-update-skeleton",
    "react-native-pulse": "^1.0.7",
    "react-native-push-notification": "^7.3.1",
    "react-native-restart": "0.0.9",
    "react-native-screens": "^2.8.0",
    "react-native-sensitive-info": "git+ssh@github.com:mCodex/react-native-sensitive-info.git#keystore",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-navigation": "4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-redux-helpers": "^4.0.1",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.5.6",
    "react-redux": "^6.0.1",
    "redux": "^3.7.2",
    "redux-devtools-extension": "^2.13.2",
    "redux-logger": "^3.0.6",
    "redux-middleware-debounce": "^2.0.3",
    "redux-mock-store": "^1.5.3",
    "redux-persist": "^6.0.0",
    "redux-persist-sensitive-storage": "^1.0.0",
    "redux-promise": "^0.5.3",
    "redux-saga": "^0.16.2",
    "redux-thunk": "^2.2.0"
},
```
```
"overrides": {
    "react-native-tab-view": {
        "react-native-reanimated": "2.9.1"
    },
    "react-navigation-drawer": {
        "react-native-reanimated": "2.9.1"
    },
    "react-navigation-tabs": {
        "react-native-reanimated": "2.9.1"
    }
},
"resolutions": {
    "react-native-reanimated": "2.9.1"
}
```

```sh
npm ls react-native-reanimated
react-native-skeleton@0.0.1 /Users/michael/development/app
├── react-native-reanimated@2.9.1
├─┬ react-navigation-drawer@2.7.2
│ └── react-native-reanimated@2.9.1 deduped
└─┬ react-navigation-tabs@2.11.2
  ├── react-native-reanimated@2.9.1 deduped
  └─┬ react-native-tab-view@2.16.0
    └── react-native-reanimated@2.9.1 deduped

```

**Comment by tomekzaw** [comment] 2022-08-11 06:51
Hey @maluramichael, did you manage to resolve the error "Container is falsy"? 😅 

> Thanks @tomekzaw that helped. But now i get another error only on android.

> i think i tried everything but i still get the Container is falsy error.

**Comment by maluramichael** [comment] 2022-08-11 06:54
@tomekzaw sadly no. I had to release our app so i removed all imports to reanimated in all node_modules for now. But i would like to resolve this problem. Right now i don't know how.

I installed the latest version of reanimated, forced dependencies to use the latest version and cleaned all caches.

**Comment by tomekzaw** [comment] 2022-08-11 08:42
@maluramichael I created a fresh RN 0.68.2 app with the following command:

```
yarn react-native init Issue3429 --version 0.68.2
```

Then I copied all `dependencies` and `devDependencies` from your comment except for these two which I cannot access:

```diff
-"react-native-image-gallery": "git+ssh://git@github.com/ever-digital/react-native-image-gallery.git#master",
-"react-native-sensitive-info": "git+ssh@github.com:mCodex/react-native-sensitive-info.git#keystore",
```

I also added `overrides` and `resolutions` field, installed dependencies with `yarn`, and checked the output of `npm ls`:
   
```
➜  Issue3429 git:(master) ✗ npm ls react-native-reanimated
Issue3429@0.0.1 /Users/tomekzaw/RNOS/Issue3429
├── react-native-reanimated@2.9.1
├─┬ react-navigation-drawer@2.7.2
│ └── react-native-reanimated@2.9.1 deduped
└─┬ react-navigation-tabs@2.11.2
  ├── react-native-reanimated@2.9.1 deduped
  └─┬ react-native-tab-view@2.16.0
    └── react-native-reanimated@2.9.1 deduped
```

I've used [this](https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/keyframeAnimations/#example) example from Reanimated docs which I copied to `App.js` and added some imports.

Unfortunately, I was still not able to reproduce the issue – it works properly both on Android and iOS:

https://user-images.githubusercontent.com/20516055/184095150-6f163d8d-35e5-464b-88c7-286dc26569d7.mov

This suggests that there is some kind of problem with your setup or config.

I've uploaded the repo to GitHub: https://github.com/tomekzaw/Issue3429 Feel free to check if it works for you.

**Comment by stee1ix** [comment] 2023-08-07 11:52
I'm facing this issue as well. **Keyframe.ts: Container is falsy**

**Comment by metrix-hu** [comment] 2023-09-11 12:18
@tomekzaw I dont know what the heck is going on, but I still also have this issue with RN 0.72.4 and reanimated 3.4.2, the only solution for me was to manually removing optional chaining from Keyframe.ts and EntryExitTransition.ts

**Comment by LuisUrrutia** [comment] 2023-11-21 00:12
Same issue over here working with iOS. I did run `yarn start --reset-cache` and I also added `@babel/plugin-syntax-optional-chaining` as suggested in another issue, but the issue remains.

**Comment by kmagiera** [comment] 2023-12-15 12:21
Hi @stee1ix, @metrix-hu and @LuisUrrutia – thanks for your comments on this issue. It appears like this isn't directly related to reanimated but rather to your specific setups. I'm afraid we won't be able to help without knowing a bit more about the project setup where you are facing this problem. 

If you want to get the issue resolved, I suggest you first try cloning the project that @tomekzaw shared earlier: https://github.com/tomekzaw/Issue3429 – this project should build and run for you correctly, unless there is some issue with your local setup.

If the project runs correctly, I suggest that you try to change its settings to match the project where you are facing the issue unless you start experiencing it. This way you should narrow down the issue to a specific setting in your project.

**Comment by Terandium** [comment] 2024-02-01 14:55
A bit late, but I had this issue with Ignite.
Using npm instead of pnpm solved it for me.

**Comment by kmagiera** [comment] 2024-02-06 13:12
Thanks, will be closing this issue then. If there are any updates please comment here and we will reopen

**Closed by kmagiera** 2024-02-06 13:12 UTC
Labels: Build or config issue
