### ISSUE TITLE
Unable to set shadowOffset through reanimated

### ISSUE THREAD

**Issue by senthilsivanath** [software-mansion/react-native-reanimated#156] opened 2018-12-25 16:48 UTC
Trying to set shadowOffset for Animated.View through animated value of gesture state, the shadow width / height throws exception. However shadowOpacity works fine. 

Exception : Expected NSNumber but received NSDictionary 

Looks like when the value going through bridge object has some prob, not sure though.
```jsx
<Animated.View style={
                        [
                            styles.box,
                            {                                
                                shadowOffset: {height:this.heightValue, width:this.widthValue}                               
                            }
                        ]}>
```

Tried supplying complexMap 
this.shadow = cond( or( eq(this.gestureState, State.BEGAN), eq(this.gestureState,State.ACTIVE)), {height:45,width:400}, {height:24,width:48});
```jsx
<Animated.View style={
                        [
                            styles.box,
                            {                                
                                shadowOffset: this.shadowValue                               
                            }
                        ]}>
```

**Comment by jakub-gonet** [comment] 2019-11-23 20:55
Hi @senthilsivanath,
firstly, sorry for the very late response.

Secondly, I was unable to reproduce this issue and it's outdated, so I'm closing it. If you need further assistance just ask.

**Closed by jakub-gonet** 2019-11-23 20:55 UTC

**Comment by MoeMamdouh** [comment] 2020-03-06 17:45
I have the same problem

**Comment by jakub-gonet** [comment] 2020-04-04 20:39
Hi @MoeMamdouh,
can you provide code (preferably on [snack](https://snack.expo.io/)) and reproductions steps, as well as versions of Reanimated and React Native?
Thanks!
