### ISSUE TITLE
Delay in TapGestureHandler?

### ISSUE THREAD

**Issue by vmarcel** [software-mansion/react-native-reanimated#1184] opened 2020-09-03 17:25 UTC
## Description

Is there an intentional delay in TapGestureHandler? I notice after about 3 secs the onGestureEvent triggers the next animation.

## Code

```js
  const initialScale = useSharedValue(1);
  const changeSize = useSharedValue(0.5);

  const gestureHandler = useAnimatedGestureHandler({
    onStart: () => {
      changeSize.value = initialScale.value === 1 ? 0.5 : 1;
    },
    onCancel: (event) => {
      console.log(event);
    },
    onEnd: () => {
      initialScale.value = withSpring(changeSize.value);
    },
  });

  //... More code

  return (
    <View style={styles.container}>
      <TapGestureHandler onGestureEvent={gestureHandler} numberOfTaps={2}>
        <Animated.View style={animatedPosition}>
          <Animated.View style={[styles.card, animatedScale]} />
        </Animated.View>
      </TapGestureHandler>
    </View>
  );
```

### Example

![mobile-ani-test](https://user-images.githubusercontent.com/20823925/92147236-ae822780-edcf-11ea-9c9e-90c8523c34c1.gif)

### Package versions

- React: 16.13.1
- React Native: 0.63.1
- React Native Reanimated: 2.0.0-alpha.5
- React Native Gesture Handler: 1.6.1

**Comment by jakub-gonet** [comment] 2020-09-03 18:07
Could you please include a snack or provide a small code example showing this behavior?

**Comment by vmarcel** [comment] 2020-09-03 18:30
@jakub-gonet I added a gif for a visual. Were you able to see it?

**Comment by jakub-gonet** [comment] 2020-09-03 18:45
Not the exact moment but I _think_ I see some small delay. I asked for repro because trying to do it on our own based on your snippet is time-consuming and not really efficient (as we're trying to write the same thing that you already have written).

**Comment by terrysahaidak** [comment] 2020-09-03 18:56
Try to play around with props: https://docs.swmansion.com/react-native-gesture-handler/docs/handler-tap

Also, there is a bug in a current `useAnimatedGestureHandler`. Try to use code from master or [my handler](https://github.com/terrysahaidak/reanimated-gallery/blob/master/src/useAnimatedGestureHandler.tsx) to reproduce it.

**Comment by gorhom** [comment] 2020-09-06 10:31
@terrysahaidak you are a saviour ❤️

**Comment by terrysahaidak** [comment] 2020-09-06 11:50
Did you try the code from master?

**Comment by gorhom** [comment] 2020-09-06 13:11
yeah, i tried your implementation of `useAnimatedGestureHandler` [from your master](https://github.com/terrysahaidak/reanimated-gallery/blob/master/src/useAnimatedGestureHandler.tsx), and it works fine

**Comment by terrysahaidak** [comment] 2020-09-06 13:19
Could you also try the one from this repo master? if it works, we can close this issue then.

**Comment by Szymon20000** [comment] 2020-09-17 08:12
Looks like the problem has been resolved. We will close it for now but feel free to reopen anytime.

**Closed by Szymon20000** 2020-09-17 08:12 UTC
Labels: Reanimated2, ❓Question
