### ISSUE TITLE
Android device log shows reanimated related message every milisecond then crashes

### ISSUE THREAD

**Issue by andreialecu** [software-mansion/react-native-reanimated#1932] opened 2021-04-13 10:47 UTC
## Description

Been troubleshooting some Android performance issues and crashes, and I noticed in the device log (using Flipper), that there's a message being logged every milisecond:

<img width="1392" alt="Screenshot 2021-04-13 at 13 46 36" src="https://user-images.githubusercontent.com/697707/114540824-ab50f300-9c5e-11eb-8b83-b451b7e39ad2.png">

Not sure if this is normal or what is causing it, but it mentions reanimated.

### Expected behavior

No log spam.

### Actual behavior & steps to reproduce

See screenshot above

## Package versions

- React Native: 0.64
- React Native Reanimated: 2.1.0

## Affected platforms

- [x] Android

**Comment by andreialecu** [comment] 2021-04-13 10:50
These could be related, as they appear to be logged immediately prior to the log spam mentioned above:

<img width="1823" alt="Screenshot 2021-04-13 at 13 50 07" src="https://user-images.githubusercontent.com/697707/114541272-2914fe80-9c5f-11eb-9381-8c56d6f616f4.png">

**Comment by andreialecu** [comment] 2021-04-13 11:08
Even Android Studio has problems keeping up with the amount of log spam:

```
2021-04-13 14:07:44.624 15644-15644/? I/MessageQueue: searched 10000messages,recent msg is { when=-886ms callback=com.swmansion.reanimated.Scheduler$1 target=com.facebook.react.bridge.queue.MessageQueueThreadHandler }head message is { when=-1s444ms callback=com.swmansion.reanimated.Scheduler$1 target=com.facebook.react.bridge.queue.MessageQueueThreadHandler }
    
    logcat: Unexpected EOF!
    
    This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
    messages as quickly as they were being produced.
    
    If you have enabled significant logging, look into using the -G option to increase log buffer sizes.
```

**Comment by andreialecu** [comment] 2021-04-13 11:14
After setting `adb logcat -G 10M` I was able to see the reason of the crash:

```
2021-04-13 14:11:29.932 1716-16416/? E/ActivityManager: ANR in the.app (the.app/.MainActivity)
    PID: 16169
    Reason: Input dispatching timed out (fdbbf7a the.app/the.app.MainActivity (server) is not responding. Waited 5005ms for MotionEvent)
    Parent: the.app/.MainActivity
    Load: 96.19 / 95.59 / 95.09
    ----- Output from /proc/pressure/memory -----
    some avg10=0.01 avg60=0.05 avg300=0.01 total=80656542
    full avg10=0.00 avg60=0.01 avg300=0.00 total=33205078
    ----- End output from /proc/pressure/memory -----
```

Seems that the OS just force closes it because it doesn't respond for 5 seconds.

**Comment by jakub-gonet** [comment] 2021-04-13 12:25
Could you search for `MessageQueue` string in your app and your dependencies (outside of react-native package) sources?

Something like:
```bash
grep -r 'MessageQueue' --include='*.java' --exclude-dir='node_modules/react-native' .
```
in your project root.

**Comment by andreialecu** [comment] 2021-04-13 12:27
Here's a repro:

https://github.com/andreialecu/rnctv-react-native-bare-test/tree/android-reanimated-crash
Run `yarn android` to run it, and press the blue button, then try swiping left/right to switch between tabs.

Notice that it only occurs on a physical Oppo A72 device (I don't have any other Android device to test). I wasn't able to get it to reproduce in the emulator. Might be related to #1912 which mentions Oppo as well.

**Comment by andreialecu** [comment] 2021-04-13 12:30
@jakub-gonet I can't find anything relevant from that search. It reproduces with the repository I linked in the previous comment, so you could run your own search in it. But there are no other dependencies than reanimated in the project.

Make sure to use the `android-reanimated-crash` branch.

**Comment by andreialecu** [comment] 2021-04-13 12:46
The only other similar type of logs that I can find is in this pastebin from 2019:
https://pastebin.com/mNyhtCqh

No idea what is logging it. I think it's related to a

**Comment by andreialecu** [comment] 2021-04-13 13:10
One note about the repro: It initially did excessive work, trying to load 1000 images. This resulted in the same issue just by itself.

I pushed a commit to it to load less, then you can see the crash occur while swiping between tabs. 

It's possible that [react-native-collapsible-tab-view](https://github.com/PedroBern/react-native-collapsible-tab-view) does something it shouldn't, but I don't think it should produce a hang/crash.

**Comment by piaskowyk** [comment] 2021-04-14 14:45
Probably this issue is related with https://github.com/software-mansion/react-native-reanimated/issues/1923

**Comment by piaskowyk** [comment] 2021-04-14 14:58
Yes. This is related to this: https://github.com/software-mansion/react-native-reanimated/pull/1842 I have already debugged this and know why. I'm working on a fix.

**Comment by andreialecu** [comment] 2021-04-14 15:02
Just a note: I'm definitely able to reproduce this on `2.0.1`, seems #1842 is only part of `2.1.0`.

I ran gradle clean and everything.

**Comment by piaskowyk** [comment] 2021-04-14 15:04
Thanks for info. I will check this and let you know when I will know what happened.

**Comment by andreialecu** [comment] 2021-04-14 15:45
So this is interesting, I switched from Hermes to JSC on 2.1.0 and tested the repro and the same logs have appeared, but this time the app wasn't force closed. It was responsive from time to time, but mostly it was hung. It would respond every few seconds or so for just one frame.

It then suddenly stopped the logs and the app became responsive. Notice the OpenGLRenderer log immediately after.

<img width="1823" alt="Screenshot 2021-04-14 at 18 43 49" src="https://user-images.githubusercontent.com/697707/114739211-5b9f2400-9d51-11eb-8a90-a3341c9f08a3.png">

**Comment by andreialecu** [comment] 2021-04-21 14:12
@piaskowyk just wondering, because you didn't mention it.

Were you able to actually reproduce this issue with my repro?

**Comment by LadislavBohm** [comment] 2021-04-29 21:25
I am having the same issue on OnePlus device when switching between BottomTabs using react-navigation. When 

1. start the animation with a button click
2. wait for animation to finish
3. navigate to another tab
4. go back to previous tab

App will hang and after few seconds crash.

**Comment by andreialecu** [comment] 2021-06-11 05:39
@piaskowyk if this helps, it appears that this happens more frequently when the main JS thread has a lot of work to do.

In our app, we're using `@formatjs` Intl polyfills which are very slow. It can take 20ms to format a single date on a real android device using Hermes.

If we have a FlatList and each item formats a date, the bigger the list is, the faster this bug occurs with reanimated.

It looks like it might be triggered by some race condition.

Regardless, the repro I attached in my earlier comment does show the issue more consistently. In the real app it occurs more randomly.

**Comment by andreialecu** [comment] 2021-06-23 16:27
An update on this. 

After optimizing everything as much as possible and reducing as JS thread cpu usage this stopped happening even on the lower end device.

I'll keep it open because the repro above still shows it.

**Comment by piaskowyk** [comment] 2023-05-23 12:01
Since this issue is opened I have never reproduced this problem :/ I hope that the many changes we made resolved this issue. Let me close this one 🙏

**Closed by piaskowyk** 2023-05-23 12:01 UTC
Labels: Bug, 🏠  Reanimated 2, bug-bash-jan22
