### ISSUE TITLE
Errro compile npx react-native run-android

### ISSUE THREAD

**Issue by kodeandoec** [software-mansion/react-native-reanimated#2307] opened 2021-08-21 11:39 UTC
Starting a Gradle Daemon (subsequent builds will be faster)
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: project ':react-native-async-storage_async-storage', project ':react-native-community_checkbox', project ':react-native-safe-area-context', ...
**> Task :app:checkDebugAarMetadata FAILED**
15 actionable tasks: 15 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-65.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: /Users/user/Desktop/Apps/project/node_modules/react-native-reanimated/android/react-native-reanimated-65.aar.
         > Transform's input file does not exist: /Users/user/Desktop/Apps/project/node_modules/react-native-reanimated/android/react-native-reanimated-65.aar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
**Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081**

FAILURE: Build failed with an exception.

* What went wrong:
**Execution failed for task ':app:checkDebugAarMetadata'.**
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-65.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: /Users/user/Desktop/Apps/project/node_modules/react-native-reanimated/android/react-native-reanimated-65.aar.
         > Transform's input file does not exist: /Users/user/Desktop/Apps/project/node_modules/react-native-reanimated/android/react-native-reanimated-65.aar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s

    at makeError (/Users/user/Desktop/Apps/project/node_modules/execa/index.js:174:9)
    at /Users/user/Desktop/Apps/project/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/Users/user/Desktop/Apps/project/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/Users/user/Desktop/Apps/project/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.

**My Project 
"react": "17.0.2",
"react-native": "0.65.0",
 "react-native-reanimated": "^2.0.0",**

**Comment by jakub-gonet** [comment] 2021-08-22 07:44
Duplicate of #2308.

**Closed by jakub-gonet** 2021-08-22 07:44 UTC
Labels: 🐞 Bug
