### ISSUE TITLE
TurboModuleRegistry.getEnforcing(...) - HELP!!!

### ISSUE THREAD

**Issue by aqilhex** [software-mansion/react-native-reanimated#1838] opened 2021-03-17 00:11 UTC
## Description
I can't find any solution to fix this error caused by react-native-reanimated@2.0.0, Downgraded to v1.x.x , Clearing cache, Enabling jetifier did not help. Someone help me please, I need it to work with react-navigation/drawer.

- React: 17.0.1
- React Native: 0.64.0
- React Native Reanimated: 2.0.0
- NodeJS: v12.16.3

**Comment by mosoakinyemi** [comment] 2021-03-17 13:01
I had this same issue for iOS, I solved it simply by:
1. Deleting the app on the simulator 
2. Running `npx react-native run-ios`

**Comment by 4yki** [comment] 2021-03-17 19:26
Same for me with:
- React Native: 0.64.0
- React Native Reanimated: 2.0.0

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

**Comment by teamzz111** [comment] 2021-03-18 02:46
Same here

 Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

**Comment by boonook** [comment] 2021-03-18 03:27
Same for me with

remove @react-navigation/drawer  normal
use @react-navigation/drawer error

**Comment by melero2000** [comment] 2021-03-18 08:59
Same issue for me:

- React Native: 0.64.0
- React Native Reanimated: 2.0.0
- react-navigation/drawer: 5.12.4

**Comment by jakub-gonet** [comment] 2021-03-18 18:18
Duplicate of #1825.

**Closed by jakub-gonet** 2021-03-18 18:18 UTC
Labels: 🏠  Reanimated2, 🐞 Bug
