### ISSUE TITLE
Getting attempt to invoke virtual method double java.lang.double.doublevalue() on a null object reference  on android simulator

### ISSUE THREAD

**Issue by fistofzen** [software-mansion/react-native-reanimated#3715] opened 2022-10-24 17:07 UTC
### Description

Hello,
My package json file is as follows and I am getting error below while opening the app. 
Could you please help?

![Screen Shot 2022-10-24 at 20 02 57](https://user-images.githubusercontent.com/6533119/197584086-12154672-571f-469b-9ffb-0a8a062ae16b.png)

`{
  "name": "AllStarsApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },

  "dependencies": {
    "@aws-amplify/core": "^4.7.8",
    "@aws-amplify/datastore": "^3.14.0",
    "@azure/core-asynciterator-polyfill": "^1.0.2",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/netinfo": "^9.3.5",
    "@react-native-community/progress-view": "^1.3.2",
    "@react-native-picker/picker": "^2.4.8",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.2",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "amazon-cognito-identity-js": "^5.2.11",
    "aws-amplify": "^4.3.39",
    "aws-amplify-react-native": "^6.0.5",
    "deprecated-react-native-prop-types": "^2.3.0",
    "lottie-react-native": "^5.1.4",
    "moment": "^2.29.4",
    "patch-package": "^6.4.7",
    "react": "18.1.0",
    "react-content-loader": "^6.2.0",
    "react-native": "0.70.3",
    "react-native-date-picker": "^4.2.5",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-modal": "^13.0.1",
    "react-native-progress": "^5.0.0",
    "react-native-purchases": "^5.1.0",
    "react-native-reanimated": "^2.11.0",
    "react-native-reanimated-carousel": "^3.1.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-svg": "^13.4.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1",
    "react-redux": "^8.0.4",
    "redux": "^4.2.0",
    "redux-thunk": "^2.4.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },

  "postinstall": "patch-package",
  
  "jest": {
    "preset": "react-native"
  }
}
`

### Steps to reproduce

1 - delete node_modules and yarn start --reset-cache
2 - npx react-native run android

### Snack or a link to a repository

none

### Reanimated version

2.11.0

### React Native version

0.70.3

### Platforms

Android

### Build type

Release mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by fistofzen** [comment] 2022-10-29 05:59
Hello, 
I figured out that it throws that error when  "@react-navigation/drawer": "^6.5.0",

Regards

**Comment by anthlasserre** [comment] 2022-12-28 09:40
@fistofzen Do you mean you were able to fix that crash issue by upgrading your `@react-navigation/drawer` version to the latest ?

**Comment by Latropos** [comment] 2023-12-14 16:04
Closing this issue. We couldn't fix it due to lack of reproduction and now it is quite old and this bug seems to have disappeared by itself 😎

**Closed by Latropos** 2023-12-14 16:04 UTC
Labels: Missing repro, Platform: Android, Needs review
