### ISSUE TITLE
Velocity shows swipe direction was changed, while it doesn't

### ISSUE THREAD

**Issue by likern** [software-mansion/react-native-reanimated#1786] opened 2021-03-04 18:56 UTC
## Description

`useAnimatedScrollHandler()` shows **velocity** as if swipe changed direction, while it doesn't.
Here are the states and the full log of recorded swipe https://gist.github.com/likern/2040a76b204be9878c1c15cd8b3f1a07
```ts
enum ScrollState {
  UNDETERMINED = 0,
  DRAG_BEGIN, // 1
  DRAG_END, // 2
  MOMENTUM_BEGIN, // 3
  MOMENTUM_END, // 4
  ON_SCROLL // 5
}
```
```bash
[Thu Mar 04 2021 21:20:47.362]  LOG      state: 0, velocity: 0
[Thu Mar 04 2021 21:20:49.190]  LOG      state: 1, velocity: 0
[Thu Mar 04 2021 21:20:49.360]  LOG      state: 5, velocity: -11.105178833007812
[Thu Mar 04 2021 21:20:49.490]  LOG      state: 5, velocity: 28.733333587646484
[Thu Mar 04 2021 21:20:49.500]  LOG      state: 2, velocity: -65.48081970214844
[Thu Mar 04 2021 21:20:49.530]  LOG      state: 3, velocity: -65
[Thu Mar 04 2021 21:20:49.680]  LOG      state: 5, velocity: 12.736842155456543
[Thu Mar 04 2021 21:20:49.870]  LOG      state: 5, velocity: 23.375
[Thu Mar 04 2021 21:20:49.120]  LOG      state: 5, velocity: 26.64285659790039
[Thu Mar 04 2021 21:20:49.122]  LOG      state: 5, velocity: 26.923076629638672
[Thu Mar 04 2021 21:20:49.137]  LOG      state: 5, velocity: 21.823530197143555
[Thu Mar 04 2021 21:20:49.154]  LOG      state: 5, velocity: 26.285715103149414
[Thu Mar 04 2021 21:20:49.171]  LOG      state: 5, velocity: 21.5
[Thu Mar 04 2021 21:20:49.209]  LOG      state: 5, velocity: 26
[Thu Mar 04 2021 21:20:49.211]  LOG      state: 5, velocity: 24
[Thu Mar 04 2021 21:20:49.220]  LOG      state: 5, velocity: 24
[Thu Mar 04 2021 21:20:49.236]  LOG      state: 5, velocity: 25.285715103149414
[Thu Mar 04 2021 21:20:49.253]  LOG      state: 5, velocity: 23.266666412353516
```

`DRAG_END` and `MOMENTUM_BEGIN` clearly shows something strange as if I abruptly changed swipe direction.
```bash
...
[Thu Mar 04 2021 21:20:49.360]  LOG      state: 5, velocity: -11.105178833007812
[Thu Mar 04 2021 21:20:49.490]  LOG      state: 5, velocity: 28.733333587646484
[Thu Mar 04 2021 21:20:49.500]  LOG      state: 2, velocity: -65.48081970214844
[Thu Mar 04 2021 21:20:49.530]  LOG      state: 3, velocity: -65
[Thu Mar 04 2021 21:20:49.680]  LOG      state: 5, velocity: 12.736842155456543
[Thu Mar 04 2021 21:20:49.870]  LOG      state: 5, velocity: 23.375
...
```

### Screenshots

https://user-images.githubusercontent.com/842306/110011285-4b4a6100-7d30-11eb-882a-fd5ed25ef80e.mp4

## Steps To Reproduce

1. Use `useAnimatedScrollHandler()` and log it's velocity on different callbacks.

```ts
export const useCalendarScroll = () => {
  const scrollState = useSharedValue<ScrollState>(
    ScrollState.UNDETERMINED,
    false
  );
  const scrollContentSize = useSharedValue<NativeScrollSize>(
    { width: 0, height: 0 },
    false
  );
  const scrollContentOffset = useSharedValue<NativeScrollPoint>(
    { x: 0, y: 0 },
    false
  );
  const scrollVelocity = useSharedValue<NativeScrollVelocity>(
    { x: 0, y: 0 },
    false
  );
  const scrollLayoutMeasurement = useSharedValue<NativeScrollSize>({
    width: 0,
    height: 0
  });

  const scrollHandler = useAnimatedScrollHandler({
    onScroll: (event) => {
      scrollState.value = ScrollState.ON_SCROLL;
      scrollContentSize.value = event.contentSize;
      scrollLayoutMeasurement.value = event.layoutMeasurement;
      scrollContentOffset.value = event.contentOffset;
      scrollVelocity.value = event.velocity;
    },
    onBeginDrag: (event) => {
      scrollState.value = ScrollState.DRAG_BEGIN;
      scrollContentSize.value = event.contentSize;
      scrollLayoutMeasurement.value = event.layoutMeasurement;
      scrollContentOffset.value = event.contentOffset;
      scrollVelocity.value = event.velocity;
    },
    onEndDrag: (event) => {
      scrollState.value = ScrollState.DRAG_END;
      scrollContentOffset.value = event.contentOffset;
      scrollVelocity.value = event.velocity;
    },
    onMomentumBegin: (event) => {
      scrollState.value = ScrollState.MOMENTUM_BEGIN;
      scrollContentOffset.value = event.contentOffset;
      scrollVelocity.value = event.velocity;
    },
    onMomentumEnd: (event) => {
      scrollState.value = ScrollState.MOMENTUM_END;
      scrollContentOffset.value = event.contentOffset;
      scrollVelocity.value = event.velocity;
    }
  });

  return {
    scrollHandler,
    scrollState,
    scrollContentSize,
    scrollContentOffset,
    scrollVelocity,
    scrollLayoutMeasurement
  };
};
```

### Expected behavior

For one-direction swipe velocity should not have different signs (directions).

### Actual behavior

Velocity has different directions.

## Snack or minimal code example

```tsx
const {
    scrollHandler,
    scrollState,
    scrollContentOffset,
    scrollContentSize,
    scrollVelocity,
    scrollLayoutMeasurement
  } = useCalendarScroll()
...
useDerivedValue(() => {
    console.log(
      `state: ${scrollState.value}, velocity: ${scrollVelocity.value.x}`
    );
  }, []);
```

## Device
 - Phone: Xiaomi Mi9T Pro
 - OS: Android 10

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0
- NodeJS: 10.19.0

**Comment by kmagiera** [comment] 2022-01-28 09:39
Hi @likern – thanks for reporting and for the detailed description. Since it's been a while since the issue's been opened can you confirm if this is still happening on the latest version?

**Comment by likern** [comment] 2022-01-28 09:43
Let's close and if any I will reopen. I just don't have access to this code.

**Comment by likern** [comment] 2022-01-28 14:31
@kmagiera Can't confirm now, but I'm sure nothing has changed in that regard.

This issue is similar to https://github.com/software-mansion/react-native-reanimated/issues/1780.

**Comment by piaskowyk** [comment] 2023-12-15 11:10
This issue seems to be a duplicate of: https://github.com/software-mansion/react-native-reanimated/issues/1780
lets keep conversation in single thread

**Closed by piaskowyk** 2023-12-15 11:10 UTC
Labels: Bug, 🏠  Reanimated 2
