### ISSUE TITLE
Build Failed Due to React-native-reanimated Download Boost Task

### ISSUE THREAD

**Issue by usamabinishaq** [software-mansion/react-native-reanimated#5568] opened 2024-01-09 12:02 UTC
### Description

Build Failed Due to React-native-reanimated Download Boost Task.
When I run my project, it starts building it, but when it reaches the Download boost task of `react-native-reanimated `, it crashes the build by saying that Not in GZIP Format.

![image](https://github.com/software-mansion/react-native-reanimated/assets/89419859/c492a8eb-3035-4822-bb16-b0c29acc8a80)

### Steps to reproduce

1. add react-native-renaniumated package to your project (make sure you have added` react-native-reanimated/plugin)` in Bable.config.js
2. Now run the [project by yarn run android 
3. it will fail the build on 97% due to download boost task 

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/issues/5542

### Reanimated version

3.5.4

### React Native version

0.70.9

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by piaskowyk** [comment] 2024-01-09 14:59
Do you have any reproduction? Because the reproduction from linked issue doesn't available:
<img width="975" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/465d8e09-2e4a-45b7-a024-83aec2c93e2b">

**Comment by Mistermo716** [comment] 2024-01-22 17:59
I think this is likely a bandwidth issue. Try downloading the library manually from link provided and placing it in node_modules/react-native-reanimated/android/build/downloads

you might have to do the same for double conversion.

**Comment by piaskowyk** [comment] 2024-09-20 15:42
I believe your suggestion is highly probable. I'll close the issue for now, but we can reopen it if anyone provides more information. 👍

**Closed by piaskowyk** 2024-09-20 15:42 UTC
Labels: Missing repro, Platform: Android, Wait for reply
