### ISSUE TITLE
useAnimatedStyle() gets rebuilt on every re-render

### ISSUE THREAD

**Issue by helixbass** [software-mansion/react-native-reanimated#1767] opened 2021-02-27 13:39 UTC
## Description

It appears that `useAnimatedStyle()` animated styles are getting rebuilt (ie changing identity) on every re-render of the enclosing component. My understanding from the docs and from comparing to behavior of eg `useDerivedValue()` is that it should only get rebuilt if eg identities of dependent values change

## Steps To Reproduce

I made an example repo at https://github.com/helixbass/ReanimatedUseAnimatedStyleRecreatedExample

When I launch the app in an Android emulator (so `yarn install`, `yarn start`, `yarn android`) I see logged in the console:
```
[Sat Feb 27 2021 08:26:59.519]  LOG      Running "Reanimated2Playground" with {"rootTag":101}
[Sat Feb 27 2021 08:26:59.519]  LOG      component re-render
[Sat Feb 27 2021 08:26:59.520]  LOG      width changed identity
[Sat Feb 27 2021 08:26:59.520]  LOG      derivedValue changed identity
[Sat Feb 27 2021 08:26:59.520]  LOG      style changed identity
[Sat Feb 27 2021 08:27:00.524]  LOG      component re-render
[Sat Feb 27 2021 08:27:00.525]  LOG      style changed identity
[Sat Feb 27 2021 08:27:01.536]  LOG      component re-render
[Sat Feb 27 2021 08:27:01.536]  LOG      style changed identity
[Sat Feb 27 2021 08:27:02.554]  LOG      component re-render
[Sat Feb 27 2021 08:27:02.555]  LOG      style changed identity
[Sat Feb 27 2021 08:27:03.571]  LOG      component re-render
[Sat Feb 27 2021 08:27:03.571]  LOG      style changed identity
...etc...
```
Here is the relevant code:
```js
  const width = useSharedValue(10);

  const derivedValue = useDerivedValue(() => width.value + 10);
  const style = useAnimatedStyle(() => {
    return {
      width: derivedValue.value,
      // width: 10,
    };
  });
  const [, setCounter] = useState(0);
  useEffect(() => {
    setInterval(() => {
      setCounter((counterVal) => counterVal + 1);
    }, 1000);
  }, []);
  console.log('component re-render');
  useEffect(() => {
    console.log('width changed identity');
  }, [width]);
  useEffect(() => {
    console.log('derivedValue changed identity');
  }, [derivedValue]);
  useEffect(() => {
    console.log('style changed identity');
  }, [style]);
```
So `useDerivedValue()` is behaving as expected and not rebuilding/changing identity on re-renders. But `useAnimatedStyle()` is not

Also if I explicitly pass dependencies `[]` to `useAnimatedStyle()` and/or make it return a fully static style object (eg `{width: 10}`) it still changes identity on every re-render 

### Expected behavior

Styles created by `useAnimatedStyle()` should have stable identities across re-renders unless one of its dependencies changes identity

### Actual behavior

Styles created by `useAnimatedStyle()` are changing identity on every re-render

## Package versions

Based on fresh `software-mansion-labs/reanimated-2-playground` clone:

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: 2.0.0-rc.3
- NodeJS: 12.3.0

**Comment by jagadishg** [comment] 2021-07-17 16:26
Any updates on this issue?

**Comment by charles-goode** [comment] 2021-08-19 00:02
This is definitely confounding. However, I was able to work around this by `useMemo(useAnimatedStyle(), deps)`

**Comment by michaelknoch** [comment] 2021-12-10 20:21
what would be a realistic value for deps @charles-goode? I found myself always using `[]`  for the deps because there is no other dependency. As far as I know there is no need to add shared values to the list, correct me if I'm wrong.

```ts
const sharedValue = useSharedValue(1337);
const _animatedStyles = useAnimatedStyle(() => ({
    transform: [{ translateY: withSpring(sharedValue.value) }],
}));

const animatedStyles = useMemo(() => animatedPreviewPlayerStyles, []);
```

**Comment by charles-goode** [comment] 2021-12-10 20:38
If this issue didn't exist, we would just rely on the deps list parameter of `useAnimatedStyle`, so my answer is anything you would want to be in that list. For example if part of the animated style relied on state or props as opposed to just shared values, you would need the style to be reconstructed when those values change otherwise they would become stale/outdated.

**Comment by hmust92** [comment] 2022-01-17 22:51
> useMemo(useAnimatedStyle(), deps)

@charles-goode Can you explain how you get this to work?

I have attempted

```
    const x = useMemo(
        useAnimatedStyle(() => ({})),
        [],
    );
```

But this breaks

**Comment by hmust92** [comment] 2022-01-17 22:52
I am also running into this issue and it's triggering unwanted rerenders when passing the style as props.

**Comment by charles-goode** [comment] 2022-01-17 23:32
@hmust92 

> But this breaks

By breaking do you mean it results in an error? If so what's the error message?

**Comment by hmust92** [comment] 2022-01-18 01:56
@charles-goode 

Thanks for the prompt response! Yes, I get an error. The error message is:

`TypeError: nextCreate is not a function. (In 'nextCreate()', 'nextCreate' is an instance of Object)`. I am on react-native v0.63.4 and react-native-reanimated v2.2.0.

Here's my component, nothing too crazy:

```
import { useAnimatedStyle } from 'react-native-reanimated';
import React, { useMemo } from 'react';
import { Button, StyleSheet, View } from 'react-native';

export default function App() {
    const [state, setState] = React.useState(0);

    const x = useMemo(
        useAnimatedStyle(() => ({})),
        [],
    );

    return (
        <View style={styles.container}>
            <Button
                title="Test"
                onPress={() => {
                    setState(Math.random());
                }}
            />
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: '#ecf0f1',
        padding: 8,
    },
});
```

**Comment by hmust92** [comment] 2022-01-19 11:09
Any update on this?

**Comment by piaskowyk** [comment] 2022-01-28 09:38
Not yet 😕 but I want to resolve it as soon as possible.

**Comment by gozdecoban** [comment] 2022-04-29 13:46
Any update on this?

**Comment by felix-lambert** [comment] 2022-08-16 10:54
Any update ?

**Comment by bitcrumb** [comment] 2023-01-24 21:48
Would be great to see this issue fixed in the near future :)

**Comment by Rag0n** [comment] 2023-04-20 14:50
The issue is fixed in reanimated 3.0

**Comment by artemis-prime** [comment] 2023-04-26 21:38
Can some please verify the fix for 3.0 and if true close?

**Comment by BishalftSaikia** [comment] 2023-05-01 09:51
seeing the issue on 3.1 , but @hmust92 code works, 
` const useMemoizedAnimatedStyle = (cb) => {
    const style = useAnimatedStyle(cb);

    return useMemo(() => style, [cb]);
  };

  //Reanimated translate style
  const translateStyle = useMemoizedAnimatedStyle(() => {
    'worklet';
    return {
      transform: [{ translateY: translateY.value }],
    };
  });`

**Comment by RRaideRR** [comment] 2023-09-10 11:03
It still exists in reanimated 3.4.2.

**Comment by ranaavneet** [comment] 2023-10-31 04:52
Hi @Latropos @piaskowyk! Is there any plan to fix it soon? If there is any PR, I would be happy to test it.

**Comment by vkukade-altir** [comment] 2023-12-30 13:09
This issue still exists in version 3. Any update here?

**Closed** 2024-02-13 15:20 UTC
Labels: Important, Repro provided, bug-bash-jan22

**Comment by JulesPatry** [comment] 2024-08-15 01:26
```
function AnimatedComponent({ children }) {
  const style = useSharedValue(12);
  const animatedOpacity = useAnimatedStyle(() => ({
    shadowRadius: style.value,
  }));
  style.value = useMemo(() => withRepeat(withTiming(20, { duration: 500 }), -1, true), []);

  return (
    <Animated.View style={[{ backgroundColor: '#cc2121', shadowColor: '#cc2121', shadowOpacity: 1 }, animatedOpacity]}>
      {children}
    </Animated.View>
  );
}

....

return (
    <AnimatedComponent key={Math.random()}> <----- key will reset the animation on each render preventing the animation from stacking
         <Text>HELLO WORLD</Text>
    </AnimatedComponent>
)
```
