### ISSUE TITLE
Upgrade to Reanimated 3 causes many things to break

### ISSUE THREAD

**Issue by coayscue** [software-mansion/react-native-reanimated#4268] opened 2023-03-24 03:51 UTC
### Description

When I upgrade from Reanimated 2 to 3, this sophisticated timeline component I have breaks in many ways.

Here is the working app on iOS with Reanimated 2. It also works well on Android with Reanimated 2. 
https://drive.google.com/file/d/1WsmQ35xj-N9DFNKDLmK7Yv49PG2ebcAN/view

Here is what it looks like on Android after upgrade to Reanimated 3. The frame rate drops to almost 0 a lot  and the app will appear frozen for a few seconds when trying to zoom or scroll.
https://drive.google.com/file/d/1NmDCpTw2IHoBt8DuHgCNpkrdvNtwAPG3/view

Here are two videos of iOS after upgrade to Reanimated 3. The first video shows this bricked state where everything appears broken - it didn’t take much playing with the timeline to get it into this state. The second video shows things partially working except: The scroll and zoom gestures are laggy - you can see when I start to zoom or scroll, there is a big lag. And dragging the cursor drops the frame rate to less than 2 fps sometimes. 
https://drive.google.com/file/d/1BqyrBqvF1I3c8I8gQzDRUM4pFqD8PqlL/view

https://drive.google.com/file/d/1sCl5Q9OEj0DSaOiAGTM73n9FhbHVHgYC/view

This timeline component is pretty complex with lots of pieces and gesture handlers, and it works really well in Reanimated 2. But I can’t justify the upgrade to Reanimated 3 or even know what to start fixing when it seems like so many things break with the upgrade.

### Steps to reproduce

- Download the repo
- Run the app on android
- sign up
- open the hamburger menu drawer
- go to "plans"
- create a "plan"
- zoom in on timeline
- zoom doesn't work

### Snack or a link to a repository

private repo - message me 

### Reanimated version

3.0.2

### React Native version

0.70.7

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by andreialecu** [comment] 2023-03-30 07:59
Possibly related to #4168

**Comment by kmagiera** [comment] 2023-03-30 11:29
@coayscue and @andreialecu – thanks for reporting and participating in this discussion. We recently landed a fix that can potentially address this issue #4280 – there is no release published with this change yet but if you have time to patch it locally and test it'd be great to hear if it fixes the problem for you.

**Comment by coayscue** [comment] 2023-03-30 23:26
Unfortunately even with the patch i'm still experiencing tons of issues

**Comment by HadiModarres** [comment] 2023-04-08 02:01
It does seem v3 on new architecture breaks things, the whole API section in the documentation about Layout animations like entering, exiting, layout props stopped working. I thought I had a problem with my packages after upgrade, but copied the `Bokeh` example from `FabricExample` in this repository and ran it on my project and it worked just fine. But layout animations that I'm using solely seem to be broken. 

React Native: 0.71.6
Reanimated: 3.0.2

**Comment by coayscue** [comment] 2023-04-12 18:19
@j-piasecki @tomekzaw Hey guys, wondering if you want to take a look at this again. I can share access to my codebase under NDA if you're interested.

You can see just how complicated my Timeline component is (100+ shared values, dozens of animated components, many complex interactions between the components). V2 works great, but upgrading to v3 breaks tons of things.

**Comment by harrisonchan** [comment] 2023-04-14 16:15
> It does seem v3 on new architecture breaks things, the whole API section in the documentation about Layout animations like entering, exiting, layout props stopped working. I thought I had a problem with my packages after upgrade, but copied the `Bokeh` example from `FabricExample` in this repository and ran it on my project and it worked just fine. But layout animations seem to be broken.
> 
> Layout animation examples in the `FabricExample` seem to be broken as well.
> 
> React Native: 0.71.6 Reanimated: 3.0.2

Seems like LayoutAnimations don't work on Fabric yet [https://github.com/software-mansion/react-native-reanimated/issues/3439](url)

**Comment by kmagiera** [comment] 2023-04-18 12:58
@harrisonchan the work on LayoutAnimations API support for Fabric has not been finalized yet, it is not a regression related to Reanimated 3, this support just hasn't landed yet

**Comment by Latropos** [comment] 2023-10-30 16:07
Closing since I understand that most of the problems were fixed in 3.1.0. nad the remaining ones (if still persist) will be handled in separate issues

**Closed by Latropos** 2023-10-30 16:07 UTC
Labels: Missing repro, Platform: Android, Platform: iOS, Needs review
