### ISSUE TITLE
TypeError: expect.extend is not a function

### ISSUE THREAD

**Issue by billnbell** [software-mansion/react-native-reanimated#3215] opened 2022-05-05 15:03 UTC
Latest RN 2.8.0 "react-native-reanimated": "2.8.0".

Getting:
 FAIL  src/__tests__/ComponentRender-test.tsx
  ● Test suite failed to run

    TypeError: expect.extend is not a function

      at Object.setUpTests (node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js:219:10)
      at Object.<anonymous> (jestSetupFile.js:163:62)

**Comment by billnbell** [comment] 2022-05-05 15:17
This happens on jest  upgrade from ^27.5.1  →  ^28.0.3

**Comment by finalight** [comment] 2022-05-24 08:02
> To fix this:
> 
> 1. Ensure you are calling this inside a script script that runs in `setupFilesAfterEnv` NOT `setupFiles`
> 2. Change the import in the script to `const { expect } = require('@jest/globals');` from `const expect = require('expect');` with `patch-package`
> 
> I have opened a PR to fix this here: #3217

i've tried the same thing you did, but it still shows me the same error

**Comment by mayconline** [comment] 2022-05-26 01:15
> To fix this:
> 
> 1. Ensure you are calling this inside a script script that runs in `setupFilesAfterEnv` NOT `setupFiles`
> 2. Change the import in the script to `const { expect } = require('@jest/globals');` from `const expect = require('expect');` with `patch-package`
> 
> I have opened a PR to fix this here: #3217

same error, i believe this resolve this error when merge,
link do helper: https://jestjs.io/pt-BR/docs/upgrading-to-jest28

**Comment by finalight** [comment] 2022-08-18 07:14
the PR is merged, but i still facing the same error

```
  ● Test suite failed to run

    TypeError: expect.extend is not a function

      22 | }
      23 |
    > 24 | require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests()
         |                                                              ^
      25 |
      26 | // eslint-disable-next-line no-underscore-dangle
      27 | global.__reanimatedWorkletInit = jest.fn()

      at Object.extend [as setUpTests] (node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js:152:12)
      at Object.setUpTests (jest-utils/jest.setup.js:24:62)
```

**Comment by Norfeldt** [comment] 2022-08-25 07:02
Here is a repo showing how it breaks after upgrading to jest 28 https://github.com/Norfeldt/expo-46-with-jest-rtnl-reanimated

**Comment by billnbell** [comment] 2022-08-25 19:10
still erroring!!!!!!

**Comment by Norfeldt** [comment] 2022-08-26 14:25
It's not missing a repo. I provided a minimal example repro that reproduce the issue.

**Comment by billnbell** [comment] 2022-08-29 03:10
pretty simple repo. I just added `require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();` in the setup-tests.js and it fails with expect.extend is not a function

```
 FAIL  src/components/member/explore/destination-screen/__tests__/helpers.test.ts
  ● Test suite failed to run

    TypeError: expect.extend is not a function

      1 | import 'react-native';
      2 |
    > 3 | require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();
        |                                                              ^
      4 |

      at Object.extend [as setUpTests] (node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js:160:12)
      at Object.setUpTests (setup-tests.js:3:62)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:16)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by billnbell** [comment] 2022-08-29 03:15
The try/catch is around the wrong things. The fix is:

 Go into `node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js`

```
export const setUpTests = (userConfig = {}) => {
    require('setimmediate');
    frameTime = Math.round(1000 / config.fps);
    config = Object.assign(Object.assign({}, config), userConfig);
    let expect;
    try {
        expect = require('expect');
        expect.extend({
            toHaveAnimatedStyle(received, expectedStyle, config = {}) {
                return compareStyle(received, expectedStyle, config);
            },
        });
    }
    catch (_) {
        // for Jest in version 28+
        const { expect: expectModule } = require('@jest/globals');
        expect = expectModule;
        expect.extend({
            toHaveAnimatedStyle(received, expectedStyle, config = {}) {
                return compareStyle(received, expectedStyle, config);
            },
        });
    }
};
```

**Comment by billnbell** [comment] 2022-08-29 03:17
Patch file

```
diff --git a/node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js b/node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js
index d8befd8..9e41d37 100644
--- a/node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js
+++ b/node_modules/react-native-reanimated/lib/reanimated2/jestUtils.js
@@ -145,23 +145,28 @@ export const advanceAnimationByFrame = (count) => {
     jest.advanceTimersByTime(frameTime);
 };
 export const setUpTests = (userConfig = {}) => {
+    require('setimmediate');
+    frameTime = Math.round(1000 / config.fps);
+    config = Object.assign(Object.assign({}, config), userConfig);
     let expect;
     try {
         expect = require('expect');
+        expect.extend({
+            toHaveAnimatedStyle(received, expectedStyle, config = {}) {
+                return compareStyle(received, expectedStyle, config);
+            },
+        });
     }
     catch (_) {
         // for Jest in version 28+
         const { expect: expectModule } = require('@jest/globals');
         expect = expectModule;
+        expect.extend({
+            toHaveAnimatedStyle(received, expectedStyle, config = {}) {
+                return compareStyle(received, expectedStyle, config);
+            },
+        });
     }
-    require('setimmediate');
-    frameTime = Math.round(1000 / config.fps);
-    config = Object.assign(Object.assign({}, config), userConfig);
-    expect.extend({
-        toHaveAnimatedStyle(received, expectedStyle, config = {}) {
-            return compareStyle(received, expectedStyle, config);
-        },
-    });
 };
 export const getAnimatedStyle = (received) => {
     return getCurrentStyle(received);
```

**Comment by billnbell** [comment] 2022-08-29 03:24
Also, for RV 0.69+hermes has moved to c++17 and it needs to be modified:

```
s.xcconfig               = {
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++14",
    "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/boost\" \"$(PODS_ROOT)/boost-for-react-native\" \"$(PODS_ROOT)/glog\" \"$(PODS_ROOT)/#{folly_prefix}Folly\" \"${PODS_ROOT}/Headers/Public/React-hermes\" \"${PODS_ROOT}/Headers/Public/hermes-engine\"",
                               "OTHER_CFLAGS" => "$(inherited)" + " " + folly_flags  }

```

Change to:

```
s.xcconfig               = {
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
    "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/boost\" \"$(PODS_ROOT)/boost-for-react-native\" \"$(PODS_ROOT)/glog\" \"$(PODS_ROOT)/#{folly_prefix}Folly\" \"${PODS_ROOT}/Headers/Public/React-hermes\" \"${PODS_ROOT}/Headers/Public/hermes-engine\"",
                               "OTHER_CFLAGS" => "$(inherited)" + " " + folly_flags  }

```

**Comment by Norfeldt** [comment] 2022-08-29 13:34
@billnbell thank you very much for sharing your fix for the issue 🙌 (will try it later this week)

@billnbell github-actions seems to think that there still are missing a repo - does it have to be you that add it? If so you can perhaps fork mine or link to it?

**Comment by Norfeldt** [comment] 2022-09-07 17:38
@billnbell is it too much to ask if you could make a PR to show the fix to the demo repo I have provided?

**Comment by yusufyildirim** [comment] 2022-09-10 12:06
Here's the fix https://github.com/software-mansion/react-native-reanimated/pull/3559

**Comment by billnbell** [comment] 2022-09-10 18:40
This does not require a repo. Install React Native 0.70 and create a simple jest test, and it blows up.

The fixes provided above work well.

**Comment by Norfeldt** [comment] 2022-09-14 13:10
@yusufyildirim 

> Here's the fix #3559

Tried to open the PR, copy the content from the file changed into the my node_modules/react-native-reanimated2 and do a `yarn patch-package react-native-reanimated` - did not work. Then I took the suggestion from @billnbell https://github.com/software-mansion/react-native-reanimated/issues/3215#issuecomment-1229705286 and replaced the content in the patch to that. Now it seems to get pass the `expect extend` error. 

There still seems to be some issues regarding `"now"`

```
TextField › input field › has accessibility label and hint for the input field

    TypeError: Cannot read properties of undefined (reading 'now')

      at Object.now (node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated.js:14:72)
      at JSReanimated.now [as getTimestamp] (node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated.js:25:34)
      at Timeout.getTimestamp [as _onTimeout] (node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated.js:32:37)
```

<img width="995" alt="Screenshot 2022-09-14 at 15 10 12" src="https://user-images.githubusercontent.com/678806/190162843-3f7042ee-a389-43b8-9c39-87abe4a6068a.png">


```
<PATH>/expo-app/node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated.js:54
          return global.ReanimatedDataMock.now();
                                           ^

TypeError: Cannot read properties of undefined (reading 'now')
    at Object.now (<PATH>/expo-app/node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated.js:14:72)
````

**Comment by bmarden** [comment] 2022-10-12 23:46
@Norfeldt 

I fixed the `now()` TypeErrors by changing `node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated.js` line 14. Inside the constructor within the `if (isJest())` statement 

before
```javascript
this.timeProvider = { now: () => global.ReanimatedDataMock.now() };
```
after
```javascript
this.timeProvider = { now: () => global.performance.now() };
```

Not sure if this is the right way to go or if it actually fixes the issue, but I'm not getting any more TypeErrors at least.

**Comment by Youssef-Durgham** [comment] 2022-10-19 21:49
any one fix this error ?

**Comment by Youssef-Durgham** [comment] 2022-10-19 22:05
fixed by doing that 
expo start -c   
will fix your error

**Comment by Latropos** [comment] 2023-08-04 10:21
Closing since fix is already merged: https://github.com/software-mansion/react-native-reanimated/pull/3559

**Closed by Latropos** 2023-08-04 10:21 UTC
Labels: Missing repro, Needs review, Missing info
