### ISSUE TITLE
Detached views with Animated nodes break

### ISSUE THREAD

**Issue by Jarred-Sumner** [software-mansion/react-native-reanimated#595] opened 2020-02-04 00:10 UTC
The error is:
```objc
-[__NSArrayM setObject:atIndexedSubscript:]: object cannot be nil
```

I spent a little time debugging this.

It happens when:
- The component is detached (e.g. `display: none`)
- Fast refresh loads the component (sometimes)

If you have any animated nodes inside a `<Modal>`, it breaks.

It happens right here:
![image](https://user-images.githubusercontent.com/709451/73701132-636b2f00-469d-11ea-8d43-2998543d0ed8.png)

In `-(id) evaluate` for most (maybe all) of the nodes, this error can happen.

Most likely, the logic for detaching animated nodes needs to account for whether the view backing the node is attached (`superview != nil && window != nil`). It probably shouldn't be trying to evaluate these nodes on a detached view, since that likely means if you have an inactive screen with animated nodes on it, those `Animated.Node` will continue to be evaluated (which can cause performance issues)

**Comment by jakub-gonet** [comment] 2020-02-21 12:15
Hey @Jarred-Sumner,

your suggestion about not evaluating nodes on detached views makes sense, but I couldn't reproduce this error (tried using modal, tried setting `display: none`), do you mind sharing some [snack](https://snack.expo.io/) with some example code which can trigger the crash reliably?

**Comment by jakub-gonet** [comment] 2020-08-08 17:48
The problem with nodes evaluation is that you can create nodes on one view and use them in the other view. If you update nodes in the second view they should evaluate nodes dependent on them, even on not active views.

Closing until some reproduction example is given.

**Closed by jakub-gonet** 2020-08-08 17:48 UTC
Labels: 🍎iOS, 🧰need-repro
