### ISSUE TITLE
ANR caused in performOperations

### ISSUE THREAD

**Issue by heroic** [software-mansion/react-native-reanimated#2251] opened 2021-08-04 03:00 UTC
## Description

We are seeing multiple ANRs with reanimated at the top of the stacktrace. These are not showing in bugsnag either, only on Play Store which is now penalising our app.

### Expected behavior

No ANR

### Actual behavior & steps to reproduce

```
"main" prio=5 tid=1 Waiting
```
```
  at sun.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt (AbstractQueuedSynchronizer.java:868)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1023)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1334)
  at java.util.concurrent.Semaphore.acquire (Semaphore.java:318)
  at com.swmansion.reanimated.NodesManager.performOperations (NodesManager.java:230)
  at com.swmansion.reanimated.NodesManager.onAnimationFrame (NodesManager.java:259)
  at com.swmansion.reanimated.NodesManager.access$000 (NodesManager.java:65)
  at com.swmansion.reanimated.NodesManager$1.doFrameGuarded (NodesManager.java:153)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1063)
  at android.view.Choreographer.doCallbacks (Choreographer.java:889)
  at android.view.Choreographer.doFrame (Choreographer.java:812)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1050)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7830)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1040)
```

## Snack or minimal code example

None available

## Package versions

- React Native: 0.63.4
- React Native Reanimated: 2.2.0
- NodeJS: 16.0.0
- Xcode: 
- Java & Gradle: openjdk 11.0.8 gradle 6.5

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by beetlebum** [comment] 2021-12-09 15:33
I am experiencing exactly the same issue since upgrading to 2.3 in production.

`Input dispatching timed out (9fff00a [My app Activity] (server) is not responding. Waited 10002ms for FocusEvent(hasFocus=false))`

```
"main" prio=5 tid=1 Waiting

 at sun.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt (AbstractQueuedSynchronizer.java:868)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1023)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1334)
  at java.util.concurrent.Semaphore.acquire (Semaphore.java:318)
  at com.swmansion.reanimated.NodesManager.performOperations (NodesManager.java:249)
  at com.swmansion.reanimated.NodesManager.onAnimationFrame (NodesManager.java:278)
  at com.swmansion.reanimated.NodesManager.access$000 (NodesManager.java:63)
  at com.swmansion.reanimated.NodesManager$1.doFrameGuarded (NodesManager.java:168)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:970)
  at android.view.Choreographer.doCallbacks (Choreographer.java:796)
  at android.view.Choreographer.doFrame (Choreographer.java:727)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:957)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:250)
  at android.app.ActivityThread.main (ActivityThread.java:7868)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:958)
```
![image](https://user-images.githubusercontent.com/227258/145425980-f11f1e82-94cd-45c6-9f75-21a6da304021.png)
![image](https://user-images.githubusercontent.com/227258/145426026-8fedf365-c57f-4ce4-a098-2b67784a7720.png)

**Comment by joy-betterhalf** [comment] 2022-01-10 19:29
Hey @heroic

Did you find any solution for it? We started facing a similar issue when we moved from APK to App bundle. 

Thanks.

**Comment by kmagiera** [comment] 2022-01-28 09:56
Hi all, thanks for reporting. The ANR is likely cause by a deadlock due to the code we use for making synchronizing UI updates. However, w/o more details it is very little we can do about it. It'd be important for us to get some more information about what kind of animations run when this occurs, or get traces from other threads if available. Any kind of additional detail that you may share may be helpful in getting to the bottom of this issue.

**Comment by heroic** [comment] 2022-01-28 14:54
From what I can tell the only animations that are happening are the React Navigation screen changes. We're seeing this when going from one `Screen` to a `Screen` containing `Tabs`, and also when going from one simple `Screen` to another `Screen`.

Here's a pastebin from one of the crash logs: https://pastebin.com/pxBRCn63

**Comment by joy-betterhalf** [comment] 2022-01-28 21:11
@heroic 

Can you please confirm your react navigation version? 

We are also seeing similar behavior at the same place where we are using Stack navigation > Tab navigation

**Comment by heroic** [comment] 2022-01-29 06:44
@joy-betterhalf RN v5

**Comment by joy-betterhalf** [comment] 2022-02-03 19:54
@kmagiera In our case, we have tried removing every place where we directly use `react-native-reanimated` for animation and kept the library as a dependency for other modules such as `https://gorhom.github.io/react-native-bottom-sheet/` still we are getting many ANRs with the same error everyone facing here and we are not sure what causes the ANR and that's why I asked @heroic on React navigation version since I thought is old and could be causing this problem. We were using V4 which now migrated to V5 but still, we are facing the same issue.

**Comment by geroale** [comment] 2022-03-10 18:01
Same issue here

**Comment by marf** [comment] 2022-03-10 18:04
We have the same issue.

**Comment by ohheyitskartik** [comment] 2022-09-07 02:22
can we merge this ? still facing this issue..

**Comment by marf** [comment] 2022-09-07 06:43
Yes, please merge the PR #3440 in the master and release an update to hopefully fix this issue. Thanks!

**Comment by androideveloper** [comment] 2022-10-13 10:30
Did anyone tried this change https://github.com/software-mansion/react-native-reanimated/pull/3440 in prod?

**Comment by HilSny** [comment] 2022-11-02 19:13
We're seeing this as well and it started when we integrated react-native-reanimated-carousel. If we show a carousel right away after app launch, the app hangs and never recovers. I don't know if that helps you but we had to disable our tutorial carousel as a result and are still seeing ANRs as a result. The crash happens before there is any interaction with the carousel.

**Comment by gollobo** [comment] 2023-01-17 11:09
Same ANRs in production here! This is by far the most common ANR cause in our apps at the moment (+60%)
Any workarounds while the bug is fixed?

**Comment by androideveloper** [comment] 2023-01-19 09:49
See my comment above

**Comment by jedashford** [comment] 2023-02-09 02:09
Following. We are also seeing significant crashes for iOS that appear related to this, thousands daily.

**Comment by pavangoyal42** [comment] 2023-02-15 17:33
@androideveloper is your fix working well so far in production app ? any issues you see like animation is starting with delay ? we are also seeing same ANRs on play console.

**Comment by androideveloper** [comment] 2023-02-21 17:10
No major issues so far 👍

**Comment by prince-housing** [comment] 2023-03-10 10:21
Thanks for the help @androideveloper, we had added the patch https://github.com/software-mansion/react-native-reanimated/pull/3440 in our app.
This helps us to fix the ANR issue on the app 👍 

But using the above fix we facing an increase in user crashes, below is the crash log for the same.

```
Fatal Exception: com.facebook.jni.CppException: bad_weak_ptr
       at com.swmansion.reanimated.Scheduler.triggerUI(Scheduler.java)
       at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:24)
       at com.swmansion.reanimated.Scheduler$2.runGuarded(Scheduler.java:43)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8218)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
```

We are using `react-native` version  `0.69.4` and `react-native-reanimated` version `2.12.0`.

**Comment by pavangoyal42** [comment] 2023-03-10 10:39
@androideveloper we have also applied the patch. no anr or issue so far.
@prince-housing we were also facing this crash. I can confirm react-native-reanimated 3.0.0 solved the issue for us. no instances seen after 3.0.0.

**Comment by prince-housing** [comment] 2023-03-10 10:51
> 

@pavangoyal42  did you also use the patch with `react-native-reanimated` `3.0.0`?

**Comment by pavangoyal42** [comment] 2023-03-10 12:39
@prince-housing yes I have used patch with 3.0.0. this solved the crash and ANR. so side effects as of now.

**Comment by piaskowyk** [comment] 2023-05-23 10:08
Fixed with https://github.com/software-mansion/react-native-reanimated/pull/4239, the fix is available since 3.+ versions

**Closed by piaskowyk** 2023-05-23 10:08 UTC
Labels: Bug, 🏠  Reanimated 2, bug-bash-jan22
