### ISSUE TITLE
Animation are flickering on IOS when Sentry integration is active

### ISSUE THREAD

**Issue by fdecampredon** [software-mansion/react-native-reanimated#6370] opened 2024-08-02 22:20 UTC
### Description

Some animations involving height / width / padding are flickering on project using `@sentry/react-native`. Disabling `enableStallTracking` in `Sentry.ReactNativeTracing` options resolves the bug. 
The behavior looks like  what's described in #5671.

The bug only appears on some devices. iPhone 15, iPhone 15 pro iPhone 15 pro max and iPhone 12 mini are affected however iPhone 11pro is not. All our devices were on IOS 17.5.1 during the tests.

[Sentry issue](https://github.com/getsentry/sentry-react-native/issues/3987)

### Steps to reproduce

Here is our sentry configuration : 

```typescript
const routingInstrumentation = new Sentry.RoutingInstrumentation();
Sentry.init({
  dsn: process.env.SENTRY_DSN,
  enabled: !__DEV__,
  environment: process.env.DEPLOYMENT_ENVIRONMENT,
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation,
    }),
  ],
});
```

We use a custom router so here is our sample code integrating with the routingInstrumentation : 
```typescript
routingInstrumentation.onRouteWillChange({
  name: route.route,
  op: 'navigation',
  data: {
    route: {
      name: route.route,
      params: route.params,
    },
    previousRoute: previous
      ? {
          name: previous.route,
          params: previous.params,
        }
      : null,
  },
});
```

### Snack or a link to a repository

can't create a valid minimal reproduction example

### Reanimated version

3.14.0

### React Native version

0.74.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by MatiPl01** [comment] 2024-08-05 09:50
Hey!
Could you please share a recording of the issue? I understand that sharing a repro might be not possible but recording may show how the issue looks like.

**Comment by fdecampredon** [comment] 2024-08-06 07:16
Here is a video showing the "flickering" animation
https://github.com/user-attachments/assets/c6725d55-1ab0-4270-8bec-54405170114d

**Comment by pavelbabenko** [comment] 2024-08-16 09:02
@fdecampredon Good catch! Works smoothly after adding `enableStallTracking: false` option to `ReactNativeTracing`

**Comment by piaskowyk** [comment] 2024-09-17 11:27
I'm sorry, but without any reproduction, we can't assist with this issue. Unfortunately, we don't have sufficient capacity to recreate a fairly complex app with navigation, animation, and integrated Sentry. 😢  Therefore, I need to close this issue. However, if anyone provides a reproduction, we will be more than happy to reopen it.

**Closed by piaskowyk** 2024-09-17 11:27 UTC
Labels: Missing repro, Platform: iOS
