### ISSUE TITLE
IOS 2.3.0-alpha.3 issue with RN 0.65.1 's native component like textinput, modal...

### ISSUE THREAD

**Issue by KoreanThinker** [software-mansion/react-native-reanimated#2370] opened 2021-09-04 13:25 UTC
## Description
Error messages
- No command found with name "focus"
- No command found with name "setTextAndSelection"

### ScreenCapture "2.3.0-alpha.3"
https://user-images.githubusercontent.com/48207131/132021725-1063ca8b-3b89-40a0-837b-b324481b5a86.mov

### Error message
<p>
<img width="360px" src="https://user-images.githubusercontent.com/48207131/132019620-9c3b77e5-802c-4837-98ea-e5527b2c8461.png" alt="1234923" />
<img width="360px" src="https://user-images.githubusercontent.com/48207131/132019709-8ef38c60-d6ae-4cf3-b4e7-6d271f0d5454.png" alt="1234923" />
</p>

#### Screen Capture "2.3.0-alpha.2"
https://user-images.githubusercontent.com/48207131/132096233-db084fc1-082f-4a58-8246-9a98eb4bb725.mov

### Actual behavior & steps to reproduce
just click textinput or open and hide modal

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-alpha.3
- NodeJS: 14.17.5
- Xcode: 12.5
- Java & Gradle:

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

### MyFooter Component
```tsx
import React, { useEffect } from 'react'
import { useCallback } from 'react'
import { useState } from 'react'
import { ActivityIndicator, Pressable, StyleSheet, TextInput, View, Keyboard, Text, BackHandler } from 'react-native'
import { COLOR1, GRAY3 } from '../../constants/styles'
import { useCreateChat } from '../../graphql/chat'
import Icon from 'react-native-vector-icons/MaterialIcons'
import useGlobalUi from '../../hooks/useGlobalUi'
import { useRef } from 'react'
import useImageUpload from '../../hooks/useImageUpload'
import { chatRoom_chatRoom } from '../../graphql/__generated__/chatRoom'


interface ChatDetailFooterProps {
    data: chatRoom_chatRoom
}

const ChatDetailFooter: React.FC<ChatDetailFooterProps> = (props) => {

    const { id, isIBlocked, isBlockedMe } = props.data

    const inputRef = useRef<TextInput>(null)

    const [createChat, { loading }] = useCreateChat()
    const [message, setMessage] = useState<string>()
    const { toast } = useGlobalUi()
    const { clear, upload, loading: imageUploadLoading } = useImageUpload('chatImage')
    const [optionVisible, setOptionVisible] = useState(false)
    const [focused, setFocused] = useState(false)

    useEffect(() => {
        const KeyboardWillShowListner = Keyboard.addListener('keyboardWillShow', () => { setOptionVisible(false); setFocused(true) })
        const KeyboardDidShowListner = Keyboard.addListener('keyboardDidShow', () => { setOptionVisible(false); setFocused(true) })
        const keyboardDidHideListner = Keyboard.addListener('keyboardDidHide', () => { setFocused(false); inputRef.current?.blur() })
        const keyboardWillHideListner = Keyboard.addListener('keyboardWillHide', () => { setFocused(false); inputRef.current?.blur() })

        return () => {
            Keyboard.removeSubscription(KeyboardWillShowListner)
            Keyboard.removeSubscription(KeyboardDidShowListner)
            Keyboard.removeSubscription(keyboardDidHideListner)
            Keyboard.removeSubscription(keyboardWillHideListner)
        }
    }, [])

    useEffect(() => { // android backhandler
        if (!optionVisible) return
        const listner = BackHandler.addEventListener('hardwareBackPress', () => {
            setOptionVisible(false)
            return true
        })

        return () => {
            listner.remove()
        }
    }, [optionVisible])


    const onSend = useCallback(async (image?: string | null) => {
        if (!message && !image) return
        if (loading || imageUploadLoading) return

        inputRef.current?.blur()
        Keyboard.dismiss()
        setOptionVisible(false)

        const { errors } = await createChat({
            variables: {
                input: {
                    chatRoomId: id,
                    message: image ? undefined : message || undefined,
                    image: image || undefined
                }
            }
        })
        if (errors) {
            toast({ content: '오류' })
            return
        }
        setMessage('')
        clear()
    }, [message, id, loading, inputRef, imageUploadLoading])

    const onOptions = useCallback(() => {
        if (isIBlocked || isBlockedMe) return setOptionVisible(false)
        if (!optionVisible) Keyboard.dismiss()
        setOptionVisible(prev => !prev)
    }, [optionVisible, isIBlocked, isBlockedMe])

    const OPTIONS = [
        {
            title: '앨범',
            icon: <Icon name='album' color='#fff' size={24} />,
            onPress: () => {
                upload({}, 'chatImage/').then(v => onSend(v))
            }
        },
        {
            title: '카메라',
            icon: <Icon name='camera' color='#fff' size={24} />,
            onPress: () => {
                upload({ camera: true }, 'chatImage/').then(v => onSend(v))
            }
        },
    ]


    return (
        <>
            <View style={[styles.container]} >
                <Pressable
                    onPress={onOptions}
                    style={[styles.addBtn, { transform: [{ rotate: optionVisible ? '45deg' : '0deg' }] }]}
                >
                    <Icon name='add' color='#fff' size={24} />
                </Pressable>
                {!(isIBlocked || isBlockedMe) ?
                    <>
                        {(!message && !focused) && <View style={styles.line} />}
                       //-------------------------- ScreenCaptrue's TextInput --------------------- //
                        <TextInput
                            ref={inputRef}
                            value={message}
                            onChangeText={(t) => setMessage(t)}
                            style={styles.input}
                            maxLength={1000}
                            multiline
                            editable={!(loading || imageUploadLoading)}
                        />
                    </>
                    :
                    <Text style={[styles.input, { opacity: 0.5 }]} >{isIBlocked ? '차단한 사용자와는 채팅할 수 없습니다' : '상대방이 차단하여 채팅할 수 없습니다'}</Text>
                }
                <Pressable
                    onPress={() => onSend()}
                    style={styles.sendBtn}
                >
                    {loading || imageUploadLoading
                        ? <ActivityIndicator color='#fff' size='small' />
                        : <Icon name='send' color='#fff' size={16} />
                    }
                </Pressable>
            </View>
            {optionVisible && <View style={styles.optionContainer} >
                {OPTIONS.map(v => (
                    <View
                        style={styles.optionItem}
                        key={v.title}
                    >
                        <View style={{ alignItems: 'center' }} >
                            <Pressable
                                onPress={v.onPress}
                                style={styles.optionIconContainer}
                            >
                                {v.icon}
                            </Pressable>
                            <Text>{v.title}</Text>
                        </View>
                    </View>
                ))}
            </View>}
        </>
    )
}

export default ChatDetailFooter

```

**Comment by andreialecu** [comment] 2021-09-04 14:45
Duplicate of #2364

**Comment by jmysliv** [comment] 2021-09-06 06:28
Duplicate of #2364

**Closed by jmysliv** 2021-09-06 06:28 UTC
Labels: 🐞 Bug

**Comment by smrutiparida** [comment] 2022-11-11 11:14
@gabimoncha @KoreanThinker we encountered this bug in Pressable recently.
