### ISSUE TITLE
Layout Animations is not working as expected

### ISSUE THREAD

**Issue by im-alihashmi14** [software-mansion/react-native-reanimated#4822] opened 2023-07-26 11:56 UTC
### Description

When I add `Animated.View` and apply `layout={Layout.springify()}`. Animation works perfectly but when I go back and navigate back to this screen this layout animation donot work. 
[https://drive.google.com/file/d/1UGQlT9lgY_EtRSrbMMFX7dcXOcCoNW6h/view?usp=sharing](https://drive.google.com/file/d/1UGQlT9lgY_EtRSrbMMFX7dcXOcCoNW6h/view?usp=sharing)

Kindly see the above video

### Steps to reproduce

Just Add Animated.View and go back and then navigate again to that screen

### Snack or a link to a repository

nan

### Reanimated version

3.3.0

### React Native version

0.71.11

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

iPhone 14 pro max

### Acknowledgements

Yes

**Comment by joeporpeglia** [comment] 2023-07-26 16:38
Possibly related to #4816. @im-alihashmi14 I can't tell what your navigator setup is, but can you see if the workaround listed in the other issue fixes this?

**Comment by im-alihashmi14** [comment] 2023-07-26 17:40
Hi @joeporpeglia. thank you so much for your response.
Yes I tried your work around and its working perfectly but now this issue is happening when I am going forward from current screen and then returning back. 

You can look at video below


https://github.com/software-mansion/react-native-reanimated/assets/59221555/c2498b7d-5caa-4d1e-863f-1f08d7478a1e




For the Navigator setup, I have bottom tab navigator and I tried to navigate from Bottom Tab to Native Stack Navigator that's where animation stops working. Now by applying your workaround, my animation is working when coming from Tab to Native Screen. But when I go from Native Screen to other Native Screen and then coming back, that's when animation stops working.

**Comment by joeporpeglia** [comment] 2023-07-26 19:50
Any chance you're using `freezeOnBlur` with that stack navigator? I'm not sure what's actually going on here, but it seems like the "detached screen" behavior is conflicting with reanimated v3 layout transitions

**Comment by Latropos** [comment] 2023-07-28 08:56
Duplicate of #4816

**Comment by Latropos** [comment] 2023-07-28 12:34
It seems that only IOS is affected

**Comment by grifotv** [comment] 2023-08-18 15:12
I'm experiencing the same issue since upgrading Reanimated from `2.14.4` to `3.3.0`.

**Comment by badalsaibo** [comment] 2023-11-18 13:16
Creating a simple `Switch` component and the layout animation won't work on the iOS emulator. On Android it works perfectly.

```
type SwitchProps = {
  value: boolean;
  toggleSwitch: () => void;
};

const Switch = ({ value, toggleSwitch }: SwitchProps) => {
  return (
    <Pressable onPress={toggleSwitch} hitSlop={10}>
      <View
        className="relative bg-app-grey-100 rounded-full flex-row items-center"
        style={{ height: 26, width: 40 }}>
        <Animated.View
          className="absolute bg-white rounded-full"
          layout={SequencedTransition}
          style={[
            {
              width: 22,
              height: 22,
              ...(value
                ? { right: 2, backgroundColor: colors['app-purple-900'] }
                : { left: 2 }),
            },
          ]}
        />
      </View>
    </Pressable>
  );
};
```

**Comment by Latropos** [comment] 2024-10-16 10:51
It seems that we forgot to close this issue after merging this fix: https://github.com/software-mansion/react-native-reanimated/pull/4997

**Closed by Latropos** 2024-10-16 10:51 UTC
Labels: Missing repro, Platform: iOS
