### ISSUE TITLE
App crashes when using lots of animated styles

### ISSUE THREAD

**Issue by diogoquintas** [software-mansion/react-native-reanimated#3858] opened 2022-12-12 17:22 UTC
### Description

When rendering a considerable amount of components that use reanimated, the app crashes with `EXC_BAD_ACCESS` on `reanimated::RuntimeDecorator::decorateUIRuntime`.

<img width="1712" alt="Reanimated error" src="https://user-images.githubusercontent.com/30559279/207104879-e0d206f8-6bb2-4a1f-a3e8-d3872c6d3aa9.png">

[report](https://github.com/software-mansion/react-native-reanimated/files/10207525/crash.txt)

The issue also happens with fewer elements but it's more difficult to reproduce.
This does not happen when using the last stable version (2.13.0), although the performance seems to be worse.

### Steps to reproduce

Just opening the app, it consistently crashes even without interaction.

### Snack or a link to a repository

https://github.com/diogoquintas/reanimated-example

### Reanimated version

3.0.0-rc.8

### React Native version

0.70.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2022-12-13 09:12
Hey @diogoquintas, thanks for reporting this issue.

It seems like the offending commit is c8a77da44a6cf53f14f224f6f15527a26c770f09. It would be very appreciated if you could revert these changes manually in your `node_modules` and confirm that it resolves the issue.

If this succeeds, the plan is to revert c8a77da44a6cf53f14f224f6f15527a26c770f09 (which will break error handling in `runOnUI`), merge #3846 (which should fix it) and then release 3.0.0-rc.9.

> This does not happen when using the last stable version (2.13.0), although the performance seems to be worse.

The issue is related to the new implementation of shared values which we released only in v3-rc in order to collect the feedback from the community so thanks again for spotting and reporting the bug! Despite the crash, we are happy that you can see the performance improvement in 3.0.0-rc.8 compared to v2.

**Comment by diogoquintas** [comment] 2022-12-15 10:40
> It seems like the offending commit is [c8a77da](https://github.com/software-mansion/react-native-reanimated/commit/c8a77da44a6cf53f14f224f6f15527a26c770f09). It would be very appreciated if you could revert these changes manually in your `node_modules` and confirm that it resolves the issue.

Although it seems to fix the issue on iOS, the app crashes when booting on Android.

Probably this is not related to the initial issue because there's no error, the app is killed by using too much resources.
In the repo provided, I can find a sweet spot of items to render that work in version `2.10.0` but crashes in `3.0.0-rc.8`.
Could it just be a performance downgrade in Android or some other issue?

I took a look at [this issue](https://github.com/software-mansion/react-native-reanimated/issues/3854) because it looks similar and tried running with the changes from #3852 but to no avail.

**Comment by graszka22** [comment] 2023-01-23 16:00
So it's fixed on iOS.
On my Android device it works too, though slowly and takes about ~2gb of memory according to android studio profiler. But I guess it's expected with 10000 animated views.

**Comment by diogoquintas** [comment] 2023-01-24 11:58
Yes, the initial issue is fixed.

The other issue I mentioned (happening on Android) seems to be more related to performance than an error itself.
The version `3.0.0-rc.8` is supposed to be faster but in that example is the other way around. 

With that said, we can probably close this issue.

**Closed** 2023-01-24 13:18 UTC
Labels: Platform: iOS, Needs review, Repro provided
