### ISSUE TITLE
Android: Animations stop working after a while

### ISSUE THREAD

**Issue by Georgio-Saad** [software-mansion/react-native-reanimated#5388] opened 2023-11-20 15:43 UTC
### Description

As the title suggested, animations (withTiming, withDecay, etc...) just stop working

I'm using Expo managed workflow

Versions:

- Expo ; 49.0.19
- React-Native ; 0.72.4
- Reanimated ; 3.3.0
- Gesture Handler ; 2.12.0

This issue has happend on recently 2 projects running reanimated 3.3.0 and expo > 49

Unfortunatley i haven't been able to provide reproducable steps because i simply dont know the cause.

### Steps to reproduce

Couldnt reproduce, but this issue started happening after we upgraded our projects to expo > 49 and reanimated 3.3.0

### Snack or a link to a repository

Couldnt reproduce in a snack

### Reanimated version

3.3.0

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo Go

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by drhootch** [comment] 2023-12-18 17:23
> This was fixed in a later version of Reanimated, I think in 3.4.x or so (not a developer of this project but just remember that I had this issue in the Reanimated version 3.3.0).

I had the same issue, the problem is Reanimated  3.4.x doesn't work with expo out of the box yet, when Reanimated is installed via ```npx expo install react-native-reanimated``` version ```3.3.0``` is installed

So to make this work i had to set :
```
"expo-dev-client": "3.1.0",
"react-native-reanimated": "~3.4.0",
```
in packages.json

**Comment by Vittor-Javidan** [comment] 2024-01-14 00:05
> > This was fixed in a later version of Reanimated, I think in 3.4.x or so (not a developer of this project but just remember that I had this issue in the Reanimated version 3.3.0).
> 
> I had the same issue, the problem is Reanimated 3.4.x doesn't work with expo out of the box yet, when Reanimated is installed via `npx expo install react-native-reanimated` version `3.3.0` is installed
> 
> So to make this work i had to set :
> 
> ```
> "expo-dev-client": "3.1.0",
> "react-native-reanimated": "~3.4.0",
> ```
> 
> in packages.json

where can i see documentation for expo-dev-client 3.x? All i can find is 2.x
I'm having this issue of not being able to update to a newer reanimated version than 3.3.0 and getting stuck with this annoying bug

**Comment by Vittor-Javidan** [comment] 2024-01-14 14:38
@drhootch your solution worked for me! But i updated my dev client to 3.3.4 instead, since the amount of downloads are much higher.

**Comment by piaskowyk** [comment] 2024-01-18 09:10
This issue is fixed with https://github.com/software-mansion/react-native-reanimated/pull/4579 and released since version 3.4.0. I recommend to update Reanimated to the latest version. You can use dev client or expo sdk 50 that contains the latest changes.

**Closed by piaskowyk** 2024-01-18 09:10 UTC
Labels: Missing repro, Platform: Android, Needs review

**Comment by mt-andreas** [comment] 2024-04-04 18:23
This helped for me.

**Comment by guilhermesandi** [comment] 2024-04-17 14:57
When i update expo-dev-client to current version i receive this error when i run "yarn android"
`gradlew.bat exited with non-zero code: 1`

**Comment by mimo-10** [comment] 2024-08-28 00:47
do i need to update the dev-client or i could just update reanimated + does it work on expo sdk 49 ?

**Comment by Vittor-Javidan** [comment] 2024-08-28 12:42
> do i need to update the dev-client or i could just update reanimated + does it work on expo sdk 49 ?

You can try just update the reanimated. The dev-client recognizes a range of version, so there is a minimum and a maximum version. If the version does not work, update the dev-client to accept newer version of reanimated. Or downgrade the dev-client if there is no other way. But since expo always force us to update to newer SDKs, because google forces API level upgrade, I do not recommend downgrade lib versions on mobile apps.
