### ISSUE TITLE
Attaching (for example creating Animated.Value or using cond, eq, set, etc) and detaching nodes blocks JS thread

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-reanimated#194] opened 2019-02-24 11:23 UTC
# Updated issue:

Reanimated uses a bridge to interact with the native side. Hight usage of bridge (lots of calls with lots of data to be passed) blocks the thread. Reanimated doing lots of calls. Even simple animation may produce 500-1500 calls. This is huge amount of calls. The main problem that it totally blocks the UI, the app might be showing just a blank screen or freeze until all the nodes are created and connected to each other.

You can verify it by using this simple snippet in your `App.js` (works only with React Native CLI project):

```js

import MessageQueue from 'react-native/Libraries/BatchedBridge/MessageQueue.js';

let count = 0;
const spyFunction = msg => {
  if (msg.module === 'ReanimatedModule') {
    console.log(++count, msg);
  }
};

MessageQueue.spy(spyFunction);
```

Most of the calls are `connectNodes`.

There is a thing which may reduce some amount of the calls – proc node. But it does not fix it for low-end devices;

You can verify the delay of rendering everything using this example:
https://snack.expo.io/@terrysahaidak/reanimated-header

### Original issue

I'm building a library which helps define an animation without any knowledge of reanimated. It's inspired a lot by [Animatable](https://github.com/oblador/react-native-animatable/) and called [react-native-reanimatable](https://github.com/terrysahaidak/react-native-reanimatable).

It relies on `Animated.Code` a lot since mostly I'm triggering animation by some props (changing value which runs/stops clocks).

But I'm noticed if I'm using several `Animated.Code`, it creates animated nodes and blocks JS Thread. It's noticeable on both Android and iOS.

You can check it out here (on my Xiaomi Mi5 and iPhone 7) with the Expo SDK 32:
https://drive.google.com/open?id=1RUaVYcP6-VG332rGS7lA5RsyRXJh7VTP
https://drive.google.com/open?id=15LDQphmnYyZtajFCERuugPgpUmeOIdG3

You can reproduce it using my lib example app:
https://github.com/terrysahaidak/react-native-reanimatable/tree/master/Example

Navigate to Base transition. It renders 10 components with `Animated.Code` under the hood. You can change count here:
https://github.com/terrysahaidak/react-native-reanimatable/blob/master/Example/screens/TransitionBase/TransitionBase.js#L103

Also here is some underlying logic:
Creating animation: https://github.com/terrysahaidak/react-native-reanimatable/blob/master/lib/core/createTransitionAnimation.js
Using of `Animated.Code`: https://github.com/terrysahaidak/react-native-reanimatable/blob/master/lib/components/TransitionAnimation.js

Thank you for such a great library!

##### UPDATE:

I've figured out that `Animation.Code` itself doesn't block the thread, but creating animation values and nodes do.

**Comment by sintylapse** [comment] 2019-08-19 21:24
@terrysahaidak does this still an issue?

**Comment by terrysahaidak** [comment] 2019-08-23 05:20
Hi @sintylapse, yes, it is. And it will be an issue untill reanimated migrate to jsi and react native use fabric.

But with 1.3 and proc nodes it might make it less obvious for the user to catch, so performance should be better, haven't tried it yet though.

**Comment by terrysahaidak** [comment] 2019-08-28 21:41
@computerjazz make sure you have ran the animation or just imported that file which has a proc defined before rendering a bunch of items in the flat list. also, make sure you've been defining procs outside the render, they should be static, only then they can be reused and won't block a js thread.

**Comment by michalsek** [comment] 2019-12-19 16:36
Hi @terrysahaidak, thanks for reporting the issue, could you provide minimal code example that reproduces the problem?

**Comment by terrysahaidak** [comment] 2019-12-19 21:41
Hi @michalsek, did you check out my original comment here? The problem not with my library I've used as an example here. 

The problem is that reanimated does too many calls to the bridge. You can easily count them using this snippet with any example:

```
import MessageQueue from 'react-native/Libraries/BatchedBridge/MessageQueue.js';

let count = 0;
const spyFunction = msg => {
  if (msg.module === 'ReanimatedModule') {
    console.log(++count, msg);
  }
};

MessageQueue.spy(spyFunction);
```

For simply animation it generates thousands of calls where React Native Animated produces 100-200. This is a huge difference. You may not notice it on iOS, but on android, even fast phone like my pixel 3 it is noticable.

We've tried already to fix it using JSI, but it didn't really help. @chrfalch made a fork for iOS where it was 2-3 faster. But there is almost no problem with it on iOS. My fork with JSI on android was 30% faster. This is just nothing.

Also to fix it @chrfalch created proc node. It does reduce amount of nodes created. But still, unfortunately, on low-end android it's unusable for most of the cases.

@kmagiera as well as @osdnk are aware of this problem.

**Comment by euroclydon37** [comment] 2020-04-15 21:04
I'm wondering what the status of this problem is. I know `proc` is a big saver in a lot of circumstances. But you can't pass arrays to it, meaning you can't fix `interpolate` which is causing huge performance issues for me because it's in a component that appears _alot_. 118 components rendered together using `interpolateColor` from `react-native-redash`, creates like 13K bridge messages.

**Comment by terrysahaidak** [comment] 2020-04-15 21:08
Everything I can say so far there is work in progress to fix this! And it's really exciting!

I hope it will be released soon!

**Comment by euroclydon37** [comment] 2020-04-15 21:08
Nice! Is there a place I can follow that work?

**Comment by Garkavenko** [comment] 2020-04-20 12:37
> Everything I can say so far there is work in progress to fix this! And it's really exciting!
> 
> I hope it will be released soon!

@terrysahaidak Could you say, how long will it take to be done(more or less than month :) )?

**Comment by slorber** [comment] 2020-05-22 10:47
For the ones interested:

![image](https://user-images.githubusercontent.com/749374/82660156-21550180-9c2a-11ea-8271-93cd4db1061e.png)


https://twitter.com/kzzzf/status/1263157145572442112



---

Also, I've had similar problems on complex animation graphs.
I wasn't really able to optimize much the mount phase, but if you memoize the graph aggressively (ie, avoid creating new node instances), I've found updates/re-renders are less expensive. Didn't measure the bridge calls but I guess it helps.

**Comment by jakub-gonet** [comment] 2020-07-22 19:42
Most issues are connected with initialization/deinitialization and we can't really avoid this because Reanimated 1 is based on animations composed on nodes, so we have to push every node through the bridge. 
Updates can be avoided in ways that @slorber mentioned (e.g. using `useValue` hook, using proc, some micro-optimizations like avoiding negative conditions in `cond` node and using `else` block, etc) and most of the time they're not problematic.
Some solutions were proposed in the past (most notably creating `jsNode` - you send js function as a string and animation is evaluated on JS VM in the native side) but the problem lies in the bridge traffic and this can't be removed completely.

I suggest following the development of Reanimated 2 (it's pretty stable at this moment) and maybe giving it a try - it's way easier to write animations in v2 than in v1.

I'm going to close this issue as there's no practical solution to it.
I'm open for discussion though.

**Closed by jakub-gonet** 2020-07-22 19:42 UTC
Labels: 🐞bug-bash-dec19, 🧰need-repro

**Comment by terrysahaidak** [comment] 2020-07-24 18:36
As someone who's been using Reanimated 2 from times way before the actual release I can confirm it fixes all the issues.
