### ISSUE TITLE
"Tried to synchronously call anonymous function from a different thread."

### ISSUE THREAD

**Issue by sebi75** [software-mansion/react-native-reanimated#3067] opened 2022-03-14 06:14 UTC
## Description
So the problem appeared only when I started making use if the "createDrawerNavigation", when react-native-reanimated was needed. 

I don't know much about the error, but all I know is that the console doesn't display any and it displays this error only on android with every move made. I tried clearing the emulator's cache, installed different versions of dependencies that should've worked together.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.64.3     |
| react-native-reanimated              |    ^2.4.1     |
| NodeJS                               |    16.14.0     |
| expo                                 |   ~44.0.0      |

## Affected platforms
![325548f8e79ade292fae391f276e8e65](https://user-images.githubusercontent.com/36008268/158115301-9c6593ef-41c1-48f3-904e-a27840827ced.png)

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by sebi75** [comment] 2022-03-14 06:32
Found someone else encountering the same error here, but in other context. Still, there was a guy that said: "downgrading to @react-navigation/drawer v6.3.0 works for the time being". It actually works, android doesn't crash anymore with every gesture, but what could be the probable cause for the problem?

* I downgraded from v6.3.1 to 6.3.0

**Comment by piaskowyk** [comment] 2022-03-21 12:01
This issue looks like a duplicate of https://github.com/software-mansion/react-native-reanimated/issues/3049 so I'm closing it to keep the discussion in one place.

**Closed by piaskowyk** 2022-03-21 12:01 UTC
Labels: 🧰needs-repro, 🤖android, needs-review, needs-more-info
