### ISSUE TITLE
Getting error in JSImodules

### ISSUE THREAD

**Issue by arifhendraween** [software-mansion/react-native-reanimated#2014] opened 2021-05-11 09:49 UTC
Get error "Attempt to invoke virtual method .etc" after installing newer version of reanimated. could you resolved it? Thank you

![image](https://user-images.githubusercontent.com/83565324/117795668-97f27100-b278-11eb-9b51-412f5c3ab809.png)

## Package versions

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android

**Comment by jakub-gonet** [comment] 2021-05-11 09:56
Could you please fill in the package versions section and describe from what version you were upgrading to what version? Try clearing cache (removing node_modules `rm -rf node_modules`, runnning metro with --reset-cache flag `yarn start --reset-cache` and clearing Gradle cache `cd android && ./gradlew clean`).

**Comment by arifhendraween** [comment] 2021-05-11 10:01
> Could you please fill in the package versions section and describe from what version you were upgrading to what version? Try clearing cache (removing node_modules `rm -rf node_modules`, runnning metro with --reset-cache flag `yarn start --reset-cache` and clearing Gradle cache `cd android && ./gradlew clean`).

I just installed latest version 2.1.0 on my new app. I got this error after installing firebase auth and RN signin google, so I don't know which package give me that error. (sorry for bad english)

**Comment by emeraldsanto** [comment] 2021-06-08 21:55
I am also experiencing this after integrating with Firebase (app and messaging). I have tried cleaning caches and using the following `react-native-reanimated` versions: `2.0.0`, `2.1.0` and `2.2.0`. I have also disabled Hermes to no avail. I'm currently on React Native `0.64` and everything works on iOS.

**Comment by piaskowyk** [comment] 2022-01-14 12:46
Does it problem still occur on Reanimated 2.3.1?

**Comment by jkadamczyk** [comment] 2022-01-28 10:15
Hi @emeraldsanto @arifhendraween 

As Krzysztof and Jakub mentioned already, in order to help you we need minimal reproduction.
Without it, we can't even try to fix the issue. I know repros are hard, since I struggle making them myself.
My advice until you manage to create repros, try clearing the cache, `rm -rf node_modules && npm install` and see if it works. If it is affecting Android only, try clearing Gradle cache as well by running `cd android && ./gradlew clean && cd ..` and stuff like that.
Since there wasn't any new activity recently, I will close the issue. Feel free to reopen if you manage to get a repro.
Have a nice day!

**Closed by jkadamczyk** 2022-01-28 10:15 UTC
Labels: 🧰needs-repro, 🐞 Bug, 🏠  Reanimated2, bug-bash-jan22
