### ISSUE TITLE
Animation lags with PanGestureHandler and inverted Flatlist (Expo / TypeScript)

### ISSUE THREAD

**Issue by MikelH911** [software-mansion/react-native-reanimated#3863] opened 2022-12-14 08:28 UTC
### Description

Hello guys,

First time opening an issue on Github, hope I will provide enough informations.
I was trying to implement a WhatsApp like cancelling recoding button.
Everything was working fine, all animations lauching correctly, start and stop recording too.

But after a few seconds pressing the gesture handler, the app freeze, all animations start to lags and FPS drop to 0.
After trying many things, I found out that it is linked with a Flatlist I have in my view. When this Flatlist is inverted, that is when everything crash.

Thinking it was may be my packages version, I started a new project and put inside my view only a Flatlist with text items and my PanGestureHandler. All packages are up to date, even though the behavior is the same. If I remove "inverted" from my Flatlist, everything work fine.

I also tried to use Animated.Flatlist but no change

In the video I attached, it happen at around 0:33 but it can happen at 0:05 too. It even crash the screen recorder.

I also tried to reproduce it on Snack Expo, on emulator it works fine, on my phone it crashes

I am doing my tests on Android emulator and on Samsung S21 Ultra. On iOS everything seems to work fine

Thank you for your help

https://user-images.githubusercontent.com/120553649/207541268-90157f66-4b04-442d-97d1-75a8eb47b5d4.mp4

### Steps to reproduce

My package.json :

`{
  "name": "animationtest",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@types/react": "^18.0.26",
    "@types/react-native": "^0.70.8",
    "expo": "~47.0.8",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-reanimated": "^2.13.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "typescript": "^4.9.4"
  },
  "private": true
}
`

### Snack or a link to a repository

https://snack.expo.dev/@mikelh997/animationtest

### Reanimated version

2.13.0

### React Native version

0.70.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

Samsung Galaxy S21 Ultra (Android 13)

### Acknowledgements

Yes

**Comment by MikelH911** [comment] 2022-12-21 19:11
I have tested on different devices, and it seems to happen only on Android 13.

It happens either with Reanimated or with React Animated, and with any kind of animations

**Comment by MikelH911** [comment] 2022-12-23 16:31
After research, it is linked to Android 13, more and more people are facing this issue.

Only solution I found on Github was [here](https://github.com/facebook/react-native/issues/34583#issuecomment-1244858120), it is the only way to make it worked while waiting for a fix

**Comment by rvenky125** [comment] 2023-04-06 06:39
Yes, you are correct. In android 13 the animation correctly stops after 1 minute. Is there any solution?

**Comment by rvenky125** [comment] 2023-04-06 06:50
It's not only with for flatlist. It's for all repeated animations.

**Comment by rvenky125** [comment] 2023-04-06 06:56
I'm using these style for a view which has a infinite repeated animation
`{
          padding: Spacing.SpaceSmall,
          elevation: 25,
          position: 'absolute',
          bottom: Spacing.SpaceLarge,
          shadowColor: colors.primary,
          borderColor: hexToRgbA(colors.primary, 0.5),
          borderWidth: 0.76,
          end: Spacing.SpaceSemiLarge,
          alignItems: 'center',
          justifyContent: 'center',
          borderRadius: 16,
          flexDirection: 'row',
          paddingHorizontal: 0,
          backgroundColor: colors.onPrimary,
          overflow: 'hidden',
}`

**Comment by minhna** [comment] 2023-05-10 15:15
I'm using `ActivityIndicator` in a inverted `FlatList` and the ui freeze after 10 seconds.
"react-native": "0.71.1",
Android 13 (Samsung A53)

**Comment by szydlovsky** [comment] 2024-06-26 08:58
Hey everyone, since the issue is strictly on the side of android and/or react-native, I am closing it.

**Closed by szydlovsky** 2024-06-26 08:58 UTC
Labels: Platform: Android, Needs review, Repro provided
