### ISSUE TITLE
useAnimatedStyle and withTiming:  Crash trying use the example from the documentation

### ISSUE THREAD

**Issue by vitto-moz** [software-mansion/react-native-reanimated#1557] opened 2020-12-22 10:21 UTC
## Description
  
Have the app crashed on trying to reproduce the simple example from the documentation:
https://docs.swmansion.com/react-native-reanimated/docs/next/api/withTiming

### Screenshots

<img width="389" alt="Android_Emulator_-_Pixel_5554" src="https://user-images.githubusercontent.com/19843391/102877475-7b7fa480-444f-11eb-8e30-a55704e996d0.png">

## Steps To Reproduce

Just try to use the component I've shared below 

### Expected behavior
There should be animation and no crash

### Actual behavior
the app crashed immediately 

## Snack or minimal code example

```
import React from 'react';
import { Button, View } from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withTiming
} from 'react-native-reanimated';
import styles from './styles';

export default function Test() {
  const width = useSharedValue(50);

  const style = useAnimatedStyle(() => {
    // return {
    //   width: width.value   // <== this works, but obviously without animation
    // };
    return {
      width: withTiming(width.value)
    };
  });

  return (
    <View>
      <Animated.View style={[styles.box, style]} />
      <Button onPress={() => (width.value = Math.random() * 300)} title='Hey' />
    </View>
  );
}

```

## Package versions

"react": "16.13.1",
"react-native": "0.63.4",
"react-native-reanimated": "2.0.0-rc.1",
NodeJS: v14.15.0

**Comment by karol-bisztyga** [comment] 2020-12-22 11:58
Hey
I could not reproduce this. Could you please give me more information about the environment? What was the app(did you set it up or it was our example app/playground)? If you set it up, how did you do that(what commands did you use etc.)?

Thanks!

**Comment by vitto-moz** [comment] 2020-12-22 12:07
Hi @karol-bisztyga,
I don't use the `example app/playground`, I have the app created on my own  with `react-native-cli`:
`npx react-native init AwesomeProject`
I use `yarn` for packages installing 
followed the instructions from here: 
https://docs.swmansion.com/react-native-reanimated/docs/next/installation

**Comment by karol-bisztyga** [comment] 2020-12-22 13:49
We've encountered problems with both `npx` and `npm`(in terms of using npm to install packages). Could you please try to run the commands below in your project's root directory and let me know if that worked(it did a trick for me):

`rm -rf node_modules && yarn && cd ios && pod install && cd .. && yarn start --reset-cache`

We postponed working on those cases due to low priority, but I'll try to take a look at it in a spare time.

**Comment by vitto-moz** [comment] 2020-12-22 14:10
Yeah, it works! woohoo :) 
thank you, @karol-bisztyga !

**Comment by karol-bisztyga** [comment] 2020-12-22 14:51
I'm glad, great! Thanks for letting me know, closing this now.

**Closed by karol-bisztyga** 2020-12-22 14:51 UTC
Labels: Reanimated2, 🐞 Bug

**Comment by karol-bisztyga** [comment] 2020-12-22 15:51
seems to me like `yarn start --reset-cache` is enough

**Comment by ha-family** [comment] 2021-04-09 08:58
same issue on ReactNative 0.64
it crash on android if i using withTiming

after running `rm -rf node_modules && yarn && cd ios && pod install && cd .. && yarn start --reset-cache`
still crash

**Comment by kaneki666** [comment] 2021-04-21 18:03
> same issue on ReactNative 0.64
> it crash on android if i using withTiming
> 
> after running `rm -rf node_modules && yarn && cd ios && pod install && cd .. && yarn start --reset-cache`
> still crash

I am facing the same issue..i used yarn too... without using withing it works...withtimng spring it crashesh
