### ISSUE TITLE
React navigation modal screen malfunctions after installing reanimated 2 (version 2.3.0-beta.3) (Android) 

### ISSUE THREAD

**Issue by onifs10** [software-mansion/react-native-reanimated#2642] opened 2021-11-18 07:58 UTC
### Discussed in https://github.com/software-mansion/react-native-reanimated/discussions/2641

<div type='discussions-op-text'>

<sup>Originally posted by **onifs10** November 18, 2021</sup>
So after installing reanimated-2, the modal screen malfunctions.

after navigating to a modal screen , on navigating back to the main screen the modal screen doesn't get fully unmounted (unstacked) 

minimal code, for the stack navigation  
```
      <NavigationContainer>
        <RootStack.Navigator
          screenOptions={{
            headerShown: false,
          }}>
          <RootStack.Group>
            <RootStack.Screen name="App" component={BottomNavigator} />
          </RootStack.Group>
          <RootStack.Group screenOptions={{presentation: 'modal'}}>
            <RootStack.Screen name="Test" component={TaskModalScreen} />
          </RootStack.Group>
        </RootStack.Navigator>
      </NavigationContainer>
```

###  screen record

https://user-images.githubusercontent.com/48095055/142374510-3d5eb2f6-7088-4bc5-920c-7b1b91fffa61.mp4

 
</div>

**Comment by lamyuho** [comment] 2021-11-18 18:49
I have same issue as well

**Comment by bobsmits** [comment] 2021-11-22 15:27
Sounds like a duplicate of: https://github.com/software-mansion/react-native-reanimated/issues/2538

**Comment by onifs10** [comment] 2021-11-22 16:17
yeah @bobsmits  but the fix provided for that is for ios , i am having this issue on andriod

**Comment by piaskowyk** [comment] 2021-11-23 19:47
Probably fixed, I will check it again

**Comment by piaskowyk** [comment] 2021-11-30 12:46
@onifs10 Could you check it again on https://github.com/software-mansion/react-native-reanimated/releases/tag/2.3.0-beta.4 please?

**Comment by onifs10** [comment] 2021-11-30 13:38
@piaskowyk tested  it now works perfectly

**Comment by piaskowyk** [comment] 2021-12-03 08:46
@onifs10 Thanks!

**Closed by piaskowyk** 2021-12-03 08:46 UTC
Labels: 🐞 Bug, 🏠  Reanimated2, navigation/screens, wait-for-reply, layout-animations
