### ISSUE TITLE
crash android in prod

### ISSUE THREAD

**Issue by philipheinser** [software-mansion/react-native-reanimated#4315] opened 2023-03-30 16:27 UTC
### Description

```
Fatal Exception: com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.NoSuchMethodError: no non-static method "Lcom/swmansion/reanimated/NativeProxy;.registerEventHandler(Lcom/swmansion/reanimated/nativeProxy/EventHandler;)V", js engine: hermes, stack:
callNativeSyncHook@1:149763
nonPromiseMethodWrapper@1:147245
NativeReanimated@1:1162319
anonymous@1:1158150
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:1180367
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:1172671
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:1153243
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:1152108
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:1642835
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:1631224
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:1629563
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:978256
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:977681
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:721436
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:671308
loadModuleImplementation@1:128621
guardedLoadModule@1:128170
metroRequire@1:127798
anonymous@1:134964
loadModuleImplementation@1:128621
guardedLoadModule@1:128127
metroRequire@1:127798
global@1:127365

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:764)
```

### Steps to reproduce

1. add reanimated 
2. launch android in prod to a lot of people

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated

### Reanimated version

3.0.2

### React Native version

0.71

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2023-03-30 19:53
Duplicate of #4135, duplicate of #4202, fixed by #4205.

**Closed by tomekzaw** 2023-03-30 19:53 UTC
Labels: Missing repro, Platform: Android, Needs review
