### ISSUE TITLE
App crashes when turning on debugging (turbomoduleregistry.getenforcing(...) 'native reanimated' could not be found)

### ISSUE THREAD

**Issue by walterholohan** [software-mansion/react-native-reanimated#1740] opened 2021-02-20 08:33 UTC
## Description

After installing `react-reanimated 2.0.0-rc.3` the app crashes when I turn on debugging via the dev menu. The below error message is displayed:

```
turbomoduleregistry.getenforcing(...) 'native reanimated' could not be found
```

### Screenshots

![image](https://user-images.githubusercontent.com/5293650/108589441-30eaad80-7356-11eb-98f4-9354380ab2c2.png)

## Steps To Reproduce

1. Install react-reanimated2.0.0-rc.3
2. Open dev menu
3. Turn on debugging

### Expected behavior
You should be able to use the chrome debugger

### Actual behavior

The app crashes

## Package versions

- React: `16.13.1`
- React Native: `0.63.4`
- React Native Reanimated: `2.0.0-rc.3`
- NodeJS: `15.1.0`

**Comment by jakub-gonet** [comment] 2021-02-20 12:32
Duplicate of #1663.

See [this comment](https://github.com/software-mansion/react-native-reanimated/issues/1663#issuecomment-770769922) for more information.

**Closed by jakub-gonet** 2021-02-20 12:32 UTC
Labels: 🐞 Bug
