### ISSUE TITLE
Entering and Exiting animations doesn't work with react new architecture

### ISSUE THREAD

**Issue by flodlc** [software-mansion/react-native-reanimated#5656] opened 2024-02-08 12:52 UTC
### Description

Hi, entering and exiting animations does not work at all with the new architecture, there is no error and the element appears but without any animation.
Works fine with the old architecture.
I have tried with canary versions too but it doesn't solve the issue.

### Steps to reproduce

With the given versions, this code won't work on the new architecture but works well on the old architecture.

```typescript
import { useState } from "react";
import { Button, View } from "react-native";
import Animated, { SlideInLeft, SlideOutDown } from "react-native-reanimated";

function App(): JSX.Element {
  const [animate, setAnimate] = useState(true);

  return (
    <View style={{ paddingTop: 100 }}>
      {animate && (
        <Animated.View
          entering={SlideInLeft.duration(2000)}
          exiting={SlideOutDown.duration(2000)}
        >
          <View style={{ backgroundColor: "orange", height: 30, width: 30 }} />
        </Animated.View>
      )}
      <Button title="animate" onPress={() => setAnimate(!animate)} />
    </View>
  );
}

export default App;

```

### Snack or a link to a repository

-

### Reanimated version

3.6.2

### React Native version

0.73.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Latropos** [comment] 2024-02-08 14:09
Hi! The issue looks exactly like if you had `reducedMotion` on. https://docs.swmansion.com/react-native-reanimated/docs/device/useReducedMotion Is it possible that for some reason `reducedMotion` turns on on new architecture?

You can set `reducedMotion` both in your simulator and on your computer. I don't know how this feature behaves if you have different settings.

**Comment by flodlc** [comment] 2024-02-08 14:58
Thanks for your answer @Latropos, unfortunately reducedMotion is `off`. I tried everything, does it work on your side with the new architecture ?

**Comment by tomekzaw** [comment] 2024-02-08 20:25
Hey @flodlc, thanks for reporting this issue. Layout Animations are not implemented on Fabric yet, but we plan to start working on it very soon. Thanks for your understanding.

Duplicate of #3439.

**Comment by tomekzaw** [comment] 2024-02-08 20:26
Closing this issue because it's a duplicate of https://github.com/software-mansion/react-native-reanimated/issues/3439.

**Closed** 2024-02-08 20:25 UTC
Labels: Platform: iOS, Repro provided

**Comment by flodlc** [comment] 2024-02-08 23:14
Ok, I didn't find this information. Can't wait for it  !

**Comment by faljabi** [comment] 2024-10-02 15:57
It is still not working with me. Simple FadeIn animation is not animating in new arch? It is working fine with new arch disabled. Any tips?

**Comment by tomekzaw** [comment] 2024-10-03 05:06
@faljabi What version of Reanimated are you on? Layout Animations are available on the New Architecture since 3.13.0 (see https://github.com/software-mansion/react-native-reanimated/pull/6055).

**Comment by faljabi** [comment] 2024-10-03 05:11
> @faljabi What version of Reanimated are you on? Layout Animations are available on the New Architecture since 3.13.0 (see #6055).

"react-native-reanimated": "^3.15.4"

However I am on react-native/releases/tag/v0.76.0-rc.3. This could be the issue?

**Comment by tomekzaw** [comment] 2024-10-03 06:21
Hmm, that should work just fine. cc @bartlomiejbloniarz Maybe you have any ideas?

**Comment by bartlomiejbloniarz** [comment] 2024-10-03 07:11
@faljabi Have you checked all types of animations? Are all entering, layout and exiting animations not working? Can you share a code snippet?

**Comment by faljabi** [comment] 2024-10-03 09:24
Hello guys @bartlomiejbloniarz, @tomekzaw,

Thank you for your prompt response.

Yes, I tried all types of animations. They do not work only when new arch is enabled. I tried the following:

- start npm with --reset-cache
- Reinstalled pods
- Deleted drived data folder
- Ensured babel plugin in place as per the docs

And nothing worked. I have not tried collapsable={false} yet because I reverted back to paper for now. But I will give it a try.

This is my component FadeIn Component

```
import Animated, { FadeIn as FadeInAnimation, FadeOut as FadeOutAnimation } from 'react-native-reanimated';

const FadeIn = ({ style, enteringDelay = 300, exitingDelay = 300, children }) => {

    return (
        <Animated.View
            style={style}
            entering={enteringDelay && FadeInAnimation.delay(enteringDelay)}
            exiting={exitingDelay && FadeOutAnimation.delay(exitingDelay)}>
            {children}
        </Animated.View>
    );
};

export default FadeIn
```

**Comment by bartlomiejbloniarz** [comment] 2024-10-04 16:23
@faljabi 

There seems to be a problem with RN 0.76. Layout Animations should work fine on 0.75

**Comment by faljabi** [comment] 2024-10-04 19:54
@bartlomiejbloniarz oh I see. Thank you for the update. I think I will wait till it gets out of rc.

**Comment by glicataeMotori** [comment] 2024-11-13 11:26
In react native with expo sdk 52 still don't working.
all exiting animation
and some of the entering

**Comment by markwitt1** [comment] 2025-01-02 11:59
Any update on this?

**Comment by GandhaSaputra** [comment] 2025-01-06 16:44
with expo 52, try to add reduceMotion if the entering and exiting animations not working

`import Animated, { ZoomIn, ReduceMotion } from 'react-native-reanimated';

  const zoomInAnimationFirst = ZoomIn.delay(0).reduceMotion(ReduceMotion.Never);
  
   <Animated.View entering={zoomInAnimationFirst}>
        <IconButton
          onPress={onPressFirstContent}
          variant="flat"
          className="h-7 w-7">
          <Image source={firstIcon} className="h-7 w-7" />
        </IconButton>
   </Animated.View>
  `

**Comment by aleganza** [comment] 2025-01-21 20:58
> with expo 52, try to add reduceMotion if the entering and exiting animations not working
> 
> `import Animated, { ZoomIn, ReduceMotion } from 'react-native-reanimated';`
> 
> `const zoomInAnimationFirst = ZoomIn.delay(0).reduceMotion(ReduceMotion.Never);`
> 
> `<Animated.View entering={zoomInAnimationFirst}>{children}</Animated.View>`

In my case I'm using Fade/FadeIn/FadeOut for both exiting and entering, and while using Expo Go the entering animations stop working after the first automatic hot refresh.
I tried this reduceMotion thing but it doesn't fix my problem.

**Comment by nicolas-mindsea** [comment] 2025-01-24 03:13
Same here.

Expo 52.0.27
RN - 76.6
Reanimated - 3.16.1

Tried ReduceMotion think but not working.

**Comment by Bruce-Ming** [comment] 2025-02-06 08:08
"react": "18.2.0",
 "react-native": "0.72.4",
"react-native-reanimated": "^3.14.0",
"react-native-gesture-handler": "^2.17.1",

same problem on android， but ios is working
