### ISSUE TITLE
Cannot add new property '__reanimatedHostObjectRef'

### ISSUE THREAD

**Issue by rpavlovs** [software-mansion/react-native-reanimated#1517] opened 2020-12-08 18:49 UTC
## Description

I can't use an array of objects coming in through a prop inside worklets. A prop with a simple value like a number works fine. Also making a deep copy with `JSON.parse(JSON.stringify(props.items))` solves the problem.

Looks like Reanimated tries to add a property on an immutable prop object and fails.

### Steps to reproduce
```ts
type Props = { 
  items: Item[]
}
const MyComponent = ({ items }: Props) => {

  const foo = () => {
    'worklet'
    const item = items[0] // <-- this line causes the error
  }

  return ...
}
```

### Expected behavior
I should be able to use any type of props in worklets

### Actual behavior
```
Cannot add new property '__reanimatedHostObjectRef'
```

## Package versions

- React Native: 0.64.rc-0
- React Native Reanimated: installed from https://github.com/software-mansion/react-native-reanimated/pull/1469

**Comment by karol-bisztyga** [comment] 2020-12-09 12:05
> React Native Reanimated: installed from #1469
I don't think we should handle problems that come from unmerged changes. If you have issues with the code from that PR, please mention them there. Once it's merged and the problem persists, please reopne this issue or open the new one. Thank you 🙏

**Closed by karol-bisztyga** 2020-12-09 12:05 UTC
Labels: Reanimated2, 🐞 Bug

**Comment by mrousavy** [comment] 2020-12-15 14:41
@rpavlovs are you still experiencing this issue? Can you confirm that it actually does work with JSC, but doesn't work with Hermes?

**Comment by rpavlovs** [comment] 2020-12-29 22:30
Hey @mrousavy, it's NOT certain that this is coming from your PR.

I haven't tried Reanimated 2 with JSC at all since logs are not usable with out setup.
I've also haven't tried it on `0.64.rc-2` which I believe has an updated version of Hermes - so might potentially affect this as well.

You can check if this is still an issue by having a deeply nested object coming from props, that later gets mutated inside a worklet.

**Comment by rassemdev** [comment] 2021-12-12 07:53
I also having this issue, when i am trying to console.log(listRef) ref of a listview.

**Comment by baronha** [comment] 2021-12-31 07:26
I also got the same error when using [react-native-reanimated-carousel](https://github.com/dohooo/react-native-reanimated-carousel/issues/66).

**Comment by braandl** [comment] 2022-02-15 11:49
I have made the following experience, but I can not say for sure yet if it is directly related to RA2:

When you send an Object that is used within RA2 to a native Module, it will crash, emitting this exact error.
Once you deepcopy the Object before sending it to the native module, it will not and work as expected.

Tested this with RA2.4.0

**Comment by dohooo** [comment] 2022-02-15 11:57
> I have made the following experience, but I can not say for sure yet if it is directly related to RA2:
> 
> 
> 
> When you send an Object that is used within RA2 to a native Module, it will crash, emitting this exact error.
> 
> Once you deepcopy the Object before sending it to the native module, it will not and work as expected.
> 
> 
> 
> Tested this with RA2.4.0

Cool， Maybe you can provide a minimal reproducible repository.

**Comment by jzxchiang1** [comment] 2022-02-16 06:07
I just got this error with react-native-bottom-sheet on react-native-v8:

```
Error: TypeError: Cannot assign to property '__reanimatedHostObjectRef' on HostObject with default setter
```
```
This error is located at:
    in BottomSheet (created by BottomSheet)
    in PortalHost (at PortalProvider.tsx:13)
    in PortalProvider (at BottomSheetModalProvider.tsx:190)
    in BottomSheetModalProviderWrapper (at App.tsx:99)
    in AuthProvider (at App.tsx:98)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at App.tsx:97)
    in GestureHandlerRootView (at GestureHandlerRootView.android.tsx:26)
    in GestureHandlerRootView (at App.tsx:96)
    in App (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40), js engine: v8
```

I'm on reanimated v2.2.2.

**Comment by braandl** [comment] 2022-02-16 09:53
> 

I currently do not have to much time, I'll try to provide one asap.

**Comment by yairopro** [comment] 2022-02-16 15:54
@karol-bisztyga @dohooo @braandl @rpavlovs 

Here's a repo reproducing the bug: https://github.com/yairopro/reanimated-2-playground
It's a fork from the playground.

https://github.com/yairopro/reanimated-2-playground/blob/ed71b4ebb75e32e9e6ef8b0f5b468af93c7ec20d/Screen.js#L19

**The bug seems to come from trying to access freezed object from a worklet.**
And components' props (unless copied) are freezed object by React.

⚠️ The bug doesn't appears in debug mode.

**Comment by braandl** [comment] 2022-02-16 16:06
@yairopro Thank you very much! you might me right with the freeze-assumption, or it is some other assertion made on the objects state. Either way, this ticket should be re-opened.

**Comment by dohooo** [comment] 2022-02-17 01:23
@yairopro Cool! Thanks!

**Comment by thisisgit** [comment] 2022-03-25 08:37
I had the same issue when trying to assign an **object** or **array of objects** from Redux state to a shared value.

e.g. using Redux Toolkit(RTK):
```typescript
// useSelector hook from RTK
const arrayOfObjects: Test[] = useSelector(selectorReturningTests);
const assignThemToMe = useSharedValue<Test[]>([]);

// Throws above error
assignThemToMe.value = arrayOfObjects;
```

I tried using mock data and it worked just fine. It only throws error when trying to assign value returned from RTK's selector.
While trying to figure out where the problem is coming from, I found this:
<img width="294" alt="a" src="https://user-images.githubusercontent.com/13231564/160079462-0150994f-7d71-4ccc-a4ea-636c9f16cf88.png">

When an object is assigned to a shared value, that object gets mutated by `reanimated` and a property called `__reanimatedHostObjRef` gets added.
Same for array of objects, every object in the array gets that property after it is assigned to shared value.
And looks like it's being added by this function: 
https://github.com/software-mansion/react-native-reanimated/blob/45c57a906b1c3881c37f08b09749a9c68faf7ce1/Common/cpp/SharedItems/ShareableValue.cpp#L21-L34
I'm assuming that it's throwing the error because it failed to mutate the object, i.e. failed to add `__reanimatedHostObjRef` property.

But why this issue only occurs when trying to assign data returned from RTK? 
I think it's because [RTK uses `immer` internally](https://redux-toolkit.js.org/usage/immer-reducers), which is used to freeze the data. And this is related to https://github.com/software-mansion/react-native-reanimated/issues/1517#issuecomment-1041810730, where it throws the same error when trying to play around with frozen object.

Probably that's why the solution of deep copying the object/array of objects using `JSON.parse(JSON.stringify(items))` works.
I think it would be better to show more readable error message if this issue doesn't get resolved anytime soon.

**Comment by dohooo** [comment] 2022-03-25 08:41
> I had the same issue when trying to assign an **object** or **array of objects** from Redux state to a shared value.
> 
> e.g. using Redux Toolkit(RTK):
> 
> ```ts
> // useSelector hook from RTK
> const arrayOfObjects: Test[] = useSelector(selectorReturningTests);
> const assignThemToMe = useSharedValue<Test[]>([]);
> 
> // Throws above error
> assignThemToMe.value = arrayOfObjects;
> ```
> 
> I tried using mock data and it worked just fine. It only throws error when trying to assign value returned from RTK's selector. While trying to figure out where the problem is coming from, I found this: <img alt="a" width="294" src="https://user-images.githubusercontent.com/13231564/160079462-0150994f-7d71-4ccc-a4ea-636c9f16cf88.png">
> 
> When an object is assigned to a shared value, that object gets mutated by `reanimated` and a property called `__reanimatedHostObjRef` gets added. Same for array of objects, every object in the array gets that property after it is assigned to shared value. And looks like it's being added by this function:
> 
> https://github.com/software-mansion/react-native-reanimated/blob/45c57a906b1c3881c37f08b09749a9c68faf7ce1/Common/cpp/SharedItems/ShareableValue.cpp#L21-L34
> 
> 
> I'm assuming that it's throwing the error because it failed to mutate the object, i.e. failed to add `__reanimatedHostObjRef` property.
> But why this issue only occurs when trying to assign data returned from RTK? I think it's because [RTK uses `immer` internally](https://redux-toolkit.js.org/usage/immer-reducers), which is used to freeze the data. And this is related to [#1517 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/1517#issuecomment-1041810730), where it throws the same error when trying to play around with frozen object.
> 
> Probably that's why the solution of deep copying the object/array of objects using `JSON.parse(JSON.stringify(items))` works. I think it would be better to show more readable error message if this issue doesn't get resolved anytime soon.

Dude, you're so cool

**Comment by aphillipo** [comment] 2022-05-26 08:49
Hello, I was having this issue when using a value generated outside of the component in a useAnimatedStyle declaration e.g.:

`es6
const data = [{ id: '1', title: 'Test', backgroundColor: 'transparent' }, { id: '2', title: 'Test another', backgroundColor: '#FF6600' }, ....etc. etc.];

const Component = () => {
    const animatedBackgroundColor = useAnimatedStyle(() => {
    const inputValues = data.map((_, index) => index); // [0,1,etc. etc.]
    const outputValues = data.map((item) => item.backgroundColor); // [0,1,etc. etc.]

    const backgroundColor = interpolateColor(
      animatedBackgroundIndex.value,
      inputValues,
      outputValues,
    );
    return {
      backgroundColor,
    };
  }, [animatedBackgroundIndex]);
};
`

**Comment by alexco2** [comment] 2022-06-09 14:59
For me this error happened when I referenced a `StyleSheet` object in the return object of `useAnimatedStyle`.

```
  const SnapAnimation = useAnimatedStyle(() => {
    return {
      ...styles.HeaderStyle, <- Error happened here
      transform: [
        {
          translateY: translateY.value,
        },
      ],
    };
  });
```

**Comment by ramiel1999** [comment] 2022-06-17 14:41
> For me this error happened when I referenced a `StyleSheet` object in the return object of `useAnimatedStyle`.
> 
> ```
>   const SnapAnimation = useAnimatedStyle(() => {
>     return {
>       ...styles.HeaderStyle, <- Error happened here
>       transform: [
>         {
>           translateY: translateY.value,
>         },
>       ],
>     };
>   });
> ```

I am having the same issue, using styles from stylesheet inside usAnimatedStyle recreates the issue
