### ISSUE TITLE
Failed to transform react-native-reanimated-63.aar (project :react-native-reanimated) to match attributes {artifactType=android-assets}

### ISSUE THREAD

**Issue by RapestaNatalia** [software-mansion/react-native-reanimated#1928] opened 2021-04-12 03:04 UTC
## Description
```
What went wrong:
Execution failed for task ':app:mergeDevDebugAssets'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
  > Failed to transform react-native-reanimated-63.aar (project :react-native-reanimated) to match attributes {artifactType=android-assets}.
   > Execution failed for JetifyTransform: /Users/nataliarapesta/Documents/App4/mobile-app-react-native/node_modules/react-native-reanimated/android/react-native-reanimated-63.aar.
     > Check failed
```

I have tested a lot of ways to resolve it. For example,I [installed the library manually](https://docs.swmansion.com/react-native-reanimated/docs/next/installation/#using-master-branch-builds), I cleaned cache a lot of times, I changed to a new version of react-native-reanimated 2.0.1 or 2.1.0 , unistalled and installed Java, Android Studio and SDKs but it is always the same error . It only happens with Android, iOS is ok and I see the library into node-modules.

It was installed with react-navigation, but in the project, it is not uses directly.

### Expected behavior

Apps build and run successfully.

### Actual behavior & steps to reproduce

App build failed.

`npm run android:dev` 

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Reanimated: ^2.0.0
- NodeJS: v14.16.1
- Java & Gradle: Java 1.8.0.282, Gradle 6.2.

## Affected platforms

- Android version 4.1.3 installed.

**Comment by jakub-gonet** [comment] 2021-04-12 06:11
Have you tried some answers [from this SO question](https://stackoverflow.com/a/56267845)?

Are you able to share the repro repository so we can test it locally?

**Comment by RapestaNatalia** [comment] 2021-04-12 10:49
I could not share the repo because it is a company solution. Maybe if you mention some specific part of the code that are important, I could share it. Apart from that, it only happens in my local environment, so it is not easy to reproduce.

As regard your link, I have tested these options:

1.	Delete ONLY the corrupted .aar from the Gradle caches folder:
`rm ~/.gradle/caches/modules-2/files-2.1/path-to/some-release.aar
`
path to= com.swmansion.reanimated or something that has the word reanimated
does not appear. We tried deleting the complete .gradle folder with the same result.

2.	specifying a set of matchingFallbacks for the build types did the trick:
```
buildTypes {
        debug {
            signingConfig signingConfigs.debug
            matchingFallbacks = ['debug']
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
```

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

```

1.	update library declaration to following implementation project(path: ':yourLibraryname', configuration: 'default')
2.	Android Studio > File > Invalidate Caches/Restart.
3.	Go to Users > (Current User) > .gradle > delete caches folder and open Android Studio again.
4.	"assemble" that specific library separately. (Use Gradle option available on RHS of Android Studio.


 `   implementation project(path: ':react-native-reanimated', configuration: 'default')`



These 3 options do not work.
Could you explain me if there is a side effect into the app if I delete it from package.json or do something like that? For now, I don’t see one. We installed it together with react-nativation.
```

module.exports = {
  assets: ['./src/assets/fonts/'],
  dependencies: {
    'react-native-reanimated': {
      platforms: {
        android: null,
      },
    },
  },
}
```

Thanks for your answer!

**Comment by RapestaNatalia** [comment] 2021-04-13 19:43
Hi @jakub-gonet. Could you see my question?Another idea to avoid this problem?

**Comment by piaskowyk** [comment] 2021-04-14 14:51
Hey, @RapestaNatalia
Is it possible for you to create an example repo to reproduce this issue?

**Comment by mamta-deswal** [comment] 2021-05-07 12:09
any update on this?

**Comment by ZiggStardust** [comment] 2021-05-10 13:18
running into the same issue :(

**Comment by ZiggStardust** [comment] 2021-05-10 13:37
@mamta-deswal hey - 0.61.5

**Comment by mamta-deswal** [comment] 2021-05-10 13:42
with react native version 0.61 please use these version of react-navigation dependency:-
  "react-native-gesture-handler": "1.4.0",
    "react-native-reanimated": "1.13.1"
    "react-native-screens": "2.14.0"
    Delete node module and update your package.json and npm install. you will good to go.

**Comment by ZiggStardust** [comment] 2021-05-10 13:56
@mamta-deswal  still getting an issue with those versions: 

`"dependencies": {
    "@material-ui/core": "^4.9.3",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "luxon": "^1.22.0",
    "react": "16.9.0",
    "react-dom": "^16.13.0",
    "react-native": "0.61.5",
    "react-native-firebase": "^5.6.0",
    "react-native-gesture-handler": "1.4.0",
    "react-native-material-ui": "^1.30.1",
    "react-native-nfc-manager": "^2.1.1",
    "react-native-push-notification": "^3.1.9",
    "react-native-reanimated": "1.13.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "2.14.0",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5"
  },`
  
  
  import com.facebook.react.bridge.ReadableMap;
                                ^
100 errors

> Task :react-native-reanimated:androidJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:androidJavadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/tom/workspace/visa/sales-app/node_modules/react-native-reanimated/android/build/tmp/androidJavadoc/javadoc.options'

**Comment by ZiggStardust** [comment] 2021-05-10 14:31
@mamta-deswal still having issues any help would be much appreciated 

"dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "axios": "^0.19.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-firebase": "^5.6.0",
    "react-native-gesture-handler": "1.4.0",
    "react-native-nfc-manager": "^2.1.1",
    "react-native-push-notification": "^3.1.9",
    "react-native-reanimated": "1.13.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "2.14.0",
    "react-native-tab-view": "^2.13.0"
  },

`> Task :react-native-reanimated:androidJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:androidJavadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/tom/workspace/visa/sales-app/node_modules/react-native-reanimated/android/build/tmp/androidJavadoc/javadoc.options'`

**Comment by mamta-deswal** [comment] 2021-05-10 17:08
allprojects {
tasks.withType(Javadoc).all { enabled = false }

**Comment by ZiggStardust** [comment] 2021-05-10 17:10
@mamta-deswal that works :) thanks

**Comment by PrinceUBS** [comment] 2021-06-25 06:04
> I am having the same issue after upgrade react-native to ^0.65.0-rc.2

same issue (in react-native 0.65.0-rc.2), ay fix?

**Comment by piaskowyk** [comment] 2021-06-25 11:21
Unfortunately, Reanimated currently doesn't support `react-native 0.65.*`. I'm working on this now. It should be available soon.

**Comment by sdumjahn** [comment] 2021-07-07 14:05
I run into the same problem as @RapestaNatalia. I can't build the android app.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:javaPreCompileDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform react-native-reanimated-63.aar (project :react-native-reanimated) to match attributes {artifactType=android-classes, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: path-to-project/node_modules/react-native-reanimated/android/react-native-reanimated-63.aar.
         > Check failed.

```

**Comment by alz10** [comment] 2021-08-17 13:13
Not working as well in RN `0.65.0-rc.4`. I need to target API level 30 (Android 11) for my apps.

<img width="1059" alt="Screen Shot 2021-08-17 at 9 09 37 PM" src="https://user-images.githubusercontent.com/38030623/129731468-ae8253a2-3304-44f1-bc5b-cae817774abf.png">

```
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-65-jsc.aar 
(project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
```

**Comment by RichardLindhout** [comment] 2021-08-17 14:31
I have the same problem as @alz10 
```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-reanimated-65-hermes.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
      > Execution failed for JetifyTransform: /...____.../node_modules/react-native-reanimated/android/react-native-reanimated-65-hermes.aar.
         > Transform's input file does not exist: /...____.../node_modules/react-native-reanimated/android/react-native-reanimated-65-hermes.aar. (See https://issuetracker.google.com/issues/158753935)

```

**Comment by RichardLindhout** [comment] 2021-08-17 14:34
What I did for now was going the node_modules/react-native-reanimated/android directory and run the following
```sh
cp react-native-reanimated-64-hermes.aar react-native-reanimated-65-hermes.aar
```

**Comment by Konntroll** [comment] 2021-08-19 16:28
> Unfortunately, Reanimated currently doesn't support `react-native 0.65.*`. I'm working on this now. It should be available soon.

Hey! Any update on this, @piaskowyk?

RN 0.65 stable got released the other day and my organisation is looking into upgrading our apps to this newer version. After some trial/error I got the apps to build and run on iOS, however, @RichardLindhout's solution only gets me to where the Android app is building and uploading to the sim but then quietly stops with Logcat spewing out `A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 25423 (create_react_co)`.

I'm assuming _this_ is still the cause of the problem, so it would be great to know if we should expect 0.65 support from RN Reanimated in the coming days/weeks or just shelve the upgrade for the time being. Any news would be appreciated!

**Comment by alz10** [comment] 2021-08-23 14:59
For those who are looking for a temporary fix just install this version
`npm i react-native-reanimated@2.3.0-alpha.2 --save --force `


> Not working as well in RN `0.65.0-rc.4`. I need to target API level 30 (Android 11) for my apps.

also `v0.65.1` latest release is now available just incase you're still using a release candidate

**Comment by mohamadnavabi** [comment] 2021-09-05 08:49
try this:

npm i react-native-reanimated@^1.13.2

**Comment by jkadamczyk** [comment] 2022-01-28 10:02
Hey!
I am very sorry you are experiencing issues with Reanimated 2.
I have 2 questions to all of you.
Do you still experience the issue mentioned here?
Do any of you have a repro that we can take a look at to try fix the issue?

@alz10 @RichardLindhout @sdumjahn @PrinceUBS @aleppos @ZiggStardust @mamta-deswal @RapestaNatalia

**Comment by RichardLindhout** [comment] 2022-01-31 09:33
No I'm not experiencing this anymore!

**Comment by chukwuma-azubuike** [comment] 2022-11-11 00:17
Issue still persists

**Comment by Saileek-bidchat** [comment] 2022-12-26 14:40
Getting same issue on RN 0.68.0 for "react-native-reanimated": "^2.3.0-alpha.2"

**Comment by AzeemSarwar1** [comment] 2023-08-03 08:03
yarn add  react-native-reanimated@2.13.0 
work for me

**Comment by Latropos** [comment] 2023-10-23 08:26
I'm closing this issue since it was only present for old versions of Reanimated 2. Upgrading reanimated should fix the issue, please use Reanimated 3.

**Closed by Latropos** 2023-10-23 08:26 UTC
Labels: Bug, 🏠  Reanimated 2, bug-bash-jan22
