### ISSUE TITLE
setObject:forKeyedSubscript:]: key cannot be nil

### ISSUE THREAD

**Issue by Deathset** [software-mansion/react-native-reanimated#2521] opened 2021-10-11 09:30 UTC
## Description
When i try to goBack() from page B to A using react navigation and drawer, reanimated crash the  app with the error 
Exception thrown while executing UI block: *** [_NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil

## Package versions
    "react-native-reanimated": "2.3.0-beta.2",
    "react-native": "0.66.0",
    "@react-navigation/drawer": "5.9.3",

- React Native:
- React Native Reanimated:
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ x] Android
- [x ] iOS
- [ ] Web

**Comment by piaskowyk** [comment] 2022-01-14 12:27
Unfortunately, I am closing this issue because I can't reproduce it. If someone prepares a repo with reproduction of this issue post it here and we will reopen the issue.

**Closed by piaskowyk** 2022-01-14 12:27 UTC
Labels: 🧰needs-repro, 🐞 Bug, 🏠  Reanimated2, crash

**Comment by justinairbase** [comment] 2022-03-17 14:28
![IMG_DF4E20D7DE9D-1](https://user-images.githubusercontent.com/51368399/158828179-62375897-aed9-478a-8b40-e9cf2304663e.jpeg)


Recently started seeing this error.

```
"react": "17.0.2",
"react-native": "0.66.2",
"react-native-gesture-handler": "2.2.0",
"react-native-reanimated": "2.4.1",
```

**Comment by ManuViola77** [comment] 2022-06-17 21:22
I have this issue too, I have two tabs and when I go back to the not animated one it crashes with this same error.

**Comment by Darapsas** [comment] 2022-08-12 17:54
A more in-depth discussion can be found [here](https://github.com/react-native-maps/react-native-maps/issues/3983).
