### ISSUE TITLE
 Error: Requiring module "node_modules/react-native-reanimated/src/animations/decay.js", which threw an exception: TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')

### ISSUE THREAD

**Issue by naxir** [software-mansion/react-native-reanimated#2189] opened 2021-07-09 11:48 UTC
Error: Requiring module "node_modules/react-native-reanimated/src/animations/decay.js", which threw an exception: TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')

After installing react-native-reanimated 
when i import  import {Transition, Transitioning} from 'react-native-reanimated';
Then I'm facing above error:

Version Details are
 "react": "^17.0.2",
  "react-native": "^0.64.2",

**Comment by jakub-gonet** [comment] 2021-07-09 12:18
Isn't this a duplicate of #2146?

**Comment by naxir** [comment] 2021-07-09 12:20
@jakub-gonet  both are same

**Comment by jakub-gonet** [comment] 2021-07-09 12:21
So I'll close this one in that case.

**Closed by jakub-gonet** 2021-07-09 12:21 UTC
Labels: 🏠  Reanimated2, 🐞 Bug
