### ISSUE TITLE
Library crashes on React Native 0.59.3 

### ISSUE THREAD

**Issue by MarianneAK** [software-mansion/react-native-reanimated#1919] opened 2021-04-08 08:53 UTC
## Description
I'm trying to install react-native-reanimated on React Native 0.59.3 for Android.
### Expected behavior
I've followed all instructions, so it should be installed correctly.
### Actual behavior & steps to reproduce
but I'm getting the following error on Android:
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'react-native-reanimated-59.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
## Snack or minimal code example
To reproduce it, follow the instructions on https://docs.swmansion.com/react-native-reanimated/docs/installation/ , but I installed through npm.

Then I run the app through react-native-run-android
## Package versions
The version I've installed is 2.1.0.

**Comment by mrousavy** [comment] 2021-04-08 09:04
In the second paragraph of the link you provided:

> As a consequence of the above the minimum supported version of React Native is **v0.62**. Before you continue with the installation, make sure that you are running the supported version of React Native.

Reanimated does not work on 0.59.

**Comment by jakub-gonet** [comment] 2021-04-08 09:08
Also, duplicate of #1918.

**Closed by jakub-gonet** 2021-04-08 09:08 UTC
Labels: 🏠  Reanimated2, 🐞 Bug
