### ISSUE TITLE
"viewTag" is read-only !  2.14.0 createAnimatedComponent(Flashlist) & createAnimatedComponent(MasonryFlashlist)

### ISSUE THREAD

**Issue by hamdij0maa** [software-mansion/react-native-reanimated#3936] opened 2023-01-12 10:08 UTC
### Description

"viewTag" is read-only !  2.14.0 createAnimatedComponent(Flashlist) & createAnimatedComponent(MasonryFlashlist)
const AnimatedMasonryFlashList =
  Animated.createAnimatedComponent(MasonryFlashList);
  
  

### Steps to reproduce

const AnimatedMasonryFlashList =
  Animated.createAnimatedComponent(MasonryFlashList);
  
<AnimatedMasonryFlashList
....
/>

### Snack or a link to a repository

https://gist.github.com/hamdij0maa/1b69577280583c3c996b013454aa6bc0#file-reanimated-flashlist-viewtag-bug

### Reanimated version

2.14.0

### React Native version

0.70.6

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro

### Acknowledgements

Yes

**Comment by hamdij0maa** [comment] 2023-01-12 10:10
> Hey! 👋
> 
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Could you provide a [snack](https://snack.expo.dev/) or a link to a GitHub repository under your username that reproduces the problem?

just use createAnimatedComponet on FlashList by shopify https://gist.github.com/hamdij0maa/1b69577280583c3c996b013454aa6bc0#file-reanimated-flashlist-viewtag-bug

**Comment by efstathiosntonas** [comment] 2023-01-12 10:11
Fixed on `2.14.1` that is about to come out any moment: https://github.com/software-mansion/react-native-reanimated/issues/3933

**Comment by hamdij0maa** [comment] 2023-01-12 10:55
Hey again @efstathiosntonas On Android => the useAnimatedScrollHandler is not wokring any more, 
same issue that was on RC  3.0.0 version

**Comment by tomekzaw** [comment] 2023-01-12 10:57
Closing this issue, duplicate of #3933, fixed in #3934, please upgrade to 2.14.1.

**Closed by tomekzaw** 2023-01-12 10:57 UTC
Labels: Missing repro, Platform: Android, Platform: iOS, Needs review

**Comment by hamdij0maa** [comment] 2023-01-12 10:58
@tomekzaw after upgrading to 2.14.1 the useAnimatedScrollHandler on Android is not working anymore, iOs working but not on android

**Comment by tomekzaw** [comment] 2023-01-12 11:02
Can you send a link to an existing issue or submit a new issue with a proper reproduction so we can look into that?

**Comment by hamdij0maa** [comment] 2023-01-12 11:08
> Can you send a link to an existing issue or submit a new issue with a proper reproduction so we can look into that?

here is the issue : https://github.com/software-mansion/react-native-reanimated/issues/3889#issuecomment-1380163581
but now on Version 2.14.1
