### ISSUE TITLE
 A crash that only appears in some Android users 

### ISSUE THREAD

**Issue by Jiyeopkim** [software-mansion/react-native-reanimated#5368] opened 2023-11-13 00:59 UTC
### Description

same to #5322

com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent

.....

```
Fatal Exception: com.facebook.jni.CppException
Exception in HostFunction: [Reanimated] Attempted to extract from a HostObject that wasn't converted to a Shareable. Error: Exception in HostFunction: [Reanimated] Attempted to extract from a HostObject that wasn't converted to a Shareable. at _scheduleOnJS (native) at anonymous (JavaScript:1:438) at anonymous (JavaScript:1:212) at anonymous (JavaScript:1:629) at handleAndFlushAnimationFrame (JavaScript:1:148)

```

Fatal Exception: com.facebook.jni.CppException
Exception in HostFunction: [Reanimated] Attempted to extract from a HostObject that wasn't converted to a Shareable. Error: Exception in HostFunction: [Reanimated] Attempted to extract from a HostObject that wasn't converted to a Shareable. at _scheduleOnJS (native) at anonymous (JavaScript:1:438) at anonymous (JavaScript:1:212) at anonymous (JavaScript:1:629) at handleAndFlushAnimationFrame (JavaScript:1:148)

This is a crash posted on firebase.

This phenomenon is happening to a very small number of users

It doesn't crash when entering certain screens, but crashes randomly.

### Steps to reproduce

Cannot be reproduced

This is a very random phenomenon.

### Snack or a link to a repository

privacy

### Reanimated version

3.5.3

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2023-11-13 19:32
Duplicate of #5322

**Comment by Jiyeopkim** [comment] 2023-11-14 03:12
> Duplicate of #5322

i know... Is there a solution?

**Comment by tomekzaw** [comment] 2023-11-14 07:52
> i know... Is there a solution?

If you open duplicate issues without reproductions, it's unlikely 😄

**Comment by Latropos** [comment] 2023-11-16 16:47
I'm closing this ticket as a duplicate, please use this one: https://github.com/software-mansion/react-native-reanimated/issues/5322

**Closed by Latropos** 2023-11-16 16:47 UTC
Labels: Missing repro, Platform: Android, Needs review
