### ISSUE TITLE
When debugging is enabled, the application crashes without errors

### ISSUE THREAD

**Issue by valery-lavrik** [software-mansion/react-native-reanimated#2884] opened 2022-01-26 12:39 UTC
after upgrading from version 1.13.2 to 2.3.1, the application began to break as soon as you turn on debugging

I added the plugin to **babel.config.js**
added changes to the **MainApplication.java**
but it didn't help

I have completely cleaned all the caches

```
rd %localappdata%\Temp\metro-cache /s /q
del %localappdata%\Temp\haste-map*
gradlew clean
rd node_modules /q /s
npm cache clean --force
npm start -- --reset-cache
```

But nothing helps

here's what it looks like  -  https://gyazo.com/3ef2d1377993b55ecd6a27549eb21267

My **package.json**
```
{
    "name": "svyaznoy-travel",
    "version": "9.7.0",
    "private": false,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint src -c .eslintrc.json --ext js,jsx",
        "lint-fix": "eslint src -c .eslintrc.json --ext js,jsx --fix",
        "debug": "open 'rndebugger://set-debugger-loc?host=localhost&port=8081'"
    },
    "dependencies": {
        "@babel/plugin-transform-runtime": "^7.13.10",
        "@ptomasroos/react-native-multi-slider": "^2.2.2",
        "@react-native-community/async-storage": "^1.11.0",
        "@react-native-community/masked-view": "^0.1.10",
        "@react-native-community/netinfo": "^6.0.0",
        "@react-native-community/progress-bar-android": "^1.0.4",
        "@react-native-community/progress-view": "^1.2.4",
        "@react-native-community/push-notification-ios": "^1.8.0",
        "@react-native-firebase/app": "^12.1.0",
        "@react-native-firebase/crashlytics": "^12.1.0",
        "@react-native-firebase/messaging": "^12.1.0",
        "@react-navigation/drawer": "^5.12.5",
        "@react-navigation/native": "^5.9.4",
        "@react-navigation/stack": "^5.14.4",
        "@types/lodash": "^4.14.168",
        "@types/ptomasroos__react-native-multi-slider": "0.0.2",
        "@types/react-redux": "^7.1.16",
        "axios": "^0.21.1",
        "babel-plugin-module-resolver": "^4.1.0",
        "babel-plugin-transform-remove-console": "^6.9.4",
        "immutability-helper": "^3.1.1",
        "lodash": "^4.17.21",
        "moment": "^2.29.1",
        "qs": "^6.10.1",
        "react": "17.0.2",
        "react-native": "0.67.1",
        "react-native-add-calendar-event": "^4.0.0",
        "react-native-apay": "git+ssh://git@bitbucket.org:svyaznoy-travel/react-native-apay",
        "react-native-appsflyer": "^6.3.20",
        "react-native-background-timer": "^2.4.1",
        "react-native-debugger": "^1.1.0",
        "react-native-device-info": "^8.0.8",
        "react-native-flash-message": "^0.1.23",
        "react-native-gesture-handler": "^1.10.3",
        "react-native-google-pay": "^2.1.0",
        "react-native-image-picker": "^2.3.3",
        "react-native-linear-gradient": "^2.5.6",
        "react-native-masked-text": "^1.13.0",
        "react-native-pdf": "6.3.0",
        "react-native-push-notification": "^7.3.1",
        "react-native-reanimated": "^2.3.1",
        "react-native-safe-area-context": "^3.2.0",
        "react-native-screens": "^3.0.0",
        "react-native-sensors": "^7.2.0",
        "react-native-svg": "^12.1.0",
        "react-native-webview": "^11.3.2",
        "react-redux": "^7.2.3",
        "redux": "^4.0.5",
        "redux-devtools-extension": "^2.13.9",
        "redux-thunk": "^2.3.0",
        "reselect": "^4.0.0",
        "rn-fetch-blob": "^0.12.0",
        "sp-react-native-in-app-updates": "^1.1.5",
        "tslint": "^6.1.2",
        "typescript": "^4.2.3"
    },
    "devDependencies": {
        "@babel/core": "^7.12.9",
        "@babel/runtime": "^7.12.5",
        "@react-native-community/eslint-config": "^2.0.0",
        "@types/react": "^17.0.3",
        "@types/react-native": "^0.64.2",
        "babel-eslint": "^10.1.0",
        "babel-jest": "^26.6.3",
        "eslint": "7.14.0",
        "eslint-config-airbnb": "^18.2.1",
        "eslint-config-prettier": "^8.1.0",
        "eslint-plugin-import": "^2.22.1",
        "eslint-plugin-jsx-a11y": "^6.4.1",
        "eslint-plugin-prettier": "^3.3.1",
        "eslint-plugin-react": "^7.23.1",
        "jest": "^26.6.3",
        "lint-staged": "^10.5.4",
        "metro-react-native-babel-preset": "^0.66.2",
        "prettier": "2.2.1",
        "react-native-typescript-transformer": "^1.2.13",
        "react-test-renderer": "17.0.2"
    },
    "jest": {
        "preset": "react-native"
    },
    "lint-staged": {
        "*.{js,jsx}": [
            "eslint --fix",
            "git add"
        ]
    }
}

```

**Comment by valery-lavrik** [comment] 2022-01-26 12:44
On the GIF animation I showed how it is reproduced

**Comment by valery-lavrik** [comment] 2022-01-26 12:50
Just found a similar problem
https://github.com/software-mansion/react-native-reanimated/issues/1674
Tell me, does she still have no solution?

**Comment by mohammedelnady** [comment] 2022-01-27 07:56
still ill

**Comment by ammarahm-ed** [comment] 2022-01-27 11:41
@valery-lavrik  Check the docs. It is mentioned that debugging with chrome etc will not work with reanimated v2

**Comment by valery-lavrik** [comment] 2022-01-27 11:53
@ammarahm-ed   
yes, thanks just found this.
It's just interesting, why release version 2, which, unlike the first one, does not support VERY important functionality...   It's more like a downgrade...

This is just my unprofessional opinion.

**Comment by ammarahm-ed** [comment] 2022-01-27 11:58
At first yes, I agree but in terms of performance this is better. Much better and faster. You can use Flipper to Debug. It can be enough in most cases.

**Comment by valery-lavrik** [comment] 2022-01-27 12:02
![image](https://user-images.githubusercontent.com/8047999/151355037-9172da30-fb2a-4955-bf34-e0f126743aae.png)
that's how I open the flipper that I just downloaded

there has been no response from the developers for a week.

**Comment by Biplovkumar** [comment] 2022-01-28 07:42
please provide solution

**Comment by valery-lavrik** [comment] 2022-01-28 07:58
https://github.com/facebook/flipper/issues/3358

there is no solution yet

**Comment by WoLewicki** [comment] 2022-01-28 11:32
Does this issue occur only on Android? If so, there has been a PR merged recently that should fix this: https://github.com/software-mansion/react-native-reanimated/pull/2795/files. Could you try and test it from the `main` branch of this repo and see if the problem is present there?

**Comment by mohammedelnady** [comment] 2022-01-30 07:40
still fu*ken ill

**Comment by WoLewicki** [comment] 2022-01-31 11:05
@mohammedelnady did you run e.g. `Example` app from the repo to test it? Just adding the newest commit of `reanimated` won't work on `Android` since the code is not built from source.

**Comment by mohammedelnady** [comment] 2022-01-31 13:29
### debugging + ### reanimated lib + ### react native bebugger = **App Crash & Stop Working** 

I Uninstall This Bullshit Library To Use The Debugger 
and remove any other library which depend on it 
debugging works like a charm !!

**Comment by mohammedelnady** [comment] 2022-01-31 13:33
Thus I Recommend Anybody not use this library anymore, if they don't use the debugger !

**Comment by valery-lavrik** [comment] 2022-01-31 13:36
> Thus I Recommend Anybody not use this library anymore, if they don't use the debugger !

I agree with you. But they already have a commit that fixes it, it remains only to wait for the new release and hopefully everything will work.  https://github.com/software-mansion/react-native-reanimated/pull/2795/files 

It's not so easy to abandon this library because my application uses react-navigator, which has an important dependency... And it is very difficult to replace react-navigator

**Comment by mohammedelnady** [comment] 2022-01-31 13:43
i am also agree with your pov, if uses redux-saga then you will be needed to use the debugger which leads to a crash !!
thus you will not able to debug the store !!
it is a catastroph manner to use this library in your next project until they update their stable version 
in legacy codes you will "console.log()" 🤷‍♂️

**Comment by piaskowyk** [comment] 2022-02-05 09:38
Fixed in release [2.4.0](https://www.npmjs.com/package/react-native-reanimated/v/2.4.0) 🎉

**Closed by piaskowyk** 2022-02-05 09:38 UTC
Labels: 🧰needs-repro, needs-review, needs-more-info, bug-bash-jan22

**Comment by adityacfcs** [comment] 2022-06-09 17:52
still crashes in 2.8.0

**Comment by drdpedroso** [comment] 2022-06-24 15:10
any chance this can be reopened? Still crashing on 2.8

**Comment by ElbinBinil** [comment] 2022-08-10 16:45
It is crashing for me tooo

**Comment by Rhut-virani** [comment] 2022-11-22 00:59
Still crashing on 2.9.1
