### ISSUE TITLE
【ios】app will be crashed when i install this plugin!!!

### ISSUE THREAD

**Issue by asagcs** [software-mansion/react-native-reanimated#5020] opened 2023-09-01 07:34 UTC
### Description

just when i installed react-native-reanimated,the react-navigation will be crashed. but android is ok!
this is my package:
```
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-pager-view": "^6.2.1",
    "react-native-reanimated": "^3.4.2",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.25.0",
    "react-native-tab-view": "^3.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}
```

this is my page:
```
import * as React from 'react';
import { View, Text, Button } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { SafeAreaProvider } from 'react-native-safe-area-context';

interface HomeProps {
  navigation: any
}

function HomeScreen({navigation}:HomeProps) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
      <Button
        title="Go to Details"
        onPress={() => navigation.navigate('Details')}
      />
    </View>
  );
}

function DetailsScreen() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Details Screen</Text>
    </View>
  );
}

const Stack = createNativeStackNavigator();

function App() {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen name="Home" component={HomeScreen} />
          <Stack.Screen name="Details" component={DetailsScreen} />
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}

export default App;
```

### Steps to reproduce

click to details page and goback later,it's happend!

### Snack or a link to a repository

https://github.com/asagcs/reanimationtest

### Reanimated version

3.4.2

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

iphone 14 pro

### Acknowledgements

Yes

**Comment by xts-bit** [comment] 2023-09-02 07:55
I am facing the same issue on the latest version of React Native When I open the app press "R" for reload it crashes the app, on iOS, Error: 
```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Project                          	       0x1029e4ff4 -[REAAnimationsManager clearAnimationConfigForTag:] + 64 (REAAnimationsManager.m:582)
1   Project                          	       0x1029fa634 -[REASharedTransitionManager clearAllSharedConfigsForViewTag:] + 100 (REASharedTransitionManager.m:636)
2   Project                          	       0x1029faefc __51-[REASharedTransitionManager clearConfigForScreen:]_block_invoke + 104 (REASharedTransitionManager.m:711)
3   Project                          	       0x1029e08d8 REANodeFind + 176 (REAAnimationsManager.m:18)
4   Project                          	       0x1029fae70 -[REASharedTransitionManager clearConfigForScreen:] + 152 (REASharedTransitionManager.m:710)
5   Project                          	       0x1029f910c -[REASharedTransitionManager runSharedTransitionForSharedViewsOnScreen:isInteractive:] + 316 (REASharedTransitionManager.m:486)
6   Project                          	       0x1029f8344 -[REASharedTransitionManager screenRemovedFromStack:] + 440 (REASharedTransitionManager.m:390)
7   Project                          	       0x1029f8100 -[REASharedTransitionManager reanimated_notifyWillDisappear] + 52 (REASharedTransitionManager.m:365)
8   Project                          	       0x102a380b4 -[RNSScreen viewWillDisappear:] + 820 (RNSScreen.mm:893)
```

**Comment by Panigale** [comment] 2023-09-04 09:41
same crash situation when upgrade to react native version 0.72.3

**Comment by Panigale** [comment] 2023-09-04 09:53
I got fixed this issue by install nightly version. try "yarn add react-native-reanimated@nightly"

**Comment by tjzel** [comment] 2023-09-06 08:26
Duplicate of #4836

**Closed by tjzel** 2023-09-06 08:26 UTC
Labels: Platform: iOS, Needs review, Repro provided
