### ISSUE TITLE
Error: Unable to resolve module `./abs` from `node_modules/react-native-reanimated/src/derived/index.js`: 

### ISSUE THREAD

**Issue by dhruv-soni-hi** [software-mansion/react-native-reanimated#1078] opened 2020-08-06 11:38 UTC
## Description

This dependency is failing. I looked into the derived/index.js file but I could not see any import statement for **./abs**. it is weird

![image](https://user-images.githubusercontent.com/66630071/89526857-0300aa00-d806-11ea-8157-46b164a0dd9d.png)

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: 2.0.0-alpha.5

**Comment by jakub-gonet** [comment] 2020-08-06 11:40
Duplicate of #1007.

**Closed by jakub-gonet** 2020-08-06 11:40 UTC
Labels: Reanimated2, 🐞 Bug
