### ISSUE TITLE
[2.2.4] [RN: 0.66.0] Crash on Samsung devices `JSON Parse error: Unexpected end of input SyntaxError:`

### ISSUE THREAD

**Issue by youmitsu** [software-mansion/react-native-reanimated#2823] opened 2022-01-11 08:49 UTC
## Description

On ReactNative 0.66.0, a crash has occurred only samsung device.

Crashlytics screenshot below:

```
Fatal Exception: java.lang.RuntimeException: JSON Parse error: Unexpected end of input

SyntaxError: JSON Parse error: Unexpected end of input
       at com.swmansion.reanimated.AndroidErrorHandler.raise(AndroidErrorHandler.java:6)
       at com.swmansion.reanimated.Scheduler.triggerUI(Scheduler.java)
       at com.swmansion.reanimated.Scheduler.access$100(Scheduler.java:9)
       at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:21)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7263)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

<img width="444" alt="スクリーンショット 2022-01-11 16 11 06" src="https://user-images.githubusercontent.com/15521227/148897093-97e9cf59-9a9c-435b-a013-b69936cbb60d.png">

### Expected behavior

- No crash

### Actual behavior & steps to reproduce

- Crashed
- I have no idea, I cannot reproduce in debug build

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |     0.66    |
| react-native-reanimated              |     2.2.4    |
| NodeJS                               |    14.17.0    |
| Xcode                                |    --     |
| Java                                 |    --     |
| Gradle                               |     --    |
| expo                                 |     --    |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by kacperkapusciak** [comment] 2022-01-28 11:44
Hello @youmitsu :wave:

I'm sorry, but the information that you've provided isn't enough to say anything useful or start working on the problem.

Could you check if the problem occurs on the newest version of `react-native-reanimated`?
If it still occurs could you provide a reproduction?

Cheers

**Comment by lachtos** [comment] 2022-02-05 18:19
Have the same issue, cannot reproduce and I am not using reanimated directly. The only place it is used is by the package react-native-draggable-flatlist. Crashes are not limited to samsung devices.

**Comment by lachtos** [comment] 2022-02-06 16:01
Still getting crashes on 2.4.0

**Comment by Ngomana** [comment] 2022-03-11 22:34
> Still getting crashes on 2.4.0

Were you able to come up with a solution?

**Comment by claudiozam** [comment] 2022-03-15 13:59
I Have the same issue. 

client.android.android_version | 10
client.android.phone_model | SM-T515
react-native-reanimated | 2.4.1

**Comment by Ngomana** [comment] 2022-03-18 17:45
Is there any alternative package to use?

**Comment by husseinAbdulnabi** [comment] 2022-04-03 19:53
having the same issue.

**Comment by pierroo** [comment] 2022-04-21 10:33
I'm afraid I am also facing this same issue.
Completely at loss of solution.
Did any of you guys find a solution?

**Comment by HessiPard** [comment] 2022-09-03 09:24
Same issue here

**Comment by xKRUTOIx** [comment] 2022-12-23 07:49
I'm having the same issue, has anyone fixed it? 🤔

**Comment by Latropos** [comment] 2023-09-13 10:06
Bug was fixed in https://github.com/software-mansion/react-native-reanimated/pull/4037

**Closed by Latropos** 2023-09-13 10:06 UTC
Labels: Missing repro, Platform: Android, Crash, Missing info, bug-bash-jan22
