### ISSUE TITLE
Could you help me, when i use useSharedValue in debug, it show error?

### ISSUE THREAD

**Issue by memberwebm** [software-mansion/react-native-reanimated#4347] opened 2023-04-10 06:46 UTC
### Description

could you help me, when i open debug dev, it show bug 
<img width="2047" alt="Screenshot 2023-04-10 at 13 42 56" src="https://user-images.githubusercontent.com/110653846/230843186-6d6d23f8-9446-41c2-85bc-d61d9761a5ee.png">
+but when i delete useSharedValue it working , i want to use useSharedValue and debug, is there any way?

### Steps to reproduce

1.use  useSharedValue
2. open debug ios
3. bug will show

### Snack or a link to a repository

 https://stackoverflow.com/help/mcve

### Reanimated version

3.0.2

### React Native version

0.69.0

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment] 2023-05-09 09:18
Duplicate of #3951, please try hints suggested in the conversation

**Comment by Latropos** [comment] 2023-05-09 09:19
Duplicate of https://github.com/software-mansion/react-native-reanimated/issues/3951

**Comment by Latropos** [comment] 2023-05-09 09:23
Duplicates #4198

**Comment by piaskowyk** [comment] 2023-05-15 14:35
Closed due to duplication. We want to keep discussion in the one place.

**Closed by piaskowyk** 2023-05-15 14:35 UTC
Labels: Missing repro, Platform: iOS, Needs review

**Comment by tjzel** [comment] 2023-05-22 14:12
@memberwebm Could you check if your issue is fixed with new version of Reanimated? (taken from either GitHub or nightly build (e.g. yarn add react-native-reanimated@nightly))
