### ISSUE TITLE
useAnimatedKeyboard stops animating when interupting animation

### ISSUE THREAD

**Issue by lauridskern** [software-mansion/react-native-reanimated#4333] opened 2023-04-04 21:11 UTC
### Description

When I open and close the keyboard fast and interrupt the opening animation by closing the keyboard again the hook stops animating the value and just jumps between 0 and max value.

https://user-images.githubusercontent.com/8788856/229920043-1c02de53-e342-4127-9300-68ace793b962.mov

### Steps to reproduce

Use the example for useAnimatedKeyboard from the website and open and close the keyboard rapidly. When interrupting the animation it will stop animating 

### Snack or a link to a repository

https://snack.expo.dev/@upo/useanimatedkeyboard-bug

### Reanimated version

3.0.2

### React Native version

0.71.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by tomekzaw** [comment] 2023-04-05 09:50
Hey @lauridskern, thanks for reporting this issue, it should be already fixed with #4266.

**Comment by tomekzaw** [comment] 2023-04-05 11:34
Duplicate of #4324, fixed with #4266 and #4329.

**Closed by tomekzaw** 2023-04-05 11:34 UTC
Labels: Platform: iOS, Needs review, Repro provided

**Comment by lauridskern** [comment] 2023-04-05 23:48
Sorry my bad

**Comment by tomekzaw** [comment] 2023-04-06 07:18
> Sorry my bad

No problem at all. Take care! 😄
