### ISSUE TITLE
java.lang.RuntimeException 'folly::toJson: JSON object value was a NaN when serializing value at "velocity"->"y"'

### ISSUE THREAD

**Issue by michaelknoch** [software-mansion/react-native-reanimated#2814] opened 2022-01-07 12:52 UTC
## Description
We see a bunch of these crashes in production, unfortunately I was not able to reproduce it yet in a local dev environment. From the error tracking it also seems to happen when interacting with unrelated ScrollViews. Do you have any idea how to fix or workaround this? I'm happy to contribute, but so far I'm still trying to understand whats wrong.

### Expected behavior
It should not crash

### Actual behavior & steps to reproduce
It creashes with `folly::toJson: JSON object value was a NaN when serializing value at "velocity"->"y"`

```
java.lang.RuntimeException: folly::toJson: JSON object value was a NaN when serializing value at "velocity"->"y"
        at com.facebook.react.bridge.NativeMap.toString(NativeMap.java:-2)
        at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:-2)
        at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:56)
        at com.facebook.react.uimanager.events.Event.dispatch(Event.java:180)
        at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:515)
        at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:489)
        at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
        at com.facebook.react.views.scroll.ReactScrollViewHelper.emitScrollEvent(ReactScrollViewHelper.java:88)
        at com.facebook.react.views.scroll.ReactScrollViewHelper.emitScrollEndDragEvent(ReactScrollViewHelper.java:57)
        at com.facebook.react.views.scroll.ReactScrollView.onTouchEvent(ReactScrollView.java:362)
        at android.view.View.dispatchTouchEvent(View.java:15199)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3914)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3578)
        at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:868)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:39)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:39)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:39)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
        at android.view.View.dispatchPointerEvent(View.java:15458)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7470)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7246)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6608)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6665)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6631)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6799)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6639)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6856)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6612)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6665)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6631)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6639)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6612)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9893)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9731)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9684)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10027)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java:-2)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9973)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10069)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:737)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8550)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

## Snack or minimal code example
tbd

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.66.4     |
| react-native-reanimated              |    2.3.0     |
| react-native-gesture-handler              |    2.1.0     |
| NodeJS                               |    16.13.1     |
| Xcode                                |   13.2      |
| Java                                 |     8    |
| Gradle                               |    6.8.1     |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment] 2022-01-14 12:24
Duplicate of: https://github.com/software-mansion/react-native-reanimated/issues/2662

**Closed by piaskowyk** 2022-01-14 12:24 UTC
Labels: 🧰needs-repro, 🤖android, needs-review, needs-more-info
