### ISSUE TITLE
ScrollView is missing the React import

### ISSUE THREAD

**Issue by camcnz** [software-mansion/react-native-reanimated#4514] opened 2023-05-31 15:38 UTC
### Description

The react import seems to be missing from ScrollView. This is causing my app to crash with the message it can't find React.
I have fixed this by importing React into ScrollView.tsx

![Screenshot 2023-05-31 at 17 31 58](https://github.com/software-mansion/react-native-reanimated/assets/42150271/e5b990d6-47ad-4e93-abcc-e88fcbff59f4)

### Steps to reproduce

Create a view using ScrollView.
```
export const Slider = styled(Animated.ScrollView)`
  width: 100%;
`;
```

### Snack or a link to a repository

-

### Reanimated version

3.2.0

### React Native version

0.67.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by v-honcharenko** [comment] 2023-06-10 11:34
Duplicate of #4531

**Closed** 2023-06-16 07:10 UTC
Labels: Missing repro, Platform: iOS, Needs review, Missing info
