### ISSUE TITLE
useSharedValue is reset to initial value after animation is complete on web

### ISSUE THREAD

**Issue by gust42** [software-mansion/react-native-reanimated#2093] opened 2021-06-02 11:29 UTC
## Description

When doing an animation on opacity and transform at the same time the opacity is reset to initial value when animation is done

Also on repo is an issue with withDelay, see comment in Star.tsx
 
### Expected behavior

opacity should not change after animation is complete

### Actual behavior & steps to reproduce

change opacity and transform on an View in react-native-web, see repo below

## Snack or minimal code example

Repo with small example of issue

https://github.com/gust42/reanimated-bug

## Package versions

- React Native: 0.64.1 (also testen in 0.63)
- React Native Reanimated: 2.2.0 (Had this issue since alfa)
- NodeJS: 14.15.0
- React Native Web: 0.16.3

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by sreuter** [comment] 2021-06-07 00:17
Same issue as reported here: https://github.com/software-mansion/react-native-reanimated/issues/2019

**Comment by jmysliv** [comment] 2021-07-23 13:11
I'm closing because this issue is a duplicate of #2019.

**Closed by jmysliv** 2021-07-23 13:11 UTC
Labels: 🏠  Reanimated2, 🐞 Bug
