### ISSUE TITLE
Bug on reanimated 3, not there in reanimated 2. useAnimatedProps not re-rendering. 

### ISSUE THREAD

**Issue by SimonAM** [software-mansion/react-native-reanimated#4336] opened 2023-04-06 09:47 UTC
### Description

Running reanimated version 3 i have bugs related to animated components not rendering/re-rendering when their corresponding useAnimatedStyle/useAnimatedProps are updated. 
When rolling back to reanimated version 2.14.4 everything works as expected. 

Does anyone else experience problems? 
Im using Expo SDK 48 dev build. (not go, so shouldn't be related to expo)  

### Steps to reproduce

This is one case thats affected, the other is an animatedStyle, but behaves in a similar fashion. 

```
const faultyAnimatedComponent = ({animatedProps}) => (
<Svg>
<AnimatedPath animatedProps={animatedProps}/>
</Svg>
)

const animatedProps =  useAnimatedProps(() => {
    const stroke = interpolateColor(scrollvalue..)
    const fill = interpolateColor(scrollvalue...)
    console.log("filled value is: ", filed.value)
    if (filled.value){
        return {
            stroke: stroke,
            fill: fill
    } else {
      return {
          stroke: stroke,
          fill: "transparent"
    }
   }
  }, [scrollValue, filled], [fillAdapter, strokeAdapter])

return (
<View>
<FaultyAnimatedComponent animatedProps={animatedProps} />
</View>
)

```
I can log the filled.value, and it updates on button press as expected. However, the AnimatedPath does not re-render on button press. 
It re-renders when scrolling, or on second button press. Second-button press leads to the component lagging one state behind (it renders as filled, when not and vice versa. And renders correctly on scroll). 

Cant really reproduce via snack, as v3 doesn't work on snack. 

### Snack or a link to a repository

https://snack.expo.dev/@pastacarbonara/93f92a

### Reanimated version

3.0.1

### React Native version

0.71.3

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Real device

### Device model

Samsung Galaxy s21 / Iphone 13

### Acknowledgements

Yes

**Comment by billnbell** [comment] 2023-04-07 23:19
us too

**Comment by Latropos** [comment] 2023-04-24 12:04
Duplicate of #3321

**Closed** 2023-05-15 11:04 UTC
Labels: Platform: Android, Platform: iOS, Needs review, Repro provided

**Comment by farmerpaul** [comment] 2023-06-06 10:54
@Latropos I've tried workarounds as suggested in #3321 to fix this issue, however none of had any effect. Would it be possible for you to share why you think this bug is duplicative of that one? We need to use Reanimated 3.2 for our project due to [this Reanimated 2 bug](https://github.com/software-mansion/react-native-reanimated/issues/2285), but we also need to be able to control our Lotties using `progress` as an animated prop, hence our encountering this issue. Not sure how to proceed.

**Comment by JiriHoffmann** [comment] 2023-06-14 21:29
Also having an issue animating the intensity prop for Expo BlurView after updating from v2 to v3.1.0

**Comment by Chronostyle** [comment] 2023-07-09 13:15
@SimonAM did you find any workaround solution? i was having a same problem like you when trying to follow this tutorial: https://www.youtube.com/watch?v=6jxy5wfNpk0, my problem occured on IOS side

**Comment by SimonAM** [comment] 2023-07-13 06:05
No i had to revert to reanimated 2. I specifically had problems with useAnimatedProps and animatedPropAdapter.
