### ISSUE TITLE
Constant crash when debugging on localhost (iOS only)

### ISSUE THREAD

**Issue by naftalibeder** [software-mansion/react-native-reanimated#216] opened 2019-03-18 21:47 UTC
When debugging locally on simulator or device, I constantly get this redbox error:

```
ExceptionsManager.js:84 Exception thrown while executing UI block:
*** -[__NSArrayM setObject:atIndexedSubscript:]: object cannot be nil
```

Is this a known issue? I'd be happy to look into it, but I wanted to check if anybody was aware of it so far. It makes debugging very difficult.

**Comment by naftalibeder** [comment] 2019-03-19 20:58
Getting somewhere! If I remove the call

`[nodesManager operationsBatchDidComplete];`

in `REAModule.m`, the exceptions stop throwing. Looking at the documentation for `(void)operationsBatchDidComplete` in `REANodesManager.m`, it doesn't seem like this call is absolutely necessary, and I'm not noticing any performance issues from the slightly deferred callback.

@kmagiera Would you mind weighing in on this? I can do a PR with the line removed, but it would help to know more about why it's there and whether there are any conditional checks we could run instead of removing it.

**Comment by naftalibeder** [comment] 2019-03-21 16:41
Well, I've encountered a situation where removing that method has a practical impact. Without it, calling `setValue()` on a node twice in quick succession fails the second time. So in some circumstances the line appears to be necessary.

**Comment by vnlebaoduy** [comment] 2019-04-05 10:25
How to fixed :'( . i alway see that when debugging

**Comment by naftalibeder** [comment] 2019-04-05 14:49
@vnlebaoduy As I mentioned [above](https://github.com/kmagiera/react-native-reanimated/issues/216#issuecomment-474581910), you can avoid this during debugging by removing/commenting the line `[nodesManager operationsBatchDidComplete]` in `REAModule.m`. This has some unfortunate side effects, but makes debugging tolerable.

You don't need to, but I put the line inside a preprocessor conditional:

```
#ifndef DEBUG
[nodesManager operationsBatchDidComplete];
#endif
```

**Comment by vnlebaoduy** [comment] 2019-04-06 09:49
@naftalibeder thanks <3

**Comment by heyman333** [comment] 2019-04-15 07:35
@naftalibeder this error occurs in debug mode only?

**Comment by naftalibeder** [comment] 2019-04-15 16:07
@heyman333 As far as I've seen, yes.

**Comment by yuanfux** [comment] 2019-05-26 05:44
Error was confirmed when I was using `setValue()` inside PanGestureHandler event callback. It seems like calling `setValue()` on a very frequent manner does cause this issue. Hopefully this can be addressed in a better form than fixing the .m file.

**Comment by district-michael** [comment] 2019-08-19 05:36
Is there any movement on getting this fixed?  Its coming up a bunch for us, and editing the .m file is not really a great solution.

**Comment by ochanje210** [comment] 2019-08-25 05:49
> @vnlebaoduy As I mentioned [above](https://github.com/kmagiera/react-native-reanimated/issues/216#issuecomment-474581910), you can avoid this during debugging by removing/commenting the line `[nodesManager operationsBatchDidComplete]` in `REAModule.m`. This has some unfortunate side effects, but makes debugging tolerable.
> 
> You don't need to, but I put the line inside a preprocessor conditional:
> 
> ```
> #ifndef DEBUG
> [nodesManager operationsBatchDidComplete];
> #endif
> ```

Why not applying what @naftalibeder did

**Comment by ochanje210** [comment] 2019-08-25 06:18
it still crashes on me in debug mode, even after following what @naftalibeder did

**Comment by flunder** [comment] 2019-09-25 12:36
> Well, I've encountered a situation where removing that method has a practical impact. Without it, calling `setValue()` on a node twice in quick succession fails the second time. So in some circumstances the line appears to be necessary.

I wrapped my setValue inside a requestAnimationFrame and that resolved that issue. Thanks for the idea. Had no idea what the error meant.

**Comment by pribeh** [comment] 2019-10-04 17:45
Same here

**Comment by pribeh** [comment] 2019-10-11 18:57
I believe @yolpsoftware found the cause

https://github.com/kmagiera/react-native-reanimated/issues/397

**Comment by jaysbytes** [comment] 2019-11-04 12:12
In my case, it crashes if I'm using `setValue` inside `call` callback

**Comment by JulianKingman** [comment] 2019-11-25 22:00
I get the same crash when using `call` inside `useCode`
```javascript
useCode(block([
    ...(otherstuff),
    cond(
      eq(state, State.END),
      call(['done'], txt => console.log(txt)),
    ),
])
```

**Comment by VBT-BB** [comment] 2019-11-29 15:06
@JulianKingman The first argument of `call` must be an array of animated nodes, it cannot be a string
See [here](https://software-mansion.github.io/react-native-reanimated/call.html)

**Comment by Hirbod** [comment] 2019-12-08 23:58
Ping @kmagiera

**Comment by michalsek** [comment] 2019-12-19 16:20
Hi @Hirbod, could you provide some minimal code example that reproduces that, and which react-native and reanimated versions are you using?

Preferably using the template below
```
--- BUG REPORT ---

## Description

## Steps To Reproduce

1. 
2. 

## Expected behavior:

## Actual behavior:

## Snack or minimal code example:

<!--
Please provide a Snack ([https://snack.expo.io/](https://snack.expo.io/)) or provide a minimal code example that reproduces the problem.
Here are some tips for providing a minimal example: [https://stackoverflow.com/help/mcve](https://stackoverflow.com/help/mcve).

You can attach screenshots or GIFs as well.
-->

## Versions

<!--
Fill in your Reanimated and React Native versions below
-->

- React Native:
- React Native Reanimated:

--- Feature request ---

## Motivation

<!--
Please provide motivation to add this feature (why is it needed, what problem it solves, etc)
-->

## Description

## Code example

<!--
If possible, add short code example which shows how this feature would be used
-->
```

**Comment by xenophilicibex** [comment] 2020-01-07 02:23
I am also encountering this issue. I am not sure what causes it, but I started noticing it more as I used more `call`s in my code. (I'm using them to hook into different states like: enter, exit animations)

**Comment by vamshi9666** [comment] 2020-02-05 11:22
occurred to me too. and yes i am calling `.setValue() `in `call` multiple times.

**Comment by mrkacan** [comment] 2020-02-05 12:18
Same here

**Comment by kmagiera** [comment] 2020-02-05 15:03
Thank you all for your comments. From your reports I see that you are experiencing some issues, however from the maintainer perspective most of those comments aren't really actionable. I'd be happy to take a look if you can post a link to github repo or expo snack which we can use to reproduce the problem.

**Comment by yolpsoftware** [comment] 2020-02-05 15:05
@kmagiera #397 might be a repro.

**Comment by yolpsoftware** [comment] 2020-03-11 11:59
@kmagiera Still having this issue. It even crashes the whole Expo app. I have `setValue()` in a `call` too.

**Comment by fozhao** [comment] 2020-03-23 09:39
> Thank you all for your comments. From your reports I see that you are experiencing some issues, however from the maintainer perspective most of those comments aren't really actionable. I'd be happy to take a look if you can post a link to github repo or expo snack which we can use to reproduce the problem.

I am experiencing this while setting value from onLayout callback of a View component to a Animated value object. Like this: 

```
    onLayout(event) {
        const {nativeEvent: { layout: {x, y, width, height}}} = event
        console.log("layout", x, y, width, height)
        this.containerHeight.setValue(height)
    }
```

Seeing the same exception in Xcode console. 
[error][tid:main][RCTUIManager.m:1112] Exception thrown while executing UI block: *** -[__NSArrayM setObject:atIndexedSubscript:]: object cannot be nil

**Comment by ninjz** [comment] 2020-03-25 14:13
Here's a minimal example that can reproduce this issue. It's clear that this error occurs when calling setValue too quickly. I can also confirm that what @naftalibeder did above also did the trick in suppressing this error from happening.

## Example
```
  useEffect(() => {
    const startTime = new Date()
    const interval = setInterval(() => {
      if (!pausedRef.current) {
        const timeElapsed = new Date() - startTime
        const formatted = formatTimeFromSeconds(Math.floor(timeElapsed / 1000))
    
        totalTime.setValue(formatted)
      }
    }, 1)

    return () => clearInterval(interval)
  }, [])
```

## Versions

- React Native: 0.61.5
- React Native Reanimated: 1.7.0

**Comment by yolpsoftware** [comment] 2020-06-03 12:59
Any update on this? Still experiencing it regularly.

**Comment by yolpsoftware** [comment] 2020-07-03 19:14
Any update on this? Still a problem. When you use `setValue`, this crash happens all the time.

**Comment by jakub-gonet** [comment] 2020-07-07 10:01
@ninjz, I wasn't able to repro this by your example, could you describe steps to notice that?

I enabled debugging and ran the app from the Xcode, no redbox, nothing in logs

**Comment by yolpsoftware** [comment] 2020-07-08 13:18
Tried the repro with `react-native-reanimated` `1.9.0`, `1.7.0` and `1.2.0`. Unfortunately, no redbox in either version.

@jakub-gonet When the error happens again, is there anything I can do to help narrow it down?

**Comment by jakub-gonet** [comment] 2020-07-08 15:36
Thanks for the followup, anything that helps to debug it is helpful — repros, stack traces, library version (commit which introduced regression if you're able to find it), things like that. Especially repros are really convenient.

**Comment by yolpsoftware** [comment] 2020-07-13 21:57
We are seeing crashes of the Expo app (running a `expo publish`ed app) while running animations which have some `setValue` calls. The Expo app just disappears randomly while running those animations.

Is it possible that this is the same issue?

@jakub-gonet here's a crash log from the Expo app:

https://www.dropbox.com/s/m8vpokbafcse1i5/Exponent%20%2007.06.20%2C%2016-15.crash?dl=0

It seems the crash was triggered by the thread `Dispatch queue: com.facebook.ABI36_0_0React.NetworkingQueue`. What would we see in the crash log, if the crash was caused by this issue?

**Comment by jakub-gonet** [comment] 2020-07-16 10:23
Frankly, hard to say. Looking at original issue (`-[__NSArrayM setObject:atIndexedSubscript:]: object cannot be nil` exception) it's happening when doing something in lines of:
```obj-c
some_array[i] = nil
```
and the only place where this can be happening is the `findNodeByID` call in the operator node.

We can't fix it without reproducing it unfortunately.

**Closed** 2020-07-24 12:15 UTC
Labels: ⚠important, 🍎iOS, 🐞bug-bash-dec19, 🧰need-repro

**Comment by chiefchief** [comment] 2020-09-12 16:23
crash when trying open via ref in useEffect 
```
  useEffect(() => {
    if (image) {
      // sheetRef?.current?.snapTo(snapPoint);
    }
  }, [image]);
```

**Comment by jakub-gonet** [comment] 2020-09-12 17:17
@chiefchief, could you include the entire code? It's way easier for us to debug it that way.

**Comment by chiefchief** [comment] 2020-09-13 11:57
> @chiefchief, could you include the entire code? It's way easier for us to debug it that way.

the problem was with snapTo, i had snapPoints - [0, value], and tried snap to value, but had to snapTo index, not value

**Comment by valin0k** [comment] 2020-10-02 16:38
i reproduced that issue by copying https://github.com/browniefed/react-native-ticker/blob/master/index.tsx to my components and using it as here

```
import React, { useState, useEffect } from "react";
import { View, StyleSheet } from "react-native";

import Ticker, { Tick } from "./ticker2";

function getRandom(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const currencies = ["$", "¥", "€"];

const App = () => {
  const [state, setState] = useState({
      currency: currencies[getRandom(0, 2)],
      value: getRandom(0, 100000)
    });

  useEffect(() => {
    setInterval(() => {
      setState({
        currency: currencies[getRandom(0, 2)],
        value: getRandom(0, 100000)
      });
    }, 500);
  }, []);

  return (
    <View style={styles.container}>
      <Ticker textStyle={styles.text}>
        <Tick rotateItems={currencies}>{state.currency}</Tick>
        {state.value.toLocaleString()}
      </Ticker>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#333"
  },
  text: {
    fontSize: 40,
    color: "#FFF"
  }
});

export default App;
```
I have the last version of the reanimated 2 and moved file without any changes. And after a few mins or earlier a have got the error. reanimated version: `2.0.0-alpha.7`, RN version: 0.63.3
<img width="394" alt="Снимок экрана 2020-10-02 в 17 54 22" src="https://user-images.githubusercontent.com/8665687/94947542-ff3c8b80-0507-11eb-981a-f2030aff6697.png">

**Comment by jakub-gonet** [comment] 2020-11-12 12:37
@valin0k this is a pretty big component, could you prepare a smaller repro without external dependencies?

**Comment by reymanov** [comment] 2021-11-04 14:32
Any updates on that ?, I can still experience that issue on version 2.3.0-beta.2
