### ISSUE TITLE
Error Not Work RN

### ISSUE THREAD

**Issue by Victorcassiano** [software-mansion/react-native-reanimated#2347] opened 2021-08-30 21:35 UTC
## Description

I did the step by step to install Moti, using only React Native, without Expo.
returned these errors to me:

<img src="https://i.imgur.com/a551x0W.png" alt="Minha Figura" width="400px">

<img src="https://i.imgur.com/TbOZ8yd.png" alt="Minha Figura" width="900px">

## Package versions

- React Native: 0.64
- React Native Reanimated: 2.0.0

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by Victorcassiano** [comment] 2021-08-30 21:39
> ## Issue validator
> The issue is invalid!
> 
> * Section expected behavior seems to be empty(for label 🐞 bug)
> * Section actual behavior & steps to reproduce seems to be empty(for label 🐞 bug)

**Comment by jmysliv** [comment] 2021-08-31 06:28
Hi @Victorcassiano! Did you follow steps from our [docs](https://docs.swmansion.com/react-native-reanimated/docs/installation) or Moti docs? Also, I would recommend bumping the reanimated version to `2.2.0` or alpha release, a lot of things have changed since `2.0.0`.

**Comment by Victorcassiano** [comment] 2021-08-31 23:20
> Hi @Victorcassiano! Did you follow steps from our [docs](https://docs.swmansion.com/react-native-reanimated/docs/installation) or Moti docs? Also, I would recommend bumping the reanimated version to `2.2.0` or alpha release, a lot of things have changed since `2.0.0`.

Hi, so I've already tested it on the latest version and did all the steps you ask for in the doc.

**Comment by jmysliv** [comment] 2021-09-06 12:26
@Victorcassiano have you tried to clear gradle cache? Also, this issue seems to be a duplicate of #1376, you can check out that issue, and I'm gonna close this for now. If then you will still encounter this issue, let me know and I'll reopen it.

**Closed by jmysliv** 2021-09-06 12:26 UTC
Labels: 🐞 Bug, 🏠  Reanimated2
