### ISSUE TITLE
useAnimatedStyle creates object with viewRef: {current: null}

### ISSUE THREAD

**Issue by Lis-Ma** [software-mansion/react-native-reanimated#1369] opened 2020-10-22 10:29 UTC
## Description

Hey everybody, I'm trying to animate the transitions of expanding and collapsing nested UI elements. For this, I wrote some generic(ish) helper functions to be able to animate the height or width of an element. 
Now, using these helper functions to animate the height of the outer UI element works fine. But when I want to animate the width of an inner UI element the same way, the animation doesn' t happen. I found that the objects that are created via useAnimatedStyle (which are passed as style props to the respective UI elements' views) differ in one property: 
The correctly animated element contains the property `viewRef: current: AnimatedComponent ...`, while the other contains `viewRef: {current: null}`. 

Am I correct thinking that this creates my error? And what can I do to solve it?

I'm new to animation in react native and also don't have that much experience with react native in general, so it can very well be that the error is on my side. I'm glad for feedback in any direction :)

## Code

The weekdays are animated correctly, the dates are not.

```js
const collapsedHeight = 140;
const collapsedWidth = 165;

const timingDef = {
        duration: 500,
        easing: Easing.bezier(0.5, 0.01, 0, 1),
    };

const weekdayValues = createSharedValues(7, 'weekday', collapsedHeight);
const weekdayStyles = createStyles(7, 'weekday', weekdayValues, timingDef, 'height');

// weekdayStyles[weekday1].viewRef = current: AnimatedComponent ...

const dateValues = createSharedValues(1, 'date', collapsedWidth);
const dateStyles = createStyles(1, 'date', dateValues, timingDef, 'width');

// dateStyles[date1].viewRef = {current: null}
```

```js
export function createSharedValues(keyAmount, elementName, initialValue) {

    const array = new Array(keyAmount).fill(null);
    const filledArray = array.map((element, index) => elementName + (index + 1));

    const object = {};

    for (const index of filledArray) {
        object[index] = useSharedValue(initialValue);
    }
    return object;
}

export function createStyles(keyAmount, elementName, valuesObject, timingDef, dimension) {

    const array = new Array(keyAmount).fill(null);
    const filledArray = array.map((element, index) => elementName + (index + 1));

    const object = {};

    if (dimension == 'height') {
        for (const index of filledArray) {
            object[index] = useAnimatedStyle(() => {
                return {
                    height: withTiming(valuesObject[index].value, timingDef),
                };
            });
        }
    }
    else if (dimension == 'width') {
        for (const index of filledArray) {
            object[index] = useAnimatedStyle(() => {
                return {
                    width: withTiming(valuesObject[index].value, timingDef),
                };
            });
        }
    }
    console.log(object);
    return object;
}
```

### Package versions

- React: 16.13.1
- React Native: 39.0.3
- React Native Reanimated: ^2.0.0-alpha.6.1

(I'm using Expo Version ^39.0.0.)

**Comment by karol-bisztyga** [comment] 2020-10-22 10:57
One output of `useAnimatedStyle` cannot be passed to multiple animated components. The proper way to handle such cases is creating a separate `useAnimatedStyle` for every animated component.

**Comment by Lis-Ma** [comment] 2020-10-22 12:10
Hey @karol-bisztyga, thank you for the fast response. 
As far as I see it, I actually don't use one output of useAnimatedStyle several times. My workaround for this is creating the objects that are returned by the functions `createSharedValues` and `createStyles`. This way, useAnimatedStyle is called for every key of the object. 

I pass the "style objects" as follows: 

WeekView.jsx :
 
``` jsx
...
const weekdayValues = createSharedValues(7, 'weekday', collapsedHeight);
const weekdayStyles = createStyles(7, 'weekday', weekdayValues, timingDef, 'height');
...

return (
        <View>
            {shownWeekdays.map((dayString, index) =>
                <Weekday
                    key={dayString}
                    id={"weekday" + (index+1)}
                    expanded={dayString == expandedDay}
                    boxStyles={weekdayStyles}
                    boxValues={weekdayValues}
                    collapsedHeight={collapsedHeight}
                    expandedHeight={expandedHeight}>
                </Weekday>
            )}
        </View>
    );
```

Weekday.jsx: 
``` jsx
return (
        <Animated.View style={ [props.boxStyles[props.id], props.expanded ? { height: props.expandedHeight } : { height: props.collapsedHeight }]} >
            <DateViewContainer
                type={props.expanded ? 'expanded' : 'collapsed'}>
            </DateViewContainer>

            { props.expanded
                ? <ExpandedWeekday> </ExpandedWeekday>
                : <CollapsedWeekday> </CollapsedWeekday>
            }
        </Animated.View>

    );
```
The animation of the height of the Weekdays works fine.

Below is the date view where the animation of the width is not shown:

DateViewContainer.jsx:
```jsx
...
const dateValues = createSharedValues(2, 'date', collapsedWidth);
const dateStyles = createStyles(2, 'date', dateValues, timingDef, 'width');
...

return (
        expandedEventDay == props.date
            ?
            <ExpandedDateView
                date={props.date}
                isActive={props.isActive}
                type={props.type}
                style={[dateStyles.date1, { width: expandedWidth }]}>

            </ExpandedDateView>
            :
            <CollapsedDateView
                date={props.date}
                isActive={props.isActive}
                type={props.type}
                style={[dateStyles.date1, { width: collapsedWidth }]}>

            </CollapsedDateView>
    )
```

CollapsedDateView.jsx: (ExpandedDateView looks the same, just with a different content)
```jsx
return (
        <Animated.View style={[mealplan.dates, props.style]}>
           //content
        </Animated.View>
```

**Comment by karol-bisztyga** [comment] 2020-10-23 11:25
I see. Could you please post a single snipped which reproduces this issue? You posted a several pieces of code but it lacks a whole picture. Please post either the whole app or a minimal snack, thank you.

**Comment by karol-bisztyga** [comment] 2021-01-22 07:59
Closing this due to a lack of minimal repro. I'm sorry but this code is not clear. Also, please trying using newer releases(newest it rc.2 or rc.0 if [you are using expo](https://docs.expo.io/versions/latest/sdk/reanimated/#experimental-support-for-v2-alpha)). If this issue persists on the newest release then please let me know here and I'll reopen this issue.

**Closed by karol-bisztyga** 2021-01-22 07:59 UTC
Labels: ❓Question, 🏠  Reanimated2
