### ISSUE TITLE
Reanimated 2.3.0-beta.1 problems

### ISSUE THREAD

**Issue by Bayramito** [software-mansion/react-native-reanimated#2458] opened 2021-09-27 08:57 UTC
I'm currently on the 2.2.2 which works stable for now.  (without debug with chrome)

So today i wanted to give a try to 2.3.0-beta.1 version, but  previous problems remains same.

"Debug with Chrome" kind a works fine but when you enable it, the app doesn't work properly. 

For example:
` WARN  Require cycle: node_modules/react-native-paper/lib/module/components/Appbar/Appbar.js -> node_modules/react-native-paper/lib/module/components/Appbar/AppbarHeader.js -> node_modules/react-native-paper/lib/module/components/Appbar/Appbar.js
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.`

this error doesn't appear normally if i dont enable debug with chrome. 

Some systems that i made before aren't also working like drag and sort with reanimated v2.  

Pan gestures kind a working but they are also bugging feels like there is some FPS drops when you move elements around.

I also tried Safari Debugger but it throws me another error "signal 6 was raised. (null)" and when i hit refresh by R key, everytime throws this error.

"react-native":"0.64.2"
"react-native-reanimated":"2.3.0-beta.1"

**Comment by tominou** [comment] 2021-10-03 04:01
Same issue here.
`react-native 0.66.0`
`react-native-reanimated 2.3.0-beta.1`

**Comment by piaskowyk** [comment] 2022-01-14 12:34
Does it problem still occur on Reanimated 2.3.1?

**Comment by kmagiera** [comment] 2022-01-28 10:13
Hi @Bayramito and @tominou – thanks for reporting and for your comments. Can you confirm this problem still persisrt on 2.3.1 version? Also it seem like the cycle is detected in `react-native-paper` and not in `react-native-reanimated` which means there is some additional setup needed to reproduce this error. The root cause could still be the reanimated upgrade but since it requires additional setup it'd be important for us to get a small repo link with all that in place to allow us to reproduce the problem w/o guessing what other packages you have installed

**Comment by Bayramito** [comment] 2022-01-28 14:56
I dont get any errors right now but debug with chrome

**Comment by piaskowyk** [comment] 2023-05-23 13:30
This issue seems to be no longer related in Reanimated 3, so let me close this request.

**Closed by piaskowyk** 2023-05-23 13:30 UTC
Labels: Bug, 🏠  Reanimated 2, bug-bash-jan22
