### ISSUE TITLE
` WARN  `new NativeEventEmitter()` react native reanimated 2

### ISSUE THREAD

**Issue by kodeandoec** [software-mansion/react-native-reanimated#2357] opened 2021-09-02 12:32 UTC
## Description
when i try npx react-native run-android have this issue
` WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.`

### Actual behavior & steps to reproduce
when i try npx react-native run-android have this issue

## Package versions
- React Native: 0.65.0
- React Native Reanimated:^2.3.0-alpha.2
- NodeJS: 14
- Xcode: 14
- Java  8
- Gradle 6.9

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by jmysliv** [comment] 2021-09-02 14:31
Duplicate of #2297.

**Closed by jmysliv** 2021-09-02 14:31 UTC
Labels: 🐞 Bug, 🏠  Reanimated2
