### ISSUE TITLE
Cannot build reanimated on RN 0.72.8

### ISSUE THREAD

**Issue by Girum** [software-mansion/react-native-reanimated#5557] opened 2024-01-04 19:45 UTC
### Description

Tried to install reanimated 3.6.1 on android 14, RN 0.72.8, not working.

After came from RN 0.70.6 to 0.72.8, I encountered many issues to build the projects...

One of these is to build reanimated 3 (I had to update to 3, because iOS is with problem with v2 with RN 0.72).

First, when I try to build for android, It says cannot found RN 0.72.8. The workaround is to remove the line

`force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION`

from `android/build.gradle`

After that the build proceeds, but stops in the reanimated, with:

```
Could not determine the dependencies of task ':react-native-reanimated:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-reanimated:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:.
     Required by:
         project :react-native-reanimated
```

How can I solve this, please.

### Steps to reproduce

-

### Snack or a link to a repository

-

### Reanimated version

3.6.1

### React Native version

0.72.8

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Latropos** [comment] 2024-01-10 14:14
Is it a possibly a duplicate of #5497?

**Comment by Latropos** [comment] 2024-01-16 14:57
@Girum Unfortunately we are unable to reproduce the issue on our end. If you provide any reproduction, please feel free to reopen this issue

**Closed by Latropos** 2024-01-16 14:57 UTC
Labels: Missing repro, Platform: Android, Missing info
