### ISSUE TITLE
Playground app immediately crashes on launch

### ISSUE THREAD

**Issue by jonbiz** [software-mansion/react-native-reanimated#955] opened 2020-07-08 00:23 UTC
## Description

When launching the app, it crashes immediately.

I've been trying to get the v2 to work on Android with `^2.0.0-alpha.3`. 
Everything works fine on iOS. Using a freshly cloned `reanimated-2-playground`. 
Using `^2.0.0-alpha.1` launches the app but crashes immediately on the JS side with error `Unknown`.

### Screenshots

Since the app just crashes, here is what `pidcat` is logging.

<img width="1440" alt="Screen Shot 2020-07-07 at 8 12 39 PM" src="https://user-images.githubusercontent.com/38219858/86858382-8b1c5400-c08e-11ea-9ea3-a42e3a355d56.png">
<img width="1440" alt="Screen Shot 2020-07-07 at 8 12 29 PM" src="https://user-images.githubusercontent.com/38219858/86858397-90799e80-c08e-11ea-86e6-77e577893c85.png">
<img width="1440" alt="Screen Shot 2020-07-07 at 8 12 26 PM" src="https://user-images.githubusercontent.com/38219858/86858403-93748f00-c08e-11ea-8a78-bb6d25d4ae9a.png">

## Steps To Reproduce

1. `git clone git@github.com:software-mansion-labs/reanimated-2-playground.git`
2. change `react-native-reanimated` from `^2.0.0-alpha.1` to `^2.0.0-alpha.3` in package.json
3. `yarn`
4. `react-native run-android`

### Expected behavior

App launch

### Actual behavior

App crash

## Snack or minimal code example

<img width="397" alt="Screen Shot 2020-07-07 at 8 18 03 PM" src="https://user-images.githubusercontent.com/38219858/86858613-fe25ca80-c08e-11ea-8991-ffd9a77bca12.png">

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Reanimated: ^2.0.0-alpha.3

**Comment by karol-bisztyga** [comment] 2020-07-09 08:49
Hey, thanks for posting!
I've tried to reproduce that issue but everything works fine on my machine. Problems like that, especially when switching between libraries' versions, are often caused by caches and that applies mostly for android. Here are some commands you could try to overcome what you've encountered:
`rm -rf node_modules/ && yarn`
`rm -rf ~/.gradle/caches/`
`rm -rf ~/.android/*cache*`
`cd android && ./gradlew clean`
And only then try to launch the app.

**Comment by hosseinmd** [comment] 2020-07-10 12:18
Crash  Reanimated2Playground when using useAnimatedStyle

<img width="303" alt="Screen Shot 2020-07-10 at 3 58 45 PM" src="https://user-images.githubusercontent.com/45505767/87153711-24d14480-c2cd-11ea-9e25-15745eda0b88.png">

**Comment by hosseinmd** [comment] 2020-07-10 13:16
I tested everything but this issue not wants to resolve.

**Comment by karol-bisztyga** [comment] 2020-07-10 14:34
@hosseinmd please provide some information like a code that causes those problems and packages versions.

**Comment by hosseinmd** [comment] 2020-07-10 17:48
I just cloned the project and ran it, nothing's changed, this problem happened in Williams reanimated 2 examples too.

**Comment by kyle-ssg** [comment] 2020-07-26 12:49
Getting exactly the same issue on android, the rest works fine.

**Comment by kyle-ssg** [comment] 2020-07-27 12:31
@karol-bisztyga I think this should be closed, I'm pretty certain this is an issue with Hermes and not this library.

**Comment by karol-bisztyga** [comment] 2020-07-28 13:15
Ok well we were unable to reproduce the problem. Everything works fine. Can you specify some more information about the environment you are working on? Like versions of the OS, node, gradle, Android studio or any other tools used for building(and also which tools you are using).

> I just cloned the project and ran it

This tells nothing, I did the same and it works, please give me anything so I can help. Thank you 😊

**Comment by hosseinmd** [comment] 2020-07-28 20:29
https://github.com/software-mansion-labs/reanimated-2-playground/issues/7

**Comment by Eli-Nathan** [comment] 2020-08-15 11:24
Experiencing this issue too. Looks like it's definitely a Hermes issue.

Is there any way to use React Native Reanimated without Hermes?. Disabling Hermes gives me a Turbo Modules error but having it on crashes the app. 😭

**Comment by terrysahaidak** [comment] 2020-08-15 12:18
Did you do a clean clone and then just npm install? There are few things Hermes don't support from es2015+, but those should not exist in the playground repo.

Also, did you use npm or yarn?

**Comment by kyle-ssg** [comment] 2020-08-15 12:20
https://github.com/facebook/hermes/issues/298#issuecomment-674388184

This issue can be closed I think @terrysahaidak .

**Comment by jakub-gonet** [comment] 2020-08-19 09:41
I couldn't repro this, so closing.

If you still experience this problem please provide information about your environment (OS, if it only crashes on android, repo with example app, etc). If you made any modifications to the playground you maybe bumped into some Hermes issue unrelated to reanimated.

**Closed by jakub-gonet** 2020-08-19 09:41 UTC
Labels: Reanimated2, 🛠build-or-config-issue
